### ISSUE TITLE
使用Android studio在真机上运行example/android里面的demo时出错

### ISSUE THREAD

**Issue by TinyLina** [XiaoMi/mace#101]
通过example/android里面的build.sh构建demo后，在Android studio里面运行demo，通过debug app方式在真机上运行，出现以下错误，请问问题是出在什么地方呢？已经重新配置环境多次。
E/ContentCatcherManager: failed to get ContentCatcherService.
W/linker: "/data/app/com.xiaomi.mace.demo-MiCA6QomL0tjX7L_1fq4xQ==/lib/arm64/libmace_mobile_jni.so" unused DT entry: type 0xf arg 0x131a3
E/image_classify attrs: openmp result: 0, threads: 2, cpu: 0
                        gpu perf: 3, priority: 3
I/APPModel: maceMobilenetSetAttrs result = 0
E/image_classify attrs: device: 0
I/MACE: mace.cc:165 Creating MaceEngine, MACE version: v0.8.1-117-g1855fe1-20180719
        mace.cc:233 Loading Model Data
A/MACE: mace.cc:41 Check failed: fd >= 0 Failed to open model data file , error code: No such file or directory
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7311 (jniThread)
D/OpenGLRenderer: HWUI GL Pipeline
Disconnected from the target VM, address: 'localhost:8605', transport: 'socket'

**Comment by nolanliou** [comment]
```
A/MACE: mace.cc:41 Check failed: fd >= 0 Failed to open model data file , error code: No such file or directory
```

**Comment by nolanliou** [comment]
模型数据文件没有上传到手机上。

**Comment by SankQin** [comment]
请先编译模型文件，才能运行demo

**Comment by TinyLina** [comment]
@nolanliou  以前没玩过android，请问我的.data文件需要放到什么文件夹呢

**Comment by TinyLina** [comment]
@SankQin  已经编译了，生成了对应的.a和.data文件，就是不知道将.data文件放在何处。

**Comment by nolanliou** [comment]
可以参考MACE android demo: https://github.com/XiaoMi/mace/tree/master/mace/examples/android.

**Comment by TinyLina** [comment]
@nolanliou  我就是使用的这个demo，也是按上面执行的。结果就是我用android studio生成apk的时候只有3M左右的大小，感觉是.data文件没有打包进去。所以我想知道我**应该怎么操作才能把.data文件打包进去或者将.data文件放在手机上的某一个目录？**请问知道吗 :)

**Comment by TinyLina** [comment]
我就是使用的这个demo，也是按上面执行的。结果就是我用android studio生成apk的时候只有3M左右的大小，感觉是.data文件没有打包进去。所以我想知道我 ** 应该怎么操作才能把.data文件打包进去或者将.data文件放在手机上的某一个目录？** 请问知道吗 :)

**Comment by SankQin** [comment]
网上有一篇android 集成mace的教程
https://blog.csdn.net/qq_27063119/article/details/81015227

**Comment by TinyLina** [comment]
@SankQin  这个我看过，也试过。有些东西他没写全，得到的结果和我现在的状况是一样的。所以目前就卡在这个地方了。 就是我想知道应该吧.data文件放到什么地方，因为之前没怎么用过android。 /抱拳

**Comment by lee-bin** [comment]
build.sh默认构建的mobilenet.a是嵌入数据的，如下所示：
https://github.com/XiaoMi/mace/blob/911c103e48560734adbd99f83ec984c53873487e/mace/examples/android/mobilenet.yml#L4
如果你自定义的模型部署文件，可以修改`model_data_format`为`code`，这样就无需指定模型数据文件。

**Comment by TinyLina** [comment]
@lee-bin  我是将model_data_format: code 改为model_data_format: file 然后build.sh的。我最开始也是model_data_format: code，然后build.sh，但是没有生成.a与.data相关文件。所以，才改成model_data_format: file的。请问，是我这样改不对吗？还是model_data_format: code也会生成相应的.a文件吗？

**Comment by lee-bin** [comment]
不需要修改任何代码，按照
https://github.com/XiaoMi/mace/blob/master/mace/examples/android/README.md
即可生成libmace.a和mobilenet.a文件，随后构建APP并安装

**Comment by TinyLina** [comment]
@lee-bin  嗯嗯，感谢 /抱拳 /抱拳

**Comment by SankQin** [comment]
@lee-bin  我用studio debug 编译，无法生成libmace_mobile_jni.so 怎么办

**Comment by lee-bin** [comment]
@SankQin 已回复，请查看 #97
