### ISSUE TITLE
目前deeplab_v3_plus模型能跑出原版的效果吗？

### ISSUE THREAD

**Issue by hylrh2008** [XiaoMi/mace#103]
input_shape:{ 1,513,513,3 }
output_shape:{ 1,65,65,21 }
请问现有的deeplab_v3_plus_mobilenet_v2模型文件能够运行出正确的分割结果吗？谢谢

**Comment by lydoc** [comment]
deeplab_v3_plus_mobilenet_v2中的主干网络结构和特征提取我们已支持，但是为了方便优化，我们使用固定尺度的“sub_7"node作为输入，"ResizeBilinear_2"作为输出，需要部署模型的时候自行做一下预处理和后处理。
