### ISSUE TITLE
tf_dsp_converter can't parse const node with input

### ISSUE THREAD

**Issue by chanchanzhang** [XiaoMi/mace#106]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04)
- **NDK version(e.g., 15c)**:
16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
I am trying to run a mobilenet SSD model on dsp, tried to convert the orginal model using transform_graph tool, it will generate const node with input, like the following:

FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D_Fold_eightbit/normalized_input_image_tensor__port__0/reduction_dims (Const): [**^normalized_input_image_tensor**], value=Tensor<type: int32 shape: [1] values: 0>

During convert, convert_ops() in tf_dsp_converter_lib.py will run 
tf_tensor = first_op.outputs[0].eval()
which will fail for such const node with input.

> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'normalized_input_image_tensor' with dtype float and shape [1,300,300,3]
>          [[Node: normalized_input_image_tensor = Placeholder[dtype=DT_FLOAT, shape=[1,300,300,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> 

Do you have a way to workaround this issue?

Thanks!
Chanchan

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by liyinhgqw** [comment]
I think there exists some control dependency in your model ([^normalized_input_image_tensor]). Please try newer version of tensorflow.

**Comment by chanchanzhang** [comment]
@liyinhgqw Thanks for the reminder! I tried 'remove_control_dependecies" of transform_graph, now it looks normal.

**Comment by cvJonathan** [comment]
Could you describe how to remove control dependecies  of transform_graph？@chanchanzhang
