### ISSUE TITLE
Can I use anrry index to access a value in a buffer of a tensor(CPU mode)，like <data_at> in caffe？

### ISSUE THREAD

**Issue by syndec** [XiaoMi/mace#107]
In Caffe， we can write like this，`bottom->data_at(n, c, h, w)` .
When I read the mace\core\tenor.h，I still have no idea，just use 1-Dimension buffer？

**Comment by llhe** [comment]
Is this what you need https://mace.readthedocs.io/en/latest/development/memory_layout.html?

**Comment by syndec** [comment]
Yeah, maybe a considerable way, thx @llhe
