### ISSUE TITLE
Exception: Mace does not support tensorflow op type StopGradient yet

### ISSUE THREAD

**Issue by lyp0413** [XiaoMi/mace#108]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:5.4.0
- **MACE version (Use the command: git describe --long --tags)**:v0.8.1-117-g1855fe1
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**:0.15.0

### Model deploy file (*.yml)
library_name: fast_style_transfer_starry
target_abis: [armeabi-v7a, arm64-v8a]
target_socs: [msm8996]
model_graph_format: code
model_data_format: code
models: 
  fast_style_transfer_starry: 
    platform: tensorflow
    model_file_path: /home/lyp/mace/mace-models/pb/starry.pb
    model_sha256_checksum: 396f38ea95e30d2e30156a370f9d9fda551419b3cca5cf304d19ec309242ffc0
    subgraphs:
      - input_tensors: X_content
        input_shapes: 1,480,640,3
        output_tensors: add_37
        output_shapes: 1,480,640,3
        validation_inputs_data:
          - home/cloud/lyp/mace/images/test_1.npy
    runtime: gpu
    limit_opencl_kernel_time: 0
    dsp_mode: 0
    obfuscate: 0
    winograd: 0

### Describe the problem
Exception: Mace does not support tensorflow op type StopGradient yet
### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
---------------------------------------------------
                Common Configuration               
---------------------------------------------------
|        key        |            value            |
===================================================
|       library_name|   fast_style_transfer_starry|
---------------------------------------------------
|        target_abis| ['armeabi-v7a', 'arm64-v8a']|
---------------------------------------------------
|        target_socs|                  ['msm8996']|
---------------------------------------------------
| model_graph_format|                         code|
---------------------------------------------------
|  model_data_format|                         code|
---------------------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

{'fast_style_transfer_starry': {'dsp_mode': 0, 'model_sha256_checksum': '396f38ea95e30d2e30156a370f9d9fda551419b3cca5cf304d19ec309242ffc0', 'data_type': 'fp16_fp32', 'platform': 'tensorflow', 'winograd': 0, 'nnlib_graph_mode': 0, 'subgraphs': [{'output_tensors': ['add_37'], 'input_shapes': ['1,480,640,3'], 'input_tensors': ['X_content'], 'output_shapes': ['1,480,640,3'], 'input_ranges': [], 'validation_inputs_data': ['home/cloud/lyp/mace/images/test_1.npy']}], 'limit_opencl_kernel_time': 0, 'obfuscate': 0, 'model_file_path': '/home/lyp/mace/mace-models/pb/starry.pb', 'weight_file_path': '', 'weight_sha256_checksum': '', 'runtime': 'gpu'}}
--------------------------------------------------------------------
fast_style_transfer_starry
************************************************************
          Convert fast_style_transfer_starry model          
************************************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.269s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Traceback (most recent call last):
  File "/home/lyp/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 300, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/lyp/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 145, in main
    output_graph_def = converter.run()
  File "/home/lyp/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 214, in run
    self.convert_ops()
  File "/home/lyp/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 256, in convert_ops
    % tf_op.type)
  File "/home/lyp/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 18, in mace_check
    raise Exception(msg)
Exception: Mace does not support tensorflow op type StopGradient yet
Traceback (most recent call last):
  File "tools/converter.py", line 1556, in <module>
    flags.func(flags)
  File "tools/converter.py", line 773, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 701, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/lyp/mace/tools/sh_commands.py", line 526, in gen_model_code
    _fg=True)
  File "/home/lyp/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/lyp/mace/mace-models/pb/starry.pb --weight_file= --model_checksum=396f38ea95e30d2e30156a370f9d9fda551419b3cca5cf304d19ec309242ffc0 --weight_checksum= --input_node=X_content --output_node=add_37 --runtime=gpu --template=mace/python/tools --model_tag=fast_style_transfer_starry --input_shape=1,480,640,3 --dsp_mode=0 --embed_model_data=True --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/fast_style_transfer_starry --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:

  STDERR:

### Additional context
I use the project from [https://github.com/lengstrom/fast-style-transfer](url) to generate a fast-style-transfer model(tensorflow),But it shows no support with op StopGradint.Is there something wrong I`ve done or MACE really does not support this op.For the latter one,will you add this support in the future?

**Comment by TonyMou** [comment]
StopGradient is unnecessary for inference. Use transform_graph tool to remove it.
https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#prepare-your-model

**Comment by lyp0413** [comment]
@TonyMou Then I meet 'Exception: Mace does not support tensorflow op type Sum yet'. Should I do the same operator?

**Comment by TonyMou** [comment]
https://mace.readthedocs.io/en/latest/user_guide/op_lists.html#operator-lists

'Sum' op is not supported yet. You can add a new op in MACE.

https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html#adding-a-new-op

 Or just use a different op with the same function instead.

**Comment by TonyMou** [comment]
@lyp0413  feel free to reopen it.

**Comment by lyp0413** [comment]
@TonyMou Can you offer the project adress which generate style-transfer models from the model-zoo?

**Comment by TonyMou** [comment]
@lyp0413 The original project is https://github.com/lengstrom/fast-style-transfer

**Comment by TonyMou** [comment]
@lyp0413 you need to transform the pb file before converting. https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#prepare-your-model

```
./transform_graph \
    --in_graph=output_graph.pb \
    --out_graph=output_graph_opt.pb \
    --inputs='image_placeholder' \
    --outputs='add_37' \
    --transforms='strip_unused_nodes(type=float, shape="1,64,64,3") 
        remove_nodes(op=Identity, op=CheckNumerics, op=StopGradient)
        fold_batch_norms
        fold_old_batch_norms
        strip_unused_nodes
        sort_by_execution_order'
```

**Comment by lyp0413** [comment]
@TonyMou Yes I did,but there were still some unsurported ops in the model,such as 'Sum'.

**Comment by lydoc** [comment]
@lyp0413 "Add" is the same with "Sum" in Eltwise op.

**Comment by lyp0413** [comment]
@yejw5 No,just tensorflow

**Comment by yejw5** [comment]
@lyp0413 You can refer to the [ops list](https://mace.readthedocs.io/en/latest/user_guide/op_lists.html) and check which ops are supported.

**Comment by TonyMou** [comment]
@lyp0413 , did you mean tf.reduce_sum? Cause I cannot find tf.sum in tensorflow. You can check the reduce_mean op source code in MACE, I think they are similar.

**Comment by lyp0413** [comment]
@TonyMou No,the Sum is encapsulated in batch_norm op(tf.contrib.layers.batch_norm).So as long as I use bn,it will centainly use the Sum op.

**Comment by TonyMou** [comment]
@lyp0413 batch norm op is in the support-list already, https://mace.readthedocs.io/en/latest/user_guide/op_lists.html
