### ISSUE TITLE
How to modify config file to use multiply output tensors?

### ISSUE THREAD

**Issue by peyer** [XiaoMi/mace#113]
I just copy the subgraphs like below
***********
subgraphs:
      - input_tensors: data
        input_shapes: 1,60,79,3
        output_tensors: prob1
        output_shapes: 1,25,35,2
    subgraphs:
      - input_tensors: data
        input_shapes: 1,60,79,3
        output_tensors: conv4-2
        output_shapes: 1,25,35,4 
*************
However, the log file shown that output node only contained conv4-2 without prob1,
How can I use both of them?

**Comment by chanchanzhang** [comment]
check https://github.com/XiaoMi/mace/issues/62
It is not working well if you are trying to run on dsp: https://github.com/XiaoMi/mace/issues/110

**Comment by peyer** [comment]
Thanks a lot
