### ISSUE TITLE
c++调用deeplab-v3模型

### ISSUE THREAD

**Issue by cuihuitao** [XiaoMi/mace#117]
调用代码主要部分如下：
mace::DeviceType device_type = mace::GPU;//CPU = 0, GPU = 2, HEXAGON = 3

	if (device_type == mace::DeviceType::GPU) 
	{
		mace::SetGPUHints(
			static_cast<mace::GPUPerfHint>(3),
			static_cast<mace::GPUPriorityHint>(3));
	}
	
	if (device_type == mace::DeviceType::GPU) 
	{
		std::vector<std::string> opencl_binary_paths = {"./opencl_binary"};
		//mace::SetOpenCLBinaryPaths(opencl_binary_paths);
	}

	//1.read pb file
	std::vector<unsigned char> model_pb_data;
    if (!ReadBinaryFile(&model_pb_data, "deeplab_v3.pb")) 
    {
		printf("=====>>>>Failed to read pb file!\n");
		return 0;
    }
	//2.create MaceEngine
	std::shared_ptr<mace::MaceEngine> engine;
    mace::MaceStatus create_engine_status;
	std::vector<std::string> input_nodes;
	input_nodes.push_back(std::string("sub_7"));
	std::vector<std::string> output_nodes;
	output_nodes.push_back(std::string("ResizeBilinear_2"));
	std::cout << "=====>>>>>start to CreateMaceEngineFromProto" << "\n";
    create_engine_status = CreateMaceEngineFromProto(model_pb_data,std::string("deeplab_v3.data"),input_nodes
	,output_nodes,device_type,&engine);
	if (create_engine_status != mace::MaceStatus::MACE_SUCCESS) 
	{
    	std::cout << "Create engine error, please check the arguments";
		return 0;
  	}
	std::cout << "=====>>>>>end to CreateMaceEngineFromProto" << "\n";
	//3.load input data
    std::cout << "====>>start to load input data" << "\n";
	std::vector<int64_t> input_shapes = {1,513,513,3};
	int64_t input_size =std::accumulate(input_shapes.begin(), input_shapes.end(), 1,std::multiplies<int64_t>());
	auto buffer_in = std::shared_ptr<float>(new float[input_size],std::default_delete<float[]>());
	std::ifstream in_file("dog.npy",std::ios::in | std::ios::binary);
    if (in_file.is_open()) 
	{
      in_file.read(reinterpret_cast<char *>(buffer_in.get()),input_size * sizeof(float));
      in_file.close();
    } else 
	{
      std::cout << "Open input file failed";
      return -1;
    }
	std::map<std::string, mace::MaceTensor> inputs;
	inputs["sub_7"] = mace::MaceTensor(input_shapes, buffer_in);
	//4.output buffer
	std::vector<int64_t> output_shapes = {1,65,65,21};
	 int64_t output_size = std::accumulate(output_shapes.begin(), output_shapes.end(), 1,std::multiplies<int64_t>());
    auto buffer_out = std::shared_ptr<float>(new float[output_size],std::default_delete<float[]>());
	std::map<std::string, mace::MaceTensor> outputs;
    outputs["ResizeBilinear_2"] = mace::MaceTensor(output_shapes, buffer_out);
	//run Model
	struct timeval tm_before,tm_after;
	gettimeofday(&tm_before,NULL);
    engine->Run(inputs, &outputs);
	gettimeofday(&tm_after,NULL);

报错如下：../mace/kernels/opencl/helper.cc:339] Check failed: error == CL_SUCCESS error: CL_INVALID_WORK_GROUP_SIZE。  Aborted (core dumped)；

求解答！

**Comment by llhe** [comment]
`CL_INVALID_WORK_GROUP_SIZE` 很可能是你的手机支持的work group size不够大，超过了模型所需要的大小。少部分低端手机有这个问题。

**Comment by llhe** [comment]
提供一下手机和芯片型号？

**Comment by cuihuitao** [comment]
用的是瑞芯微的RK3399的arm-linux开发板，能运行mace的deeplab-v3的分割模型吗？谢谢！

**Comment by cuihuitao** [comment]
用的是瑞芯微的RK3399的arm-linux开发板，能运行mace的deeplab-v3的分割模型吗？谢谢！ @llhe

**Comment by feixuedudiao** [comment]
@cuihuitao 
同求，能否RK3399上运行，谢谢。

**Comment by llhe** [comment]
@feixuedudiao @cuihuitao  可以参考这里https://github.com/XiaoMi/mace/issues/36，手动编译：`bazel build -s --config aarch64_linux --define openmp=true --define opencl=true --define neon=true //mace/libmace:libmace.so`

后续会集成到converter.py里面

**Comment by terryzhangthu** [comment]
deeplabv3中，mace模型的输出是output_shapes = {1,65,65,21}， 怎样才可以转化为原始模型的SemanticPredictions的输出的？

**Comment by lydoc** [comment]
@terryzhangthu output之后的操作需要自己写一下，比如Argmax和Resize。

**Comment by terryzhangthu** [comment]
多谢回复，输入的Sub_7也不是直接传原图数据的float型吧？请问有如何处理数据的参考代码么？

**Comment by lydoc** [comment]
@terryzhangthu 可以将原图转为numpy的ndarray输入。数据处理大多使用numpy，不太复杂。
