### ISSUE TITLE
How to reshape input size of engine after CreateMaceEngineFromCode?

### ISSUE THREAD

**Issue by peyer** [XiaoMi/mace#119]
I have a full-convolution network named PNet(MTCNN used), and want to run it on multi-scale, so I need reshape the input size of PNet like caffe::Net<T>::Reshape(), does mace support this implementation? 
I only found three member functions of mace::MaceEngine without reshape

**Comment by llhe** [comment]
@peyer What do you mean by multi-scale? Different size of inputs or you model need reshapes to generate different scale of feature maps?

If it's the 1st case, you can use the max size of inputs.

**Comment by peyer** [comment]
@llhe I am sorry about not explaining clearly. I just want to know that if I have a  FCN(Fully-Convolutional Nets) with different input size，how should I modify the config file?
However, I have got your advice at#124. Thanks a lot.
Another question about HexagonNN, I have followed your provided method of compiling nnlib, but only obtained dynamic file without an executive file named graph_app, how should I do next?

**Comment by liyinhgqw** [comment]
You do not need do nothing about yaml, just pass input with different size to engine run interface.

About mace-with-hexagonNN, you do not need executive file `graph_app`, HexagonNN is only compiled to generate an `nn-skel.so`. You can push the so to the vendor lib of phone as is shown in nnlib `README`. Then you can compile and run your model with MACE. 

See also https://mace.readthedocs.io/en/latest/faq.html

**Comment by peyer** [comment]
@liyinhgqw OK, I will try. Thanks so much
