### ISSUE TITLE
华为p9运行demo崩溃

### ISSUE THREAD

**Issue by carbon1985** [XiaoMi/mace#126]
华为p9（android版本7.0）运行demo（armeabi-v7a，没有改动代码，只是换了armeabi-v7a的构建abi），切换到gpu模式下，运行mobiltnet-v2，会崩溃
崩溃日志：
在华为p9上运行demo，使用gpu进行mobilenetv2的inference，会崩溃，具体的错误是：
-13475/com.xiaomi.mace.demo E/linker: library "/system/vendor/lib/libOpenCL.so" ("/vendor/lib/libOpenCL.so") needed or dlopened by "/data/app/com.xiaomi.mace.demo-1/lib/arm/libmace_mobile_jni.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xiaomi.mace.demo-1/lib/arm:/data/app/com.xiaomi.mace.demo-1/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.xiaomi.mace.demo"]
07-25 22:39:47.083 13446-13475/com.xiaomi.mace.demo E/linker: library "/system/vendor/lib/egl/libGLES_mali.so" ("/vendor/lib/egl/libGLES_mali.so") needed or dlopened by "/data/app/com.xiaomi.mace.demo-1/lib/arm/libmace_mobile_jni.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xiaomi.mace.demo-1/lib/arm:/data/app/com.xiaomi.mace.demo-1/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.xiaomi.mace.demo"]
07-25 22:39:47.083 13446-13475/com.xiaomi.mace.demo E/MACE: opencl_wrapper.cc:284 Failed to load OpenCL library, please make sure there exist OpenCL library on your device, and your APP have right to access the library.
07-25 22:39:47.084 13446-13475/com.xiaomi.mace.demo A/MACE: opencl_wrapper.cc:380 Check failed: openclLibraryImpl->Load()
07-25 22:39:47.084 13446-13475/com.xiaomi.mace.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 13475 (jniThread)

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by llhe** [comment]
The reason is /system/vendor/lib/libOpenCL.so can't be loaded by the app due to permission issue.

Can you make sure you phone support OpenCL? For example, use this App: https://play.google.com/store/apps/details?id=com.robertwgh.opencl_z_android&hl=en.

If OpenCL-Z can also reports negative, perhaps you should contact device maker for this feature.
