### ISSUE TITLE
No module named sh

### ISSUE THREAD

**Issue by zhangkom** [XiaoMi/mace#129]
when I do: 
     python tools/converter.py convert --config=../mace-models/vgg16/vgg16-caffe-gpu.yml
error happened as following:

Traceback (most recent call last):
  File "tools/converter.py", line 20, in <module>
    import sh
ImportError: No module named sh

**Comment by llhe** [comment]
@zhangkom You need install the dependencies first: https://mace.readthedocs.io/en/latest/installation/env_requirement.html
