### ISSUE TITLE
set proper ANDROID_NDK_HOME, why still cannot find some head files

### ISSUE THREAD

**Issue by samsun639** [XiaoMi/mace#13]
using ndk-r16b , when run command: "python tools/converter.py build --config=docs/getting_started/models/demo_app_models.yaml"

ERROR HAPPEN as below, any idea? 

external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:10: fatal error: 'wchar.h' file not found
#include <wchar.h>
         ^~~~~~~~~
1 error generated.
Target //mace/tools/validation:mace_run_static failed to build
INFO: Elapsed time: 3.311s, Critical Path: 0.59s
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1348, in <module>
    flags.func(flags)
  File "tools/converter.py", line 888, in build_library
    flags.disable_openmp, flags.address_sanitizer)
  File "tools/converter.py", line 862, in generate_library
    address_sanitizer)
  File "tools/converter.py", line 720, in build_specific_lib
    address_sanitizer=address_sanitizer
  File "/local/mnt/mace/tools/sh_commands.py", line 323, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/bazel build //mace/tools/validation:mace_run_static --config android --cpu=armeabi-v7a --define neon=true --define openmp=true --define hexagon=false --config optimization

  STDOUT:

  STDERR:

**Comment by TonyMou** [comment]
please run 'ndk-build ' to make sure the ANDROID_NDK_HOME is right.

**Comment by samsun639** [comment]
thanks for feedback!
checked the ndk-build is there
> which ndk-build 
/root/android-ndk-r16b/ndk-build

**Comment by samsun639** [comment]
it is strange that the compiler look header files under "external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/...." 

there is no such directory "external/androidndk/ndk/"  .

**Comment by samsun639** [comment]
I synced the mace repo this morning.

**OS**: ubuntu14.04 x86_64
**Bazel version:**
Build label: 0.11.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 14 07:48:23 +50148 (1520362424903)
Build timestamp: 1520362424903
Build timestamp as int: 1520362424903

**Comment by TonyMou** [comment]
bazel version need to be >= 0.13.0.

please refer to : https://mace.readthedocs.io/en/latest/getting_started/how_to_build.html

**Comment by samsun639** [comment]
ooh. cool.

issue resolved after using the latest bazel .  



Thanks!
