### ISSUE TITLE
新加入一个PB文件,无法编译通过

### ISSUE THREAD

**Issue by hongsui169163** [XiaoMi/mace#133]
新加入了一个PB文件,只改了一个yml文件

  model_file_path: /home/asd/log_07_27/mobilenet-v1-1.0_test.pb
  model_sha256_checksum: 10aa4f3b1c44b7060fd8727099b059cd0617d7bc795c15ee8fd22511450681e3
请问新加入自己的PB文件都需要更改哪些地方?谢谢 
无法编译通过,错误 如下:
 raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
Traceback (most recent call last):
  File "tools/converter.py", line 1348, in <module>
    flags.func(flags)
  File "tools/converter.py", line 885, in build_library
    convert_model(configs)
  File "tools/converter.py", line 660, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/asd/log_07_27/test/mace-master/tools/sh_commands.py", line 521, in gen_model_code
    _fg=True)
  File "/home/asd/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/asd/log_07_27/mobilenet-v1-1.0_test.pb --weight_file= --model_checksum=10aa4f3b1c44b7060fd8727099b059cd0617d7bc795c15ee8fd22511450681e3 --weight_checksum= --input_node=input --output_node=MobilenetV1/Predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=1 --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_build_type=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:

**Comment by lydoc** [comment]
可以参考https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html

**Comment by hongsui169163** [comment]
你好：
    參考這個
./transform_graph \
    --in_graph=/path/to/your/tf_model.pb \
    --out_graph=/path/to/your/output/tf_model_opt.pb \
    --inputs='input node name' \
    --outputs='output node name' \
    --transforms='strip_unused_nodes(type=float, shape="1,64,64,3")
        strip_unused_nodes(type=float, shape="1,64,64,3")
        remove_nodes(op=Identity, op=CheckNumerics)
        fold_constants(ignore_errors=true)
        flatten_atrous_conv
        fold_batch_norms
        fold_old_batch_norms
        strip_unused_nodes
        sort_by_execution_order'
請問：
    --inputs='input node name' \
    --outputs='output node name' \
   這倆個參數該如何填？感謝

**Comment by lydoc** [comment]
请参考
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#inspecting-graphs

**Comment by hongsui169163** [comment]
你好：
     我想请教一下，yml填写参数的问题
     从http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz.下载包，
     用
./summarize_graph --in_graph="/home/asd/log_07_27/lizi/classify_image_graph_def.pb" 
No inputs spotted.
No variables spotted.
Found 1 possible outputs: (name=softmax, op=Softmax) 
Found 23885411 (23.89M) const parameters, 0 (0) variable parameters, and 99 control_edges
Op types used: 489 Const, 99 CheckNumerics, 99 Identity, 94 BatchNormWithGlobalNormalization, 94 Conv2D, 94 Relu, 11 Concat, 9 AvgPool, 5 MaxPool, 1 Sub, 1 Softmax, 1 ResizeBilinear, 1 Reshape, 1 Mul, 1 MatMul, 1 ExpandDims, 1 DecodeJpeg, 1 Cast, 1 BiasAdd
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/home/asd/log_07_27/lizi/classify_image_graph_def.pb --show_flops --input_layer= --input_layer_type= --input_layer_shape= --output_layer=softmax
   这里面的--input_layer=  --input_layer_shape= 这些参数都是空的，我看看MACE的例子上这些参数这些都是有的，现在是空的该如何填
./transform_graph \
    --in_graph=/path/to/your/tf_model.pb \
    --out_graph=/path/to/your/output/tf_model_opt.pb \
    --inputs='input node name' \
    --outputs='output node name' \
    --transforms='strip_unused_nodes(type=float, shape="1,64,64,3")
        strip_unused_nodes(type=float, shape="1,64,64,3")
     这里面的参数，感谢

**Comment by lydoc** [comment]
https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models 
使用这里新的inception model试试？2015版本的inception model 是用旧版本tensorflow训练得到的，你可以使用最新的模型试试

**Comment by hongsui169163** [comment]
HI:
    有没有现成的新的PB文件？都不支持哪些TYPE？训练数据时都有什么要求，才能转换成功？比如TENSORFLOW必须多少以上的版本训练？

**Comment by hongsui169163** [comment]
HI:
    比如我们训练出来的PB文件，也是不如贵司的例子明确：
$ ./summarize_graph --in_graph="/home/asd/log_07_27/20180408-102900.pb"
Found 2 possible inputs: (name=batch_size, type=int32(3), shape=<unknown>) (name=phase_train, type=bool(10), shape=<unknown>) 
No variables spotted.
Found 2 possible outputs: (name=label_batch, op=Identity) (name=embeddings, op=Mul) 
Found 23512505 (23.51M) const parameters, 0 (0) variable parameters, and 675 control_edges
Op types used: 2019 Switch, 1104 Const, 1056 Identity, 449 Sub, 449 Merge, 248 Mul, 224 FusedBatchNorm, 132 Conv2D, 131 Relu, 23 ConcatV2, 23 Add, 21 BiasAdd, 3 MaxPool, 3 Shape, 3 Reshape, 2 Placeholder, 1 QueueDequeueUpToV2, 1 AvgPool, 1 Sum, 1 StridedSlice, 1 Square, 1 Rsqrt, 1 RealDiv, 1 RandomUniform, 1 FIFOQueueV2, 1 Pack, 1 Maximum, 1 MatMul, 1 Floor
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/home/asd/log_07_27/20180408-102900.pb --show_flops --input_layer=batch_size,phase_train --input_layer_type=int32,bool --input_layer_shape=: --output_layer=label_batch,embeddings
input_layer_shape=不明确，帮忙看一下这里然TYPE哪些是不支持的？感谢

**Comment by lydoc** [comment]
这里是我们目前支持的op type，我们会持续进行新op的支持:
https://mace.readthedocs.io/en/latest/user_guide/op_lists.html
这里是我们目前所需的环境：
https://mace.readthedocs.io/en/latest/installation/env_requirement.html
input node, output node的相关信息也可以通过tensorboard查看。

**Comment by hongsui169163** [comment]
HI:
    贵司要求python2.7  ，pip install -I tensorflow==1.6.0
    我们现在能用python3.6.5    tensorflow1.9去训练数据吗？还是说必须python2.7+tensorflow1.6的版本去训练数据啊？
