### ISSUE TITLE
怎么样才能做出贵司能转换的PB文件？都需要哪些条件？

### ISSUE THREAD

**Issue by hongsui169163** [XiaoMi/mace#135]
你好：
      我们发现随便找一个PB文件都不能成功转换到贵司能识别的PB，不是训练数据时的TENSORFLOW版本过低，就是各种类似Exception: Mace does not support tensorflow op type Switch yet。还有concat也不支持。目前只有贵司提供然实例PB编的顺利。
      请问：不支持的类型一共有哪些？我们在训练数据时需要哪些条件和注意事项，才能成功与你们对接？感谢

**Comment by llhe** [comment]
可以参考这里
* TensorFlow版本：　https://mace.readthedocs.io/en/latest/installation/env_requirement.html
* Op支持列表：https://mace.readthedocs.io/en/latest/user_guide/op_lists.html

**Comment by hongsui169163** [comment]
HI:
贵司要求python2.7 ，pip install -I tensorflow==1.6.0
我们现在能用python3.6.5 tensorflow1.9去训练数据吗？还是说必须python2.7+tensorflow1.6的版本去训练数据啊？

**Comment by hongsui169163** [comment]
HI：
    我们现在什么也不改，直接用MODEL训练出数据，直接拿来转换就出现TYPE不支持的情况。比如Exception: Mace does not support tensorflow op type Switch yet
     怎么样才能做出像贵司例子的PB一样顺利遍过的文件？

**Comment by lydoc** [comment]
@hongsui169163 可以用python3.6.5 tensorflow1.9去训练。得到的frozen的pb使用transform_graph进行优化。对于暂时未能支持的op，欢迎贡献代码。

**Comment by hongsui169163** [comment]
HI:
   请问贵司是通过哪个MODEL训练出的可以顺利编译通过的PB文件？我们这边训练出的数据，使用transform_graph进行优化后的PB，不能通过编译，感谢

**Comment by lydoc** [comment]
Hi, 请参考https://github.com/XiaoMi/mace-models

**Comment by hongsui169163** [comment]
HI:
    你们这个https://github.com/XiaoMi/mace-models里面的这么几个PB是怎么生成的？刚好也没有不支持的TYPE？我们这边就是想做出这么几个能与你们对接的PB文件，目前我们生成的总有TYPE不支持，无法编译通过。请指点一下，感谢

**Comment by llhe** [comment]
>> 刚好也没有不支持的TYPE？

不是这样的，MACE的算子是一步步完善的，不支持的算子是需要实现的。

>>我们这边就是想做出这么几个能与你们对接的PB文件，目前我们生成的总有TYPE不支持，无法编译通过。请指点一下，感谢

那就需要添加这个算子，或者改成[已经支持的算子](https://mace.readthedocs.io/en/latest/user_guide/op_lists.html)绕过去。另外，tensorflow的算子众多，添加的原则是尽量选择通用的算子。添加步骤参考: https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html

**Comment by hongsui169163** [comment]
HI: 
    请问，这个绕过去的方法是在训练数据前做好一些？还是在转换PB时，在MACE上添加好一些？
   贵司已经在OPS加过的这些算子，实现的代码在哪里？能否给参考一下。感谢

**Comment by hongsui169163** [comment]
HI:
    有人关注 我的问题吗？

**Comment by llhe** [comment]
绕过去，就是指用其他已经支持的算子来替换不支持的算子。

**Comment by hongsui169163** [comment]
HI:
     我明白这个意思，我的意思是比如CONCAT，现在MACE不支持，在训练数据前，我已经知道不支持CONCAT了，就把这个换成MACE支持的算子，就可以了吧？就不用再MACE端再绕了。
    那我是在哪个位置处理比较合适呢？

**Comment by llhe** [comment]
* https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html
* https://mace.readthedocs.io/en/latest/user_guide/op_lists.html
* 代码：https://github.com/XiaoMi/mace/tree/master/mace/ops，https://github.com/XiaoMi/mace/tree/master/mace/kernels
