### ISSUE TITLE
mace修改一个地方，重新编译需要很久

### ISSUE THREAD

**Issue by zhangkom** [XiaoMi/mace#137]
重新编译有没有简单快速方法

**Comment by lydoc** [comment]
请问是修改了什么地方？修改后也只需编译一次即可。

**Comment by zhangkom** [comment]
随便增加个打印，重新编译要好久。

**Comment by liyinhgqw** [comment]
在 yaml 文件里，改动如下两行：
model_graph_format: file
model_data_format: file

可以加快 convert 的编译速度。
