### ISSUE TITLE
where call clGetPlatformInfoFunc

### ISSUE THREAD

**Issue by zhangkom** [XiaoMi/mace#138]
I can not find where call the clGetPlatformInfoFunc，clEnqueueNDRangeKernelFunc，clBuildProgramFunc and so on, please tell me where these function will be called? thanks a lot.

**Comment by llhe** [comment]
* clXXFunc is a type alias
* Actual func ptr is defined here: https://github.com/XiaoMi/mace/blob/master/mace/core/runtime/opencl/opencl_wrapper.cc#L198
* Loaded and assigned here: https://github.com/XiaoMi/mace/blob/master/mace/core/runtime/opencl/opencl_wrapper.cc#L329
* Called here: https://github.com/XiaoMi/mace/blob/master/mace/core/runtime/opencl/opencl_wrapper.cc#L392
