### ISSUE TITLE
webgl 加速卷积神经网络计算

### ISSUE THREAD

**Issue by samshi** [XiaoMi/mace#14]
本人是前端工程师，近期研究一个基础项目：如何用webgl来加速大尺度卷积神经网络的计算。很赞成你们专注前端的观点，更进一步，我坚信浏览器能力会不断提升，会承担越来越大的作用。
我们团队在上海仪电AI大赛里演示了这个项目，并获得三等奖。
下面这个链接是宣讲keynote：http://hdcafe.com/new_computing/new_computing.key
希望能够一起探讨合作

**Comment by llhe** [comment]
@samshi 谢谢关注，web端目前没有在我们的计划中。你可以关注下TVM，或许可以解决你的问题。
