### ISSUE TITLE
clion+bazel

### ISSUE THREAD

**Issue by xiaoyaozhuzi** [XiaoMi/mace#142]
I have always worked with clion+bazel  to reading Tensorflow source code, but I can not do the same thing with mace, why?
And how IDE can I use to read the mace source code in Mac Pro?

**Comment by liyinhgqw** [comment]
Try adding this line into CMakeLists.txt under the project root directory:
`include_directories(.)`

**Comment by xiaoyaozhuzi** [comment]
clion不能识别，请问你们是使用什么IDE开发mace的代码的，有什么推荐吗？bazel编译mace没问题，但是clion的bazel插件不能识别。

**Comment by xiaoyaozhuzi** [comment]
我不是用来编译，编译用bazel是OK的，我是为了阅读代码方便，mac下我一般使用clion阅读，但是因为这个项目不是用cmake关联的，所以阅读不了，函数跳转之类的基本功能都没有，clion有bazel插件，tensorflow的源代码我都是用clion+bazel阅读的，但是mace项目关联失败，我想知道你们怎么阅读修改这些代码，不用IDE吗？

**Comment by liyinhgqw** [comment]
clion 为什么不能阅读 mace 代码呢。请发一下项目路径底下的 CMakeLists.txt

**Comment by liyinhgqw** [comment]
如果选 import project，clion 会自动生成 CMakLists.txt

**Comment by xiaoyaozhuzi** [comment]
这样做protobuf相关的代码关联不起来吧

**Comment by xiaoyaozhuzi** [comment]
因为没有生成对应的C++文件

**Comment by liyinhgqw** [comment]
有对应的C++文件，编译一遍就会在 bazel-mace/external 里生成

**Comment by wayen820** [comment]
直接用QtCreator来读，新建 import Non Qt project，跳转什么的都支持

**Comment by MaggieCui** [comment]
> 我不是用来编译，编译用bazel是OK的，我是为了阅读代码方便，mac下我一般使用clion阅读，但是因为这个项目不是用cmake关联的，所以阅读不了，函数跳转之类的基本功能都没有，clion有bazel插件，tensorflow的源代码我都是用clion+bazel阅读的，但是mace项目关联失败，我想知道你们怎么阅读修改这些代码，不用IDE吗？

请问这个问题解决了吗？我也遇到了这种问题

**Comment by weinixuehao** [comment]
我也遇到了macosx + clion + bazel plugin. 似乎在mac osx支持有问题。

**Comment by lu229** [comment]
@weinixuehao clion + baze我这边没有试验过，不过试验过clion + cmake是可以的，仅用于阅读代码，编译还是使用shell

**Comment by weinixuehao** [comment]
@lu229 改用qt了，感觉还不错。vscode 其实也不错就是项目大的时候高内存。
