### ISSUE TITLE
about winograd issue

### ISSUE THREAD

**Issue by 18810579179** [XiaoMi/mace#143]
HI:

Thank you for the great job.  I have a question.

 You said that winograd algorithm was introduced to speed up convolution operations. which winograd model has better performance, f(2,3), f(4,3) or f(6,3)?

Look forward to your reply.
Best wishes.

**Comment by liyinhgqw** [comment]
It depends on the size of feature map. 
But for most cases, f(6,3) is theoretically faster.
In practice, f(6,3) is better on CPU for large feature maps, and f(4,3) is better on GPU considering register issues.

**Comment by 18810579179** [comment]
you mean large feature map, about how large is the size ? 
and about how much improvement do the f(2,3), f(4,3) and f(6,3) have comparing to the direct convolution respectively?

Thanks.
