### ISSUE TITLE
Running converted mace model on linux

### ISSUE THREAD

**Issue by Zhengtq** [XiaoMi/mace#144]
In the example.cc(mace/examples/example.cc), I am confused about parameter "input_file" and the discription of which is "input file name | input file prefix for multiple inputs."
Can anyone tells me how to generate the "input_file"?

**Comment by liyinhgqw** [comment]
You can use `input_file` to specify the prefix of input data file. Considering there may be several input tensors, each name should be appended to `input_file` to differentiate them. 

Say, you run it with `--input_file my_data`, and your model have two input tensors with names `input_a`, `input_b`, then the actual data files stored should be with names:
`my_data_input_a` and `my_data_input_b`

**Comment by liyinhgqw** [comment]
We use numpy-like format, for which each float value of tensor has size 4bytes. You can also use numpy array method to generate input file.
`data.astype(np.float32).tofile(input_file_name)`

**Comment by Zhengtq** [comment]
@liyinhgqw Thanks for your reply.
