### ISSUE TITLE
Failed to run a caffemodel obtaining AbsVal_layer

### ISSUE THREAD

**Issue by peyer** [XiaoMi/mace#145]
I have successfully built dynamic library of mace using tools/build_standalone.sh by adding new  code assigning with absval operator including mace/ops/absval.cpp+mace/ops/absval.h+mace/kernels/absval.h+mace/kernels/opencl/absval.cpp+mace/kernels/opencl/cl/absval.cl.
I also modified mace/python/tools/caffe_converter.py and mace/python/tools/shape_inference.py and mace/python/tools/base_converter.py to support the new absval operator, and successfully run python tools/convert.py convert --config=/path/of/my/yaml to generate library.
However, when I tried to run python tools/convert.py run --config=/path/of/my/yaml to test, 
it shown  error info like below
F registry.h:45 Key not registered: AbsVal0T_DT_FLOAT
Aborted
ERROR: [Mace Run] Mace run failed.
How could solved it?

**Comment by liyinhgqw** [comment]
You need to register your new op.
@yejw5 ， could you complement docs (https://github.com/XiaoMi/mace/issues/145) for 'Adding new ops' session?

**Comment by yejw5** [comment]
@peyer 
- Firstly, use `.cc` extension instead of `.cpp` for your source files.
- And than register the new op in `mace/ops/ops_register.cc`. I will update the relevant docs later.

**Comment by liyinhgqw** [comment]
Please refer to doc https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html

**Comment by peyer** [comment]
@liyinhgqw I am so sorry about not clearly making sense of adding new op that leading to not add corresponding code in mace/ops/ops_register.cc. I have modified. Thanks a lot!

**Comment by peyer** [comment]
@liyinhgqw I copied opencl kernel of addn operator to my absval operator, and changed add mode to abs mode. However, when I tried to use absval op in GPU device, the return value of  runtime->command_queue().enqueueNDRangeKernel( ) of TuningOrRun2DKernel() became CL_INVALID_KERNEL.
what about your advice?
