### ISSUE TITLE
是否支持facenet训练完成的pb模型

### ISSUE THREAD

**Issue by DenisZheng** [XiaoMi/mace#15]
你好：
    基于inception_resnet_v1训练的模型能否支持？

**Comment by liyinhgqw** [comment]
Any ops listed in https://mace.readthedocs.io/en/latest/getting_started/op_lists.html should have been already supported. You can check if your model has ops that are not listed.

If it is supported, mace config will be welcomed (by contributing [Mace Model Zoo](https://github.com/XiaoMi/mace-models)).

**Comment by llhe** [comment]
We are interested in facenet, however, we don't have enough resources to port it. Contributions are welcome.
