### ISSUE TITLE
faceNet模型的训练数据合入报错

### ISSUE THREAD

**Issue by hongsui169163** [XiaoMi/mace#152]
你好：
    我用./summarize_graph  --in_graph="/home/asd/log_07_27/20180801-1714411_opt.pb"
Found 2 possible inputs: (name=batch_size, type=int32(3), shape=<unknown>) (name=phase_train, type=bool(10), shape=<unknown>) 
No variables spotted.
Found 2 possible outputs: (name=label_batch, op=Identity) (name=embeddings, op=Mul) 
Found 22822614 (22.82M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 1122 Switch, 877 Const, 225 Merge, 224 FusedBatchNorm, 132 Conv2D, 131 Relu, 23 ConcatV2, 22 Mul, 21 BiasAdd, 21 Add, 3 MaxPool, 3 Reshape, 2 Identity, 2 Placeholder, 2 Shape, 1 AvgPool, 1 Sum, 1 StridedSlice, 1 Square, 1 Rsqrt, 1 QueueDequeueUpToV2, 1 Pack, 1 Maximum, 1 MatMul, 1 FIFOQueueV2
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/home/asd/log_07_27/20180801-1714411_opt.pb --show_flops --input_layer=batch_size,phase_train --input_layer_type=int32,bool --input_layer_shape=: --output_layer=label_batch,embeddings
然后用上面的数据，做了以下转换，生成优化后的PB
./transform_graph  --in_graph=/home/asd/log_07_27/20180801-1714411.pb     --out_graph=/home/asd/log_07_27/20180801-1714411_opt.pb     --inputs='batch_size,phase_train'     --outputs='label_batch,embeddings'     --transforms='strip_unused_nodes(type=float, shape="1,160,160,3")
        strip_unused_nodes(type=float, shape="1,160,160,3")
        remove_nodes(op=Identity, op=CheckNumerics)
        fold_constants(ignore_errors=true)
        flatten_atrous_conv
        fold_batch_norms
        fold_old_batch_norms
        remove_control_dependencies
        strip_unused_nodes
        sort_by_execution_order'
然后把优化后的PB放入工程编译，yml如下
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: /home/asd/log_07_27/mace-master0727/mace-master/mace/examples/android/20180801-1714411_opt.pb
    model_sha256_checksum: 039024993180653754ea8fa9fb478989b8026975aeb0d51c818368ab77742c0b
    subgraphs:
      - input_tensors:
          - batch_size
          - phase_train
        input_shapes:
          - 1,160,160,3
          - 1,160,160,3
        output_tensors:
          - slabel_batch
          - embeddings
        output_shapes:
          - 1,1001
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
编译不过，报
    raise ValueError(err.message)
ValueError: An unknown shape must not have any dimensions set. for 'batch_size' (op: 'Placeholder') with input shapes: .

这个错误，请问这是哪里的问题？

**Comment by lee-bin** [comment]
batch_size和phase_train是训练时使用的，这里的输入应该是input

**Comment by hongsui169163** [comment]
你好：
Exception: Mace does not support tensorflow op type Switch yet
我们现在又报这个错误，如何处理？感谢

**Comment by yejw5** [comment]
@hongsui169163 这个报错意思是mace不支持Switch这个op，当前已支持的op可以参考：https://mace.readthedocs.io/en/latest/user_guide/op_lists.html。
