### ISSUE TITLE
Regarding nnlib_graph_mode in DSP runtime 

### ISSUE THREAD

**Issue by PennySHE** [XiaoMi/mace#157]
I didn's see much information about nnlib_graph_mode. 
In xiaomi MACE documentation, there's very limited introduction 
Could MACE genius provide more details about the usage/output of nnlib_graph_mode settings?

**Comment by lee-bin** [comment]
目前没有使用nnlib_graph_mode

**Comment by ysh329** [comment]
你们说的，nnlib_graph_mode是啥呀，我看部署模型时候是配置文件里的一项
