### ISSUE TITLE
关于编译Android库的一些问题

### ISSUE THREAD

**Issue by yeyupiaoling** [XiaoMi/mace#158]
我在文档上看到有两种编译编译得到Android库的方式：

 1. https://github.com/XiaoMi/mace/blob/master/docs/user_guide/basic_usage.rst#basic-usage
 2. https://github.com/XiaoMi/mace/blob/master/mace/examples/android/build.sh

**第一种方式**，我是只执行一下命令：
```
git clone https://github.com/XiaoMi/mace.git

git clone https://github.com/XiaoMi/mace-models.git

bash tools/build-standalone-lib.sh

python tools/converter.py convert --config=/path/to/mace-models/mobilenet-v2/mobilenet-v2.yml
```

便得到了类似以下的文件：
```
builds
├── include
│   └── mace
│       └── public
│           ├── mace.h
│           └── mace_runtime.h
├── lib
│   ├── arm64-v8a
│   │   └── cpu_gpu
│   │       ├── libmace.a
│   │       └── libmace.so
│   ├── armeabi-v7a
│   │   ├── cpu_gpu
│   │   │   ├── libmace.a
│   │   │   └── libmace.so
│   │   └── cpu_gpu_dsp
│   │       ├── libhexagon_controller.so
│   │       ├── libmace.a
│   │       └── libmace.so
│   └── linux-x86-64
│       ├── libmace.a
│       └── libmace.so
└── mobilenet-v1
    ├── model
       ├── mobilenet_v1.data
       └── mobilenet_v1.pb
```
这个编译得到的文件感觉比较简单一些，但是这中编译及得不到Android Demo中的这个文件`mace_engine_factory.h`

**第二种方式**，执行Android Dome中的这个文件`build.sh` ，这样就得到`mace_engine_factory.h` 和其他一些文件。

我看脚本的命令更上面的也差不多，就多了以下这条命令，这个命令是什么意思呢？
```
bazel build --config android --config optimization mace/libmace:libmace_static --define neon=true --define openmp=true --define opencl=true --cpu=$TARGET_ABI
```

另外模型的配置文件也有点不一样，主要是这个：
```
model_graph_format: file
model_data_format: file
```

```
model_graph_format: code
model_data_format: code
```

两个方式得到的文件不一样，是哪个问题呢？两种方式得到的文件是否都是可以在Android上使用的呢？

**Comment by lee-bin** [comment]
1、对于`model_graph_format`和`model_data_format`请参考文档https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#id1
2、`mace_engine_factory.h`会在`model_graph_format`为`code`时生成。
3、Android Demo目前采用了
```
model_graph_format: code
model_data_format: code
```
可以改用其他方式，具体参考1中文档。

**Comment by yeyupiaoling** [comment]
@lee-bin 好的，谢谢回答。
