### ISSUE TITLE
Is this the framework used by MIUI?

### ISSUE THREAD

**Issue by valleykid** [XiaoMi/mace#16]
Other questions:

> Mobile AI Compute Engine (or MACE for short) is a deep learning inference framework optimized for mobile heterogeneous computing platforms.
 
* Where is the `deep learning` embodied in the framework?
* Over time, will it automatically optimize computing?

**Comment by llhe** [comment]
1. Yes, some AI features use MACE
2. MACE is not a standalone library in MIUI, it's just enbeded in the MIUI applications somewhere.
3. No, at least not now, but may be we might considering to introduce online GPU kernel tuning.
