### ISSUE TITLE
BUILD.bazel:5:1: Executing genrule @opencl_clhpp//:gen_opencl_clhpp failed (Exit 1): bash failed: error executing command

### ISSUE THREAD

**Issue by 2501026434** [XiaoMi/mace#160]
BUILD.bazel:5:1: Executing genrule @opencl_clhpp//:gen_opencl_clhpp failed (Exit 1): bash failed: error executing command
请问这个是什么问题呢

**Comment by nolanliou** [comment]
请按照模板把环境列出来

**Comment by 2501026434** [comment]
root@ubuntu:/home/zhy/mace_new# bash tools/build-standalone-lib.sh 
build shared lib for armeabi-v7a + cpu_gpu_dsp
Starting local Bazel server and connecting to it...
..............
INFO: Analysed target //mace/libmace:libmace_dynamic (26 packages loaded).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/072cb37ffc8a85633ecb17c28f607471/external/opencl_clhpp/BUILD.bazel:5:1: Executing genrule @opencl_clhpp//:gen_opencl_clhpp failed (Exit 1): bash failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/072cb37ffc8a85633ecb17c28f607471/execroot/mace && \
  exec env - \
    PATH=/home/soft/android-ndk-r16b:/home/soft/cmake-3.11.4-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; workdir=$(mktemp -d -t opencl-clhpp-build.XXXXXXXXXX); cp -aL $(dirname external/opencl_clhpp/CMakeLists.txt)/* $workdir; pushd $workdir; mkdir build; pushd build; cmake ../ -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF; make generate_clhpp generate_cl2hpp; popd; popd; cp -a $workdir/build/* bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp; rm -rf $workdir; echo installing to  bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp')

Use --sandbox_debug to see verbose messages from the sandbox
cp: failed to preserve ownership for '/tmp/opencl-clhpp-build.8LkKFkUPxW/BUILD.bazel': Invalid argument
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 56.665s, Critical Path: 6.27s
INFO: 4 processes, linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by yejw5** [comment]
@2501026434 你是在docker里面运行的代码？`cp: failed to preserve ownership`这个报错似乎是用户权限、或者磁盘存储格式之类的问题。试一下在docker里面拉取代码，并只使用docker内的文件目录编译试试？

**Comment by ashes1106** [comment]
> BUILD.bazel:5:1: Executing genrule @opencl_clhpp//:gen_opencl_clhpp failed (Exit 1): bash failed: error executing command
> 请问这个是什么问题呢


> root@ubuntu:/home/zhy/mace_new# bash tools/build-standalone-lib.sh
> build shared lib for armeabi-v7a + cpu_gpu_dsp
> Starting local Bazel server and connecting to it...
> ..............
> INFO: Analysed target //mace/libmace:libmace_dynamic (26 packages loaded).
> INFO: Found 1 target...
> ERROR: /root/.cache/bazel/_bazel_root/072cb37ffc8a85633ecb17c28f607471/external/opencl_clhpp/BUILD.bazel:5:1: Executing genrule @opencl_clhpp//:gen_opencl_clhpp failed (Exit 1): bash failed: error executing command
> (cd /root/.cache/bazel/_bazel_root/072cb37ffc8a85633ecb17c28f607471/execroot/mace &&
> exec env -
> PATH=/home/soft/android-ndk-r16b:/home/soft/cmake-3.11.4-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
> /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; workdir=$(mktemp -d -t opencl-clhpp-build.XXXXXXXXXX); cp -aL $(dirname external/opencl_clhpp/CMakeLists.txt)/* $workdir; pushd $workdir; mkdir build; pushd build; cmake ../ -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF; make generate_clhpp generate_cl2hpp; popd; popd; cp -a $workdir/build/* bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp; rm -rf $workdir; echo installing to bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp')
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> cp: failed to preserve ownership for '/tmp/opencl-clhpp-build.8LkKFkUPxW/BUILD.bazel': Invalid argument
> Target //mace/libmace:libmace_dynamic failed to build
> INFO: Elapsed time: 56.665s, Critical Path: 6.27s
> INFO: 4 processes, linux-sandbox.
> FAILED: Build did NOT complete successfully

请问这个问题最后是怎么解决的呢？

**Comment by lu229** [comment]
@ashes1106 你是遇到了这个问题吗？这个问题应该是使用了切换root和普通用户进行编译导致，可以重新clone一份代码，使用非root进行编译就好了。
