### ISSUE TITLE
Android的Demo中的JNI接口可用通用的吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [XiaoMi/mace#161]
我想使用各个分类模型的，不止是Demo中的MobileNet，还有Resnet，inception-v3，可用直接使用以下的接口吗？还是要自己写？
https://github.com/XiaoMi/mace/blob/ba4157f78aaf1c534ce69a0eb7c96c331b024c53/mace/examples/android/macelibrary/src/main/java/com/xiaomi/mace/JniMaceUtils.java#L23-L27

**Comment by lee-bin** [comment]
这只是MobileNet的，其他模型需要修改模型部署文件和JNI文件https://github.com/XiaoMi/mace/blob/master/mace/examples/android/macelibrary/src/main/cpp/image_classify.cc
java代码也需要相应做修改。可参考demo。

**Comment by TinyLina** [comment]
可以使用这些接口，但是你得修改模型的输入输出参数，

`public static native float[] maceMobilenetClassify(float[] input); `

返回的数组就是你得数据，进行处理即可。
