### ISSUE TITLE
Does mace support RaspberryPi3B, if yes can you provide compile options. 

### ISSUE THREAD

**Issue by ghimiredhikura** [XiaoMi/mace#167]
Does mace support RaspberryPi3B, if yes can you provide compile options.

**Comment by llhe** [comment]
RaspberryPi is not supported yet.

**Comment by madhavajay** [comment]
What is required to get this working? Does anyone know the issues so that the community can help work on it?

**Comment by llhe** [comment]
A bazel toolchain for Raspberry is needed. An example from community is here:
https://github.com/hbwangjinwu/mace_cross_compile_guide

By the way, RaspberryPi3B GPU/OpenCL(https://github.com/doe300/VC4CL) does not support full profile OpenCL(a major issue is Image is not supported), which is not currently supported. OpenCL Buffer will be supported and we will check whether this embeded profile can be supported or not.

**Comment by madhavajay** [comment]
Okay so with Bazel compiled for RPi the other problem is OpenCL.
What about the instructions here to patch and compile for CPU only without OpenCL:
https://github.com/XiaoMi/mace/issues/111
https://github.com/ctuning/ck-math/tree/master/package/lib-mace-cpu-0.8.1/patch.linux

**Comment by madhavajay** [comment]
Okay so... I have compiled Bazel on my ARM TinkerBoard with TinkerOS v2.0.7.

Was that supposed to be a problem?

```
linaro@tinkerboard:~$ uname -r
4.4.103+

linaro@tinkerboard:~$ cat /proc/version
Linux version 4.4.103+ (jenkins@fdc-06) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) ) #1 SMP Fri Jun 22 16:14:49 CST 2018

linaro@tinkerboard:~$ cat  /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc0d
CPU revision	: 1

processor	: 1
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc0d
CPU revision	: 1

processor	: 2
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc0d
CPU revision	: 1

processor	: 3
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc0d
CPU revision	: 1

Hardware	: Rockchip (Device Tree)
Revision	: 0000
Serial		: 6071d2e7dbcfc36e

root@tinkerboard:/home/linaro/bazel/output# ./bazel version
Build label: 0.16.1- (@non-git)
Build target: bazel-out/arm-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 24 02:51:48 2018 (1535079108)
Build timestamp: 1535079108
Build timestamp as int: 1535079108
```

**Comment by madhavajay** [comment]
Okay so I got MACE to build on my TinkerBoard Rockchip RK3288 Mali-T764 GPU using this repo:
https://github.com/madhavajay/mace-makefile-project

I forked it and updated the README.md to English with the steps I followed.
It seems to work.

Can you comment on the performance numbers, from an earlier benchmark
```
model_name                     device_name   soc        abi           runtime   init       warmup     run_avg    tuned
mobilenet_v2                   polaris       sdm845     armeabi-v7a   GPU       42.868     11.087     9.908      True
mobilenet_v2                   MI MAX        msm8952    armeabi-v7a   GPU       122.791    43.038     39.875     True
mobilenet_v2                   BKL-AL00      kirin970   armeabi-v7a   GPU       767.932    1226.373   

48.016     True
mobilenet_v2                   polaris       sdm845     armeabi-v7a   CPU       16.035     69.761     41.627     False
mobilenet_v2                   MI MAX        msm8952    armeabi-v7a   CPU       31.319     86.206     67.586     False
mobilenet_v2                   BKL-AL00      kirin970   armeabi-v7a   CPU       22.521     137.963    
```

These are the CPU / GPU benchmark numbers coming from the mace-makefile-project repo:
```
GPU
=====>>>>>Warm up Run Model spend time:1412 ms
=====>>>>>Normal Run Model spend time:167 ms

CPU
=====>>>>>Warm up Run Model spend time:513 ms
=====>>>>>Normal Run Model spend time:171 ms
```

Should this not be closer to the above numbers of other armeabi-v7a CPU?

**Comment by madhavajay** [comment]
Regarding compiling Bazel on the TinkerBoard, I did the following:

Install Open JDK 8
```
$ sudo apt-get install openjdk-8-jdk openjdk-8-jre
```

Grab latest src for bazel:
```
wget https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-dist.zip
```

Increase memory in: ./scripts/bootstrap/compile.sh
on line 122 Add: -J-Xms512m -J-Xmx512m after run "${JAVAC}"
Like:
```
run "${JAVAC}" -J-Xms512m -J-Xmx512m -classpath "${classpath}" -sourcepath "${sourcepath}" \
```

*NOTE*: If it runs out of memory during compilation just keep running it until it finishes.

Compile:
```
$ bash ./compile.sh
```

**Comment by madhavajay** [comment]
I tried to understand the instructions here but its in a chinese word doc:
https://github.com/hbwangjinwu/mace_cross_compile_guide

The understanding I have is that the normal Bazel build for MACE wont compile some things properly like Protobuf and to fix it theres a few files that need working around. However it seems that the Makefile project (https://github.com/zhy520xp/mace-makefile-project) works around this by providing a Makefile instead.

Is there a way we could unite the two and get the ability to make these corrections to the main MACE project so that these workarounds arent needed?

**Comment by madhavajay** [comment]
Those three chipsets actually look pretty fast:

**MI MAX        msm8952**
http://www.hisilicon.com/en/Media-Center/News/Key-Information-About-the-Huawei-Kirin970

**CPU**
4x ARM Cortex A73
4x ARM Cortex A53
CPU Clock Speed: 1.8 GHz - 2.36 Ghz
neural-network processing unit (NPU)

**GPU**
Mali G72 MP12 (12-core)

**polaris       sdm845**
https://www.qualcomm.com/products/snapdragon/processors/650
Qualcomm MSM8956 Snapdragon 650

**CPU**
2x ARM Cortex A72
4x ARM Cortex A53
CPU Clock Speed: Up to 1.8 GHz

**GPU**
Qualcomm® Adreno™ 510 GPU

**SDM845**
https://www.qualcomm.com/products/sdm845

**CPU**
8x Qualcomm® Kryo™ 385 CPU
CPU Clock Speed: Up to 2.8 GHz

**GPU**
Qualcomm® Adreno™ 630

**Comment by liyinhgqw** [comment]
Arm linux cross compilation has been already supported by bazel in MACE. You can refer to documentation and give it a try.
