### ISSUE TITLE
Mace Android Example has too large model libraries

### ISSUE THREAD

**Issue by SunAriesCN** [XiaoMi/mace#171]
### Describe the problem
Following the convert step and build.sh of android example,  my 3M model will generate a 20M libmace_mobile_jni.so. Although I get use the strip tool, the libraries also could be 6.2M...

### To Reproduce
Just following the document

**Comment by yejw5** [comment]
Did you pull latest code?

**Comment by SunAriesCN** [comment]
Yes, I just check the latest code results, and the libraries still around 6.7M with gpu+cpu mode.....
