### ISSUE TITLE
mace可以取出中间层的结果吗，不是output里的

### ISSUE THREAD

**Issue by CodeforL** [XiaoMi/mace#173]
想取出中间层权重

**Comment by CodeforL** [comment]
多谢大神指点，通过配置yml文件现在可以指定中间层作为output，
不过，我还想取出中间卷积层的param权重w,不知我该如何操作

**Comment by llhe** [comment]
现在还不支持，可以使用caffe或者tensorflow看一下吧？

查看权重是需要解决什么问题吗？

**Comment by CodeforL** [comment]
这样子啊，我是想要通过feature map和w计算响应热图，再去处理其他任务

**Comment by CodeforL** [comment]
感谢解惑，那我从caffe模型里读参数吧
