### ISSUE TITLE
Mace IE perfomance compare vs Tensorflow Lite and NCNN bad result

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#175]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ubuntu 16.0
- **NDK version(e.g., 15c)**:
17
- **GCC version(if compiling for host, e.g., 5.4.0)**:
clang
- **MACE version (Use the command: git describe --long --tags)**:
v9.0
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
14

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
Hi , I converted tensorflow model that include several separable convolution layers to test Mace performance .
Device I used is Google Pixel 2 with only 4 cores available (android image configuration)
I compiled Mace with no openmp support, single thread tested.
I am NOT using Mace API for multi threading.
Same model was converted to Tensorflow Lite and NCNN .
Performance of Mace IE vs Tensorflow Lite vs NCNN:
Mace=~400ms  TFLite=190ms NCNN=150ms

What reason for such GAP ???

Thanks.

### Error information / logs
conversion logs:
```
Remove identity: conv_0/depthwise_weights/read(Identity)
Remove identity: conv_0/pointwise_weights/read(Identity)
Remove identity: conv_0/biases/read(Identity)
Remove identity: conv_1/depthwise_weights/read(Identity)
Remove identity: conv_1/pointwise_weights/read(Identity)
Remove identity: conv_1/biases/read(Identity)
Remove identity: conv_2/depthwise_weights/read(Identity)
Remove identity: conv_2/pointwise_weights/read(Identity)
Remove identity: conv_2/biases/read(Identity)
Remove identity: output(Identity)
Fold biasadd: conv_0/separable_conv2d(Conv2D)
Fold biasadd: conv_1/separable_conv2d(Conv2D)
Fold biasadd: conv_2/separable_conv2d(Conv2D)
Transpose filters to OIHW
Transpose output shapes: conv_0/separable_conv2d/depthwise(DepthwiseConv2d)
Transpose output shapes: conv_0/separable_conv2d(Conv2D)
Transpose output shapes: conv_1/separable_conv2d/depthwise(DepthwiseConv2d)
Transpose output shapes: conv_1/separable_conv2d(Conv2D)
Transpose output shapes: conv_2/separable_conv2d/depthwise(DepthwiseConv2d)
Transpose output shapes: conv_2/separable_conv2d(Conv2D)
Transpose input/output to NCHW
Reshape fully connected weight shape
update op with float data type
Sort by execution
Final ops:
input (Transpose): [[1L, 1L, 128L, 128L]]
conv_0/separable_conv2d/depthwise (DepthwiseConv2d): [[1L, 1L, 128L, 128L]]
conv_0/separable_conv2d (Conv2D): [[1L, 64L, 128L, 128L]]
conv_1/separable_conv2d/depthwise (DepthwiseConv2d): [[1L, 64L, 128L, 128L]]
conv_1/separable_conv2d (Conv2D): [[1L, 128L, 128L, 128L]]
conv_2/separable_conv2d/depthwise (DepthwiseConv2d): [[1L, 128L, 128L, 128L]]
conv_2/separable_conv2d (Conv2D): [[1L, 256L, 128L, 128L]]
mace_output_node_output (Transpose): [[1L, 128L, 128L, 256L]]
start optimize memory.
total op: 8
0 CPU_BUFFER [4194304L]
1 CPU_BUFFER [4194304L]
origin mem: 14712832, optimized mem: 8388608
Memory optimization done.
***************************************************
          Model separable_model converted          
***************************************************

-------------------------------------------------
                     Library                     
-------------------------------------------------
|      key       |            value             |
=================================================
| MACE Model Path| builds/separable_models/model|
-------------------------------------------------
```

![capture](https://user-images.githubusercontent.com/36672340/44507317-15fd2c80-a678-11e8-8a04-e0e0ff9afe94.PNG)

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by liyinhgqw** [comment]
Did you run it on cpu or gpu ?

Can you send yaml config and model for us to test?

**Comment by dimitryn** [comment]
CPU only

[after_conversion.zip](https://github.com/XiaoMi/mace/files/2313306/after_conversion.zip)
[before_conversion.zip](https://github.com/XiaoMi/mace/files/2313307/before_conversion.zip)

**Comment by dimitryn** [comment]
@liyinhgqw  When do you expect release optimized version?
Thanks.

**Comment by liyinhgqw** [comment]
I think it is going to take one more week.

**Comment by dimitryn** [comment]
Great, Thanks .

**Comment by dimitryn** [comment]
Hi @liyinhgqw  does master include optimized version?
