### ISSUE TITLE
ERROR: [RUN] You should convert model first.

### ISSUE THREAD

**Issue by madhavajay** [XiaoMi/mace#176]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**: None
- **GCC version(if compiling for host, e.g., 5.4.0)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- **MACE version (Use the command: git describe --long --tags)**: master (3e3cd176f431eaa971ca8014d8bb20ec8f1b4f42), also tried tags/v0.9.0
- **Python version(2.7)**: Python 2.7.12 (default, Dec  4 2017, 14:50:18)
- **Bazel version (e.g., 0.13.0)**: Build label: 0.16.1

### Model deploy file (*.yml)
```yaml
library_name: mobilenet-v2-host
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v2_host:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu
    limit_opencl_kernel_time: 0
    dsp_mode: 0
    obfuscate: 1
    winograd: 0
```

### Describe the problem

I followed the example instruction on compiling the model as written:
```
$ python tools/converter.py run --config=~/mace-models/mobilenet-v2/mobilenet-v2-host.yml --example
```

### To Reproduce
Steps to reproduce the problem:
```bash
$ python tools/converter.py run --config=~/mace-models/mobilenet-v2/mobilenet-v2-host.yml --example
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
* Build //mace/libmace:libmace_static with ABI host
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/libmace:libmace_static (1 packages loaded).
INFO: Found 1 target...
Target //mace/libmace:libmace_static up-to-date:
  bazel-genfiles/mace/libmace/libmace.a
INFO: Elapsed time: 0.718s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

* Build //mace/examples/cli:example_static with ABI host
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/examples/cli:example_static (1 packages loaded).
INFO: Found 1 target...
Target //mace/examples/cli:example_static up-to-date:
  bazel-bin/mace/examples/cli/example_static
INFO: Elapsed time: 0.767s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

ERROR: [RUN] You should convert model first.
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
I didnt install the NDK, to get rid of the ADB error I installed adb from here:
https://askubuntu.com/questions/34702/how-do-i-set-up-android-adb

**Comment by madhavajay** [comment]
Its not my model. Its the default model that comes with the mobilenet-v2-host.yml file and is hosted on the xiaomi website.

Are you telling me the default instructions tell you to use the default model zoo yml files but that they dont work out of the box?

It says explicitly in the documentation that urls can be local or remote so it makes sense that this example uses a remote model on the xiaomi website.

If it needs to be "converted first" then it makes no sense to have a command like the above as part of the "basic usage" documentation.

```
#3. Build a generic MACE library.
cd path/to/mace
# Build library
# output lib path: builds/lib
bash tools/build-standalone-lib.sh
Note

Libraries in builds/lib/armeabi-v7a/cpu_gpu/ means it can run on cpu or gpu devices.
The results in builds/lib/armeabi-v7a/cpu_gpu_dsp/ need HVX supported.

# 4. Convert the pre-trained mobilenet-v2 model to MACE format model.
cd path/to/mace
# Build library
python tools/converter.py convert --config=/path/to/mace-models/mobilenet-v2/mobilenet-v2.yml
```

https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v2/mobilenet-v2-host.yml

**Comment by lydoc** [comment]
I think @liyinhgqw wants to say you should run this command first:
```
python tools/converter.py convert --config=/path/to/mace-models/mobilenet-v2/mobilenet-v2.yml
```
which means convert the pre-trained mobilenet-v2 model to MACE format model, and then, you can run:
```
python tools/converter.py run --config=~/mace-models/mobilenet-v2/mobilenet-v2-host.yml --example
```

**Comment by madhavajay** [comment]
Ah I see the very obvious mistake I have made, I apologise. I looked at it several times but I think by that time I was in need of sleep. Now with fresh eyes its very obvious. Sorry.

Maybe I got confused when skimming by the comment above the line.
It reads:
```
# Build library
```
Which must have been copy and pasted from the above step, during quick scrolling I think I skipped past it.

Perhaps it should be changed to:
```
# Convert Model
```

**Comment by liyinhgqw** [comment]
Make a good point. Thx.
