### ISSUE TITLE
doubt about gpu conv result 

### ISSUE THREAD

**Issue by haolongzhangm** [XiaoMi/mace#177]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
16.04
- **NDK version(e.g., 15c)**:
14b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
eddba255733cb
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
   library_name: squeezenet-v11
  1 target_abis: [arm64-v8a]
  2 model_graph_format: file
  3 model_data_format: file
  4 target_socs: [all]
  5 embed_model_data: 0
  6 build_type: code
  7 models:
  8   squeezenet_v11:
  9     platform: caffe
 10     model_file_path: squeezenet_224x224_new.prototxt
 11     weight_file_path: squeezenet_224x224_new.caffemodel
 12     model_sha256_checksum: 175f83b43c6f1d64978b4cf5f27aad40cde2a8f9a0d621f06a852fe1145c0801
 13     weight_sha256_checksum: 84bc4617d32cd461a4a71922a8149f60d0120688f4cbf1644a183e9766e6699b
 14     subgraphs:
 15       - input_tensors: data
 16         output_tensors: prob
 17         input_shapes: 1,224,224,3
 18         output_shapes: 1,1,1,13
 19     runtime: cpu+gpu
 20     limit_opencl_kernel_time: 0
 21     nnlib_graph_mode: 0
 22     obfuscate: 0
 23     winograd: 0
......
```

### Describe the problem
conv bias logic diff with caffe
at caffe every conv output should share with same bias

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by haolongzhangm** [comment]
create input all data to 0.0 
at cpu side, print out conv+relu data from caffe side as below:
bottom[0][1 64 111 111] data detail: index:0 = 0.023424
bottom[0][1 64 111 111] data detail: index:1 = 0.023424
bottom[0][1 64 111 111] data detail: index:2 = 0.023424
bottom[0][1 64 111 111] data detail: index:3 = 0.023424
bottom[0][1 64 111 111] data detail: index:4 = 0.023424
bottom[0][1 64 111 111] data detail: index:5 = 0.023424
bottom[0][1 64 111 111] data detail: index:6 = 0.023424
bottom[0][1 64 111 111] data detail: index:7 = 0.023424
bottom[0][1 64 111 111] data detail: index:8 = 0.023424
bottom[0][1 64 111 111] data detail: index:9 = 0.023424
bottom[0][1 64 111 111] data detail: index:10 = 0.023424
bottom[0][1 64 111 111] data detail: index:11 = 0.023424
bottom[0][1 64 111 111] data detail: index:12 = 0.023424
bottom[0][1 64 111 111] data detail: index:13 = 0.023424
bottom[0][1 64 111 111] data detail: index:14 = 0.023424
bottom[0][1 64 111 111] data detail: index:15 = 0.023424
bottom[0][1 64 111 111] data detail: index:16 = 0.023424
bottom[0][1 64 111 111] data detail: index:17 = 0.023424
bottom[0][1 64 111 111] data detail: index:18 = 0.023424
bottom[0][1 64 111 111] data detail: index:19 = 0.023424
bottom[0][1 64 111 111] data detail: index:20 = 0.023424
bottom[0][1 64 111 111] data detail: index:21 = 0.023424
bottom[0][1 64 111 111] data detail: index:22 = 0.023424
bottom[0][1 64 111 111] data detail: index:23 = 0.023424
bottom[0][1 64 111 111] data detail: index:24 = 0.023424
bottom[0][1 64 111 111] data detail: index:25 = 0.023424
bottom[0][1 64 111 111] data detail: index:26 = 0.023424
bottom[0][1 64 111 111] data detail: index:27 = 0.023424
bottom[0][1 64 111 111] data detail: index:28 = 0.023424
bottom[0][1 64 111 111] data detail: index:29 = 0.023424
bottom[0][1 64 111 111] data detail: index:30 = 0.023424
bottom[0][1 64 111 111] data detail: index:31 = 0.023424
bottom[0][1 64 111 111] data detail: index:32 = 0.023424
bottom[0][1 64 111 111] data detail: index:33 = 0.023424
bottom[0][1 64 111 111] data detail: index:34 = 0.023424
bottom[0][1 64 111 111] data detail: index:35 = 0.023424
bottom[0][1 64 111 111] data detail: index:36 = 0.023424
bottom[0][1 64 111 111] data detail: index:37 = 0.023424
bottom[0][1 64 111 111] data detail: index:38 = 0.023424
bottom[0][1 64 111 111] data detail: index:39 = 0.023424
bottom[0][1 64 111 111] data detail: index:40 = 0.023424
bottom[0][1 64 111 111] data detail: index:41 = 0.023424
bottom[0][1 64 111 111] data detail: index:42 = 0.023424
bottom[0][1 64 111 111] data detail: index:43 = 0.023424

.....  first output share with the the same bias about "0.023424"

**Comment by haolongzhangm** [comment]
about mace gpu side print output with kernel "in_out_image_to_buffer" after fisrt 3 *3 conv +relu
as below:
bottom[0][1 64 111 111] data detail: index:0 = 0.023424
bottom[0][1 64 111 111] data detail: index:1 = 0.005351
bottom[0][1 64 111 111] data detail: index:2 = 0.015752
bottom[0][1 64 111 111] data detail: index:3 = 0.000000
bottom[0][1 64 111 111] data detail: index:4 = 0.000000
bottom[0][1 64 111 111] data detail: index:5 = 0.009992
bottom[0][1 64 111 111] data detail: index:6 = 0.006196
bottom[0][1 64 111 111] data detail: index:7 = 0.000000
bottom[0][1 64 111 111] data detail: index:8 = 0.000000
bottom[0][1 64 111 111] data detail: index:9 = 0.000000
bottom[0][1 64 111 111] data detail: index:10 = 0.000000
bottom[0][1 64 111 111] data detail: index:11 = 0.000000
bottom[0][1 64 111 111] data detail: index:12 = 0.000899
bottom[0][1 64 111 111] data detail: index:13 = 0.001537
bottom[0][1 64 111 111] data detail: index:14 = 0.000000
bottom[0][1 64 111 111] data detail: index:15 = 0.000380
bottom[0][1 64 111 111] data detail: index:16 = 0.000666
bottom[0][1 64 111 111] data detail: index:17 = 0.000000
bottom[0][1 64 111 111] data detail: index:18 = 0.000000
bottom[0][1 64 111 111] data detail: index:19 = 0.007685
bottom[0][1 64 111 111] data detail: index:20 = 0.000000
bottom[0][1 64 111 111] data detail: index:21 = 0.000000
bottom[0][1 64 111 111] data detail: index:22 = 0.002274
bottom[0][1 64 111 111] data detail: index:23 = 0.000000
bottom[0][1 64 111 111] data detail: index:24 = 0.002632
bottom[0][1 64 111 111] data detail: index:25 = 0.000351
bottom[0][1 64 111 111] data detail: index:26 = 0.004653
bottom[0][1 64 111 111] data detail: index:27 = 0.000073
bottom[0][1 64 111 111] data detail: index:28 = 0.006569
bottom[0][1 64 111 111] data detail: index:29 = 0.000000
bottom[0][1 64 111 111] data detail: index:30 = 0.000000
bottom[0][1 64 111 111] data detail: index:31 = 0.000000
bottom[0][1 64 111 111] data detail: index:32 = 0.009020
bottom[0][1 64 111 111] data detail: index:33 = 0.000235
bottom[0][1 64 111 111] data detail: index:34 = 0.000000
bottom[0][1 64 111 111] data detail: index:35 = 0.000000
bottom[0][1 64 111 111] data detail: index:36 = 0.000000
bottom[0][1 64 111 111] data detail: index:37 = 0.013871
bottom[0][1 64 111 111] data detail: index:38 = 0.000495


from the reslut , we can find the same output  loop pick the bias , do not share with the same bias

**Comment by nolanliou** [comment]
It seems the format of the result is different between MACE and caffe.
