### ISSUE TITLE
请问，目前支持哪些框架的参数转换到mace，分别支持这些框架的哪些OP？

### ISSUE THREAD

**Issue by bigbao9494** [XiaoMi/mace#179]
如题，是否支持mxnet的转换呢？

**Comment by lydoc** [comment]
目前支持tensorflow和caffe的转换，暂时还不支持MXNET的转换：
https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#prepare-your-model
目前支持的op可以参考：
https://mace.readthedocs.io/en/latest/user_guide/op_lists.html
