### ISSUE TITLE
Is graph quantization supported?

### ISSUE THREAD

**Issue by paulgheorghecristian** [XiaoMi/mace#180]
Hello,

I tried converting an inception v3 model to MACE model (which works), but I wanted to also quantize it (by putting quantize: 1 in .yml). I encountered errors by doing so; I realized it needs a "quantize_range_file", but I'm not sure what that is. I tried writing a quantize_range_file as:
"tensor_name@@minVal,maxVal" based on transformer.py, but it still does not work. Could you please provide insight for this quantize range file? Thanks!

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:
android-ndk-r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:
5.4.0
- **MACE version (Use the command: git describe --long --tags)**:
v0.9.0-33-g28f4355
- **Python version(2.7)**: 
2.7.12
- **Bazel version (e.g., 0.13.0)**:
0.16.1

### Model deploy file (*.yml)
```yaml
library_name: inception-v3
target_abis: [host] #armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  inception_v3:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception-v3.pb
    model_sha256_checksum: 632bb664547c846e7b4e44fe6a2ff9e35df277eb6440b80d9b559302baab1b8d
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,299,299,3
        output_tensors:
          - InceptionV3/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu #cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 1
    winograd: 4
    quantize: 1
```

### Describe the problem
Putting quantize: 1 in .yml makes python tools/converter.py convert --config=../mace-models/inception-v3/inception-v3.yml not work.

### To Reproduce
Steps to reproduce the problem:
```bash
1. put quantize: 1 in .yml
2. cd /path/to/mace
3. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
  STDERR:
Traceback (most recent call last):
  File "/home/paul/Work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 319, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/paul/Work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 190, in main
    output_graph_def = mace_transformer.run()
  File "/home/paul/Work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 113, in run
    changed = transformer()
  File "/home/paul/Work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1381, in add_quantize_tensor_range
    wit... (90 more, please see e.stderr)
```

**Comment by lydoc** [comment]
For  converting a model into quantized one, you can refer to:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#eight-bit-calculations
and
https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#prepare-your-model

Also, in our mace models, you can use [inception-v3-dsp.yml](https://github.com/XiaoMi/mace-models/blob/master/inception-v3/inception-v3-dsp.yml) as a deployment file to build the quantized inception-v3 model.

**Comment by paulgheorghecristian** [comment]
Hey, thanks for the reply! Any idea why https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception-v3-q-2016.pb contains an operation that is not supported by MACE? QuantizeV2 is the one and it crashes tensorflow_converter.py at line 262.

**Comment by lydoc** [comment]
@paulgheorghecristian Mace supports QuantizeV2 operation, Could you paste your full log and the model deploy file?

**Comment by paulgheorghecristian** [comment]
@lydoc Ok, so I see that only on DSP you support QuantizeV2 and overall, the quantize operation. Could you please tell me why this is the case?

**Comment by lydoc** [comment]
Yes, Mace supports quantization only on DSP at present, and we will support quantized models on CPU/GPU soon.

**Comment by paulgheorghecristian** [comment]
Thanks a lot! I appreciate your help.
