### ISSUE TITLE
Run demo app failed with fatal error

### ISSUE THREAD

**Issue by Pinnh** [XiaoMi/mace#182]
### System information
Running Platform: Android 7.1.2 (Redmi 5 Plus)

### Describe the problem
All permissions are granted success, but run demo app failed with fatal error.

### To Reproduce
Just install App

### Error information / logs
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.xiaomi.mace.demo, PID: 25178
AndroidRuntime: java.lang.RuntimeException: setParameters failed
AndroidRuntime: 	at android.hardware.Camera.native_setParameters(Native Method)
AndroidRuntime: 	at android.hardware.Camera.setParameters(Camera.java:2045)
AndroidRuntime: 	at com.xiaomi.mace.demo.camera.CameraApiLessM.setOutputConfig(CameraApiLessM.java:112)
AndroidRuntime: 	at com.xiaomi.mace.demo.camera.CameraApiLessM.openCamera(CameraApiLessM.java:45)
AndroidRuntime: 	at com.xiaomi.mace.demo.camera.CameraEngage.onSurfaceTextureAvailable(CameraEngage.java:197)
AndroidRuntime: 	at android.view.TextureView.getHardwareLayer(TextureView.java:390)
AndroidRuntime: 	at android.view.TextureView.draw(TextureView.java:339)
AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16196)
AndroidRuntime: 	at android.view.View.draw(View.java:16980)
...
AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6396)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
octvm_klo: klo lock
WtProcessController: Receive am_crash event for pid: 25178 pkg = com.xiaomi.mace.demo

**Comment by liyinhgqw** [comment]
Can you provide info by grepping results of 'adb logcat'?

**Comment by Pinnh** [comment]
Top erro log information is generated by adb logcat , there is a bug when set size param which in  getSupportedPreviewSizes() that not real support , I debuged the setParameter, width and height is 2048x1080，I set 1920x1080 is no issue，getOptimalSize input w,h is 1080x1826， besides getOptimalSize not get optimal size when compare h/w ratio

**Comment by baijunhui** [comment]
> Top erro log information is generated by adb logcat , there is a bug when set size param which in getSupportedPreviewSizes() that not real support , I debuged the setParameter, width and height is 2048x1080，I set 1920x1080 is no issue，getOptimalSize input w,h is 1080x1826， besides getOptimalSize not get optimal size when compare h/w ratio

camera.getParameters().getSupportedPreviewSizes() size height and width are the opposite, so getOptimalSize input h/w ratio should be change to w/h 

You can also add a mobile phone camera angle judgment.

**Comment by lee-bin** [comment]
Have you @Pinnh tried what @baijunhui suggested and was it resolved?

**Comment by Pinnh** [comment]
resolved
