### ISSUE TITLE
交叉编译出来的gpu库，运行模型时报错Program received signal SIGSEGV, Segmentation fault。

### ISSUE THREAD

**Issue by leeburt** [XiaoMi/mace#184]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.10
NDK version(e.g., 15c):15c
GCC version(if compiling for host, e.g., 5.4.0): GCC 5.4.0
MACE version (Use the command: git describe --long --tags): master
Python version(2.7): 2.7
Bazel version (e.g., 0.13.0):0.13.0

### Model deploy file (*.yml)
# The name of library
library_name: openposecaffe_128
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  openposecaffe_128: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # support local path, http:// and https://
    model_file_path: /home/songbiao/libo/model/openpose/caffe/openpose_pose_coco_128.prototxt
    weight_file_path: /home/songbiao/libo/model/openpose/caffe/openpose_pose_coco_128.caffemodel
    # sha256_checksum of your model's graph and data files.
    # get the sha256_checksum: sha256sum path/to/your/file
    model_sha256_checksum: 44f5ced31607736661bc4d66c4b9a6fcfca436f3df0110b106105fc83031c140
    weight_sha256_checksum: b4cf475576abd7b15d5316f1ee65eb492b5c9f5865e70a2e7882ed31fb682549
    # define your model's interface
    # if there multiple inputs or outputs, write like blow:
    # subgraphs:
    # - input_tensors:
    #     - input0
    #     - input1
    #   input_shapes:
    #     - 1,224,224,3
    #     - 1,224,224,3
    #    output_tensors:
    #      - output0
    #      - output1
    #    output_shapes:
    #      - 1,1001
    #      - 1,1001
    subgraphs:
      - input_tensors:
          - image
        input_shapes:
          - 1,128,128,3
        output_tensors:
          - Mconv7_stage6_L2
        output_shapes:
          - 1,16,16,19
    runtime: cpu+gpu
    winograd: 0

### Describe the problem
运行时错。

### To Reproduce
https://github.com/zhy520xp/mace-makefile-project在这个 基础上编译了master版本的mace的gpu版本。通过最新的mace转换的cpu+gpu模型文件，运行gpu版本时报错。

### Error information / logs
=====>>>>>start to CreateMaceEngineFromProto
I ../mace/libmace/mace.cc:426] Create MaceEngine from model pb
I ../mace/libmace/mace.cc:203] Creating MaceEngine, MACE version: v0.9.0-12-gba4157f-20180828
I ../mace/libmace/mace.cc:280] Loading Model Data
I ../mace/libmace/mace.cc:211] Initializing MaceEngine
W/Adreno-CB (31408): <isCLProfilingEnabled:2130>: PROFILER: (cl) Unable to load q3dtools library /usr/lib/libq3dtools.so (2599992)

W/Adreno-CB (31408): <isCLProfilingEnabled:2130>: PROFILER: (cl) Unable to load q3dtools library /usr/lib/libq3dtools.so (2600096)

I ../mace/utils/tuner.h:147] There is no tuned parameters.
[New Thread 0xa93f8440 (LWP 31447)]
[New Thread 0xa8bf8440 (LWP 31448)]
=====>>>>>end to CreateMaceEngineFromProto

Program received signal SIGSEGV, Segmentation fault.
0xab50912e in cl_object_is_valid () from /usr/lib/libCB.so
(gdb) bt
#0  0xab50912e in cl_object_is_valid () from /usr/lib/libCB.so
#1  0xab4fac66 in cl_image_is_valid () from /usr/lib/libCB.so
#2  0xab5047e4 in cb_set_kernel_arg () from /usr/lib/libCB.so
#3  0x000cc6c8 in clSetKernelArg ()
#4  0x001195dc in mace::kernels::PoolingFunctor<(mace::DeviceType)2, half_float::half>::operator()(mace::Tensor const*, mace::Tensor*, mace::StatsFuture*) ()
#5  0x00095dce in mace::ops::PoolingOp<(mace::DeviceType)2, half_float::half>::Run(mace::StatsFuture*) ()
#6  0x0002289a in mace::SerialNet::Run(mace::RunMetadata*) ()
#7  0x00016efa in mace::MaceEngine::Impl::Run(std::map<std::string, mace::MaceTensor, std::less<std::string>, std::allocator<std::pair<std::string const, mace::MaceTensor> > > const&, std::map<std::string, mace::MaceTensor, std::less<std::string>, std::allocator<std::pair<std::string const, mace::MaceTensor> > >*, mace::RunMetadata*) ()
#8  0x0000d740 in main ()

**Comment by yejw5** [comment]
@leeburt 可以向这个项目的开发人员提问
