### ISSUE TITLE
Keras模型转换后CPU模式下的deconv_2d的output_shape计算有错误，GPU模式正常

### ISSUE THREAD

**Issue by minizon** [XiaoMi/mace#185]
------------------------

### System information
使用的是默认的docker镜像
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**: 
- **MACE version (Use the command: git describe --long --tags)**: master
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Describe the problem
问题1.
利用keras训练U-Net模型，之后h5->pb->mace
在windows的android studio下构建demo使用GPU模式可以正常运行，但是CPU模型报错
/kernels/deconv_2d.h 193-194行MACE_CHECK(expected_input_width == in_width, expected_input_width, "!=", in_width);
检查后发现GPU下输出
Check failed: isNCHW input shape 1 4 3 256 output shape 1 8 6 256, stride shape 2 2
而CPU下输出 input shape 1 256 4 3 output shape 1 512 8 256, stride shape 2 2
网络结构：
    1x8x6x256    -->concat[...   1x8x6x256]  -> [1x8x6x512]
_________|  ->       1x4x3x256   ->  |conv2dtranspose

conv_pw_102_relu/Relu6 (Activation): [[1L, 256L, 4L, 3L]]
conv2d_transpose_1/Shape (Shape): [[4L]]
conv2d_transpose_1/strided_slice (StridedSlice): [[]]
conv2d_transpose_1/strided_slice_1 (StridedSlice): [[]]
conv2d_transpose_1/mul (ScalarMath): [[]]
conv2d_transpose_1/strided_slice_2 (StridedSlice): [[]]
conv2d_transpose_1/mul_1 (ScalarMath): [[]]
conv2d_transpose_1/stack (Stack): [[4L]]
conv2d_transpose_1/conv2d_transpose (Deconv2D): [[1L, 256L, 8L, 6L]]
conv2d_transpose_1/BiasAdd (BiasAdd): [[1L, 256L, 8L, 6L]]
concatenate_1/concat (Concat): [[1L, 512L, 8L, 6L]]
conv_dw_103/depthwise (DepthwiseConv2d): [[1L, 512L, 8L, 6L]]
  
大致看出GPU使用了和tensorflow一样的NHWC格式，而CPU使用了caffe的NCHW，但是在计算反卷积时CPU的模式出现了问题
另外在/kernels/deconv_2d.h  265行 改成了          paddings_.data(), false); 即tf下CalcDeconvPaddingAndInputSize 的isNCHW=false

问题2.
GPU模式下输出值范围不在[0,1]之间，我的模型是以Activation('sigmoid')作为输出，但是JniMaceUtils.maceMobilenetClassify(input)得到的结果需要加sigmoid函数才符合要求，编译时有提示
Remove identity: output_0(Identity)
Fold biasadd: conv2d_1/convolution(Conv2D)
Fold activation: BiUpsampling/conv2d_transpose(Deconv2D)   <--该层为输出激励函数前一层

**Comment by TonyMou** [comment]
CPU下Shape的bug已经fix了，代码近期会更新。

**Comment by yejw5** [comment]
@minizon bug已经fix，可以拉取最新代码测试
