### ISSUE TITLE
convert model reported error:"ProtoCompile third_party/caffe/caffe_pb2.py failed (Exit 1): protoc failed"

### ISSUE THREAD

**Issue by feixuedudiao** [XiaoMi/mace#189]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.11.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
when I convert mobilenet_v1 model with mace new version, it reported abow error:
* Generate mace engine creator source
Generate mace engine creator source done!

***************************************************
          Convert mobilenet_v1_host model          
***************************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/video/user/sunjf/code/mace_official/mace-master/third_party/caffe/BUILD:13:1: ProtoCompile third_party/caffe/caffe_pb2.py failed (Exit 1): protoc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/3f057ed8e0515311f39c885db3e1e095/execroot/mace && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/lib \
    PATH=/usr/local/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  bazel-out/k8-fastbuild/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/k8-fastbuild/genfiles/' -I. -Iexternal/com_google_protobuf/python -Ibazel-out/k8-fastbuild/genfiles/external/com_google_protobuf/python third_party/caffe/caffe.proto)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_protobuf/python: warning: directory does not exist.
third_party/caffe/caffe.proto: No such file or directory

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
/home/video/user/sunjf/code/mace_official/mace-master# python tools/converter.py convert --config=/home/video/user/sunjf/code/mace_official/mace-master/models/mobilenet-v1-host.yml 
----------------------------------------
          Common Configuration          
----------------------------------------
|        key        |      value       |
========================================
|       library_name| mobilenet-v1-host|
----------------------------------------
|        target_abis|          ['host']|
----------------------------------------
|        target_socs|                []|
----------------------------------------
| model_graph_format|              code|
----------------------------------------
|  model_data_format|              code|
----------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

***************************************************
          Convert mobilenet_v1_host model          
***************************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/video/user/sunjf/code/mace_official/mace-master/third_party/caffe/BUILD:13:1: ProtoCompile third_party/caffe/caffe_pb2.py failed (Exit 1): protoc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/3f057ed8e0515311f39c885db3e1e095/execroot/mace && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/lib \
    PATH=/usr/local/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  bazel-out/k8-fastbuild/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/k8-fastbuild/genfiles/' -I. -Iexternal/com_google_protobuf/python -Ibazel-out/k8-fastbuild/genfiles/external/com_google_protobuf/python third_party/caffe/caffe.proto)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_protobuf/python: warning: directory does not exist.
third_party/caffe/caffe.proto: No such file or directory
Target //mace/python/tools:converter failed to build
INFO: Elapsed time: 0.352s, Critical Path: 0.11s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

Traceback (most recent call last):
  File "tools/converter.py", line 1763, in <module>
    flags.func(flags)
  File "tools/converter.py", line 846, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 771, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/video/user/sunjf/code/mace_official/mace-master/tools/sh_commands.py", line 563, in gen_model_code
    bazel_build_common("//mace/python/tools:converter")
  File "/home/video/user/sunjf/code/mace_official/mace-master/tools/sh_commands.py", line 391, in bazel_build_common
    _err_to_out=True)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/bazel build //mace/python/tools:converter

  STDOUT:

  STDERR:

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by yejw5** [comment]
@feixuedudiao Please format your log description firstly. And could offer your .yml file contents? Did you pull the latest code?
