### ISSUE TITLE
Linux环境下编译linux-x86-64版本出错

### ISSUE THREAD

**Issue by daishiwen** [XiaoMi/mace#190]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (Linux Ubuntu 18.04 LTS)**:
- **NDK version(15c)**:
- **GCC version(7.3.0)**:
- **MACE version (v0.9.0-136-g7f9612d3)**:
- **Python version(2.7.15rc1)**: 
- **Bazel version (0.15.1)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
今天刚从官网down的代码，commit：379c730d3032757fd2b43e3932787f500c1d5e44，
分支为master。
紧接着进入mace工程的根目录，执行./tools/build-standalone-lib.sh 当编译linux-x86-64版本时会抛出如下错误，前后试了十多遍，依旧不行。期间试过`bazel clean --expunge`和`sudo rm -rf /home/user/.cache/bazel/`方法。

arm64-v8a和armeabi-v7a版本可以正常输出，但我们期望得到linux-x86-64版本的动态或静态库。
这个问题卡了我好久，希望小米的大神们能给予援助，不胜感激~~

build shared lib for linux-x86-64
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
...........
v0.9.0-136-g7f9612d3-20180911
INFO: Analysed target //mace/libmace:libmace_dynamic (22 packages loaded).
INFO: Found 1 target...
ERROR: /home/baidu/Desktop/mace/mace/core/BUILD:20:1: C++ compilation of rule '//mace/core:core' failed (Exit 1): gcc failed: error executing command 
  (cd /home/baidu/.cache/bazel/_bazel_baidu/ef47d5e8e549a8a59e368ce13a3cd72e/execroot/mace && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/lib: \
    PATH=/usr/lib/jvm/jdk1.8.0_11/bin:/usr/lib/jvm/jdk1.8.0_11/jre/bin:/home/baidu/Documents/android-studio/bin:/home/baidu/Documents/pycharm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/baidu/Android/Sdk/ndk-bundle:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/mace/core/_objs/core/mace/core/runtime/cpu/cpu_runtime.pic.d '-frandom-seed=bazel-out/k8-opt/bin/mace/core/_objs/core/mace/core/runtime/cpu/cpu_runtime.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/genfiles/external/com_google_protobuf -iquote external/gemmlowp -iquote bazel-out/k8-opt/genfiles/external/gemmlowp -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_OPENMP -DMACE_USE_NNLIB_CAF -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers -fopenmp -DMACE_ENABLE_OPENMP -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mace/core/runtime/cpu/cpu_runtime.cc -o bazel-out/k8-opt/bin/mace/core/_objs/core/mace/core/runtime/cpu/cpu_runtime.pic.o)

Use --sandbox_debug to see verbose messages from the sandbox
mace/core/runtime/cpu/cpu_runtime.cc: In function 'mace::MaceStatus mace::GetCPUBigLittleCoreIDs(std::vector<int>*, std::vector<int>*)':
mace/core/runtime/cpu/cpu_runtime.cc:102:12: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 5 [-Werror=format-truncation=]
 MaceStatus GetCPUBigLittleCoreIDs(std::vector<int> *big_core_ids,
            ^~~~~~~~~~~~~~~~~~~~~~
mace/core/runtime/cpu/cpu_runtime.cc:102:12: note: directive argument in the range [0, 2147483647]
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6349,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /usr/include/c++/7/array:39,
                 from /usr/include/c++/7/tuple:39,
                 from /usr/include/c++/7/bits/stl_map.h:63,
                 from /usr/include/c++/7/map:61,
                 from ./mace/public/mace.h:22,
                 from ./mace/core/runtime/cpu/cpu_runtime.h:20,
                 from mace/core/runtime/cpu/cpu_runtime.cc:15:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: '__builtin_snprintf' output between 29 and 38 bytes into a destination of size 32
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
cc1plus: all warnings being treated as errors
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 128.288s, Critical Path: 18.03s
INFO: 218 processes: 218 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by jliu22** [comment]
No problem:
https://github.com/jliu22/blogs/blob/master/mace_build_log_x86_64.txt

I made one more steps:
~/mace# python ./mace/python/tools/encrypt_opencl_codegen.py
Generate OpenCL kernel done.

**Comment by yejw5** [comment]
@daishiwen 我们还未尝试过在ubuntu18上编译mace，由于编译器版本更高，warning可能不同，可以先去掉编译里的`-Werror`选项，或者我们这边测试过ubuntu18之后fix这些报错。

**Comment by yejw5** [comment]
@daishiwen 这个问题我们已经[fix](https://github.com/XiaoMi/mace/commit/51ca5d0d77f2b45d320aebedd7dc66d37f347444)， 可以拉取最新代码测试。issue先关闭了，后续有问题可以在打开
