### ISSUE TITLE
any plan to support GPU upsampling layer?

### ISSUE THREAD

**Issue by haolongzhangm** [XiaoMi/mace#192]
any plan to support GPU upsampling layer?

**Comment by llhe** [comment]
@haolongzhangm Is https://github.com/XiaoMi/mace/blob/master/mace/kernels/opencl/cl/resize_bilinear.cl or https://github.com/XiaoMi/mace/blob/master/mace/kernels/opencl/cl/resize_bicubic.cl what you want?

**Comment by haolongzhangm** [comment]
@llhe  看了下你提供的两个kernel， 似乎和caffe的upsampling 有一些微小的差异
caffe的实现: 
cpu:https://github.com/alexgkendall/caffe-segnet/blob/segnet-cleaned/src/caffe/layers/upsample_layer.cpp

gpu: https://github.com/alexgkendall/caffe-segnet/blob/segnet-cleaned/src/caffe/layers/upsample_layer.cu

上面的代码和你提供的kernel代码的差异主要有两点：
1：
caffe这个放大图像对应点的坐标是通过 pooling 层生成的mask 得到的
caffe pooling生成mask 的代码参考如下：
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp

2：
upsampling 并没有做插值的动作

**Comment by llhe** [comment]
这个upsample层只是一个第三方的自定义实现，目前没有计划支持。

**Comment by llhe** [comment]
可以采用反卷积，并固定特定的参数来替代resize做训练。导出模型修改成resize即可。使用反卷积近似resize，也是[caffe官方文档](https://caffe.berkeleyvision.org/doxygen/classcaffe_1_1BilinearFiller.html#details)里面的推荐方式。
