### ISSUE TITLE
Successful in CPU mode but fail to use the GPU mode macecamera A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid ... (inference)

### ISSUE THREAD

**Issue by minizon** [XiaoMi/mace#194]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
Docker-full
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**: master
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Describe the problem
This time I've made success in running the cpu mode, but failed to run the model in GPU mode.

### Error information / logs
09-13 21:02:45.312 16466-16466/? I/art: Late-enabling -Xcheck:jni
09-13 21:02:45.324 16466-16466/? D/TidaProvider: TidaProvider()
09-13 21:02:45.334 16466-16466/? V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
    mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
    mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
    mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
    mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
09-13 21:02:45.338 16466-16466/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@fb3814a
09-13 21:02:45.498 16466-16466/com.example.macecamera I/InstantRun: starting instant run server: is main process
09-13 21:02:45.566 16466-16498/com.example.macecamera W/linker: /data/app/com.example.zhoulei3.macecamera-2/lib/arm64/libmace_mobile_jni.so: unused DT entry: type 0xf arg 0x13634
09-13 21:02:45.574 16466-16498/com.example.macecamera I/APPModel: maceMobilenetCreateGPUContext result = 0
09-13 21:02:45.576 16466-16498/com.example.macecamera I/image_classify attrs: gpu perf: 3, priority: 3
    device: 2
09-13 21:02:45.585 16466-16498/com.example.macecamera I/MACE: mace.cc:400 Creating MaceEngine, MACE version: unknown-20180913
09-13 21:02:45.621 16466-16498/com.example.macecamera I/MACE: mace.cc:421 Initializing MaceEngine
09-13 21:02:45.644 16466-16466/com.example.macecamera D/ActivityThreadInjector: clearCachedDrawables.
09-13 21:02:45.661 16466-16503/com.example.macecamera I/Adreno: QUALCOMM build                   : dd15ef5, Ic280a69317
    Build Date                       : 05/09/17
    OpenGL ES Shader Compiler Version: XE031.09.00.04
    Local Branch                     : 
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING

09-13 21:02:46.633 16466-16501/com.example.macecamera A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16501 (inference)

**Comment by yejw5** [comment]
Please provide full messages as ISSUE_TEMPLATE.md

**Comment by minizon** [comment]
Sorry, I've carefully made a compilation for the mace libs and the model, this time it works fine for the GPU mode.
