### ISSUE TITLE
 Some wrong of Tensorflow model convert to Mace model

### ISSUE THREAD

**Issue by ruyiweicas** [XiaoMi/mace#196]
1、I used docker to install mace, so i can make sure the environment is ok
2、I forzen ckpt to pb model,i can run the pb model on server successful. Then i use tensorflow graph optimize the model ,but when i convert the pb model to mace model ,some wrong was happen.

The Error LOG  is 
```
root@localhost:/mace# python tools/converter.py convert --config=/model/hg.yml
/usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size 

··· （_delete some log Info ,full log info can find in attachment_ ）

Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 144, in main
    output_graph_def = converter.run()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 217, in run
    self.convert_ops()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 262, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 473, in convert_fused_batchnorm
    var_value + epsilon_value)) * gamma_value)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 2042, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1998, in _get_ufunc_and_otypes
    raise ValueError('cannot call `vectorize` on size 0 inputs '
ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/model/hourglass_op.pb --weight_file= --model_checksum=8ecc9eb73770d27d736f3fc2340353c71ba047d2749f3f4042ee1bb1e05c470a --weight_checksum= --input_node=inputs/input_img --output_node=model/final_output --runtime=cpu+gpu --template=mace/python/tools --model_tag=HG --input_shape=1,256,256,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/HG --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:

```

### PS: tensorflow graph command is 
```
./bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
    --in_graph=/model/hg.pb \
    --out_graph=/model/hg_op.pb \
    --inputs='inputs/input_img' \
    --outputs='model/final_output' \
    --transforms='
        strip_unused_nodes(type=float, shape="1,256,256,3")
        remove_nodes(op=Identity, op=CheckNumerics)
        fold_constants(ignore_errors=true)
        flatten_atrous_conv
        fold_batch_norms
        remove_control_dependencies
        strip_unused_nodes
        sort_by_execution_order'
```

3、I put  the required files for each step of model transformation on [baidunet disk](https://pan.baidu.com/s/1jrW0_SpkubIy_4Kn9cybMA), The directory is shown below

hg model is finetune form https://github.com/wbenbihi/hourglasstensorlfow

│  hg.pb                   (ckpt forzen to hg.pb)   
│  hg_op.pb             (tensorflow graph op hg.pb to hg_op.pb )
│  hg_op.yml            (yml file for deploy)
│  tensorboard.png (tensorboard graph)
│
├─ckpt  
│      hg_DogIris_8pts_200.data-00000-of-00001
│      hg_DogIris_8pts_200.index
│      hg_DogIris_8pts_200.meta
│
└─convert2pb      ( convert ckpt 2 pb)
      │     convert_pb.py
     └─    create_tf_record.py

## Something i confused about 
 i can run the pb model on my server,but when i convert the model to mace model, numpy tell me model error ,I am not sure whether my conversion is wrong or the problem of mace code ,i sincerely hope that i can get your help,thx

**Comment by oneTaken** [comment]
can you provide a brief model information? The error logs seems to be wrong when dealing with the BN layer.

**Comment by ruyiweicas** [comment]
@oneTaken  yes ,I put the required files for each step of model transformation on [baidunet disk](https://pan.baidu.com/s/1jrW0_SpkubIy_4Kn9cybMA), The directory is shown below

**Comment by ruyiweicas** [comment]
![image](https://user-images.githubusercontent.com/14344027/45730459-48ad2d00-bc04-11e8-9b68-3aeb5991600f.png)

Thanks to @pengzuiji ，i find the problem is is_training=true in BN layer

**Comment by ruyiweicas** [comment]
@oneTaken  Can MACE provide Support for Switch?
![image](https://user-images.githubusercontent.com/14344027/45792646-3d6c0700-bcc1-11e8-8ba0-91d60233483f.png)

**Comment by llhe** [comment]
@ruyiweicas No, you can check the supported list: https://mace.readthedocs.io/en/latest/user_guide/op_lists.html.

You should make sure you model is frozen with https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

**Comment by ruyiweicas** [comment]
@llhe thx，The Switch is ubiquitous in the facenet， maybe I need to change the network structure
