### ISSUE TITLE
请问mace-model中有训练好的objection detection的模型吗

### ISSUE THREAD

**Issue by outlookerr** [XiaoMi/mace#197]
如题，请给一些建议

**Comment by lydoc** [comment]
很快将支持MobileNet SSD，后续会支持更多的目标检测模型。

**Comment by leeburt** [comment]
@lydoc 后期支持的Mobilenet-ssd可以用gpu吗？

**Comment by lydoc** [comment]
@leeburt 有个别op不支持GPU

**Comment by leeburt** [comment]
@lydoc 谢谢你的回答，请问是不是可以理解因为个别op不支持所以Mobilenet-ssd不能在gpu上跑？还是说Mobilenet-ssd可以在gpu上跑但是有个别op不支持gpu。

**Comment by madhavajay** [comment]
What is the ETA on this and is there anything that can be done to help?

**Comment by lydoc** [comment]
@lydoc 个别op不支持，所以不能完全地在gpu上跑

**Comment by lydoc** [comment]
@madhavajay It will be completed soon. Welcome to contribute code.

**Comment by madhavajay** [comment]
@lydoc Awesome! I am currently testing the arm_linux stuff which isn't working for me. However I did a PR to improve the Python3 handling of the encrypted opencl jinja2 template.

Is there anything specific you need help with. Do you have a WIP branch somewhere?

**Comment by madhavajay** [comment]
@lydoc Do you have twitter or email, I would like to understand whats involved with the MobileNet SSD stuff and help out!

**Comment by xiaqing10** [comment]
hope object detection models come soon.

**Comment by waltner** [comment]
I would also be very interested. Any status update as to the progress within the last two months?

**Comment by lydoc** [comment]
Yolo-v3 and SSD-Mobilenet models has been pushed to model zoo now. ( https://github.com/XiaoMi/mace-models )
