### ISSUE TITLE
fast-style-transfer get wrong result on Huawei Mate 10 Pro with GPU, CPU result is correct

### ISSUE THREAD

**Issue by xiuchen** [XiaoMi/mace#204]
------------------------
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux AI-Host-154 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **NDK version(e.g., 15c)**: r17b
- **GCC version(if compiling for host, e.g., 5.4.0)**: gcc version 5.4.0 20160609
- **MACE version (Use the command: git describe --long --tags)**:  v0.9.0-193-g51ca5d0
- **Python version(2.7)**:  2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Model deploy file (*.yml)
```fast_style_transfer_la_muse.yml in mace-models/fast-style-transfer

### Describe the problem
1. fast-style-transfer get wrong result on Huawei Mate 10 Pro with GPU, CPU result is correct.
2. for anohter model I modified from fast-style-transfer, only  replace each convolution with depthwise convolution & pointwise convolution in fast-style-transfer model , but the result is not correct, both on GPU and CPU , in both Huawei Mate 10 pro ( soc kirin970 ) and Samsung S9 (soc sdm845), and the result run on GPU is different with result run on CPU, 
the network like : depthwise conv -> pointwise conv -> instance norm -> depthwise conv -> pointwise conv -> instance norm -> ..... 
the output in second pointwise convolution is different with output in tensorflow, but the input & weights are the same.

please check this problem. thanks

**Comment by xiuchen** [comment]
@TonyMou 

1.  I only tested  fast-style-transfer la_muse  model before I sumit this issue, and today I test fast-style-transfer scream model, following is the validation result of scream model run on Huawei Mate 10 pro with GPU, CPU result is correct:
img_placeholder [1, 480, 640, 3]
add_37 MACE VS TENSORFLOW similarity: 0.911967000125
ERROR: [] ******************************************
          Similarity Test Failed
******************************************

2. I can not provide my own model currently, you can easily get one with  code in https://github.com/lengstrom/fast-style-transfer with little modification

**Comment by TonyMou** [comment]
@xiuchen, the above problems have the same cause. Instance-norm has a squared-diff op which may produce out-of-range results when the input data is not normalized, because on gpu runtime we use half datatype by default. We'll find a way to fix this. Thanks for your share.

**Comment by TonyMou** [comment]
already resolved.
