### ISSUE TITLE
Support Caffe Op Scale

### ISSUE THREAD

**Issue by ziyu-zhang** [XiaoMi/mace#205]
Would it be possible to support the Scale operation in Caffe?

**Comment by nolanliou** [comment]
It is possible, but there is no plan yet. Contribution is welcome.

**Comment by llhe** [comment]
@ziyu-zhang Can this Scale layer be fused with BatchNorm?

**Comment by ziyu-zhang** [comment]
@llhe We're converting Caffe models, and in Caffe I believe BatchNorm layer doesn't support in-layer scaling...

**Comment by yejw5** [comment]
@ziyu-zhang Can you provide a testing model?

**Comment by yejw5** [comment]
@ziyu-zhang Did the Scale op act on BatchNorm results? If yes, BatchNorm + Scale layer will be comprised to fused BatchNorm layer in Mace.

**Comment by ziyu-zhang** [comment]
@yejw5 Let me get back to you soon. In my prototxt, Scale always follow a BatchNorm, but Mace seems to give error messages. I'll send you a toy example that reproduces my problem soon. Thank you for your help and patience.

**Comment by yuanyuanli85** [comment]
@ziyu-zhang you can try to use merge_bn.py from https://github.com/chuanqi305/MobileNet-SSD to fuse batchnorm+scale into conv explictily.

**Comment by ziyu-zhang** [comment]
@yejw5 @yuanyuanli85 @llhe I apologize for the late reply. Our caffe model has a Scale layer following a non-BatchNorm layer. That's why the error message persists: `Exception: Mace does not support caffe op type Scale yet`.

**Comment by kweisamx** [comment]
@yuanyuanli85 May I ask you, if I convert prototxt by merge.bn.py, the caffe model don't so anything right?

**Comment by yuanyuanli85** [comment]
@kweisamx mrege_bn.py need to take both prototxt and caffe model.  If you convert prototxt only and don't change caffe model accordingly, the network will not work.

**Comment by yejw5** [comment]
@ziyu-zhang OK. I will add `Scale` to Mace lately.

**Comment by yejw5** [comment]
@ziyu-zhang Caffe Op `Scale` is supported now. You can have a try.
