### ISSUE TITLE
团队成员没有中国人吗？

### ISSUE THREAD

**Issue by zeroonestring** [XiaoMi/mace#21]
团队成员没有中国人吗？为什么没有中文文档？

**Comment by jambillking** [comment]
好像没有，

**Comment by llhe** [comment]
还没时间写文档，等稳定了再考虑

**Comment by zeroonestring** [comment]
可能你们是国际范吧，我感觉既然是中国团队，应该必须有中文，而且这个中文文档应该是第一时间出来的。

**Comment by BUG1989** [comment]
Reading English documents is the basic skillof a programmer

**Comment by zeroonestring** [comment]
唉！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
