### ISSUE TITLE
mace::MaceTensor constructor.

### ISSUE THREAD

**Issue by TKNgu** [XiaoMi/mace#211]
Why mace::Mace Tensor constructor need std::shared_ptr<float> when can user float * ?.  mace::Mace Tensor not create data show it can't free it. 
I build a RAII object to processing data use one memory for anytime processing.

https://stackoverflow.com/questions/6675651/when-should-i-use-raw-pointers-over-smart-pointers
P/S Sorry for my English.

**Comment by liyinhgqw** [comment]
It defends useful data not to be destroyed by users during mace run.
