### ISSUE TITLE
FOLD_ACTIVATION leads to wrong results if deconv is followed by sigmoid and there is no bias in the deconv layer

### ISSUE THREAD

**Issue by ziyu-zhang** [XiaoMi/mace#212]
I'm attaching a few files to reproduce the bug:

* `generate_frozen_pb.py` which constructs, initializes and freezes a simple neural network of one deconv layer (no bias) followed by a sigmoid layer
* `debug_fold_activation.frozen.pb` which is generated from the the previous .py file
* `config.yml` which specifies the config to run the previous .pb file

If FOLD_ACTIVATION is on (which is the default way), validation won't pass. If FOLD_ACTIVATION is off, validation passes.

[debug_fold_activation.zip](https://github.com/XiaoMi/mace/files/2435851/debug_fold_activation.zip)

**Comment by TonyMou** [comment]
@gwangsc @ziyu-zhang, this is a bug, thanks for your sharing. we'll update master branch to fix this. Or you can just fix this by changing line 37-38 in mace/ops/deconv_2d.h to the following:

```
kernels::StringToActivationType(
                 0.0f) {}
                     OperatorBase::GetOptionalArg<std::string>("activation",
                                                               "NOOP")),
                 OperatorBase::GetOptionalArg<float>("max_limit", 0.0f)) {}
```
