### ISSUE TITLE
Deconv2dGeneral thread safety 

### ISSUE THREAD

**Issue by herbakamil** [XiaoMi/mace#217]
I'm thinking if the current implementation is correct with respect to race conditions.

Because we have:
`#pragma omp parallel for collapse(4)`
`    for (int b = 0; b < batch; ++b) {`
`      for (int oc = 0; oc < out_channels; ++oc) {`
`        for (int i = 0; i < in_height; ++i) {`
`          for (int j = 0; j < in_width; ++j) {`
and operation
`out_base[out_idx] += val * filter[kernel_idx];`
might be called from different threads so it could happen that out_base[out_idx]  is read and increased by 2 threads at the same time and looks as if we could loose some additions.

Is it design decision to sacrifice thread safety for speed or maybe there are some mechanisms which prevent this behaviour?

**Comment by TonyMou** [comment]
The `out_idx` in each thread is different.

**Comment by herbakamil** [comment]
But out_idx is sum of base which is indeed different and shift for each kernel element so it looks as if two different threads could have the same out_idx

**Comment by TonyMou** [comment]
```
#pragma omp parallel for collapse(4)
    for (int b = 0; b < batch; ++b) {
      for (int oc = 0; oc < out_channels; ++oc) {
        for (int i = 0; i < in_height; ++i) {
          for (int j = 0; j < in_width; ++j) {
            float *out_base =
                output + (b * out_channels + oc) * out_img_size;
            const index_t out_offset =
                i * strides[0] * out_width + j * strides[1];
            for (int ic = 0; ic < in_channels; ++ic) {
              const index_t input_idx =
                  (b * in_channels + ic) * in_img_size + i * in_width + j;
              const float val = input[input_idx];
              const index_t kernel_offset =
                  (oc * in_channels + ic) * kernel_size;
              for (int k = 0; k < kernel_size; ++k) {
                const index_t out_idx = out_offset + index_map[k];
                const index_t kernel_idx = kernel_offset + k;
                out_base[out_idx] += val * filter[kernel_idx];
              }
            }
          }
        }
      }
    }
```
Only the first four loops will be paralleled because of the 'collapse(4)', so each block in these four loops will independently calculate a deconv output value. In other words, different threads will operate out_base on different offsets.

**Comment by herbakamil** [comment]
let's consider b=oc=i=0, kernel 3x3 with stride 1 and j = 0 and j = 1

val for i=j=0 * kernel[0] (I guess there's some reversal of filter values on some earlier stage because index_map has only positive values and they're added - but I will ignore it for simplicity)
and val for i=0 j=1 * kernel[2] need to be added the same out_idx by definition of deconvolution

and it seems as these two blocks could be run parallel.

**Comment by llhe** [comment]
@herbakamil Thanks for reporting, this is an thread safety issue, we will roll back the related change to fix it.

**Comment by llhe** [comment]
Fixed by https://github.com/XiaoMi/mace/commit/7e2e776f7701eb02401e43cf12173a88eb8364ef
