### ISSUE TITLE
I want to add new op "permute" , but have some issue in permute.cl

### ISSUE THREAD

**Issue by dlkdqpi** [XiaoMi/mace#218]
the c++ code like this :
if(OrderType::HWC == order_type_){ // whc -> hwc
#pragma omp parallel for   
            for(index_t b = 0; b < batch; ++b){
                for (index_t c = 0; c < channels; ++c){
                    for(index_t w = 0; w < width; ++w){
                        for(index_t h = 0; h < height; ++h){
                            index_t input_offset = b * batch + c * channels
                                + h * width + w;
                            index_t output_offset = b * batch + c * channels
                                + w * height + h;
                            output_ptr[output_offset] = input_ptr[input_offset];
                        }
                    }
                }
            }
        }
If I want to use OpenCL to implement the relevant code , how shall I do?

**Comment by liyinhgqw** [comment]
You need implement an OpenCL kernel, please refer to `kernels/opencl/cl/channel_shuffle.cl`
