### ISSUE TITLE
customer hardware mace porting

### ISSUE THREAD

**Issue by xmmxkk** [XiaoMi/mace#221]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:       Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:           Rcar tool chain
- **GCC version(if compiling for host, e.g., 5.4.0)**:      aarch64-poky-linux-gcc -v  gcc version 7.3.0 (GCC)
- **MACE version (Use the command: git describe --long --tags)**:   I mace/core/mace.cc:377] Creating MaceEngine, MACE version: v0.9.0-213-g68518b9-20180928
- **Python version(2.7)**:    2.7
- **Bazel version (e.g., 0.13.0)**:    0.13.0

### Model deploy file (*.yml)
```yaml              mace-models/mobilenet-v1/mobilenet-v1.yml   
......
```

### Describe the problem
在rcar上验证mace框架正确性

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

参考了https://github.com/zhy520xp/mace-makefile-project工程

想请教一下将mace移植到其他嵌入式平台的思路问题：
1，剥离源码
       我这边先基于tools/aarch64_compiler 编译链将mace项目编译通过，然后将生成文件中的bazel-out/aarch64-fastbuild/genfiles/mace/codegen/ 中的encrypt_opencl_kernel.cc  version.cc
以及mace.proto生成的mace.pb.h， mace.pb.cc拷贝到组建目录的codegen中，目录结构保持不变，同时将mace/mace下的core， kernels， libmace，ops，proto，utils中的代码保持原目录结构剥离出来，组建基于makefile的工程；
2，组建makefile工程
编辑makefile，core，kernels，等目录下的测试文件以及benchmark测试文件没有包含进来，头文件和外部依赖库文件protobuf3.4.0交叉编译的库提出来，和gemmlowp 加到include文件下，同时opencl的头文件以及half.hpp 组织好也放到include目标下，基于目标平台的toolchain将整个项目编译通过后。
3， 验证框架的正确性
    结合example.cc 和上述git中unit_test_gpu中的实现，调用编译出调用该工程的可执行文件，在目标平台下运行，log如下：
=====>>>>>start to CreateMaceEngineFromProto
I mace/core/mace.cc:619] Create MaceEngine from model pb
I mace/core/mace.cc:377] Creating MaceEngine, MACE version: v0.9.0-213-g68518b9-20180928
NOTE: This GSX library has the time limitation by reason of an evaluation module.
I mace/core/mace.cc:473] Loading Model Data
I mace/core/mace.cc:403] Initializing MaceEngine
=====>>>>>end to CreateMaceEngineFromProto
=====>>>>>Warm up Run Model spend time:9725 ms
=====>>>>>Normal Run Model spend time:39 ms

I mace/core/mace.cc:492] Destroying MaceEngine
对于dog.npy的推理置信度是错误的，打印出来非0值均为0.062500；

1，想请问这样做思路是否可行？？
2，部分生成的cc文件在基于tools/aarch64_compiler编译的时候没有生成，如tuning/tuning_params.cc,是否会影响mace库的正常运行？
3，模型转换能否直接基于bazel toolchain为tools/aarch64_compiler编译通过的相同版本进行转换？
4，如果出现上述结果异常，有啥好的办法调试么？
希望各位大神能在思路上指导一下，拜谢！！

**Comment by llhe** [comment]
@xmmxkk rcar是什么系统？

**Comment by xmmxkk** [comment]
rcar是瑞萨的一款硬件，是运行在linux系统上面；https://elinux.org/R-Car/Boards/Salvator-X
这款soc有一个PowerVR™GX6650的gpu,想将mace在这个soc上运行起来！请教大佬，上述思路是否可行？

**Comment by llhe** [comment]
开发板很快会有官方支持，可以先参考 https://github.com/XiaoMi/mace/issues/36 里面的编译命令`bazel build --config arm_linux --define openmp=true --define opencl=true --define neon=true //mace/libmace:libmace.so --sandbox_debug`。

如果还有精度问题，不排除是GPU的兼容性问题，需要进一步看一下。

**Comment by xmmxkk** [comment]
@llhe I found the main error of mobilenet-v1 inference the dog.npy but get wrong results, mainly because the model deployment file, I set the runtime: gpu  when test on GPU. after change to runtime: cpu+gpu, it get the right results. close this isse
