### ISSUE TITLE
Does mace support tf.image.resize_bilinear ?

### ISSUE THREAD

**Issue by minizon** [XiaoMi/mace#223]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker-full
- **NDK version(e.g., 15c)**: 15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: docker-full
- **MACE version (Use the command: git describe --long --tags)**: master
- **Python version(2.7)**:  docker-full
- **Bazel version (e.g., 0.13.0)**: docker-full

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
When I replace the Conv2DTranspose of keras in a model with a custom layer containing the tf.image.resize_bilinear, the tools/converter.py fails

### Error information / logs

Transform model to one that can better run on device
/usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/usr/local/lib/python2.7/dist-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/usr/local/lib/python2.7/dist-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/usr/local/lib/python2.7/dist-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/usr/local/lib/python2.7/dist-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/usr/local/lib/python2.7/dist-packages/scipy/ndimage/measurements.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _ni_label
Traceback (most recent call last):
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 352, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 165, in main
    output_graph_def = converter.run()
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 241, in run
    self.convert_ops(session)
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 292, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 595, in convert_resize_bilinear
    size_value = tf_op.inputs[1].eval().astype(np.int32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 710, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 5180, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,256,192,3]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,256,192,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]**

Caused by op u'input_1', defined at:
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 352, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 154, in main
    option, FLAGS.model_file)
  File "/home/mace-1016/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 231, in __init__
    tf.import_graph_def(tf_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 513, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 303, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3540, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3428, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,256,192,3]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,256,192,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Traceback (most recent call last):
  File "tools/converter.py", line 1778, in <module>
    flags.func(flags)
  File "tools/converter.py", line 856, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 781, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/mace-1016/tools/sh_commands.py", line 601, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc

### Additional context
The custom layer is attached.
[custom_layer_upsampling2d.zip](https://github.com/XiaoMi/mace/files/2483091/custom_layer_upsampling2d.zip)

**Comment by llhe** [comment]
It's supported, and you need to freeze your model first as described in the docs to avoid this kind of error:
```
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,256,192,3]
[[Node: input_1 = Placeholderdtype=DT_FLOAT, shape=[1,256,192,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
```

**Comment by minizon** [comment]
@llhe I think the model is already frozen before conversion, because if I use the conv2dtranspose to do the upsampling, the tools/converter.py works. The relevant codes and models are attached.

[mace.zip](https://github.com/XiaoMi/mace/files/2486365/mace.zip)

**Comment by lydoc** [comment]
I think maybe you use just the GraphDef(*.pb) which do not include weights information. Could you use SavedModel and try again? And you can also attach the conv2dtranspose model.

**Comment by minizon** [comment]
@lydoc I don't think so. I used the pipeline keras h5-to-pb to generate the pb file, the weights are stored in the file. You can try the conv2dtranspose model attached, it goes through the whole conversion process.
[mace.zip](https://github.com/XiaoMi/mace/files/2548222/mace.zip)

**Comment by yuanyuanli85** [comment]
@minizon I meet this kind of error before. In my case, I used the graph_transform tool with "remove_device remove_control_dependencies ", and that solved my problem.

**Comment by minizon** [comment]
@lydoc Can you give more instructions in details?

I printed the relevant ops in that graph.
<tf.Operation 'conv_pw_17_relu/Relu6' type=Relu6>, <tf.Operation 'up_sampling2d_5/Shape' type=Shape>, <tf.Operation 'up_sampling2d_5/strided_slice' type=StridedSlice>, <tf.Operation 'up_sampling2d_5/mul' type=Mul>, <tf.Operation 'up_sampling2d_5/ResizeBilinear' type=ResizeBilinear>, <tf.Operation 'concatenate_5/concat' type=ConcatV2>

```
>>> tf.get_default_graph().get_operation_by_name('up_sampling2d_5/ResizeBilinear').inputs[0]
<tf.Tensor 'conv_pw_17_relu/Relu6:0' shape=(?, 64, 48, 8) dtype=float32>
>>> tf.get_default_graph().get_operation_by_name('up_sampling2d_5/ResizeBilinear').inputs[1]
<tf.Tensor 'up_sampling2d_5/mul:0' shape=(2,) dtype=int32>
>>> with tf.Session():
...     tf.get_default_graph().get_operation_by_name('up_sampling2d_5/ResizeBilinear').inputs[1].eval()
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,256,192,3]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,256,192,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

>>> tf.get_default_graph().get_operation_by_name('up_sampling2d_5/mul').inputs[0]
<tf.Tensor 'up_sampling2d_5/strided_slice:0' shape=(2,) dtype=int32>

>>> tf.get_default_graph().get_tensor_by_name('concatenate_5/concat:0')
<tf.Tensor 'concatenate_5/concat:0' shape=(?, 128, 96, 16) dtype=float32>
```

And in keras I think the shape of each layer is already defined. 
```
conv_pw_17_relu (Activation)    (None, 64, 48, 8)    0           conv_pw_17_bn[0][0]              
__________________________________________________________________________________________________
up_sampling2d_5 (UpSampling2D)  (None, 128, 96, 8)   0           conv_pw_17_relu[0][0]            
__________________________________________________________________________________________________
concatenate_5 (Concatenate)     (None, 128, 96, 16)  0           up_sampling2d_5[0][0]            
                                                                 conv1_relu[0][0]  
```

In the file custom_layer_upsampling2d.py, the function resize_image() calculates the shape using
```
original_shape = K.int_shape(x)
new_shape = tf.shape(x)[rows:cols + 1]
new_shape *= tf.constant(np.array([height_factor, width_factor], dtype='int32'))
```
So do you mean that I have to give a specific number for the shape, instead of inferring from the previous layer?

**Comment by lydoc** [comment]
@minizon Yes, in your custom graph, you have the certain shape of each layer, so you could use a specific number for the shape as a const input, instead of a tensor calculated by the previous arguments.

**Comment by minizon** [comment]
@lydoc Thank you very much.
