### ISSUE TITLE
 Build did NOT complete successfully when bash tools/build-standalone-lib.sh

### ISSUE THREAD

**Issue by jolinlinlin** [XiaoMi/mace#224]
I followed https://mace.readthedocs.io/en/latest/installation/env_requirement.html to build environment for Mace, but I met a problem when bash tools/build-standalone-lib.sh
build shared lib for armeabi-v7a + cpu_gpu_dsp
WARNING: Processed legacy workspace file /home/zhoulin/MACE/mace/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Analysed target //mace/libmace:libmace_dynamic (27 packages loaded).
INFO: Found 1 target...
INFO: From Executing genrule @opencl_clhpp//:gen_opencl_clhpp:
/tmp/opencl-clhpp-build.vEWNGyU6FS /home/zhoulin/.cache/bazel/_bazel_zhoulin/671bf24f8bc59d331bccb3d5f212ccb5/sandbox/linux-sandbox/2/execroot/mace
/tmp/opencl-clhpp-build.vEWNGyU6FS/build /tmp/opencl-clhpp-build.vEWNGyU6FS /home/zhoulin/.cache/bazel/_bazel_zhoulin/671bf24f8bc59d331bccb3d5f212ccb5/sandbox/linux-sandbox/2/execroot/mace
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/opencl-clhpp-build.vEWNGyU6FS/build
Scanning dependencies of target generate_clhpp
[100%] Rebuilding cl.hpp ...
[100%] Built target generate_clhpp
Scanning dependencies of target generate_cl2hpp
[100%] Rebuilding cl2.hpp ...
[100%] Built target generate_cl2hpp
/tmp/opencl-clhpp-build.vEWNGyU6FS /home/zhoulin/.cache/bazel/_bazel_zhoulin/671bf24f8bc59d331bccb3d5f212ccb5/sandbox/linux-sandbox/2/execroot/mace
/home/zhoulin/.cache/bazel/_bazel_zhoulin/671bf24f8bc59d331bccb3d5f212ccb5/sandbox/linux-sandbox/2/execroot/mace
installing to bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp
ERROR: /home/zhoulin/MACE/mace/mace/libmace/BUILD:47:1: Linking of rule '//mace/libmace:libmace.so' failed (Exit 1): clang failed: error executing command 
  (cd /home/zhoulin/.cache/bazel/_bazel_zhoulin/671bf24f8bc59d331bccb3d5f212ccb5/execroot/mace && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64 \
    PATH=/usr/local/cuda-9.0/bin:/home/zhoulin/bin:/home/zhoulin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/android-ndk-r15c \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -shared -o bazel-out/armeabi-v7a-opt/bin/mace/libmace/libmace.so '-Wl,-rpath,$ORIGIN/../../_solib_armeabi-v7a/_U_S_Sthird_Uparty_Snnlib_Clibhexagon___Uthird_Uparty_Snnlib' -Lbazel-out/armeabi-v7a-opt/bin/_solib_armeabi-v7a/_U_S_Sthird_Uparty_Snnlib_Clibhexagon___Uthird_Uparty_Snnlib -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/libmace/liblibmace.lo -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/ops/libops.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/kernels/libkernels.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/core/libcore.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/codegen/libgenerated_version.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/proto/libmace_cc.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/libprotobuf_lite.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/codegen/libgenerated_opencl.a -Wl,-no-whole-archive -lhexagon_controller -Wl,-whole-archive bazel-out/armeabi-v7a-opt/bin/mace/utils/libutils.a -Wl,-no-whole-archive external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a -Wl,-soname,libmace.so -Wl,--version-script mace_version_script.lds -lm -ldl -lm -llog -static-libgcc -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -no-canonical-prefixes -target armv7-none-linux-androideabi -Wl,--fix-cortex-a8 -Wl,--strip-all -Wl,--gc-sections -static-libgcc '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm')

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: no such file or directory: 'mace_version_script.lds'
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 211.588s, Critical Path: 39.73s
INFO: 319 processes: 319 linux-sandbox.
FAILED: Build did NOT complete successfully

I don't konw why and how to do with it. Can anyone help me?Thank you very much!

**Comment by yejw5** [comment]
@jolinlinlin Please refer to [issue template](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)

The building termination may be caused by bazel >= 0.17.0. You can downgrade bazel env for a test.

**Comment by jolinlinlin** [comment]
@yejw5 Thank you very much.I have solved this problem.

**Comment by jolinlinlin** [comment]
@yejw5 Thank you very much. My bazel version is 0.18.0, and I have solved this problem ,but I met another problem when run bash tools/build-standalone-lib.sh:
build shared lib for armeabi-v7a + cpu_gpu_dsp
WARNING: Processed legacy workspace file /home/zhoulin/MACE/mace/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
Starting local Bazel server and connecting to it...
INFO: Analysed target //mace/libmace:libmace_dynamic (27 packages loaded).
INFO: Found 1 target...
Target //mace/libmace:libmace_dynamic up-to-date (nothing to build)
INFO: Elapsed time: 186.141s, Critical Path: 34.76s
INFO: 99 processes: 99 linux-sandbox.
INFO: Build completed successfully, 101 total actions
build shared lib for armeabi-v7a + cpu_gpu
WARNING: Processed legacy workspace file /home/zhoulin/MACE/mace/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/libmace:libmace_dynamic (0 packages loaded).
INFO: Found 1 target...
Target //mace/libmace:libmace_dynamic up-to-date (nothing to build)
INFO: Elapsed time: 142.342s, Critical Path: 27.82s
INFO: 99 processes: 99 linux-sandbox.
INFO: Build completed successfully, 101 total actions
build shared lib for arm64-v8a + cpu_gpu
WARNING: Processed legacy workspace file /home/zhoulin/MACE/mace/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/libmace:libmace_dynamic (0 packages loaded).
INFO: Found 1 target...
Target //mace/libmace:libmace_dynamic up-to-date (nothing to build)
INFO: Elapsed time: 9.207s, Critical Path: 3.25s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
build shared lib for linux-x86-64
WARNING: Processed legacy workspace file /home/zhoulin/MACE/mace/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
ERROR: Invalid options syntax: -cxxopt=-std=c++11
Do you have any suggestion?

**Comment by oneTaken** [comment]
I got same problem too.
And my bazel version is 0.18.0.
After downgrading to 0.13.1, it works well.

**Comment by jolinlinlin** [comment]
@oneTaken Thank you very much.I have figured it out.
