### ISSUE TITLE
Does Mace running on Arm with Ubuntu OS

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#229]
Hi , Can I run libmace on ubuntu machine with ARM CPU ?
How to change build script to compile library ?
Thanks.

**Comment by llhe** [comment]
@dimitryn Would you want to make a local compiling or using a cross compiling?

Now we provide a Linaro cross toolchain which can produce both ARM 32/64 ABI. And we are working on the tools to make this process same as Android build.

If you just want a local build, which you need is to enable NEON or OpenCL options which is now only applied to Android.

**Comment by dimitryn** [comment]
Hi @llhe  , we local compiling + NEON on ubuntu

**Comment by llhe** [comment]
You can try whether this works:
```
bazel build --define openmp=true --define opencl=true --define neon=true //mace/libmace:libmace.so --sandbox_debug
```

Or using the built-in cross compiler (will be integrated into converter.py soon), for example, arm-linux-gnueabihf:
```
bazel build --config arm_linux --define openmp=true --define opencl=true --define neon=true //mace/libmace:libmace.so --sandbox_debug
```

**Comment by dimitryn** [comment]
Thanks.
