### ISSUE TITLE
Dose mace support half now?

### ISSUE THREAD

**Issue by weiliangdashen** [XiaoMi/mace#230]
I know there is half type interface in MACE, but it seems not working because of the followings:
1. Many kinds of layers just use DtToUpCompatibleCLDt while build OpenCL program, which force the type to be float.
2.Many kinds of layers use DtToUpCompatibleCLDt while input type different from output type. Won't this cause error while using a float pointer to access the underlying half data?
3.According to the OpenCL1.2 specification, half type can not be derefrenced using *p, but in the kernel the half type pointer is derefrenced while DATA_TYPE is half.
So does MACE support half type or run some half model correctly now?

**Comment by nolanliou** [comment]
Not now.
The default way is half-type storage and float-type computation(fp16_fp32), the loss of some models' precision is not acceptable with half-type computation. Actually, the half-type computation could be supported for users to choose. The contribution is welcome.

**Comment by xmmxkk** [comment]
@nolanliou “The default way is half-type storage and float-type computation”，means caffe or tensorflow model should save in half-float-precision way  before convert to mace model  ???   

or it means the mace convert tools will  convert the model （which saved in float-precision ）to  a half-float-precision mace-model???

**Comment by llhe** [comment]
@xmmxkk MACE convert tool will do this conversion.

**Comment by xmmxkk** [comment]
@llhe thanks for your reply!!   ^_^
the option "data_type" in .yml file ，if set it to "fp16_fp32", MACE convert tool will save the converted model in fp16, and if set it to "fp32_fp32", MACE convert tool will save the converted model in fp32, my understanding is right?
I found the  mace model with option "data_type " set to "fp16_fp32" or "fp32_fp32" get totally different result for the same input?  the fp32_fp32 model get the right result, same as caffe framework, but the result of fp16_fp32 seems wrong? is it normal?

**Comment by liyinhgqw** [comment]
Duplicated with
https://github.com/XiaoMi/mace/issues/236
