### ISSUE TITLE
opencl_runtime.cc:667 error: CL_INVALID_PROGRAM

### ISSUE THREAD

**Issue by dlkdqpi** [XiaoMi/mace#234]
com.xiaomi.mace.demo E/MACE: opencl_runtime.cc:667 error: CL_INVALID_PROGRAM
新加了个op，运行时提示这个错误。
但是我从打印出来的log看，没有找到什么问题：
   net.cc:74  Running operator  S_Pooling1(Pooling)
    opencl_runtime.cc:655 built +++++ : name：pooling  ---key: pooling -DCMD_DATA_TYPE=f -DDATA_TYPE=float -DPOOL_AVG -Dpooling=p453171
    net.cc:74  Running operator  S_PadChannel1(PadChannel)
    opencl_runtime.cc:655 built +++++ : name：pad_channel  ---key: pad_channel -DCMD_DATA_TYPE=f -DDATA_TYPE=float -Dpad_channel=pquhv1v9_2_
10-25 19:56:43.240 3766-3785/com.xiaomi.mace.demo E/MACE: opencl_runtime.cc:666 error: CL_INVALID_PROGRAM

**Comment by liyinhgqw** [comment]
Can you past your patch?

**Comment by dlkdqpi** [comment]
#include "mace/kernels/pad_channel.h"
#include "mace/core/runtime/opencl/opencl_runtime.h"
#include "mace/kernels/opencl/helper.h"
#include "mace/utils/tuner.h"
#include "mace/utils/utils.h"

namespace mace {
namespace kernels {

template <typename T>
MaceStatus PadChannelFunctor<DeviceType::GPU, T>::operator()(
    const Tensor *input,
    Tensor *output,
    StatsFuture *future){
    //MACE_CHECK();

    auto input_shape = input->shape();
    std::vector<index_t> output_shape = {
        input_shape[0],
        input_shape[1],
        input_shape[2],
        input_shape[3] + this->num_channels_to_pad_};

    std::vector<size_t> image_shape;
    CalImage2DShape(output_shape, BufferType::IN_OUT_CHANNEL, &image_shape);
    MACE_RETURN_IF_ERROR(output->ResizeImage(output_shape, image_shape));

    const index_t batch = output->dim(0);
    const index_t height = output->dim(1);
    const index_t width = output->dim(2);
    const index_t channels = output->dim(3);

    const index_t channel_blocks = RoundUpDiv4(channels);

    auto runtime = context_->device()->opencl_runtime();

    //  set operate
    if (kernel_.get() == nullptr) {
        std::set<std::string> built_options;
        OUT_OF_RANGE_CONFIG(kernel_error_, context_);
        NON_UNIFORM_WG_CONFIG;
        std::string kernel_name = MACE_OBFUSCATE_SYMBOL("pad_channel");
        built_options.emplace("-Dpad_channel=" + kernel_name);
        auto dt = DataTypeToEnum<T>::value;
        built_options.emplace("-DDATA_TYPE=" + DtToUpCompatibleCLDt(dt));
        built_options.emplace("-DCMD_DATA_TYPE=" + DtToUpCompatibleCLCMDDt(dt));
        
        MACE_RETURN_IF_ERROR(runtime->BuildKernel("pad_channel",
                                                kernel_name,
                                                built_options,
                                                &kernel_));
        kwg_size_ =
            static_cast<uint32_t>(runtime->GetKernelMaxWorkGroupSize(kernel_));
    }

    const uint32_t gws[3] = {static_cast<uint32_t>(channel_blocks),
                            static_cast<uint32_t>(width),
                            static_cast<uint32_t>(height * batch)};

    // set argument
    if (!IsVecEqual(input_shape_, input->shape())) {
        uint32_t idx = 0;
        OUT_OF_RANGE_SET_ARG;
        SET_3D_GWS_ARGS(kernel_);
        kernel_.setArg(idx++, *(input->opencl_image()));
        kernel_.setArg(idx++, *(output->opencl_image()));
        kernel_.setArg(idx++, static_cast<int32_t>(input_shape[3]));
//        kernel_.setArg(idx++, static_cast<int32_t>(output_shape[1]));
        kernel_.setArg(idx++, this->num_channels_to_pad_);

        input_shape_ = input->shape();
    }

    const std::vector<uint32_t> lws = Default3DLocalWS(runtime, gws, kwg_size_);
    
    std::string tuning_key =
        Concat("pad_channel_opencl_kernel_", output->dim(0), output->dim(1),
            output->dim(2), output->dim(3));
    MACE_RETURN_IF_ERROR(TuningOrRun3DKernel(runtime, kernel_, tuning_key,
                                           gws, lws, future));
    OUT_OF_RANGE_VALIDATION(kernel_error_);

    return MACE_SUCCESS;
}

template struct PadChannelFunctor<DeviceType::GPU, float>;
template struct PadChannelFunctor<DeviceType::GPU, half>;
}  // namespace kernels
}  // namespace mace

**Comment by dlkdqpi** [comment]
pad_channel.cl ：
#include <common.h>
// Supported data types: half/float
__kernel void pad_channel(KERNEL_ERROR_PARAMS
                      GLOBAL_WORK_GROUP_SIZE_DIM3
                      __read_only image2d_t input,
                      __private const int input_channel,
                      __private const int num_channels_to_pad,
                      __write_only image2d_t output){
    // current data/tile position
    const int chan_idx = get_global_id(0);
    const int width_idx = get_global_id(1);
    const int hb_idx = get_global_id(2);

#ifndef NON_UNIFORM_WORK_GROUP
    if (chan_idx >= global_size_dim0 || width_idx >= global_size_dim1
        || hb_idx >= global_size_dim2) {
        return;
    }
#endif

    const int out_width = global_size_dim1;
    
    const int pos = mad24(chan_idx, out_width, width_idx);

    DATA_TYPE4 data = 0;
    if(chan_idx <= input_channel){
        data = READ_IMAGET(input,
                            SAMPLER,
                            (int2)(pos,hb_idx));
    }

    WRITE_IMAGET(output, (int2)(pos, hb_idx), data);
}

**Comment by liyinhgqw** [comment]
The OpenCL kernel args' order is not consistent with what you set.

**Comment by dlkdqpi** [comment]
>           The OpenCL kernel args' order is not consistent with what you set.
I adjusted the sequence of parameters. But it's not work. Error is still the same

**Comment by nolanliou** [comment]
Have you add the path of OpenCL kernel file to the file https://github.com/XiaoMi/mace/blob/master/repository/opencl-kernel/opencl_kernel_configure.bzl?

**Comment by dlkdqpi** [comment]
> https://github.com/XiaoMi/mace/blob/master/repository/opencl-kernel/opencl_kernel_configure.bzl

Yes,you are right. thank you very much.
