### ISSUE TITLE
converted mace-models/squeezenet.v10.yml with “data_type: fp16_fp32” or “data_type: fp32_fp32” , get totaly completely different result for same input   on PowerVR Rogue GX6650 GPU, why?

### ISSUE THREAD

**Issue by xmmxkk** [XiaoMi/mace#236]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:    cross compile
- **GCC version(if compiling for host, e.g., 5.4.0)**:   gcc version 7.3.0 (GCC)
- **MACE version (Use the command: git describe --long --tags)**:  MACE version: v0.9.0-213-g68518b9-20180928
- **Python version(2.7)**:  2.7
- **Bazel version (e.g., 0.13.0)**:
0.13.0

### Model deploy file (*.yml)
```yaml
...... mace-models/squeezenet.v10.yml
```
with different "data_type: fp32_fp32" and "data_type: fp16_fp32" at the end of the .yml file

### Describe the problem

runing  mace-models/squeezenet.v10.yml converted with different data_type options ,fp16_fp32  and fp32_fp32 , but got totoaly different result for the same input. 227x227x3 buffer subtract the channel-mean value.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```
runing  mace-models/squeezenet.v10.yml converted with different data_type options ,fp16_fp32  and fp32_fp32 , but got totoaly different result for the same input. 227x227x3 buffer subtract the channel-mean value formated in NHWC.

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

mace/models/mobilenet-v2 converted with data_type options ,fp16_fp32  and fp32_fp32 get approximately the same results,  but all the other caffe model  i tested on mace get the same phenomenon.  the performace are also different. fp16_fp32 mace model is faster than fp32_fp32.
what‘s wrong？？  Any suggestion will be appreciate!

**Comment by nolanliou** [comment]
fp16_fp32 stands for the tensor storage type with float16 and calculation with float32, which is faster than fp32_fp32, and a little difference is also reasonable.
