### ISSUE TITLE
How to build without Docker

### ISSUE THREAD

**Issue by mychina75** [XiaoMi/mace#24]
Hi, there
Thank you for your amazing work.

I can not access the docker server, so, are there solution to build without docker?
And I can not find the example about how to use caffe model. 
Would  you please make more introduction about caffe model usage? Thank you so much~

**Comment by nolanliou** [comment]
We will update the document soon.

**Comment by nolanliou** [comment]
https://github.com/XiaoMi/mace-models/blob/master/vgg16/vgg16-caffe-gpu.yml

**Comment by llhe** [comment]
The document was updated and aliyun docker registry was provided.
