### ISSUE TITLE
cannot locate symbol "__kmpc_fork_call"

### ISSUE THREAD

**Issue by opyk** [XiaoMi/mace#240]
Using android ndk to call the libmace.so library, the error of the not locate symbol "__kmpc_fork_call" appears.
I have added
LOCAL_CFLAGS += -fopenmp
LOCAL_LDFLAGS += -fopenmp

But it is useless。
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”
OS Platform and Distribution（window eclipse）
NDK version(15c):
GCC version(if compiling for host, e.g., 5.4.0):
MACE version (v0.9.0  release):
Python version(2.7):
Bazel version (e.g., 0.13.0):
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”
Model deploy file（mobilenet_v1.yml）
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”
Eclipse uses jni to call the officially compiled libmace.so library, showing an error：
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__kmpc_fork_call" referenced by "/data/app/com.example.mace2-1/lib/arm/libmace.so"...
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”
android.mk（Part）
"""""""""""""""""
LOCAL_LDLIBS += -landroid -llog 
LOCAL_CXXFLAGS += -fopenmp
LOCAL_CFLAGS += -fopenmp
LOCAL_LDLIBS += -llog -fopenmp
 
LOCAL_SHARED_LIBRARIES += mace
""""""""""""""""""""""""""""""
Application.mk
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”
APP_CPPFLAGS += -frtti -std=c++11 -fexceptions 
APP_ABI := armeabi-v7a
APP_STL := gnustl_static
NDK_TOOLCHAIN_VERSION = 4.9
APP_PLATFORM := android-16
APP_CFLAGS += -fexceptions -frtti -std=c++11
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”

**Comment by lee-bin** [comment]
1. Please reformat your issue according to https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md
2. Did you use the same NDK to compile libmace.so and your application ?

**Comment by lee-bin** [comment]
1. How did you set NDK for libmace.so?
2. How did you set NDK for your application in Eclipse?

**Comment by lee-bin** [comment]
Closing. Feel free to reopen.
