### ISSUE TITLE
Mace model protection benefits .

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#241]
Hi ,
What benefits you can tell if we will use your model protection solution over other's independent solutions.
Thanks.

**Comment by lee-bin** [comment]
Model protection has been the highest priority since the beginning of MACE design. Various techniques are introduced like converting models to C++ code and literal obfuscations.

**Comment by dimitryn** [comment]
Hi @lee-bin ,
Yes , Are you consider converting model to C++ code as STRONG protection ?

**Comment by lee-bin** [comment]
I do not consider it an absolutely safe protection, but it would definitely increase the difficulties of hacking and prevent random developers to peep at.

**Comment by dimitryn** [comment]
ok, thanks
