### ISSUE TITLE
encoded question:transform tensorflow model into mace model 

### ISSUE THREAD

**Issue by z397164725** [XiaoMi/mace#244]
### System information
- **OS Platform and Distribution (Ubuntu 16.04):
- **Python version(3.6):
- **Jinja2 version (2.10):

### Model deploy file (*.yml)
library_name: test
target_abis: [armeabi-v7a]
model_graph_format: code
model_data_format: code

### Describe the problem
Execute "python tools/converter.py convert --config_file=/path/to/your/model_deployment_file" to transform tensorflow model into mace model:
When the format is “file”, it is normal. When the format is “code”, it is abnormal.

### Modify
/mace-master/mace/python/tools/mace_engine_factory_codegen.py
/mace-master/mace/python/tools/model_saver.py
with open(*****, "wb") as f:
            f.write(**source.encode('utf-8').strip()**)

/mace-master/tools/converter.py
def convert_model(configs, cl_mem_type):
    ……
    if configs[YAMLKeyword.model_graph_format] == ModelFormat.code:
        os.makedirs(model_header_dir)     
        sh_commands.gen_mace_engine_factory_source(
            **list(configs[YAMLKeyword.models].keys())**,
            embed_model_data)
        sh.cp("-f", glob.glob("mace/codegen/engine/*.h"),
              model_header_dir)
    ……

/mace-master/mace/python/tools/operator.jinja2
void CreateOperator{{i}}(mace::OperatorDef *op) {
    ……
    {%- if arg.HasField('s') %}
    arg->set_s({{ **arg.s|string|tojson** }});
    {%- endif %}
    ……

**Comment by nolanliou** [comment]
Could you paste the error log?

**Comment by z397164725** [comment]
--------------------------------------
         Common Configuration         
--------------------------------------
|        key        |     value      |
======================================
|       library_name|             test|
--------------------------------------
|        target_abis| ['armeabi-v7a']|
--------------------------------------
|        target_socs|              []|
--------------------------------------
| model_graph_format|            code|
--------------------------------------
|  model_data_format|            code|
--------------------------------------

* Generate mace engine creator source
@@@@@@@@@@@@@@@@@@@@@@@@@@@@
dict_keys(['cpm_v1'])
True
Traceback (most recent call last):
  File "tools/converter.py 

", line 1739, in <module>
    flags.func(flags)
  File "tools/converter.py 

", line 888, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py 

", line 761, in convert_model
    embed_model_data)
  File "/home/ww/njc/code/mace-master/tools/sh_commands.py 

", line 428, in gen_mace_engine_factory_source
    codegen_tools_dir)
  File "mace/python/tools/mace_engine_factory_codegen.py 

", line 38, in gen_mace_engine_factory
    embed_model_data=embed_model_data,
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/site-packages/jinja2/asyncsupport.py 

", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/site-packages/jinja2/environment.py 

", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/site-packages/jinja2/environment.py 

", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/site-packages/jinja2/_compat.py 

", line 37, in reraise
    raise value.with_traceback(tb)
  File "mace/python/tools/mace_engine_factory.h.jinja2", line 46, in top-level template code
    std::make_pair({{ model_tags[i]|tojson }}, {{ i }}),
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/site-packages/jinja2/filters.py 

", line 1078, in do_tojson
    return htmlsafe_json_dumps(value, dumper=dumper, **options)
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/site-packages/jinja2/utils.py 

", line 565, in htmlsafe_json_dumps
    rv = dumper(obj, **kwargs) \
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/json/encoder.py 

", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/json/encoder.py 

", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ww/anaconda3/envs/tensorflow-gpu36/lib/python3.6/json/encoder.py 

", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Undefined' is not JSON serializable

**Comment by z397164725** [comment]
/mace-master/mace/python/tools/operator.jinja2
void CreateOperator{{i}}(mace::OperatorDef *op) {
……
{%- if arg.HasField('s') %}
arg->set_s({{ arg.s|tojson }});
{%- endif %}
……

Modify

/mace-master/mace/python/tools/operator.jinja2
void CreateOperator{{i}}(mace::OperatorDef *op) {
……
{%- if arg.HasField('s') %}
arg->set_s({{ arg.s.decode()|tojson }});
{%- endif %}
……
