### ISSUE TITLE
DECONV 为什么没有kernel= 2x2 stride = 2 的neon 实现?

### ISSUE THREAD

**Issue by victorygogogo** [XiaoMi/mace#251]
DECONV 为什么没有kernel= 2x2 stride = 2 的neon 实现???

如果没有 deconv22 能否以deconv 33 44 那样的方式实现？

**Comment by victorygogogo** [comment]
@nolanliou   who can help me ?

**Comment by TonyMou** [comment]
可以参考下3x3s2或4x4s2

**Comment by victorygogogo** [comment]
@TonyMou 
参考了，计算出来结果不对呢。
需要做什么特殊处理吗？

**Comment by victorygogogo** [comment]
@TonyMou   按照下面的方式进行实现
         for (; j < w; j++) {
            float val = in[0];
            for (int k = 0; k < 2; ++k) {
              out_row_0[k] += val * k0[k];
              out_row_1[k] += val * k1[k];
            }
            in++;
            out_row_0 += 2;
            out_row_1 += 2;
          }
思想都是一样的，deconv22  一个输入对应着四个输出。

**Comment by TonyMou** [comment]
已经在测试中，很快会上线

**Comment by TonyMou** [comment]
master分支已经更新支持了

**Comment by victorygogogo** [comment]
@TonyMou    这种实现方式 input和weights 按照nchw 方式访问的吗 ？
