### ISSUE TITLE
ERROR: Config value android is not defined in any .rc file

### ISSUE THREAD

**Issue by mooc179** [XiaoMi/mace#255]
bash tools/build-standalone-lib.sh error:
build shared lib for armeabi-v7a + cpu_gpu_dsp
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/xyh/C:/mace/tools/bazel.rc
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
ERROR: Config value android is not defined in any .rc file

**Comment by lee-bin** [comment]
Duplicated with https://github.com/XiaoMi/mace-models/issues/9
Already fixed in 838754361d56d7956979c3e032497f118dcf4a43
