### ISSUE TITLE
请问mace支持gpu版本的mobilenetssd模型吗？

### ISSUE THREAD

**Issue by yangfei963158659** [XiaoMi/mace#259]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lydoc** [comment]
location，confidence，priorbox的特征提取支持GPU操作，最后的detection output 层仅支持cpu操作。

**Comment by yangfei963158659** [comment]
priorbox op的cl代码是哪个文件呢？

**Comment by yangfei963158659** [comment]
我在cl目录下没找到与priorbox相关的cl代码

**Comment by lydoc** [comment]
@yangfei963158659 不好意思刚刚答复有误，priorbox也是在cpu上生成的，priorbox之前的特征输入都可以在GPU上做。

**Comment by yangfei963158659** [comment]
嗯，好的。谢了

**Comment by yangfei963158659** [comment]
mace除了能支持小米手机的gpu，还能支持别的手机的gpu吗？我在oppo手机上跑gpu的demo的时候，会抛出java.lang.UnsatisfiedLinkError: dlopen failed: library "/vendor/lib/libOpenCL.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"。。网上说是android N以后，限制了程序对系统私有库的访问。导致libOpenCL.so加载不起来

**Comment by yejw5** [comment]
@yangfei963158659 其他手机只要能够找到opencl的动态库就可以支持

**Comment by yangfei963158659** [comment]
我的oppo手机里有libOpenCL.so库。但是在跑demo的时候一直提示java.lang.UnsatisfiedLinkError: dlopen failed: library "/vendor/lib/libOpenCL.so" 。网上说是android N以后，限制了程序对系统私有库的访问。导致libOpenCL.so加载不起来，不知道有没有什么解决方法

**Comment by yejw5** [comment]
这个还真没遇到过，库的路径是对的吧
