### ISSUE TITLE
master编译失败

### ISSUE THREAD

**Issue by zhangpu1987** [XiaoMi/mace#260]
root@qme:/home/qme/build_mace/mace# bash tools/build-standalone-lib.sh
build shared lib for armeabi-v7a + cpu_gpu_dsp
WARNING: The following configs were expanded more than once: [cross_compile]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Analysed target //mace/libmace:libmace_dynamic (0 packages loaded).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/c0475f1b60755e951f77e8b534c4aa53/external/com_google_protobuf/BUILD:105:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/util/internal/json_escaping.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h'
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 2.513s, Critical Path: 1.87s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by yejw5** [comment]
@zhangpu1987 请先按照[模板](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)提供一下具体的环境，这边会继续跟进这个问题
