### ISSUE TITLE
Fold conv and bn 的疑问

### ISSUE THREAD

**Issue by dlkdqpi** [XiaoMi/mace#262]
### System information
- **RK3288:
- **NDK 16**:
- **MACE version 0.9**:
- **Python version 2.7 **: 
- **Bazel version  0.13.0**:

### Describe the problem
我做测试时基本上都是运行mace，在mace_context.engine->Run(inputs, &outputs);后打印outputs，然后与caffe输出的blob做比较。如果差值较小便认为正确。
现在的问题是运行ResNet网络，第一层卷积输出就存在较大差值，但大致的数据曲线一致。于是分几个步骤做了测试：
(1)在卷积输入都为0，bias为0的情况下，mace output_tensors 设为Bacthnorm1输出与caffe一致。由此可证明mace bn层的参数读取与计算没有问题。（为什么没有设output_tensors 为conv1，我的理解是mace针对移动计算，做了模型压缩一类的优化，减少数据搬移开稍，把conv、bn、scale和relu的tensor集中在一个计算单元处理，因此output_tensors 设置为conv1时，得到的是relu后的结果，无法看到单纯的卷积输出结果）；
(2)在卷积输入为0，bias读取原值的情况下，mace bacthnorm1输出与caffe存在误差，初步判断在卷积bias时出了问题；
(3)从转换脚本打印卷积的bias参数，与caffe一致，问题不在参数读取上，是否在bias计算上；
(4)用mace运行了LeNet，各层输出结果均与caffe致，说明卷积层计算没有问题（bias一个简单加法，卷积常用的层，按理也不该有问题）；
(5)没有5了，我蒙圈了，不知道该 怎么办了

**Comment by dlkdqpi** [comment]
(5)卷积tensor的bias都设为0，mace与 caffe输出一致。否则，存在较大差值。

**Comment by dlkdqpi** [comment]
所以怀疑出现的问题跟Fold conv and bn有关

**Comment by yejw5** [comment]
@dlkdqpi 我这边测试一下你说的情况

**Comment by dlkdqpi** [comment]
在conv_2d.h中第723行LOG输出 bias_data[c] 没发现问题

**Comment by dlkdqpi** [comment]
在conv_2d.h中第723行LOG输出output_data[(b * channels + c) * height * width + i]，发现这是经过batchnorm后，才加的卷积的bias，存在明显bug!!!

**Comment by yejw5** [comment]
@dlkdqpi root cause找到了，我们在transformer.py里面，将`conv + bn` fold到一起了，就是fold_conv_and_bn这个函数做的事情。但是我们遗漏了一个重要的点，就是bn的scale乘以conv的filter，但是没有对conv的bias做scale，所以导致了结果有误差。bug当前正在fix的流程中

**Comment by dlkdqpi** [comment]
一个filter对应的 conv batchnorm scale relu 压缩下来大致对应的就是下面的公式了：
| ((((A1*X1+ ... + An*Xn) + Cbias) - Mean) / Var ) * S + Sbias |
=| A1*S*X1/Var + ... + An*s*Xn/Var + Cbias*S/Var - Mean*s/Var + Sbias |
令 An*S/Var = Bn ,  Cbias*S/Var - Mean*s/Var + Sbias = Newbias
= | B1*X1+ ... +Bn*Xn + Newbias |
所以现在出的错就是该加 Newbias的地方，还是加的原来的Cbias
赋值的问题吧？好改

**Comment by yejw5** [comment]
已修复：https://github.com/XiaoMi/mace/commit/d003635101cbb869b7c85830dc818328dd09bfcb
