### ISSUE TITLE
[BUG] Mace.cc 有bug

### ISSUE THREAD

**Issue by huanyingjun** [XiaoMi/mace#265]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: 15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**:  2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0
--------------------------------

Mace.cc   line 473
```c++
net_ = std::unique_ptr<NetBase>(new SerialNet(op_registry_.get(),
                                                  net_def,
                                                  ws_.get(),
                                                  device_.get()));
    MACE_RETURN_IF_ERROR(net_->Init());
#ifdef MACE_ENABLE_HEXAGON
  }
#endif
  if (device_type_ == DeviceType::GPU) {
    ws_->RemoveAndReloadBuffer(*net_def, model_data, device_->allocator());
  }
```

这里先调用 new SerialNet构造了net，每个op中的input  tensor 都new分配好了，并将地址push到了inputs_
然后调用 RemoveAndReloadBuffer  
```c++
tensor_map_.erase(iter);
      std::vector<index_t> dims;
      for (const index_t d : const_tensor.dims()) {
        dims.push_back(d);
      }
      std::unique_ptr<Tensor> tensor(
          new Tensor(alloc, const_tensor.data_type()));
      tensor->Resize(dims);
      MACE_CHECK(tensor->size() == const_tensor.data_size(),
                 "Tensor's data_size not equal with the shape");
      tensor->CopyBytes(model_data + const_tensor.offset(),
                        const_tensor.data_size() *
                            GetEnumTypeSize(const_tensor.data_type()));

      tensor_map_[const_tensor.name()] = std::move(tensor);
```
这里把tensor erase 然后又马上重新new了一个，这里并没有再更新 op中的inputs_
如果重新new出来的地址和之前erase的不同，那么在run的时候op取到的tensor 地址就是非法的
（因为erase和new是紧挨着的，测试中发现绝大部分情况下在这里erase 和 new出来的地址是一样的，run也不会报错，极少数情况出现了erase和new地址不一样->crash）

应该在mace.cc 中将 new SerialNet 移到RemoveAndReloadBuffer  后面

**Comment by liyinhgqw** [comment]
We have fixed this issue,
Thank your very much for your help.
