### ISSUE TITLE
MTK手机上找不到libOpenCL.so的库

### ISSUE THREAD

**Issue by yinyulin** [XiaoMi/mace#266]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
手机平台MTK，F9-LOTUS，v10-o-lotus-dev

### Describe the problem
同样的代码选择mace::DeviceType::CPU时候可以运行，但是选择mace::DeviceType::GPU时候，在mace初始化的时候找不到library "/system/vendor/lib64/libOpenCL.so" ("/vendor/lib64/libOpenCL.so")，看这个 /system/vendor/lib64/libOpenCL.so路径是骁龙处理器手机的OPENCL库，而我的手机是MTK的，本身没有这个库，个人认为可能的原因是否是因为在用mace转caffe模型的时候连入的是一个骁龙处理器手机，是否是因为转化模型的时候将路径写入了libmace.a或者是生成的模型的.a文件里面。

### Error information / logs
11-30 10:56:25.765 E/flpscreen(  543): flp_screen_monitor_thread: Screen on
11-30 10:56:25.766 E/flpscreen(  543): flp_screen_monitor_thread: Wake Monitor Restart
11-30 10:56:26.332 E/BatteryExternalStatsWorker( 1017): no controller energy info supplied for wifi
11-30 10:56:26.332 E/BatteryExternalStatsWorker( 1017): no controller energy info supplied for bluetooth
11-30 10:56:26.388 E/BatteryExternalStatsWorker( 1017): modem info is invalid: ModemActivityInfo{ mTimestamp=506854621 mSleepTimeMs=10796 mIdleTimeMs=-9276 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=11364 mEnergyUsed=0}
11-30 10:56:27.227 E/se.dirac.effect(  412): first processing
11-30 10:56:27.231 E/        (  412): [Awinic] mecLibInit:[ERROR]version: 5.0.1 
11-30 10:56:27.266 E/AudioALSAPlaybackHandlerBase(  412): -getHardwareBufferInfo(), pcm_get_htimestamp fail, ret = -1, pcm_get_error = 
11-30 10:56:27.740 E/BatteryExternalStatsWorker( 1017): no controller energy info supplied for wifi
11-30 10:56:27.740 E/BatteryExternalStatsWorker( 1017): no controller energy info supplied for bluetooth
11-30 10:56:27.775 E/BatteryExternalStatsWorker( 1017): modem info is invalid: ModemActivityInfo{ mTimestamp=506856023 mSleepTimeMs=1145 mIdleTimeMs=-2561 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=2826 mEnergyUsed=0}
11-30 10:56:28.003 E/TouchFilter( 1017): setTouchFilter LOG Enable prameter: 0
11-30 10:56:28.008 E/libc    ( 1017): Access denied finding property "ro.sf.lcd_density"
11-30 10:56:28.008 E/InputTransport( 1017): ro.sf.lcd_density must be defined as a build property
11-30 10:56:28.478 E/libc    (19935): Access denied finding property "ro.sf.lcd_density"
11-30 10:56:28.478 E/InputTransport(19935): ro.sf.lcd_density must be defined as a build property
11-30 10:56:28.526 E/libc    (15694): Access denied finding property "ro.sf.lcd_density"
11-30 10:56:28.526 E/InputTransport(15694): ro.sf.lcd_density must be defined as a build property
11-30 10:56:28.653 E/Cta5File(  570): Cta5File::isCta5NormalFile false, bad magic:OggS
11-30 10:56:28.653 E/Cta5File(  570): Cta5File::isCta5MultimediaFile false, bad magic:���
11-30 10:56:28.661 E/APEExtractor(  568): getAPEInfo not ape 20481
11-30 10:56:28.665 E/Cta5File(  570): Cta5File::isCta5NormalFile false, bad magic:OggS
11-30 10:56:28.665 E/Cta5File(  570): Cta5File::isCta5MultimediaFile false, bad magic:
11-30 10:56:28.669 E/tsf_dft (  582): [createTsf()] Main sensorDevID: 0x0486
11-30 10:56:28.669 E/tsf_dft (  582):  (createTsf){#369:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/lsc_mgr/TsfDft.cpp}
11-30 10:56:28.674 E/APEExtractor(  568): getAPEInfo not ape 20481
11-30 10:56:28.678 E/Cta5File(  570): Cta5File::isCta5NormalFile false, bad magic:OggS
11-30 10:56:28.678 E/Cta5File(  570): Cta5File::isCta5MultimediaFile false, bad magic:
11-30 10:56:28.684 E/FACE_RANK(  582): bool litesdm::SDMModel::LoadModel_C(), 0.0, 32
11-30 10:56:28.684 E/FACE_RANK(  582): bool litesdm::SDMModel::LoadModel_C(), 0.1, 120
11-30 10:56:28.684 E/FACE_RANK(  582): bool litesdm::SDMModel::LoadModel_C(), 0.2, 21
11-30 10:56:28.684 E/FACE_RANK(  582): bool litesdm::SDMModel::LoadModel_C(), 0.3, 5
11-30 10:56:28.686 E/APEExtractor(  568): getAPEInfo not ape 20483
11-30 10:56:28.687 E/FACE_RANK(  582): bool litesdm::SDMModel::LoadModel_C(), 0.4 done
11-30 10:56:28.695 E/CameraService(  557): onTorchStatusChangedLocked: cannot get torch status of camera 1: No such file or directory (-2)
11-30 10:56:28.795 E/PowerHalWrapper( 1017): <amsBoostStop> duration: 6000ms
11-30 10:56:28.958 E/aao_buf_mgr(  582): [AAOBufMgrImp()] Main sensorDevID: 0x0486
11-30 10:56:28.958 E/aao_buf_mgr(  582):  (AAOBufMgrImp){#270:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/buf_mgr/AAOBufMgr.cpp}
11-30 10:56:28.959 E/pso_buf_mgr(  582): [PSOBufMgrImp()] Main sensorDevID: 0x0486
11-30 10:56:28.959 E/pso_buf_mgr(  582):  (PSOBufMgrImp){#277:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/buf_mgr/PSOBufMgr.cpp}
11-30 10:56:28.982 E/LCSDrv  (  582): [-Fail to get LCS tuning ] FrmId(1) (p1TuningNotify){#692:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/lcs/lcs_drv.cpp}
11-30 10:56:28.982 E/LCSDrv  (  582): [-Fail to get LCS Queue ] (p1TuningNotify){#695:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/lcs/lcs_drv.cpp}
11-30 10:56:28.982 E/Hal3ARaw(  582): [send3ACtrl]  E3ACtrl_SetLcsoParam getResult fail, P1 Driver FrmId: 1 (send3ACtrl){#2770:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/wrapper/Hal3ARawImp.cpp}
11-30 10:56:28.992 E/ae_mgr  (  582): Unsupport AE Metering Mode: -1
11-30 10:56:28.992 E/ae_mgr  (  582):  (setAEMeteringMode){#1380:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/mt6765/ae_mgr/ae_mgr.cpp}
11-30 10:56:29.362 E/linker  (19935): library "/system/vendor/lib64/libOpenCL.so" ("/vendor/lib64/libOpenCL.so") needed or dlopened by "/data/app/com.xiaomi.camerascene-p19u1RqtPZ6osCDn--9avA==/lib/arm64/libcamera_scene_jni.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xiaomi.camerascene-p19u1RqtPZ6osCDn--9avA==/lib/arm64:/data/app/com.xiaomi.camerascene-p19u1RqtPZ6osCDn--9avA==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.xiaomi.camerascene"]
11-30 10:56:29.366 E/MACE    (19935): opencl_wrapper.cc:305 Failed to load OpenCL library, please make sure there exists OpenCL library on your device, and your APP have right to access the library.
11-30 10:56:29.366 E/MACE    (19935): opencl_runtime.cc:292 No OpenCL platforms found
11-30 10:56:29.367 E/MiAILab (19935): Fail to create engine
11-30 10:56:29.541 E/nima    (19935): engine run begin
11-30 10:56:29.541 F/MACE    (19935): mace.cc:527 'data' does not belong to model's inputs: []
11-30 10:56:29.541 F/libc    (19935): Fatal signal 6 (SIGABRT), code -6 in tid 19953 (omi.camerascene), pid 19935 (omi.camerascene)
11-30 10:56:29.614 F/DEBUG   (20043): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-30 10:56:29.614 F/DEBUG   (20043): Build fingerprint: 'xiaomi/lotus/lotus:8.1.0/O11019/8.11.12:user/release-keys'
11-30 10:56:29.614 F/DEBUG   (20043): Revision: '0'
11-30 10:56:29.614 F/DEBUG   (20043): ABI: 'arm64'
11-30 10:56:29.614 F/DEBUG   (20043): pid: 19935, tid: 19953, name: omi.camerascene  >>> com.xiaomi.camerascene <<<
11-30 10:56:29.614 F/DEBUG   (20043): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-30 10:56:29.619 F/DEBUG   (20043): Abort message: 'mace.cc:527 'data' does not belong to model's inputs: []'
11-30 10:56:29.619 F/DEBUG   (20043):     x0   0000000000000000  x1   0000000000004df1  x2   0000000000000006  x3   0000000000000008
11-30 10:56:29.619 F/DEBUG   (20043):     x4   00000000776e0209  x5   00000000776e0209  x6   00000000776e0209  x7   09026e77ffffffff
11-30 10:56:29.619 F/DEBUG   (20043):     x8   0000000000000083  x9   0000000010000000  x10  000000704cd6edf0  x11  0000000000000001
11-30 10:56:29.619 F/DEBUG   (20043):     x12  0000000000000002  x13  0000000000000002  x14  ffffffff00000000  x15  ffffffffffffffff
11-30 10:56:29.619 F/DEBUG   (20043):     x16  000000557aa26fa8  x17  00000070e8ab2790  x18  0000000000000000  x19  0000000000004ddf
11-30 10:56:29.619 F/DEBUG   (20043):     x20  0000000000004df1  x21  0000000000000083  x22  000000704c7dd780  x23  000000000000000a
11-30 10:56:29.619 F/DEBUG   (20043):     x24  000000704cd6ee40  x25  000000704cd6ee40  x26  000000704b1de708  x27  000000704cd6f588
11-30 10:56:29.619 F/DEBUG   (20043):     x28  000000704b1de858  x29  000000704cd6ee30  x30  00000070e8a67860
11-30 10:56:29.619 F/DEBUG   (20043):     sp   000000704cd6edf0  pc   00000070e8a67888  pstate 0000000060000000

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lydoc** [comment]
初步分析是这台手机可能没有libOpenCL的库，那就没办法用GPU，只能用CPU运行。或者有libOpencl的库，但是路径不是/system/vendor/lib64/libOpenCL.so，这个路径跟转图没关系，是mace写死再code里面的，可以全局搜索一下，看是否有libOpenCL.so

**Comment by yinyulin** [comment]
> 初步分析是这台手机可能没有libOpenCL的库，那就没办法用GPU，只能用CPU运行。或者有libOpencl的库，但是路径不是/system/vendor/lib64/libOpenCL.so，这个路径跟转图没关系，是mace写死再code里面的，可以全局搜索一下，看是否有libOpenCL.so

我的手机这个目录下/system/vendor/lib64/libOpenCL.so下有这个库还是报一样的错误
library "/system/vendor/lib64/libOpenCL.so" ("/vendor/lib64/libOpenCL.so") needed or dlopened by "/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64/libcamera_scene_jni.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64:/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.xiaomi.camerascene"]
11-30 14:12:02.389 E/MACE    (25733): opencl_wrapper.cc:305 Failed to load OpenCL library, please make sure there exists OpenCL library on your device, and your APP have right to access the library.
11-30 14:12:02.389 E/MACE    (25733): opencl_runtime.cc:292 No OpenCL platforms found

**Comment by leeli92** [comment]
> > 初步分析是这台手机可能没有libOpenCL的库，那就没办法用GPU，只能用CPU运行。或者有libOpencl的库，但是路径不是/system/vendor/lib64/libOpenCL.so，这个路径跟转图没关系，是mace写死再code里面的，可以全局搜索一下，看是否有libOpenCL.so
> 
> 我的手机这个目录下/system/vendor/lib64/libOpenCL.so下有这个库还是报一样的错误
> library "/system/vendor/lib64/libOpenCL.so" ("/vendor/lib64/libOpenCL.so") needed or dlopened by "/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64/libcamera_scene_jni.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64:/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.xiaomi.camerascene"]
> 11-30 14:12:02.389 E/MACE (25733): opencl_wrapper.cc:305 Failed to load OpenCL library, please make sure there exists OpenCL library on your device, and your APP have right to access the library.
> 11-30 14:12:02.389 E/MACE (25733): opencl_runtime.cc:292 No OpenCL platforms found

您好，我的MTk手机目录下面也有这个库，但是release-v0.11.0rc1版本还是报错说找不到，请问后面你是怎么解决的呀，怎么close了？

**Comment by yinyulin** [comment]
system/etc/public.libraries.txt或者其他路径，在
public.libraries.txt中添加libOpenCL.so

 
---原始邮件---
发件人: "leeli92"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 下午4:07
收件人: "XiaoMi/mace"<mace@noreply.github.com>;
抄送: "State change"<state_change@noreply.github.com>;"yinyulin"<348493084@qq.com>;
主题: Re: [XiaoMi/mace] MTK手机上找不到libOpenCL.so的库 (#266)


  
初步分析是这台手机可能没有libOpenCL的库，那就没办法用GPU，只能用CPU运行。或者有libOpencl的库，但是路径不是/system/vendor/lib64/libOpenCL.so，这个路径跟转图没关系，是mace写死再code里面的，可以全局搜索一下，看是否有libOpenCL.so
  
我的手机这个目录下/system/vendor/lib64/libOpenCL.so下有这个库还是报一样的错误
 library "/system/vendor/lib64/libOpenCL.so" ("/vendor/lib64/libOpenCL.so") needed or dlopened by "/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64/libcamera_scene_jni.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64:/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.xiaomi.camerascene"]
 11-30 14:12:02.389 E/MACE (25733): opencl_wrapper.cc:305 Failed to load OpenCL library, please make sure there exists OpenCL library on your device, and your APP have right to access the library.
 11-30 14:12:02.389 E/MACE (25733): opencl_runtime.cc:292 No OpenCL platforms found
  
您好，我的MTk手机目录下面也有这个库，但是release-v0.11.0rc1版本还是报错说找不到，请问后面你是怎么解决的呀，怎么close了？

**Comment by leeli92** [comment]
> system/etc/public.libraries.txt或者其他路径，在 public.libraries.txt中添加libOpenCL.so
> […](#)
> ---原始邮件--- 发件人: "leeli92"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 下午4:07 收件人: "XiaoMi/mace"<mace@noreply.github.com>; 抄送: "State change"<state_change@noreply.github.com>;"yinyulin"<348493084@qq.com>; 主题: Re: [XiaoMi/mace] MTK手机上找不到libOpenCL.so的库 (#266) 初步分析是这台手机可能没有libOpenCL的库，那就没办法用GPU，只能用CPU运行。或者有libOpencl的库，但是路径不是/system/vendor/lib64/libOpenCL.so，这个路径跟转图没关系，是mace写死再code里面的，可以全局搜索一下，看是否有libOpenCL.so 我的手机这个目录下/system/vendor/lib64/libOpenCL.so下有这个库还是报一样的错误 library "/system/vendor/lib64/libOpenCL.so" ("/vendor/lib64/libOpenCL.so") needed or dlopened by "/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64/libcamera_scene_jni.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/lib/arm64:/data/app/com.xiaomi.camerascene-cFX10zW8RAKiY0mAYWFCXA==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.xiaomi.camerascene"] 11-30 14:12:02.389 E/MACE (25733): opencl_wrapper.cc:305 Failed to load OpenCL library, please make sure there exists OpenCL library on your device, and your APP have right to access the library. 11-30 14:12:02.389 E/MACE (25733): opencl_runtime.cc:292 No OpenCL platforms found 您好，我的MTk手机目录下面也有这个库，但是release-v0.11.0rc1版本还是报错说找不到，请问后面你是怎么解决的呀，怎么close了？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

好的谢谢，我这边修改不了里面的内容，说是只读文件系统，您遇到过吗

**Comment by yinyulin** [comment]
> > system/etc/public.libraries.txt或者其他路径，在 public.libraries.txt中添加libOpenCL.so
> 
> 好的谢谢，我这边修改不了里面的内容，说是只读文件系统，您遇到过吗

root 手机，adb remount

**Comment by leeli92** [comment]
> > > system/etc/public.libraries.txt或者其他路径，在 public.libraries.txt中添加libOpenCL.so
> > 
> > 
> > 好的谢谢，我这边修改不了里面的内容，说是只读文件系统，您遇到过吗
> 
> root 手机，adb remount

好的谢谢，辛苦~

**Comment by CUITzyt** [comment]
最后怎么解决的？
