### ISSUE TITLE
Writing Image based kernels from Buffer based kernels

### ISSUE THREAD

**Issue by ssj4gogeta** [XiaoMi/mace#268]
Architecture: arm64-v8a
Operating system: Android 9 Pie
Hello,
If we have a buffer based kernel [like in compute library] & I want to write an image based kernel [like in MACE] based on the same, how would I go about doing that? What are the differences in memory layout & what potential problems I might face? Any pointers are appreciated.
Thanks in Advance.

**Comment by nolanliou** [comment]
1. You could refer to the [document](https://mace.readthedocs.io/en/latest/development/memory_layout.html).
2. Actually looking at the code is the best choice
