### ISSUE TITLE
Build failure with native toolchain on Arm64 platform

### ISSUE THREAD

**Issue by JammyZhou** [XiaoMi/mace#270]
Hi,

I'm trying to build MACE on my ROCK960/RK3399 96Boards with native toolchain, and the bazel command below is used (I just want to try NEON first, so I disabled OpenCL).

`bazel build --config optimization mace/libmace:libmace_dynamic --define neon=true --define openmp=true --define opencl=false --define quantize=true --cpu=aarch64`

And I ran into the error below. Since I'm new to Bazel, it will be appreciated if you can give some suggestions. Thanks!
```
build shared lib for arm64-v8a + cpu_gpu
INFO: Invocation ID: 60fd79d4-36d4-4c73-8569-1337822c36dd
ERROR: Analysis of target '//mace/libmace:libmace_dynamic' failed; build aborted: no such package '@tflite//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 0.780s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 2 targets conf\
igured)
    Fetching @gemmlowp; fetching
```

**Comment by nolanliou** [comment]
We cannot analyse the reason if you do not fill the ISSUE table.

**Comment by llhe** [comment]
The official build is supported now and this command is not suggested. Just close this issue.
