### ISSUE TITLE
May be should update quantization doc? 是否考虑更新量化文档？

### ISSUE THREAD

**Issue by wincle** [XiaoMi/mace#271]
我注意到量化相关的文档貌似已经过期了，是否考虑更新一下呢？

**Comment by liyinhgqw** [comment]
目前这是最新的文档，使用的过程有问题吗？

**Comment by wincle** [comment]
嗯，的确遇到了问题，主要是在生成range_log那一步，并没有得到一些有关 tensor range的结果，而是得到了一个tar包，里面包含了模型的pb和data文件，我以为mace做了更新，想tflite一样把min/max信息包含在了模型里，所以这样提问。也可能是我使用方法有问题，但我已经按照文档说明的（ target_abis to host, runtime to cpu, and obfuscate to 0, appending :0 to output_tensors）这样做了，唯一的疑问就是input_dir 指定的是否是包含图片的目录？附上我得到的range_log结果。
`* Build //mace/libmace:libmace_static with ABI host
Build done!

* Build //mace/examples/cli:example_static with ABI host
Build done!

^[[95m**************************************************
          Run model inception_v3 on host
**************************************************
^[[0m
Generate input file:  builds/inception-v3/_tmp/inception_v3/93dde2b3c29f3b10ebd43b11c80dbab5/host/model_input_input
Generate input file done.
* Run 'inception_v3' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
I mace/libmace/mace.cc:731] Create MaceEngine from model pb
I mace/libmace/mace.cc:389] Creating MaceEngine, MACE version: v0.9.0-380-g1b272a6-20181207
I mace/libmace/mace.cc:493] Loading Model Data
I mace/libmace/mace.cc:415] Initializing MaceEngine
I mace/libmace/mace.cc:514] Destroying MaceEngine
mace version: v0.9.0-380-g1b272a6-20181207
input node: input
input shape: 1,299,299,3
output node: InceptionV3/Predictions/Reshape_1:0
output shape: 1,1001
input_file: builds/inception-v3/_tmp/inception_v3/93dde2b3c29f3b10ebd43b11c80dbab5/host/model_input
output_file: builds/inception-v3/_tmp/inception_v3/93dde2b3c29f3b10ebd43b11c80dbab5/host/model_out
input_dir: valid
output dir:
model_data_file: builds/inception-v3/model/inception_v3.data
model_file: builds/inception-v3/model/inception_v3.pb
device: CPU
round: 1
restart_round: 1
gpu_perf_hint: 3
gpu_priority_hint: 3
omp_num_threads: -1
cpu_affinity_policy: 1
restart round 0
Finished

Running finished!

builds/inception-v3/model/
builds/inception-v3/model/inception_v3.pb
builds/inception-v3/model/inception_v3.data
_______________________________
_______________________________
* Package libs for inception-v3
Start packaging 'inception-v3' libs into builds/inception-v3/libmace_inception-v3.tar.gz
Packaging Done!

^[[92m---------------------------------------------------------------------------
                                  Library
---------------------------------------------------------------------------
|          key           |                     value                      |
===========================================================================
| MACE Model package Path| builds/inception-v3/libmace_inception-v3.tar.gz|
---------------------------------------------------------------------------
^[[0m
`

**Comment by lee-bin** [comment]
１、range_log这段代码在重构时被误删了。。已在最新代码修复。
２、input_dir是输入tensor的目录，需要事先按照模型做预处理，可以参考[tools/image/image_to_tensor.py](https://github.com/XiaoMi/mace/blob/master/tools/image/image_to_tensor.py)

**Comment by wincle** [comment]
好的，感谢。
