### ISSUE TITLE
We need ShuffleNet

### ISSUE THREAD

**Issue by AlpacaKnight** [XiaoMi/mace#272]
We need ShuffleNet.
大佬能支持一下ShuffleNet么？
請問可以支持ShuffleNet麼？
Können Sie shuffleNet bereitstellen?
Você Pode fornecer ShuffleNet?
Pouvez-vous fournir shuffleNet
¿Puede proporcionar shuffleNet?
Можете ли вы предоставить shuffleNet?
저희는 ShuffleNet 이 필요해요.
ShuffleNetを提供することができますか

***************************************************
I found that shufflenet is already supported, but there is no conversion tool, can be completed as soon as possible, we need to use shufflenet, Thanks.

我发现已经支持shufflenet了，但是没有转换工具，可以尽快完成么，我们需要使用shufflenet，谢谢

**Comment by liyinhgqw** [comment]
ShuffleNet-V2 すでに支持した.
Thanks.

**Comment by nolanliou** [comment]
ShuffleNet-V2 supported now. please refer to https://github.com/XiaoMi/mace-models/blob/master/shufflenet-v2/shufflenet-v2.yml
