### ISSUE TITLE
do not have opencl buffer

### ISSUE THREAD

**Issue by wincle** [XiaoMi/mace#277]
Hi,你好，我在部署shuffernetv2 mace模型时遇到问题，报错：
ShuffleNetV2/ShuffleNetV2_part_0/unit_1/conv1x1_after/Relu:0 do not have opencl buffer
请问您知道是什么原因吗？谢谢！

**Comment by wincle** [comment]
是在Android端部署的。

**Comment by wincle** [comment]
好的，模型和配置文件传到google云盘了。
我怀疑是里面用了ShuffleNet的transpose结点导致的，目前mace的opencl实现是不是还不支持5维的transpose？我把shufflenet换成mobilenet，模型是可以运行的了。
另外，这个模型里还有个小问题，就是concat时检测到一个输入的channel不能被4整除，会报异常退出，虽然我在修改channel通道数后重新训练，模型能够运行了，但还是想请教下，为什么要加这个除4的验证呢？

**Comment by wincle** [comment]
https://drive.google.com/open?id=1WimFLFzJ_wAUJapVyPuKnCWNqfeYp_65

**Comment by lydoc** [comment]
对，opencl的transpose不支持5维的transpose
concat因为opencl image实现的问题，确实需要是4的倍数，具体可以参考https://mace.readthedocs.io/en/latest/development/memory_layout.html

**Comment by wincle** [comment]
好的，感谢。
