### ISSUE TITLE
为什么MACE转化后模型的精度损失很多

### ISSUE THREAD

**Issue by yk0607** [XiaoMi/mace#278]
我做图像分割  用原网络在PC上测试结果 分割轮廓明显   ,  用tflite转化后在终端测试 结果 分割轮廓也很明显 ,  但使用MACE转化后的模型 在终端测试 时间上很有优势  但是分割轮廓很不明显 (转化的校验相似度为1).  请问为什么MACE 转化后的模型精确度会有这么大的损失呢?

**Comment by yk0607** [comment]
附: 模型 以及 PC端网络测试的结果
  望大佬们指导一下!
[model.zip](https://github.com/XiaoMi/mace/files/2685110/model.zip)
[test.zip](https://github.com/XiaoMi/mace/files/2685112/test.zip)

**Comment by liyinhgqw** [comment]
Did your model run on CPU or GPU, we need more details.

**Comment by yk0607** [comment]
> Did your model run on CPU or GPU, we need more details.

My model run on CPU  now ,   the accuracy  i have tested  for GPU is worse .    Except for the poor accuracy of the results, there are no exceptions.
Attach the YMAL file.

[YAML.zip](https://github.com/XiaoMi/mace/files/2685443/YAML.zip)

**Comment by llhe** [comment]
@yk0607 Is your issue resolved?

**Comment by liyinhgqw** [comment]
One way to validate this is to test your own input image using following config, and see it is consistent with tensorflow output.
```
          validation_inputs_data:
            - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
```

models:
  mobilenet_v1:
      platform: tensorflow
      model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
      model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
      subgraphs:
        - input_tensors:
            - input
          input_shapes:
            - 1,224,224,3
          output_tensors:
            - MobilenetV1/Predictions/Reshape_1
          output_shapes:
            - 1,1001
          validation_inputs_data:
            - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
      runtime: cpu+gpu
      limit_opencl_kernel_time: 0
      obfuscate: 0
      winograd: 0
