### ISSUE TITLE
Can it deploy the model on PC?

### ISSUE THREAD

**Issue by zhijl** [XiaoMi/mace#28]
Like the tile, can it deploy the model on personal computer use MACE? I also want to compile with other cross-compilation tools instead of NDK, is it supported? Thanks!

**Comment by llhe** [comment]
1. Currently Linux is supported, but the kernels is not optimized (e.g. without memory locality optimization and x86 AVX, FMA optimization)
2. It's possible but not supported yet, you can check this guide: https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain

**Comment by zhijl** [comment]
I see, thanks for the answer!
