### ISSUE TITLE
tensorflow训练的mobilenetV2模型转mace模型时失败

### ISSUE THREAD

**Issue by AlpacaKnight** [XiaoMi/mace#280]
失败报错信息如下：
ValueError: NodeDef mentions attr 'shape' not in Op<name=Identity; signature=input:T -> output:T; attr=T:type>; NodeDef: MobilenetV2/input = Identity[T=DT_FLOAT, _output_shapes=[[1,56,56,1]], shape=[1,56,56,1]](Reshape). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

使用的是这个网络：
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_v2.py

这是修改训练好的模型
[model.zip](https://github.com/XiaoMi/mace/files/2693114/model.zip)

谢谢

**Comment by nolanliou** [comment]
yaml文件呢？

**Comment by AlpacaKnight** [comment]
# The name of library
library_name: test
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  tracking: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # support local path, http:// and https://
    model_file_path: /container/path/MACE/test/test.pb
    model_sha256_checksum: 
    # define your model's interface
    # if there multiple inputs or outputs, write like blow:
    subgraphs:
      - input_tensors:
          - MobilenetV2/input
        input_shapes:
          - 1,56,56,1
        output_tensors:
          - MobilenetV2/Conv_1/Relu6
        output_shapes:
          - 1,3,3,8
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0

**Comment by nolanliou** [comment]
试了一下最新代码，在transform_graph时就报错了，应该是模型有问题，看着像batchnorm的输入不对。
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Beta input to batch norm has bad shape: [32]
```

**Comment by AlpacaKnight** [comment]
嗯，那我再看一下我的模型的问题，刚开始用tensorflow还不是特别会，麻烦你啦，谢谢

**Comment by AlpacaKnight** [comment]
> 失败报错信息如下：
> ValueError: NodeDef mentions attr 'shape' not in Op<name=Identity; signature=input:T -> output:T; attr=T:type>; NodeDef: MobilenetV2/input = Identity[T=DT_FLOAT, _output_shapes=[[1,56,56,1]], shape=[1,56,56,1]](Reshape). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
> 
> 使用的是这个网络：
> https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_v2.py
> 
> 这是修改训练好的模型
> [model.zip](https://github.com/XiaoMi/mace/files/2693114/model.zip)
> 
> 谢
