### ISSUE TITLE
virtual memory is not enough when convert mobilenet graph and data to code

### ISSUE THREAD

**Issue by leihong1986** [XiaoMi/mace#283]
Hi,

It seems that the virtual memory is not enough when convert mobilenet v1 graph and data to code with converter.py from mace. It works well when convert mobilenet v1 model graph to code, convert data to file. And I start a thread in ubuntu to monitor the memory with "free -m" command, it proved my guess when the issue happened.

BTW: I found that converter.py took almost 2.5G memory when the issue happened, I only distribute 3.9 G for ubuntu in virtualbox.

### System information
- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **GCC version (gcc version 5.4.0 20160609)**:
- **MACE version (From latest master branch)**:
- **Python version(3.6)**: 
- **Bazel version (0.13.0)**:

### Model deploy file (*.yml)
library_name: mobilenet-v1-host
target_abis: [host]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

### To Reproduce
Steps to reproduce the problem:
```bash
$ python tools/converter.py convert --config=/home/leihong/code/mace-models/mace-models/mobilenet-v1/mobilenet-v1.yml
```

### Error information / logs
************************************************
          Model mobilenet_v1 converted          
************************************************

******************************************
          Building model library          
******************************************

* Build //mace/codegen:generated_models with ABI host
INFO: Analysed target //mace/codegen:generated_models (1 packages loaded).
INFO: Found 1 target...
ERROR: /home/leihong/code/mace/mace/mace/codegen/BUILD:10:1: C++ compilation of rule '//mace/codegen:libmodels' failed (Exit 1): gcc failed: error executing command 
  (cd /home/leihong/.cache/bazel/_bazel_leihong/1155f2f1f80c6466697af3e2f5c9e279/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/mace/codegen/_objs/libmodels/mace/codegen/models/mobilenet_v1/tensor_data.pic.d '-frandom-seed=bazel-out/k8-opt/bin/mace/codegen/_objs/libmodels/mace/codegen/models/mobilenet_v1/tensor_data.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/genfiles/external/com_google_protobuf -iquote external/half -iquote bazel-out/k8-opt/genfiles/external/half -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_OPENMP -DMACE_USE_NNLIB_CAF '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_OPENMP -DMACE_USE_NNLIB_CAF -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections '-fvisibility=hidden' '-fvisibility=hidden' -Werror -Wextra -Wno-missing-field-initializers -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mace/codegen/models/mobilenet_v1/tensor_data.cc -o bazel-out/k8-opt/bin/mace/codegen/_objs/libmodels/mace/codegen/models/mobilenet_v1/tensor_data.pic.o)

Use --sandbox_debug to see verbose messages from the sandbox
virtual memory exhausted: Cannot allocate memory
Target //mace/codegen:generated_models failed to build
INFO: Elapsed time: 49.230s, Critical Path: 37.65s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1241, in <module>
    flags.func(flags)
  File "tools/converter.py", line 763, in convert_func
    build_model_lib(configs, flags.address_sanitizer)
  File "tools/converter.py", line 732, in build_model_lib
    symbol_hidden=True
  File "/home/leihong/code/mace/mace/tools/sh_commands.py", line 298, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/leihong/bin/bazel build --define openmp=true --define quantize=false //mace/codegen:generated_models --config optimization --config symbol_hidden

  STDOUT:

  STDERR:

Please provide your suggestions about the issue. Thanks very much

**Comment by liyinhgqw** [comment]
Can you run another round and use `top` to determine if `python` process consumes too memory or `gcc` does?

Please paste stat to the issue.

Thanks.

**Comment by leihong1986** [comment]
Hi Liyin,

Thanks for your quick reply.
I tried to use top to take a look the issue, it seems that gcc consumes too memory, when the issue happened, it took almost 90% memory.....

**Comment by leihong1986** [comment]
![image](https://user-images.githubusercontent.com/46023952/50330601-d4519500-0536-11e9-808e-89fa15f0c162.png)

**Comment by liyinhgqw** [comment]
Thanks.

I guess bazel estimated wrongly about ram size in your virtual machine. There might be two methods to solve this problem:

1. Edit tools/bazel.rc, add the following line to the beginning:
```
build --ram_utilization_factor 10
```
The last number if percentage of your RAM, make sure it is small enough to avoid out out memory.

Or

2. Edit tools/bazel.rc, add the following line to the beginning:
```
build --local_resources 512,1.0,1.0
```
The first number is RAM size (in MB), make sure it is small enough to avoid out out memory.


You can refer to:
https://docs.bazel.build/versions/master/user-manual.html

**Comment by leihong1986** [comment]
Hi Liyin,

Thanks for your suggestions.
I tried the two methods separately, but it doesn't help for the issue. Bazel still consumes almost 90% memory.
Here are my commands:
build --ram_utilization_factor 50  Or  build --local_resources 1024,1.0,1.0
![image](https://user-images.githubusercontent.com/46023952/50335907-c0625f00-0547-11e9-9746-899849809387.png)

**Comment by liyinhgqw** [comment]
Is it Bazel, python or cc1plus which consumes memory a lot ?

**Comment by leihong1986** [comment]
Hi Liyin,

Always cc1plus

**Comment by liyinhgqw** [comment]
I tested `build --local_resources 1024,1.0,1.0` in my machine which worked.

By specifying 1.0 cpu, is there only one core used to compile? If yes, try decrease memory limit, say 256?

**Comment by leihong1986** [comment]
Yes, only one core. OK, I will try.

**Comment by leihong1986** [comment]
Bad news, it doesn't work. But I think I can use another machine with enough memory to try.

**Comment by liyinhgqw** [comment]
It is weird. Maybe you can post an issue to BazelBuild project.

Let us know if any solution works.
