### ISSUE TITLE
全卷积网络，数据通道在输入之前被改变。

### ISSUE THREAD

**Issue by wienerjeff** [XiaoMi/mace#284]
1.install Environment.
2.Transfer CAFFE Model
3.按照NCHW组织数据，COPY到INPUT MaceTensor之后。模型第一层是卷积，数据顺序被改变，方差和均值都被改变。
4.将提取出数据（CONV1输入）输入到CAFFE，卷积结果也不一样，怀疑是CONV+BN转换PROBLEM。
ORIGN:
0.615686 0.611765 0.619608 0.619608 0.619608 0.627451 0.627451 0.631373 0.623529 0.623529 0.631373 0.631373 0.631373 0.631373 0.635294 0.639216 0.643137 0.647059 0.647059 0.643137 0.65098 0.65098 0.654902 0.654902 0.654902 0.662745 0.658824 0.65098 0.647059 0.647059 0.647059 0.658824 0.670588 0.658824 0.658824 0.666667 0.670588 0.670588 0.678431 0.658824 
CONV1 INPUT:
0.615686 0.619608 0.627451 0.623529 0.631373 0.639216 0.647059 0.65098 0.654902 0.65098 0.647059 0.658824 0.670588 0.658824 0.682353 0.682353 0.690196 0.686275 0.698039 0.701961 0.701961 0.705882 0.721569 0.717647 0.721569 0.721569 0.729412 0.741176 0.733333 0.74902 0.737255 0.741176 0.756863 0.756863 0.756863 0.776471 0.760784 0.768627 0.776471 0.776471 0.776471 0.772549 0.784314 0.776471 0.784314 0.792157 0.796078 0.796078 0.796078 0.8 0.796078 0.8 0.8 0.796078 0.796078 0.803922 0.803922 0.796078 0.807843 0.811765 0.796078 0.811765 0.811765 0.8 0.807843

![image](https://user-images.githubusercontent.com/46042058/50328230-4d4bef00-052d-11e9-8517-694183ac6e34.png)
将输出提取后送到CAFFE
![image](https://user-images.githubusercontent.com/46042058/50328395-e4b14200-052d-11e9-8f9c-820bbec3709b.png)

MACE只支持CLASSIFICATION？

**Comment by wienerjeff** [comment]
![image](https://user-images.githubusercontent.com/46042058/50341501-f4468000-0559-11e9-9681-4d59f08ebec2.png)
CPU 上做的Inferen BGR数据格式 NCHW通道

**Comment by wienerjeff** [comment]
CPU Caffe模型 在输入前数据已经变了

**Comment by lee-bin** [comment]
１、MACE中CPU / GPU的默认输入都是NHWC的。
２、CPU浮点型中间计算采用NCHW格式，MACE执行时会自动将输入的NHWC格式转换为NCHW。
