### ISSUE TITLE
qcom845 DSP运行aibenchmark失败

### ISSUE THREAD

**Issue by sunhuchang** [XiaoMi/mace#285]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu16
- **NDK version(e.g., 15c)**: NDK15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
在qcom845上运行mobile-ai-benchmark, MACE DSP runtime没跑起来，也没看到有用的log信息。libhexagon_nn_skel.so自己下载nnlib编译放到rdsp下了。libhexagon_controller.so是benchmark自带的，libcdsprpc.so 是qcom的系统自带的原名叫libcdsprpc_system.so ，自己改名成libcdsprpc.so.
请教一下可能是哪里的配置有问题？或者如何查看更多的log，我已经 export MACE_CPP_MIN_VLOG_LEVEL=0， 看logcat好像没有啥变化。
详情如下：

### To Reproduce
Steps to reproduce the problem:
sunhuchang@ubuntu:/mnt/hgfs/sunhuchang/WorkSpace/sourcecode/Mi-ai-benchmark/mobile-ai-bench$ export MACE_CPP_MIN_VLOG_LEVEL=0
sunhuchang@ubuntu:/mnt/hgfs/sunhuchang/WorkSpace/sourcecode/Mi-ai-benchmark/mobile-ai-bench$ bash tools/benchmark.sh --benchmark_option=Performance --executors=MACE --device_type=DSP  --target_abis=armeabi-v7a
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //aibench/python:benchmark (17 packages loaded).
INFO: Found 1 target...
Target //aibench/python:benchmark up-to-date:
  bazel-bin/aibench/python/benchmark
INFO: Elapsed time: 24.545s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Prepare to run models on armeabi-v7a
* Build //aibench/benchmark:model_benchmark with ABI armeabi-v7a
WARNING: The following configs were expanded more than once: [cross_compile]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //aibench/benchmark:model_benchmark (27 packages loaded).
INFO: Found 1 target...
Target //aibench/benchmark:model_benchmark up-to-date:
  bazel-bin/aibench/benchmark/model_benchmark
INFO: Elapsed time: 45.672s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

Pull /data/local/tmp/aibench/result.txt to output/SDM845 for arm64_sdm845_armeabi-v7a_result.txt
Error msg: remote object '/data/local/tmp/aibench/result.txt' does not exist

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by sunhuchang** [comment]
注：只有DSP有问题，cpu和gpu都OK

**Comment by lee-bin** [comment]
Mobile-AI-Bench还未添加MACE的DSP模型，所有的benchmark在这里：
https://github.com/XiaoMi/mobile-ai-bench/blob/master/aibench/proto/benchmark.meta
Mobile-AI-Bench的问题请在这里提：
https://github.com/XiaoMi/mobile-ai-bench/issues

**Comment by sunhuchang** [comment]
谢谢，请问是MACE现在还不支持hexagon DSP吗？

**Comment by lee-bin** [comment]
可以先试用MACE 0.8
新版在内部review，即将支持

**Comment by liuchao198746** [comment]
@lee-bin MACE 现在支持ＣＥＶＡ　XM6 DSP 设备吗？　谢谢

**Comment by lee-bin** [comment]
目前不支持。
