### ISSUE TITLE
Is Kaldi related support on the roadmap?

### ISSUE THREAD

**Issue by imcaspar** [XiaoMi/mace#287]
In the following sharing( [小米移动端深度学习框架实践 AICON2018](https://static001.geekbang.org/con/37/pdf/1228823430/file/%E5%B0%8F%E7%B1%B3%E7%A7%BB%E5%8A%A8%E7%AB%AF%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E6%A1%86%E6%9E%B6%E5%AE%9E%E8%B7%B5%20%E4%BD%95%E4%BA%AE%E4%BA%AE.pdf), Page 18 ) Kaldi has been mentioned.
But I cant find any related doc or code in this repo, is Kaldi related support on the roadmap?

**Comment by llhe** [comment]
@imcaspar This feature will be released soon as mentioned in AICon.

**Comment by imcaspar** [comment]
@llhe thx for the quick reply.
