### ISSUE TITLE
[Feature Request] MaceTensor API which does not take away the ownership of data

### ISSUE THREAD

**Issue by Alnlll** [XiaoMi/mace#289]
### Describe the problem
We use Python for business implementation and c/c++ for basic interfaces.But there is a problem when using mace, mace use all the "shared_ptr"s which is annoying for c.

So will there be a c interface provided in the predictable future?
Or you guys have a workaround for this?
Or mace will not take such situation into consideration?

Look forward to your responding?

**Comment by llhe** [comment]
@Alnlll Thanks for the feedback. We will provide a workaround for shared_ptr ownership issue.

By the way, what about your OS and compiler?

**Comment by Alnlll** [comment]
Thanks for responding!!

I'm running a cross-compilation:
- host: 
  - OS: ubuntu 16.04
  - compiler: linaro_linux_gcc 5.4.0
- target:
  - OS: filefly adapts from ubuntu 16.04
  - compiler: linaro_linux_gcc 5.4.0

**For more information**,  I noticed that mace will use linaro_linux_gcc 7.3.1, there is a version mismatch.

**Comment by llhe** [comment]
@Alnlll For tool chain, you can simple create a new one, similar to the current one.

For the C interface issue, what's your real issue?

Do you need to hold the ownership of the tensor buffer? Like:
```c
// global variable
float *buffer_in = (float *) malloc(M);
float *buffer_out = (float *) malloc(N);

// make inference somewhere
// mace_run wrapped the C++ interface
mace_run(buffer_in, buffer_out);

// finally deallocate the memory
free(buffer_in);
free(buffer_out);
```

**Comment by Alnlll** [comment]
@llhe Yes,you're right. That's exactly what I mean.

One specific situation is like:
```
void cwrapper_run_engine(float * buffer_in, float * buffer_out,...)
{
    // Because of MaceTensor just take shared_ptr<float> as data, I should get a share_ptr
    // type pointer like example.cc does and copy buffer_in data into this buffer, 
    // then send this shared_ptr pointer holding  buffer into 
    // MaceTensor so I can hold the ownership of my original data buffer.

   auto buffer_in_dup = std::shared_ptr<float>(new float[input_size], std::default_delete<float[]>());
   memcpy(buffer_in_dup.get(), buffer_in, input_size*sizeof(float));

   // then run mace engine, get result.
}
```

**Comment by llhe** [comment]
@Alnlll The real question is whether MaceTensor should take the ownership of the input/outpur buffer instead of whether it's shared_ptr or not. For example, simple a new API can be added with plain pointer:
```c
  MaceTensor(const std::vector<int64_t> &shape,
             float *data,
             const DataFormat format = DataFormat::NHWC);
```
Where MaceTensor will take the ownership of `data`.

By the current desing, MaceTensor will own the buffer. We are considering whether to provide a new API which does not take the ownership of the i/o buffer.


Here is a quick workaround if your i/o buffer can be allocated by MACE code:
```c
void *create_buffer(int size) {
  auto buffer = std::make_shared<float>(size);
  return new MaceTensor(buffer);
}

float *get_c_buffer(void *tensor) {
  return reinterpret_cast<MaceTensor *>(tensor).data().get();
}

void destroy_buffer(void *tensor) {
  delete reinterpret_cast<MaceTensor *>(tensor);
}
```

**Comment by Alnlll** [comment]
@llhe Yes, ownership is the key.
Unfortunately there is no way to allocate I/O buffer as your providing, I'll try to find other way before getting the new version API not taking away ownership of the buffers.

Thanks for your help.

**Comment by Alnlll** [comment]
@llhe That works for me!!

So mace take the ownership of data by using "shared_ptr", and the ownership is depend on deleter in "shared_ptr".
If that's right, MaceTensor API is just fine.

**Comment by llhe** [comment]
@Alnlll Yes, I also added this in the MaceTensor API docs. This should be the clean and simple solution. So we can close this issue.
