### ISSUE TITLE
新版cpu线程设置不生效

### ISSUE THREAD

**Issue by qw87494512** [XiaoMi/mace#290]
设置线程数默认最大线程跑。

**Comment by liyinhgqw** [comment]
What cpu policy did you use ?

**Comment by llhe** [comment]
不生效是指性能有regression，还是实际线程数不符合预期？

**Comment by qw87494512** [comment]
昨天lichao帮我解决了。谢谢

**Comment by liyinhgqw** [comment]
按照当时的设计，如果想指定线程数，请使用 HIGH_PERFORMANCE 这个 policy
