### ISSUE TITLE
mace编译失败

### ISSUE THREAD

**Issue by StephenLee2016** [XiaoMi/mace#291]
Mace编译失败，日志如下：

build shared lib for armeabi-v7a + cpu_gpu_dsp
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 16. The major revisions supported by Bazel are [10, 11, 12, 13, 14]. Defaulting to revision 14.
ERROR: build interrupted
INFO: Elapsed time: 58.082s
FAILED: Build did NOT complete successfully (2 packages loaded)
    currently loading: mace/proto

**Comment by nolanliou** [comment]
需要把你的环境信息列出来，才能分析为啥出错

**Comment by lu229** [comment]
The warning about ndk is not the cause of compiling failed, can you provide more info?

**Comment by daichuanliang** [comment]
MACE 在x86上编译失败。
环境如下：
OS: Ubuntu 14.04
cpu: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
mace version: v0.10.0
requirements: 都已按照Guide中正确安装对应版本

现象: armeabi-v7a ,arm64-v8a 等平台都能成功编译，在linux-x86-64 编译失败

出错日志:  bazel build mace/libmace:libmace_dynamic --config optimization --define quantize=true --define openmp=true
INFO: Analysed target //mace/libmace:libmace_dynamic (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/dilu-auto-server/cldai/mace/mace/core/BUILD:21:1: C++ compilation of rule '//mace/core:core' failed (Exit 1): gcc failed: error executing command
  (cd /home/dilu-auto-server/.cache/bazel/_bazel_dilu-auto-server/e8f8dd3f548e400259d3929c63c9dfb7/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -I/home/dilu-auto-server/.cache/bazel/_bazel_dilu-auto-server/e8f8dd3f548e400259d3929c63c9dfb7/external/local_config_cc -I/usr/local/cuda-8.0/include -MD -MF bazel-out/k8-opt/bin/mace/core/_objs/core/mace/core/allocator.pic.d '-frandom-seed=bazel-out/k8-opt/bin/mace/core/_objs/core/mace/core/allocator.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/genfiles/external/com_google_protobuf -iquote external/half -iquote bazel-out/k8-opt/genfiles/external/half -iquote external/gemmlowp -iquote bazel-out/k8-opt/genfiles/external/gemmlowp -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_OPENMP '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_OPENMP -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers -fopenmp -DMACE_ENABLE_OPENMP -DMACE_ENABLE_QUANTIZE -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mace/core/allocator.cc -o bazel-out/k8-opt/bin/mace/core/_objs/core/mace/core/allocator.pic.o)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mace/core/types.h:22:0,
                 from ./mace/core/allocator.h:26,
                 from mace/core/allocator.cc:15:
external/half/include/half.hpp:275:8: error: missing space between '""' and suffix identifier
   half operator""_h(long double);
        ^
external/half/include/half.hpp:1086:24: error: missing space between '""' and suffix identifier
   friend half literal::operator""_h(long double);
                        ^
external/half/include/half.hpp:1199:15: error: missing space between '""' and suffix identifier
   inline half operator""_h(long double value) { return half(detail::binary, detail::float2half<half::round_style>(value)); }
               ^
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 1.714s, Critical Path: 1.54s
INFO: 1 process, linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by daichuanliang** [comment]
> 你们是x86嵌入式设备吗？目前我们没有明显的需求，所以没有对x86做优化，应该会与tensorflow, caffe这些服务端框架有较大的差距。
> 
> 如果能提供更多信息，我们评估下要不要对x86做下优化。

不是嵌入式设备，就是普通的PC或者服务器。

**Comment by llhe** [comment]
这个场景，建议尝试一下OpenVINO，适合你的应用场景
