### ISSUE TITLE
The question about parameter "input_dir" in quantization.

### ISSUE THREAD

**Issue by wincle** [XiaoMi/mace#292]
I have set the input_dir to a folder which contain many .dat  file which generate by tools/image/image_to_tensor.py when logging tensor range of each activation layer. But I found it didn't use these samples when computing the range, because when I didn't set the input_dir , it still get the almost same result, could you please tell me why did it happened or how did the parameter "input_dir" work? 
Really appreciate of you!

**Comment by lee-bin** [comment]
The program will print `input_dir`, you can see that from the log.
`input_dir` should be a directory on the phone with all the input tensors(.dat files you generated).

**Comment by wincle** [comment]
I'm kind of confused , which program will print input_dir ?
My android deployment app or tools/convert.py ?

**Comment by wincle** [comment]
Thanks, I found it !
But no matter what I set to `input_dir`,the log print none of the input_dir , like this:

mace version: v0.9.0-425-gaca4c5e-20181226
input node: image
input shape: 1,192,192,3
output node: Convolutional_Pose_Machine/stage_5_out:0
output shape: 1,96,96,14
input_file: builds/cpm/_tmp/cpm_v1/3f6ce444283ad6cfcb83c8d613d8dad9/host/model_input
output_file: builds/cpm/_tmp/cpm_v1/3f6ce444283ad6cfcb83c8d613d8dad9/host/model_out
input_dir: 
output dir: 
model_data_file: builds/cpm/model/cpm_v1.data
model_file: 
device: CPU
round: 1
restart_round: 1
gpu_perf_hint: 3
gpu_priority_hint: 3
omp_num_threads: -1
cpu_affinity_policy: 1
restart round 0
Finished

**Comment by lee-bin** [comment]
You can pull the latest code and try it again since `input_dir` may not work in your version.

**Comment by wincle** [comment]
I have pull the latest code and rebuild mace.
Now I could saw `input_dir` parameter in log, but I found the tensor range of each activation layer dis have been disappeared, so may be somewhere goes wrong?

**Comment by lee-bin** [comment]
All the input tensor file names should be started with input tensor name.
So for MobileNet, it should start with `input`.
You can see log here if you processed some image:
https://github.com/XiaoMi/mace/blob/aea5e30a1151b1fe75becac697793917b89b8ed1/mace/examples/cli/example.cc#L277

**Comment by wincle** [comment]
It worked，Thank you!
