### ISSUE TITLE
A/MACE: quantize.h:160 Check failed: real_multiplier > 0.f && real_multiplier < 1.f 0

### ISSUE THREAD

**Issue by wincle** [XiaoMi/mace#293]
I want to quantize my model with mace and deploy it on my android phone, I have been succeeded with the original model , but quantization model cause one error as the title:
`A/MACE: quantize.h:160 Check failed: real_multiplier > 0.f && real_multiplier < 1.f 0`
I could run it on the host with no error message.
And what may cause the multiplier be zero?
Thank you!

**Comment by lee-bin** [comment]
Maybe it does not have quantization info which then does not set scale(multiplier, defaults to zero).
You can check its scale and zero_point.

**Comment by wincle** [comment]
Thank you ! I will check it.

**Comment by wincle** [comment]
I think I found where is the problem, I don't know why my input data are all zero, which made the input scale be 0, finally cause the multiplier to zero.
