### ISSUE TITLE
[CPU affinity policy] AFFINITY_HIGH_PERFORMANCE is slowest on rk3399

### ISSUE THREAD

**Issue by Alnlll** [XiaoMi/mace#295]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: None
- **GCC version(if compiling for host, e.g., 5.4.0)**: linaro linux gcc 7.3.1 for aarch64(using RK3399)
- **MACE version (Use the command: git describe --long --tags)**: v0.9.0-389-ga46158c-20181217
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**: 0.15.2

### Describe the problem
Running benchmark for mobilev1 from model-zoo on firefly(RK3399) with different cpu affinity policy: 
```c
AFFINITY_BIG_ONLY = 1,
AFFINITY_LITTLE_ONLY = 2,
AFFINITY_HIGH_PERFORMANCE = 3
```
and  got such results:
- AFFINITY_BIG_ONLY
```
------------------------------------------------------------------------
                          Summary of Ops' Stat
------------------------------------------------------------------------
| round | first(ms) | curr(ms) | min(ms) | max(ms) | avg(ms) |     std |
------------------------------------------------------------------------
|   100 |    84.936 |   84.730 |  84.383 |  86.444 |  85.021 | 403.299 |
------------------------------------------------------------------------
```
- AFFINITY_LITTLE_ONLY
```
------------------------------------------------------------------------
                          Summary of Ops' Stat
------------------------------------------------------------------------
| round | first(ms) | curr(ms) | min(ms) | max(ms) | avg(ms) |     std |
------------------------------------------------------------------------
|    85 |   115.365 |  115.283 | 115.163 | 116.108 | 115.423 | 144.200 |
------------------------------------------------------------------------
```
- AFFINITY_HIGH_PERFORMANCE
```
-------------------------------------------------------------------------
                          Summary of Ops' Stat
-------------------------------------------------------------------------
| round | first(ms) | curr(ms) | min(ms) | max(ms) | avg(ms) |      std |
-------------------------------------------------------------------------
|    56 |   177.581 |  174.511 | 141.210 | 179.872 | 176.193 | 5070.302 |
-------------------------------------------------------------------------
```

as you can see "AFFINITY_HIGH_PERFORMANCE" has a worst latency performance which is unnormal by my opinion.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. add one line mace/benchmark/benchmark_model.cc:222 like:
============================================
    +++ FLAGS_cpu_affinity_policy = 2; // 1,2,3
    LOG(INFO) << "cpu_affinity_policy: [" << FLAGS_cpu_affinity_policy << "]";
============================================
3. python tools/converter.py benchmark --config=/path/to/model.yml  --device_yml=/path/to/device.yml --mace_lib_type=dynamic
```

**Comment by liyinhgqw** [comment]
I think it is due to dynamic scheduling policy. Using more heterogeneous cores to run a small model makes performance of high variation on RK3399.

We are tuning things related to threads. Before we figure it out, you can use homogeneous cores only.

**Comment by dimitryn** [comment]
Hi @Alnlll , I am working on RK3399 and observing the same performance issues you have. Does this issue still exist for you ?

**Comment by Alnlll** [comment]
@dimitryn 
Have no idea, I haven't tried the newest version. In my opinion,  using just the little or big cores is not a bad idea if not necessary.
