### ISSUE TITLE
Winograd convolution.

### ISSUE THREAD

**Issue by ssj4gogeta** [XiaoMi/mace#296]
Hello,

I was trying to port Image2D Winograd Convolution Layer to Arm Compute Libary.

I have successfully ported Normal Convolutions to Arm Compute Library. Using Buffer to Image Kernels.

When I try to do the same for Winograd Convolution, I am getting wrong answer.

Here is what I am doing. Winograd block size came to be 4.

1) Converting the filter to winograd filter buffer to image with block size of 4. 

2) Converting the input buffer [This is already in image2d format, same is used for image2d conv] using winograd transform kernel [4x4] is used.

3) Doing matmul between transformed filter & transformed input buffer & getting output.

4) Transforming the output obtained from step 3 using winograd inverse trasnform kernel [4x4] into final output [This is already in image2d format, same is used for image2d conv]. 

5) I am getting wrong answer doing this. Moreover, the answer is changing if I change wino_blk_size to 2.

Is there anything that I am doing wrong? Any leads will be appreciated.

Thanks.

**Comment by ssj4gogeta** [comment]
Hello @nolanliou ,

Yes, I am using the same memory layout.

I wanted to port this to ACL because this is faster on Adreno platform as compared to the ACL one which is based on Buffers.

**Comment by llhe** [comment]
@ssj4gogeta You can read this paper: https://arxiv.org/pdf/1509.09308.pdf. This paper is quite practicable as a guide to implement Winograd Convolution.
