### ISSUE TITLE
Use self cross toolchain to compile mace-master error.

### ISSUE THREAD

**Issue by spacegrass** [XiaoMi/mace#299]
-- When I use a arm-linux cross toolchain to compile mace-master. there are some errors.
-- The following is the error.

ERROR: /home/candy/sg_code/mace-master/mace/mace/codegen/BUILD:41:1: C++ compilation of rule '//mace/codegen:generated_version' failed (Exit 2): arm-linux-gcc failed: error executing command 
  (cd /home/candy/.cache/bazel/_bazel_candy/608b4caa92261277845e578083280aad/execroot/mace && \
  exec env - \

-------------------
Does mace support elf-32 cross toolchain on ubuntu64 os ?
I have wrote a compile scripts according to arm-linux-armhf.

**Comment by llhe** [comment]
@spacegrass Can you paste the full error log?

It should be supported

**Comment by spacegrass** [comment]
Thank you for your reply.
Our cross toolchain is a modified version based linaro 4.8.5.
I updated it to 4.9 64 bit cross toolchain and compile successly.
