### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [XiaoMi/mace#30]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [the following](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?").
* [CPUAllocator:New](https://github.com/JakobEngel/dso/blob/f6e43e277a8e6f606265c1d90fd7549e475e6ea6/src/util/DatasetReader.h#L92 "CPUAllocator::New function")
* [Tensor](https://github.com/XiaoMi/mace/blob/c569dbb438af22f40abeba7f0fe8c23ccb35d14c/mace/core/tensor.h#L126 "Destructor for Tensor")

**Comment by liyinhgqw** [comment]
Yes, I think things will go well if we `delete nullptr` for C++14.
But we are not sure it is also the case in C++11 or older version. 
See https://stackoverflow.com/questions/6731331/is-it-still-safe-to-delete-nullptr-in-c0x

Feel free to notice us or contribute as long as you can find a document to prove it.

**Comment by elfring** [comment]
Would you like to extend any system configuration checks for the involved versions of mentioned application programming interfaces so that the software implementation can be improved a bit more?

**Comment by llhe** [comment]
Close this due to  inactivity.
