### ISSUE TITLE
errors when i build the examples in docker

### ISSUE THREAD

**Issue by ShiyangZhang** [XiaoMi/mace#301]
I met errors when i ran:

> cd mace/exampls/android
> ./build.sh dynamic

* What went wrong:

> Execution failed for task ':macelibrary:generateJsonModelDebug'.
> > Error occurred while communicating with CMake server. Check log /mace-0.10.0/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/cmake_server_log.txt for additional information.
> 

------------------------

### System information
I pull the docker registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem

> error building examples in docker

### To Reproduce

> Steps to reproduce the problem:
> sudo docker run -it --privileged -d --name container-lite \
>            -v /dev/bus/usb:/dev/bus/usb --net=host \
>            -v /home/zhang:/nfs \
>            -v /usr/bin/docker:/usr/bin/docker \
>            -v /var/run/docker.sock:/var/run/docker.sock \
>            registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite
> 
> sudo docker exec -it container-lite /bin/bash
> 
> (download mace-0.10.0)
> 
> cd path/to/mace-0.10.0
> bash tools/build-standalone-lib.sh
> 
> cd mace/exampls/android
> ./build.sh dynamic
> 

### Error information / logs

> > Task :macelibrary:generateJsonModelDebug
> 
> 
> [== "CMake Server" ==[
> 
> {"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":1}],"type":"hello"}
> 
> ]== "CMake Server" ==]
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':macelibrary:generateJsonModelDebug'.
> > Error occurred while communicating with CMake server. Check log /mace-0.10.0/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/cmake_server_log.txt for additional information.
> 

### Additional context

cmake_server_log.txt :+1: 

CMAKE SERVER:

CMAKE SERVER: [== "CMake Server" ==[

CMAKE SERVER: {"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":1}],"type":"hello"}

CMAKE SERVER: ]== "CMake Server" ==]

**Comment by lee-bin** [comment]
Maybe this can help you?
https://stackoverflow.com/questions/47393862/errorerror-occurred-while-communicating-with-cmake-server?rq=1

**Comment by ShiyangZhang** [comment]
> Maybe this can help you?
> https://stackoverflow.com/questions/47393862/errorerror-occurred-while-communicating-with-cmake-server?rq=1

hi lee-bin, thanks for your reply.
I can not build any apk inside the docker now. I will try android studio later.

**Comment by yejw5** [comment]
@ShiyangZhang It's caused by the upgrade of gradle default cmake, from 3.6 to 3.10. You can use `sdkmanager` command (in `/ops/sdk/`) to downgrade cmake version.

## list all avaiable cmake version
```sh
/opt/sdk/tools/bin/sdkmanager --list | grep cmake

#   cmake;3.10.2.4988404                                                                     | 3.10.2       | CMake 3.10.2.4988404                                                
#  cmake;3.6.4111459                                                                        | 3.6.4111459  | CMake 3.6.4111459
```

## install specific cmake (3.6.4)
```sh
/opt/sdk/tools/bin/sdkmanager "cmake;3.6.4111459"
```

## uninstall inappropriate version (3.10.2)
```sh
/opt/sdk/tools/bin/sdkmanager "cmake;3.10.2.4988404"
```

**Comment by ShuaiHuang** [comment]
> @ShiyangZhang It's caused by the upgrade of default cmake in gradle, from 3.6 to 3.10. You can use `sdkmanager` command (in `/ops/sdk/`) to downgrade cmake version.
> 
> ## list all avaiable cmake version
> ```shell
> /opt/sdk/tools/bin/sdkmanager --list | grep cmake
> 
> #   cmake;3.10.2.4988404                                                                     | 3.10.2       | CMake 3.10.2.4988404                                                
> #  cmake;3.6.4111459                                                                        | 3.6.4111459  | CMake 3.6.4111459
> ```
> 
> ## install specific cmake (3.6.4)
> ```shell
> /opt/sdk/tools/bin/sdkmanager "cmake;3.6.4111459"
> ```
> 
> ## uninstall inappropriate version (3.10.2)
> ```shell
> /opt/sdk/tools/bin/sdkmanager "cmake;3.10.2.4988404"
> ```

Thank you @yejw5 ! It solves my problem.

**Comment by ShiyangZhang** [comment]
> @ShiyangZhang It's caused by the upgrade of default cmake in gradle, from 3.6 to 3.10. You can use `sdkmanager` command (in `/ops/sdk/`) to downgrade cmake version.
> ## list all avaiable cmake version
> 
> ```shell
> /opt/sdk/tools/bin/sdkmanager --list | grep cmake
> 
> #   cmake;3.10.2.4988404                                                                     | 3.10.2       | CMake 3.10.2.4988404                                                
> #  cmake;3.6.4111459                                                                        | 3.6.4111459  | CMake 3.6.4111459
> ```
> 
> ## install specific cmake (3.6.4)
> 
> ```shell
> /opt/sdk/tools/bin/sdkmanager "cmake;3.6.4111459"
> ```
> 
> ## uninstall inappropriate version (3.10.2)
> 
> ```shell
> /opt/sdk/tools/bin/sdkmanager "cmake;3.10.2.4988404"
> ```

Thanks so much for your reply and sorry  for my late reply.  I failed and decided to re-build from the begining. I will report the result when it has been finished.
