### ISSUE TITLE
something is wrong during building mace

### ISSUE THREAD

**Issue by chiwangnvp** [XiaoMi/mace#302]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by chiwangnvp** [comment]
chiwang@ubuntu:~/mace$ bash tools/build-standalone-lib.sh 
build shared lib for armeabi-v7a + cpu_gpu_dsp
INFO: Invocation ID: 9df59309-223f-420b-83c6-1bb7d7c9d2d4
ERROR: Analysis of target '//mace/libmace:libmace_dynamic' failed; build aborted: no such package '@tflite//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 0.705s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 54 targets co\
nfigured)
    currently loading: @androidndk//
    Fetching @tflite; fetching

**Comment by chiwangnvp** [comment]
my operations are as following:
git clone https://github.com/XiaoMi/mace.git
cd mace
bash tools/build-standalone-lib.sh

**Comment by nolanliou** [comment]
If your bazel version beyond 0.20.0,  downgrade to bazel 0.19.2 could resolve the issue.
