### ISSUE TITLE
building error : bazel command not found

### ISSUE THREAD

**Issue by chiwangnvp** [XiaoMi/mace#303]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by chiwangnvp** [comment]
chiwang@ubuntu:~/mace$ sudo bash tools/build-standalone-lib.sh 
build shared lib for armeabi-v7a + cpu_gpu_dsp
tools/build-standalone-lib.sh: line 35: bazel: command not found

and line 35 in the build-standalone-lib.sh is :
bazel build --config android --config optimization mace/libmace:libmace_dynamic --define neon=true --define openmp=true --define opencl=true --define hexagon=true --define quantize=true --cpu=armeabi-v7a

**Comment by chiwangnvp** [comment]
my bazel version :

chiwang@ubuntu:~/mace$ bazel version
Build label: 0.19.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Nov 19 16:25:09 2018 (1542644709)
Build timestamp: 1542644709
Build timestamp as int: 1542644709

**Comment by lee-bin** [comment]
You should not use `sudo` to run `bash tools/build-standalone-lib.sh` which invokes `bazel` as bazel is installed under user `chiwang` instead of `root`.

**Comment by chiwangnvp** [comment]
If I don't use sudo, it's reporting "Permission Denied" :

chiwang@ubuntu:~/mace$ bash tools/build-standalone-lib.sh 
rm: cannot remove ‘builds/lib/armeabi-v7a/cpu_gpu’: Permission denied
rm: cannot remove ‘builds/lib/armeabi-v7a/cpu_gpu_dsp’: Permission denied
chiwang@ubuntu:~/mace$

**Comment by chiwangnvp** [comment]
Why ?

**Comment by yejw5** [comment]
@chiwangnvp Your previous command run with `sudo`. So the created directory `builds` in the root dir of Mace Project is owned by root user. You need to remove `./builds` with sudo permission firstly.

**Comment by yejw5** [comment]
@chiwangnvp Your previous command run with `sudo`. So the created directory `builds` in the root dir of Mace Project is owned by root user. You need to remove `./builds` with sudo permission firstly.
