### ISSUE TITLE
bash tools/build-standalone-lib.sh ERROR

### ISSUE THREAD

**Issue by chiwangnvp** [XiaoMi/mace#305]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by chiwangnvp** [comment]
chiwang@ubuntu:~/mace$ bash tools/build-standalone-lib.sh 
build shared lib for armeabi-v7a + cpu_gpu_dsp
v0.10.0-10-ga6c02e7-20190109
Generate OpenCL kernel done.
INFO: Analysed target //mace/libmace:libmace_dynamic (24 packages loaded, 1733 targets configured).
INFO: Found 1 target...
ERROR: /home/chiwang/.cache/bazel/_bazel_chiwang/d116ea2584a02de296c07491a26bef23/external/com_google_protobuf/BUILD:260:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1) gcc failed: error executing command 
  (cd /home/chiwang/.cache/bazel/_bazel_chiwang/d116ea2584a02de296c07491a26bef23/execroot/mace && \
  exec env - \
    PATH=/home/chiwang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/chiwang/android-ndk-r10b \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_service.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_service.o' -iquote external/com_google_protobuf -iquote bazel-out/host/genfiles/external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/genfiles/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -g0 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-writable-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/java/java_service.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_service.o)

Use --sandbox_debug to see verbose messages from the sandbox: gcc failed: error executing command 
  (cd /home/chiwang/.cache/bazel/_bazel_chiwang/d116ea2584a02de296c07491a26bef23/execroot/mace && \
  exec env - \
    PATH=/home/chiwang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/chiwang/android-ndk-r10b \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_service.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_service.o' -iquote external/com_google_protobuf -iquote bazel-out/host/genfiles/external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/genfiles/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -g0 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-writable-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/java/java_service.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_service.o)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error: unrecognized command line option '-fcolor-diagnostics'
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 28.275s, Critical Path: 0.58s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
FAILED: Build did NOT complete successfully
chiwang@ubuntu:~/mace$ gcc version
gcc: error: version: No such file or directory
gcc: fatal error: no input files
compilation terminated.
chiwang@ubuntu:~/mace$ 
chiwang@ubuntu:~/mace$ 
chiwang@ubuntu:~/mace$ 
chiwang@ubuntu:~/mace$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

chiwang@ubuntu:~/mace$

**Comment by chiwangnvp** [comment]
gcc: error: unrecognized command line option '-fcolor-diagnostics'

**Comment by chiwangnvp** [comment]
chang my ndk to version r15c, still the same error :
chiwang@ubuntu:~/mace$ bash tools/build-standalone-lib.sh 
build shared lib for armeabi-v7a + cpu_gpu_dsp
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/libmace:libmace_dynamic (2 packages loaded, 5947 targets configured).
INFO: Found 1 target...
[1 / 4] no action

ERROR: /home/chiwang/.cache/bazel/_bazel_chiwang/d116ea2584a02de296c07491a26bef23/external/com_google_protobuf/BUILD:260:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1) gcc failed: error executing command 
  (cd /home/chiwang/.cache/bazel/_bazel_chiwang/d116ea2584a02de296c07491a26bef23/execroot/mace && \
  exec env - \
    PATH=/home/chiwang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/chiwang/android-ndk-r15c \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_doc_comment.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_doc_comment.o' -iquote external/com_google_protobuf -iquote bazel-out/host/genfiles/external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/genfiles/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -g0 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-writable-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/java/java_doc_comment.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_doc_comment.o)

Use --sandbox_debug to see verbose messages from the sandbox: gcc failed: error executing command 
  (cd /home/chiwang/.cache/bazel/_bazel_chiwang/d116ea2584a02de296c07491a26bef23/execroot/mace && \
  exec env - \
    PATH=/home/chiwang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/chiwang/android-ndk-r15c \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_doc_comment.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_doc_comment.o' -iquote external/com_google_protobuf -iquote bazel-out/host/genfiles/external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/genfiles/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -g0 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-writable-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/java/java_doc_comment.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/java_doc_comment.o)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error: unrecognized command line option '-fcolor-diagnostics'
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 48.023s, Critical Path: 1.21s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
FAILED: Build did NOT complete successfully
chiwang@ubuntu:~/mace$

**Comment by chiwangnvp** [comment]
it seems something wrong with gcc :
gcc: error: unrecognized command line option '-fcolor-diagnostics'

**Comment by chiwangnvp** [comment]
I upgrad my gcc to 5.4.0 , but still the same mistake.
What happened?Plz help me.

**Comment by lee-bin** [comment]
You can try `bazel clean --expunge` and then build again.
