### ISSUE TITLE
[Platform Support] aarch64 android support

### ISSUE THREAD

**Issue by Alnlll** [XiaoMi/mace#306]
I'm using RK3399(aarch64) with android-7.1, and noticed that mace supports for aarch64 chips on linux(according to build-standalone-lib.sh).
Is there a recent plan to add support for aarch64 on android or can I get a simple instruction for buiding support by myself?

**Comment by llhe** [comment]
Now the following ABIs are supported and optimized with NEON(other ABIs may also be built but not optimized):
* Android
  * armeabi-v7a
  * arm64-v8a
* Linux
  * arm-linux-gnueabihf
  * aarch64-linux-gnu

I guess you mean arm64-v8a, which you can just define it in your model like this: https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v1/mobilenet-v1.yml#L2
