### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [XiaoMi/mace#31]
Would you like to [wrap any pointer variables](https://github.com/XiaoMi/mace/blob/73980a50c58ac3a49e09e18d8979aae339af4c76/mace/kernels/arm/conv_winograd.cc#L655 "Update candidate: WinoGradConv3x3s1()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by liyinhgqw** [comment]
Not exactly, only if ownership needs to be transferred.
We stick to [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Ownership_and_Smart_Pointers).

Quote:
"If dynamic allocation is necessary, prefer to keep ownership with the code that allocated it. If other code needs access to the object, consider passing it a copy, or passing a pointer or reference without transferring ownership. Prefer to use std::unique_ptr to make ownership transfer explicit. "

**Comment by elfring** [comment]
How do you think about [the guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation")?

**Comment by llhe** [comment]
@elfring 
We just follow this principle. And we only use raw pointer in allocator.

**Comment by elfring** [comment]
Would you like to [reconsider questionable source code in the implementation of a function like “`WinoGradConv3x3s1`”](https://github.com/XiaoMi/mace/blob/73980a50c58ac3a49e09e18d8979aae339af4c76/mace/kernels/arm/conv_winograd.cc#L655 "Update candidate: WinoGradConv3x3s1()")?
