### ISSUE TITLE
Opencl 1.2 comments #pragma OPENCL EXTENSION cl_khr_fp16 : enable

### ISSUE THREAD

**Issue by spacegrass** [XiaoMi/mace#310]
Question:    Does mace 0.10.0 supports modified opencl 1.2 ?
Description:  1. opencl version: 1.2 
                     2. extern:    cl_khr_byte_addressable_store 
					cl_khr_global_int32_base_atomics 
					cl_khr_global_int32_extended_atomics 
					cl_khr_local_int32_base_atomics 
					cl_khr_local_int32_extended_atomics 
					cl_khr_gl_sharing 
I comments the sentence:  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
in mace/ops/opencl/cl/common.h

Error: 
I mace/core/runtime/opencl/opencl_runtime.cc:551] build err. ret: -11 build_options_str:  -DCMD_DATA_TYPE=h -DDATA_TYPE=half -Dfilter_buffer_to_image=fy2AxAkxG344HrLHuDI8ED -Werror -cl-mad-enable -cl-fast-relaxed-math

I mace/core/runtime/opencl/opencl_runtime.cc:556] Program build log: (192:0) : error : function: 'write_imageh' hasn't the corresponding declaration
--------------------------------------------------
How could i solve it ? Thank you.

**Comment by nolanliou** [comment]
Use the `data_type: fp32_fp32` in your model deployment file(.yml), and comment the line `#pragma OPENCL EXTENSION cl_khr_fp16 : enable`

**Comment by spacegrass** [comment]
Thank you for your reply.
After adding     data_type: fp32_fp32     item to movilenetv2.yml, mace can run the model successfully.
But the speed is very slow.
![image](https://user-images.githubusercontent.com/3315048/51537060-6deaca00-1e88-11e9-8ef3-12335d03a281.png)
-------------
loop_1: 25.293s
loop_2: 1.18778s
.....

Does because the fp32 ?

**Comment by nolanliou** [comment]
There are some devices which GPU may slow than CPU, so what's your hardware?

**Comment by spacegrass** [comment]
Thank you for your reply.
I convert mtcnn to mace model and run 3 net on the board, but the speed is still very slow.
![image](https://user-images.githubusercontent.com/3315048/51961882-36d47400-2499-11e9-9c36-adf47ea06a6c.png)
![image](https://user-images.githubusercontent.com/3315048/51961896-4358cc80-2499-11e9-9a26-3cbee00c8a99.png)
![image](https://user-images.githubusercontent.com/3315048/51961903-4c499e00-2499-11e9-8780-f5226b568556.png)

The above 3 images are PNet/RNet/ONet. 
PNet input: 64*48
RNet: 24*24
ONet: 48*48

The speed is so slow as mobilenetv2 224*224. I think there is something wrong.

![image](https://user-images.githubusercontent.com/3315048/51962058-cd089a00-2499-11e9-91ea-8ba5db3fa04f.png)

The chip is powerful.
arm 32 os
Does it because of the os ?

**Comment by spacegrass** [comment]
The input data buf-data 2 img-data and output data img-data 2 buf-data will build kernel everytime when we run the net. so I modify the code and it only create once.

**Comment by 92ypli** [comment]
Hello, how to modify the code and it only create once?

**Comment by spacegrass** [comment]
you can review the code. add a flag when create the layer or let the layer not be a temporary-instance. I can't remember the detail.
