### ISSUE TITLE
mobilenet-ssd计算得到的结果不正确。

### ISSUE THREAD

**Issue by leeburt** [XiaoMi/mace#319]
**相关的环境配置和模型配置文件见** #309 

### Describe the  problem
将mace得到的最后三层的结果和opencv的结果做对比发现有差异特别是“mbox_priorbox”层。

### 保存的“mbox_loc”和“mbox_priorbox”数据
[mace_mboc_priorbox.txt](https://github.com/XiaoMi/mace/files/2781131/mace_mboc_priorbox.txt)
[mace_mbox_loc.txt](https://github.com/XiaoMi/mace/files/2781132/mace_mbox_loc.txt)
[opencv_mbox_loc.txt](https://github.com/XiaoMi/mace/files/2781141/opencv_mbox_loc.txt)
[opencv_mbox_priorbox.txt](https://github.com/XiaoMi/mace/files/2781139/opencv_mbox_priorbox.txt)

**Comment by lydoc** [comment]
该bug已经修复，正在内部code review，会在这一两天更新到master。

**Comment by leeburt** [comment]
@lydoc 我先试试，想问问如果出现了这种问题，我自己如何定位问题？把每一层的结果打印出来吗？

**Comment by lee-bin** [comment]
你可以参考这里https://mace.readthedocs.io/en/latest/development/how_to_debug.html#debug-correctness
用MACE提供的工具验证一下所怀疑层的结果。

**Comment by lydoc** [comment]
ION需要在host上已经分配一块内存用在gpu上。需要的话可以在mace初始化的时候做。

**Comment by leeburt** [comment]
> ION需要在host上已经分配一块内存用在gpu上。需要的话可以在mace初始化的时候做。

谢谢回答，如果用ION的方法是不是可以在进一步优化耗时，值得尝试吗，另外这样做有什么缺点吗？

**Comment by llhe** [comment]
@leeburt ION buffer是高通扩展，除了兼容性目前没有其他已知问题，你可以尝试一下

**Comment by leeburt** [comment]
> @leeburt ION buffer是高通扩展，除了兼容性目前没有其他已知问题，你可以尝试一下

谢谢回答~新春快乐！

**Comment by leeburt** [comment]
> @leeburt ION buffer是高通扩展，除了兼容性目前没有其他已知问题，你可以尝试一下

@llhe 你好，这两天着手进行内存共享代码修改，但是发现mace的源码代码量有些大，不知从何着手，能提供一些修改的思路和建议吗？
