### ISSUE TITLE
convert tensorflow model failed

### ISSUE THREAD

**Issue by moliqian** [XiaoMi/mace#320]
###environment
my environment is the same with https://mace.readthedocs.io/en/latest/installation/env_requirement.html
 tensorflow==1.8

### Describe the problem
when i convert pb model file( running: python tools/converter.py convert --config=/home/shinchan/software/mace/EOD/eod-unet_resnet.yml ). it' wrong like below. what can i do??
tf.layers.conv2d_transpose()  and i never use batch normalization.

(tensorflow) shinchan@:~/software/mace$ python tools/converter.py convert --config=/home/shinchan/software/mace/EOD/eod-unet_resnet.yml 
------------------------------------
        Common Configuration        
------------------------------------
|        key        |    value     |
====================================
|       library_name|           eod|
------------------------------------
|        target_abis| ['arm64-v8a']|
------------------------------------
|        target_socs|            []|
------------------------------------
| model_graph_format|          code|
------------------------------------
|  model_data_format|          code|
------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

********************************************
          Convert unetresnet model          
********************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.200s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
Fold deconv and bn: unet_resnet/upsample_1/conv2d_transpose/conv2d_transpose(Deconv2D)
Traceback (most recent call last):
  File "/home/shinchan/software/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 355, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/shinchan/software/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 196, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/home/shinchan/software/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 125, in run
    changed = transformer()
  File "/home/shinchan/software/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 627, in fold_deconv_and_bn
    offset = self._consts[consumer_op.input[2]]
  File "/home/shinchan/.cache/bazel/_bazel_shinchan/35c464927a318a04ae8f288698ec1134/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/shinchan/software/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/home/shinchan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/shinchan/anaconda2/envs/tensorflow/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/shinchan/software/mace/EOD/unetresnet/freeze_model.pb --weight_file= --model_checksum=e532ecc2307da3c546b7f9f1cbd1e5d51ee8b57a5d279bc9f84bbf4d137d2ded --weight_checksum= --input_node=input --input_data_formats=NHWC --output_node=unet_resnet/DepthToSpace --output_data_formats=NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=unetresnet --input_shape=1,4608,3456,1 --input_range= --output_shape=1,4608,3456,3 --check_shape= --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/unetresnet --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:

  STDERR:

**Comment by TonyMou** [comment]
方便提供你的模型文件测试一下吗？

**Comment by moliqian** [comment]
@TonyMou 请问你的邮箱多少呢？我发过去给你。谢谢

**Comment by moliqian** [comment]
@TonyMou  [](https://pan.baidu.com/s/1i-wLbpT_Sef9k1V2Eaqykw)

**Comment by moliqian** [comment]
https://pan.baidu.com/s/1i-wLbpT_Sef9k1V2Eaqykw

**Comment by moliqian** [comment]
@TonyMou 搞定了。mace文件：mace/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py中去掉fold_deconv_and_bn函数中if条件中的input_len == 3.
同时，注释掉mace/mace/python/tools/converter_tool.py中line473-478行。
解决。
谢谢@TonyMou

**Comment by moliqian** [comment]
@TonyMou 你好。我又把这个issue打开了。注释和删除那些代码之后，发现生成的库文件有问题。在创建engine的时候程序崩溃了。pb文件如下：https://pan.baidu.com/s/1ItF3_IIOedEotHFRG8KTiQ

**Comment by TonyMou** [comment]
已解决，很快会更新代码。如着急可以先用这个patch，将mace/python/tools/converter_tool/transformer.py中631行的if 语句改为：
```
if consumer_op.type == MaceOp.BatchNorm.name and (
                        (framework == FrameworkType.CAFFE.value and
                         (input_len == 2 or (input_len == 3 and
                                             op.input[-1] in self._consts))) or
                        (framework == FrameworkType.TENSORFLOW.value and
                         (input_len == 3 or (input_len == 4 and
                                             op.input[-1] in self._consts)))):
```

**Comment by zy2008cn** [comment]
> 已解决，很快会更新代码。如着急可以先用这个patch，将mace/python/tools/converter_tool/transformer.py中631行的if 语句改为：
> 
> ```
> if consumer_op.type == MaceOp.BatchNorm.name and (
>                         (framework == FrameworkType.CAFFE.value and
>                          (input_len == 2 or (input_len == 3 and
>                                              op.input[-1] in self._consts))) or
>                         (framework == FrameworkType.TENSORFLOW.value and
>                          (input_len == 3 or (input_len == 4 and
>                                              op.input[-1] in self._consts)))):
> ```

@TonyMou 您好，我和@moliqian遇到相同的问题，错误列表几乎一致，我看了下我的这个文件mace/python/tools/converter_tool/transformer.py，已经有这段代码
