### ISSUE TITLE
Mace doesn't support Clip or Constant

### ISSUE THREAD

**Issue by ericdanz** [XiaoMi/mace#321]
Onnx version 1.3.0, Mace version 0.10 
I can optimize the onnx file using onnx_optimizer.py, but running convert fails with 

Exception: Mace does not support onnx op type Clip yet

If I run convert with the unoptimized onnx file, I get a similar error:

Exception: Mace does not support onnx op type Constant yet

Any ideas when these ops will be supported?

**Comment by xiaqing10** [comment]
Exception: Mace does not support tensorflow op type Enter yet
I have also this problem

**Comment by eudora-jia** [comment]
again, Any ideas when these ops will be supported?
