### ISSUE TITLE
请问mace支持任意大小的图像作为输入吗

### ISSUE THREAD

**Issue by czczup** [XiaoMi/mace#322]
在TensorFlow中，我的输入是tf.placeholder(tf.float32, [1, None, None, 3], name='input')，输出的尺寸和输入尺寸相同。而在mace的yml里，应该是需要定义一个输入大小吧？就像下面这样：
input_tensors: img_placeholder
input_shapes: 1,480,640,3
output_tensors: add_37
output_shapes: 1,480,640,3
而我需要的是：
input_tensors: img_placeholder
input_shapes: 1,None,None,3
output_tensors: add_37
output_shapes: 1,None,None,3
这样该怎么在mace中实现呢？

**Comment by TonyMou** [comment]
支持任意尺寸输入，填你需要的最大的shape
