### ISSUE TITLE
一些关于 MaceTensor 的建议

### ISSUE THREAD

**Issue by Pinnh** [XiaoMi/mace#324]
### System information
- **OS Platform and Distribution  Linux Ubuntu 16.04
- **NDK version 16b
- **GCC version 5.4.0
- **MACE version master
- **Python version 2.7 
- **Bazel version  0.13.1 

### Describe the problem

MaceTensor没有自持的数据及shape，所以会完全依赖于外部数据及其shape，这也会导致后面的问题， 
如： 很多时候（如：全卷积网络）我们输入shape是不固定的，输出shape也是不固定的，这个输出shape用户并不一定能够计算出来，尤其是复杂的模型，但是框架是能够直接从开始计算得出output_shapes，所以建议MaceTensor有自持数据及在框架内计算出output_shapes

 以上为个人理解，如果有误的话，请详解。

**Comment by liyinhgqw** [comment]
我们已经解决了这个问题，代码即将 merge

**Comment by Pinnh** [comment]
好的，期待！
