### ISSUE TITLE
include 多个 mace_engine_factory.h 会发生冲突

### ISSUE THREAD

**Issue by Pinnh** [XiaoMi/mace#326]
### System information
- **OS Platform and Distribution   Linux Ubuntu 16.04
- **NDK version 16b
- **GCC version 5.4.0
- **MACE version master
- **Python version 2.7
- **Bazel version  0.13.1

### Describe the problem
mobilenet-v2/
├── include
│   └── mace
│       └── public
│           ├── mace_engine_factory.h
│           └── mobilenet_v2.h
└── model
    ├── arm64-v8a
        └── mobilenet-v2.a

xnet/
├── include
│   └── mace
│       └── public
│           ├── mace_engine_factory.h
│           └── xnet.h
└── model
    ├── arm64-v8a
        └── xnet.a

当Convert model(s) to C++ code 时, mobilenet_v2.h这个头文件基本没用（冗余），而如果有多个模型包含在同一个cpp文件时 include 多个 mace_engine_factory.h 会发生冲突
如：
#include "mace/public/mace.h"
#include "mobilenet-v2/include/mace/public/mobilenet_v2.h"
#include "mobilenet-v2/include/mace/public/mace_engine_factory.h"

#include "xnet/include/mace/public/xnet.h"
#include "xnet/include/mace/public/mace_engine_factory.h"

CreateMaceEngineFromCode（...）该函数使用会出错，感觉生成的命名空间有问题

可能出现的错误（mobilenet-v2和xnet的 input_name 不同时）：
 MACE    : mace.cc:432 Creating MaceEngine, MACE version: v0.10.0-30-g858dda5-20190122
01-24 15:49:32.960 20016 20016 I MACE    : mace.cc:464 Initializing MaceEngine
01-24 15:49:32.960 20016 20016 F MACE    : mace.cc:483 'data' does not belong to model's inputs: [input]
01-24 15:49:32.960 20016 20016 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 20016 (com.test.mace), pid 20016 (com.test.mace)

建议:
只生成一个头文件，包含mobilenet_v2.h和mace_engine_factory.h的内容
CreateMaceEngineFromCode（...）在模型命名空间内使用，或不同的模型使用不同的创建方式

以上为个人理解，有问题欢迎指出。

**Comment by Pinnh** [comment]
好吧，这样的确可以

**Comment by nolanliou** [comment]
是这样设计的
