### ISSUE TITLE
winograd parameter

### ISSUE THREAD

**Issue by herbakamil** [XiaoMi/mace#327]
https://github.com/XiaoMi/mace/blob/a74002cb411c39098692b1ebf54c5ab0ac339304/mace/ops/conv_2d.cc#L145

Do I understand correctly that Winograd parameter is used only in case of GPU and for CPU Winograd algorithm is always used if and only if we have convolution with kernel of height, width = 3 and stride, dilation equal 1?

It's not clear from documentation and it would be nice to clarify if I understand correctly.

**Comment by sumant85** [comment]
@nolanliou is there a good way to determine whether to use `winograd:2` or `winograd:4` for GPU inference?

**Comment by nolanliou** [comment]
`winograd:4` take more memory than `2` and precision may be a little lower. You could test your model and choose which one to use according to your needs.
