### ISSUE TITLE
running example.cc using mobilenet-v2

### ISSUE THREAD

**Issue by gururaghavendraprasad** [XiaoMi/mace#328]
While running example.cc in mace on imx8. i am  getting following error.
"input_node0' does not belong to model's inputs: [input]"
where should i give input_node and what to give.
mace engine is successfully initialized.

Thanks

**Comment by nolanliou** [comment]
You should use your model's input tensor name, and keep the name same between model deployment file(.yml) and `inputs` variable in C++.

**Comment by gururaghavendraprasad** [comment]
thanks for the reply !!
can you specify where we should do that ?
I got to know the message is getting printed in "//Set storage path for internal usage" block in C++ file

**Comment by gururaghavendraprasad** [comment]
thanks for the reply !!
can you specify where we should do that ?
I got to know the message is getting printed in "//Set storage path for internal usage" block in C++ file

**Comment by nolanliou** [comment]
what is your model's input tensor name?

**Comment by gururaghavendraprasad** [comment]
Thanks for the help !!
 I got it.
