### ISSUE TITLE
Crash on mali-T860 mp4 gpu

### ISSUE THREAD

**Issue by Pinnh** [XiaoMi/mace#329]
### System information
- **OS Platform and Distribution  Linux Ubuntu 16.04 
- **NDK version  16b
- **GCC version  5.4.0
- **MACE version master
- **Python version 2.7 
- **Bazel version  0.13.1

### Model deploy file (*.yml)
自己的模型

### Describe the problem

模型在mali-860 gpu只能运行一次，运行第二次会crash，删除本地mace_cl_compiled_program.bin后正常运行一次后继续crash，只要mace_cl_compiled_program.bin生成后再运行就会crash。

在高通adreno gpu上运行没有问题

已经看到了 [[#245]](https://github.com/XiaoMi/mace/issues/245) 描述的问题，请问在自定义模型上如何避免该问题？

### Error information / logs

mali_so : [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 976; [Func] : base_context_deal_with_version_affairs_rk_ext;
01-26 06:59:17.415  5726  5742 I mali_so : arm_release_ver of this mali_so is 'r14p0-01rel0', rk_so_ver is '6@0'.
01-26 06:59:17.415  5726  5742 D mali_so : [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 981; [Func] : base_context_deal_with_version_affairs_rk_ext;
01-26 06:59:17.415  5726  5742 D mali_so : current process is NOT sf, to bail out.
01-26 06:59:17.418  5726  5742 I OpenGLRenderer: Initialized EGL, version 1.4
01-26 06:59:17.418  5726  5742 D OpenGLRenderer: Swap behavior 1
01-26 06:59:17.427   204   467 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0x900.
01-26 06:59:17.440   204   467 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0x900.
01-26 06:59:17.453   204   467 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0x900.
01-26 06:59:17.466   204   661 E BufferQueueProducer: [com.test.mace/com.test.mace.MainActivity] connect: already connected (cur=1 req=1)
01-26 06:59:17.467  5726  5742 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
01-26 06:59:17.511   204   211 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0xb00.
01-26 06:59:17.523  5726  5742 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0xb00.
01-26 06:59:17.547   204   211 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0xb00.
01-26 06:59:17.558  5726  5742 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0xb00.
01-26 06:59:17.892   554  1417 D IpReachabilityMonitor: RtNetlinkNeighborMessage{ nlmsghdr{StructNlMsgHdr{ nlmsg_len{76}, nlmsg_type{28(RTM_NEWNEIGH)}, nlmsg_flags{0())}, nlmsg_seq{0}, nlmsg_pid{0} }}, ndmsg{StructNdMsg{ family{AF_INET}, ifindex{4}, state{16 (NUD_PROBE)}, flags{0 ()}, type{1} }}, destination{192.168.0.1} linklayeraddr{3C46D86B5FC0} probes{1} cacheinfo{NdaCacheInfo{ ndm_used{32040}, ndm_confirmed{1980}, ndm_updated{0}, ndm_refcnt{2} }} }
01-26 06:59:17.907   554  1417 D IpReachabilityMonitor: RtNetlinkNeighborMessage{ nlmsghdr{StructNlMsgHdr{ nlmsg_len{76}, nlmsg_type{28(RTM_NEWNEIGH)}, nlmsg_flags{0())}, nlmsg_seq{0}, nlmsg_pid{0} }}, ndmsg{StructNdMsg{ family{AF_INET}, ifindex{4}, state{2 (NUD_REACHABLE)}, flags{0 ()}, type{1} }}, destination{192.168.0.1} linklayeraddr{3C46D86B5FC0} probes{1} cacheinfo{NdaCacheInfo{ ndm_used{0}, ndm_confirmed{2000}, ndm_updated{0}, ndm_refcnt{2} }} }
01-26 06:59:20.094   204   211 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0xb00.
01-26 06:59:20.107  5726  5742 D GRALLOC-ROCKCHIP: enter, w : 1920, h : 1016, format : 0x1, usage : 0xb00.
01-26 06:59:20.216   243   307 D alsa_route: route_set_controls() set route 24
01-26 06:59:20.236  5726  5726 I MACE    : mace.cc:432 Creating MaceEngine, MACE version: v0.10.0-30-g858dda5-20190122
01-26 06:59:20.254  5726  5726 I MACE    : mace.cc:464 Initializing MaceEngine
01-26 06:59:20.260  5726  5726 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xee9ee33b6a in tid 5726 (com.test.mace)

**Comment by Pinnh** [comment]
嗯， 不用指定storage_path可以运行， 设备是 Firefly-RK3399

**Comment by Pinnh** [comment]
请问会降低GPU运行性能吗？ 从测试来看，在骁龙GPU运行时间从350ms上升到了5030ms，性能下降太多了

**Comment by nolanliou** [comment]
这是只会影响第一次运行的时间，需要编译OpenCL的kernel。不过对mali gpu影响不大。

**Comment by Pinnh** [comment]
OK，了解，谢谢解答！
