### ISSUE TITLE
MACE GPU inference failing on Adreno 330

### ISSUE THREAD

**Issue by sumant85** [XiaoMi/mace#337]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage? YES
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Version 10.13.6 (17G65)
- **NDK version(e.g., 15c)**: r16b with clang/libc++
- **GCC version(if compiling for host, e.g., 5.4.0)**: N/A
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.20.0-homebrew

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
- Trying to run Mobilenet-v2 model on Sony Xperia (D6708) with Adreno 330 (Running GPU inference mode)

### To Reproduce
- Current MACE master conversion tools don't work with clang toolchain directly, so I'm running MACE within a separate test application. I'm using example code from https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#build-and-run-an-example-model. 
- Mobilenet v2 is directly obtained from mace model zoo (https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v2/mobilenet-v2.yml) without quantization.

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
I opencl_runtime.cc:555 Program build log: BC-src-code:784:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
 #pragma unroll
         ^
BC-src-code:938:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
 #pragma unroll
         ^
BC-src-code:1115:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
 #pragma unroll
         ^
3 diagnostic(s) generated.

W opencl_runtime.cc:557 Build program buffer_to_image from source failed: -11
I buffer_to_image.h:124 Mace runtime failure: ./mace/ops/opencl/image/buffer_to_image.h:124. Out of resources:
F conv_2d.cc:1002 Check failed: TransformFilter<T>( context, operator_def_.get(), 1, OpenCLBufferType::CONV2D_FILTER, mem_type) == MaceStatus::MACE_SUCCESS
```

### Additional context
- Most of the mace library is unmodified, except some header includes to support compilation with clang/libc++ toolchain.

**Comment by llhe** [comment]
@sumant85 Could you please post the OpenCL version info? You can get it by MACE log or by [OpenCL-Z](https://play.google.com/store/apps/details?id=com.robertwgh.opencl_z_android&hl=en_US)

And you can try to disable the warning by setting  `-Wno-unknown-pragmas` or remove `-Werror` here:
https://github.com/XiaoMi/mace/blob/54bbb62b80ec48c80b5a24ca4654ca0ee807745a/mace/core/runtime/opencl/opencl_runtime.cc#L600.

**Comment by sumant85** [comment]
@llhe The device is using OpenCL 1.1 (checked with OpenCl-Z) Let me know if you need any additional information.

**Comment by llhe** [comment]
@sumant85 Did you resolve it by removing `-Werror` or adding `-Wno-unknown-pragmas`?

**Comment by sumant85** [comment]
Yes, thank you! Will close the issue.
