### ISSUE TITLE
instruction to run on firefly rk3399 linux

### ISSUE THREAD

**Issue by kaishijeng** [XiaoMi/mace#338]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by kaishijeng** [comment]
I like to run mace on ubuntu 16.04 on a firefly rk3399. Do I need to install NDK?
when I run
python tools/converter.py convert --config_file=--config=mace-models/mobilenet-v2/mobilenet-v2.yml
It has an error:
sh.CommandNotFound: adb.

SInce I like to run it on rk3399 ubuntu itself, why does it still need adb?

Thanks

**Comment by kaishijeng** [comment]
Why do I get the following error when I run python tools/converter.py convert --config_file=--config=mace-models/mobilenet-v2/mobilenet-v2.yml

 sh.CommandNotFound: adb.

Do I need to change anything in mobilenet-v2.yml to avoid adb?

**Comment by nolanliou** [comment]
please refer to the [document](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#run-you-model-on-the-embedded-device-arm-linux).

**Comment by kaishijeng** [comment]
This is not my usecase. I want to do convert a model using my rk3399 linux
machine and then run converted model on this rk3399 too.
Why does it need "adb" during model conversion?

Thanks,

**Comment by nolanliou** [comment]
You can convert and build your model on rk3399 If you have the environment on your machine, but there is no need to do it. You could convert your model on your development machine with `abi==arm64` or `abi==armhf`, then push and run the program to your rk3399 with `ssh`.
Actually, MACE tools (`tools/converter.y`) does all the above things with a single command. so you just need to write your model deployment file(.yml) and run it.

**Comment by kaishijeng** [comment]
Thanks,
