### ISSUE TITLE
MACE run fails due to MACE_CHECK error

### ISSUE THREAD

**Issue by sumant85** [XiaoMi/mace#346]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.6
- **NDK version(e.g., 15c)**: r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0
- **Python version(2.7)**:  2.7
- **Bazel version (e.g., 0.13.0)**: 0.20.0-homebrew

### Model deploy file (*.yml)
```
Not available since testing on a custom model
```

### Describe the problem
- `MACE_CHECK` fails on the following https://github.com/XiaoMi/mace/blob/fef913af05fb1651ee58af8818f8afa0f6693c57/mace/core/tensor.h#L348 

### To Reproduce
- Current MACE master conversion tools don't work with clang toolchain directly, so I'm running MACE within a separate test application. I'm using example code from https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#build-and-run-an-example-model.
- I'm using a custom model, so can't share the network structure directly, but I've shared some context below.

### Error information / logs
- The exact error message is as follows:
```
F tensor.h:353 Check failed: image_shape[0] <= buffer_->shape()[0] && image_shape[1] <= buffer_->shape()[1] tensor (source op activation_2_output): current physical image shape: 896, 100 < logical image shape: 228, 101
```
which occurs when running the following operation:
```
I logging.h:105 Running operator activation_2_output<2, BatchNorm, 3> started
```
More Info about tensor:
- InputShape = OutputShape = `100(H) 56(W) 16(C)`
- Previous layer is of type `Deconv2D`
- Fused PRELU activation
- `I workspace.cc:272 Tensor: activation_2_output Mem: 5 Data type: 3 Image shape: 896, 100`
- For previous layer: `I workspace.cc:272 Tensor: conv2d_transpose_1_output Mem: 2 Data type: 3 Image shape: 448, 400`

### Additional context
- Most of the mace library is unmodified, except some header includes to support compilation with clang/libc++ toolchain.
- Got same error on OnePlus5 and Galaxy S9+ which are both running opencl 2.0.

**Comment by sumant85** [comment]
Was a bug in computing output shape for deconv2d (incorrect framework specified)

**Comment by cncowboy** [comment]
你好，请问你是怎么解决的？
