### ISSUE TITLE
Do you modified nnlib as well?

### ISSUE THREAD

**Issue by chanchanzhang** [XiaoMi/mace#35]
By checking src code, it looks like there are several API call made which are not support by native nnlib.
like:
hexagon_nn_append_const_node_list
hexagon_nn_append_node_list
hexagon_nn_set_graph_mode

Do you have plan to open the modified nnlib?

Thanks,

**Comment by llhe** [comment]
Yes, there are small modifications over nnlib. We're going through the internal process to try to make this open.

**Comment by llhe** [comment]
@chanchanzhang The modified version is available here: https://github.com/XiaoMi/nnlib
