### ISSUE TITLE
Exception: Mace does not support caffe op type Normalize yet

### ISSUE THREAD

**Issue by Pinnh** [XiaoMi/mace#350]
Any proposal for Caffe Normalize Layer ?

**Comment by liyinhgqw** [comment]
What model do you use, is it SSD? Is it possible to use BatchNormalize instead?

**Comment by Pinnh** [comment]
It's trained by other people， Normalize layer  is just a suggestion, if mace will not support Normalize layer in the future you can close this issue.

**Comment by liyinhgqw** [comment]
Not sure about it. I close it for now.
Feel free to open a feature request if you don't find a workaround.
