### ISSUE TITLE
crash when aspect_ratio not set , no default value?

### ISSUE THREAD

**Issue by Pinnh** [XiaoMi/mace#351]
### System information
- **OS Platform and Distribution  Linux Ubuntu 16.04 
- **NDK version 16b 
- **GCC version 5.4.0 
- **MACE version master
- **Python version 2.7 
- **Bazel version 0.13.1

### Describe the problem
crash when aspect_ratio not set, piror_box.cc : aspect_ratio is required!
Is there no default value of aspect_ratio(=1.0)?

prototxt (add **aspect_ratio: 1.0** in prior_box_param works fine): 
layer {
  name: "conv17_2_mbox_priorbox"
  type: "PriorBox"
  bottom: "conv17_2"
  bottom: "data"
  top: "conv17_2_mbox_priorbox"
  prior_box_param {
    min_size: 214.0
    max_size: 300.0
    flip: true
    clip: false
    variance: 0.1
    variance: 0.1
    variance: 0.2
    variance: 0.2
    offset: 0.5
  }
}

**Comment by lydoc** [comment]
No, we have referred to https://github.com/weiliu89/caffe/blob/4817bf8b4200b35ada8ed0dc378dceaf38c539e4/src/caffe/proto/caffe.proto#L1400

**Comment by Pinnh** [comment]
OK, I know , 
but as describle

**// Various of aspect ratios. Duplicate ratios will be ignored.
// If none is provided, we use default ratio 1.
repeated float aspect_ratio = 3;**

they use default ratio 1.0 , if none is provided , but not get a crash

**Comment by lydoc** [comment]
Yes, you are right, I made a mistake and will fix this soon.

**Comment by lydoc** [comment]
We have fixed this bug, you can use the latest master branch.

**Comment by Pinnh** [comment]
get it.
