### ISSUE TITLE
Fully connected layer GPU mode shape is mismatch

### ISSUE THREAD

**Issue by spacegrass** [XiaoMi/mace#353]
The error tips is like this:
**F mace/ops/fully_connected.cc:230] Check failed: input->dim(1) == weight->dim(2) && input->dim(2) == weight->dim(3) && input->dim(3) == weight->dim(1) The shape of Input: [1, 640, 1, 1]The shape of Weight: [5, 640, 1, 1] don't match.**

the last layer of the caffe net is inner-product and output is 5. the bottom layer of inner-product layer is 1x640.

I find there is diffence of CPU and GPU. Does GPU sort the weight data ?

**Comment by nolanliou** [comment]
which version of MACE did you use?

**Comment by spacegrass** [comment]
mace release 1.0。i have checked 0.9 1.0 master are also the same code.

**Comment by nolanliou** [comment]
The bottom layer of inner-product is `Reshape`?

**Comment by spacegrass** [comment]
The bottom layer of inner-product is Flatten. Flatten layer's bottom layer shape is [1, 640, 1, 1] (nchw).

**Comment by lydoc** [comment]
Is it convenient to provide your model and yml files?
