### ISSUE TITLE
Cannot quantize model

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#358]
I'm running MACE within the provided docker image.

When trying to quantize a model, I get stuck in converting the model to the final target with the following error:

`Add quantize tensor range`
`Add default quantize info for ops like Pooling, Softmax`
`Add default quantize info for input`
`Input range data: [-1.0, 1.0]`
`Add mace quantize and dequantize nodes`
`Traceback (most recent call last):`
`  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 355, in <module>`
`    main(unused_args=[sys.argv[0]] + unparsed)`
`  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 196, in main`
`    output_graph_def, quantize_activation_info = mace_transformer.run()`
`  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 125, in run`
`    changed = transformer()`
`  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1427, in quantize_nodes`
`    % (op.name, op.type))`
`  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check`
`    raise Exception(msg)`
**`Exception: Quantization only support float ops, but get Sub(Eltwise)`**
`Traceback (most recent call last):`
`  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)`
`  File "tools/converter.py", line 761, in convert_func`
`    convert_model(configs, flags.cl_mem_type)`
`  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))`
`  File "/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)`
`  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc`
`sh.ErrorReturnCode_1: `
``
`  RAN: /root/.pyenv/versions/2.7.14/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/spaghnet/frozen_model.pb --weight_file= --model_checksum=6a593674c46bb95df02c6733b06b23fd26777f1f5557bc1244902b69a46355a6 --weight_checksum= --input_node=data --input_data_formats=NHWC --output_node=fc1/add_1:0 --output_data_formats=NHWC --check_node= --runtime=gpu --template=mace/python/tools --model_tag=spaghnet --input_shape=1,112,112,3 --input_range= --output_shape=1,512 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=1 --quantize_range_file=/mace/overall_range --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/spaghnet --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image`
``
`  STDOUT:`
``
``
`  STDERR:`

It seems like it requires float ops, but my ops are all float.

**Comment by liyinhgqw** [comment]
Hi bin,

Is it possible to refactor 'quantized add' code to support 'sub'?

**Comment by lee-bin** [comment]
Is it convenient for you to share your model with us so that I can test it?

**Comment by gasgallo** [comment]
@lee-bin 

I temporary solved the problem by replacing the sub with a combination of add and multiply
