### ISSUE TITLE
GPU benchmark gflops gap

### ISSUE THREAD

**Issue by spacegrass** [XiaoMi/mace#361]
I find there is a big gap between GPU gflops and net gflops.
mobilenetv2 
![image](https://user-images.githubusercontent.com/3315048/53007349-06696f80-3472-11e9-9bbe-bcc83a136de5.png)
![image](https://user-images.githubusercontent.com/3315048/53007384-1aad6c80-3472-11e9-829f-1f3eccbc5328.png)

I think the gap is too big. How could I evaluate MACE gpu version on a device before running ?

**Comment by nolanliou** [comment]
There is always a gap between ideal and reality. Memory, Algorithm, Scheduling......
