### ISSUE TITLE
tensorflow_converter.py - Min, Max

### ISSUE THREAD

**Issue by w-adamski** [XiaoMi/mace#362]
### System information
- **OS Platform and Distribution**: Linux Mint 19
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-82-g19bf36b7
- **Python version**: 2.7.15rc1
- **Tensorflow version**: 1.12.0-rc0

### Problem description
Currently in tensorflow_converter.py 'Min' is treated exactly the same way as 'Minimum' and 'Max' as 'Maximum'. However in a current tensorflow 'Min' and 'Max' should be used for tf.math.reduce_min() and tf.math.reduce_max() instead of tf.math.minimum() and tf.math.maximum(). Was that code ever correct and tensorflow version should be taken into account when adding reduce_min() and reduce_max() to the converter, or it was always incorrect and 'Min' and 'Max' can be unconditionally remapped to appropriate functions?

**Comment by TonyMou** [comment]
@w-adamski Could you provide the links of 'Min' and 'Max''s documentation in Tensorflow.

**Comment by herbakamil** [comment]
What is important is not documented in https://www.tensorflow.org/api_docs/python/tf/math/reduce_min or https://www.tensorflow.org/api_docs/python/tf/math/reduce_max but can be easily checked via this piece of code which can be run in some Python interpreter:
```
import tensorflow as tf
c = tf.constant([1, 2])
op = tf.math.reduce_min(c)
op.op.node_def
```
result is 
```
name: "Min"
op: "Min"
input: "Const_2"
input: "Const_3"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tidx"
  value {
    type: DT_INT32
  }
}
attr {
  key: "keep_dims"
  value {
    b: false
  }
}min(c).op.node_def
```
Which shows that 'Min' is the name of the reduce_min operation.
Of course if we replace last two lines of code with `tf.minimum(c, c).op.node_def` result is significantly different

**Comment by TonyMou** [comment]
@herbakamil Thanks for pointing out this. We will update this part soon.

**Comment by TonyMou** [comment]
Already resolved.
