### ISSUE TITLE
高通gpu与cpu数据共享优化问题。

### ISSUE THREAD

**Issue by leeburt** [XiaoMi/mace#367]
想统计gpu和cpu之间进行数据拷贝用了多少时间，通过哪些log可以反映出来？如果cpu和gpu之间拷贝耗时多，想进行优化。

**Comment by lydoc** [comment]
可以使用benchmark看一下？https://mace.readthedocs.io/en/latest/user_guide/benchmark.html#model-benchmark

**Comment by summerspringwei** [comment]
MACE的日志是看不出来的，可以参考这篇回答
https://stackoverflow.com/questions/23178947/memory-transfer-between-host-and-device-in-opencl
