### ISSUE TITLE
执行android目录下的build脚本出错

### ISSUE THREAD

**Issue by 1860Sonic** [XiaoMi/mace#369]
System information
- MacOS 10.14
- NDK 19.1:
- cmake 3.6.0-rc2:
- Python version 2.7: 
- Bazel version 0.22.0:

当我完成安装步骤的Required dependencies之后 在exampls/android目录下执行 ./build.sh dynamic

出现以下错误

/WorkSpace/mace-master /WorkSpace/mace-master/mace/examples/android
------------------------------------
        Common Configuration        
------------------------------------
|        key        |    value     |
====================================
|       library_name|     mobilenet|
------------------------------------
|        target_abis| ['arm64-v8a']|
------------------------------------
|        target_socs|            []|
------------------------------------
| model_graph_format|          code|
------------------------------------
|  model_data_format|          code|
------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

****************************************************
          Convert mobilenet_v2_quant model          
****************************************************

INFO: Invocation ID: 875d5820-17c6-47c4-9fb3-d2345fc75392
ERROR: /WorkSpace/mace-master/mace/python/tools/BUILD:41:1: no such package '@six_archive//': The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule. and referenced by '//mace/python/tools:converter'
ERROR: Analysis of target '//mace/python/tools:converter' failed; build aborted: no such package '@six_archive//': The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 0.075s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)
    currently loading: @bazel_tools//tools/zip

Traceback (most recent call last):
  File "tools/converter.py", line 1300, in <module>
    flags.func(flags)
  File "tools/converter.py", line 774, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 704, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/WorkSpace/mace-master/tools/sh_commands.py", line 495, in gen_model_code
    bazel_build_common("//mace/python/tools:converter")
  File "/WorkSpace/mace-master/tools/sh_commands.py", line 324, in bazel_build_common
    _err_to_out=True)
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/xxx/bin/bazel build //mace/python/tools:converter

  STDOUT:

  STDERR:

**Comment by lee-bin** [comment]
Duplicated with https://github.com/XiaoMi/mace/issues/347
