### ISSUE TITLE
Suggestion: keep downloaded models to avoid repeated downloading

### ISSUE THREAD

**Issue by samsun639** [XiaoMi/mace#37]
If the model_file_path of yml file is a URL. Every time I run python tools/converter.py build ***.yml , it will download the model again, even though the  model has already downloaded before. 

It is a waste of time downloading again and again. Some models are large and costs time.

So, my suggestion is that keep the downloaded models in a separate directory, not temp file.
Then converter.py  can firstly check if the model already downloaded in the separate directory. If already there and the checksum is right, then skip the downloading process. 

Thanks!

**Comment by TonyMou** [comment]
@samsun639  You can replace the url with your local path to the model file.

**Comment by liyinhgqw** [comment]
Make a very good point, samsun.
It saves us from repeatedly downloading and converting models.
We're working on it now.

**Comment by lee-bin** [comment]
Merged in 803f2621697a5f46583f9641eab73731bd7e767e
