### ISSUE TITLE
Cannot convert model using converter.py

### ISSUE THREAD

**Issue by zhongyu2013** [XiaoMi/mace#370]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-0-g22e40d6
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Model deploy file (*.yml) 
```yaml
mobilenet-v2.yml
```

### Describe the problem
I tried to convert mobilenet-v2 on mace-models using converter.py but the following error message pops up:

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/mace-models/mobilenet-v2/mobilenet-v2.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 757, in convert_func
    configs = format_model_config(flags)
  File "tools/converter.py", line 245, in format_model_config
    available_socs = sh_commands.adb_get_all_socs()
  File "/Documents/mace/tools/sh_commands.py", line 172, in adb_get_all_socs
    socs.append(props["ro.board.platform"])
KeyError: 'ro.board.platform'

```

### Additional context
Thank you for your time and efforts.

**Comment by liyinhgqw** [comment]
Could you run "adb shell getprop" after connecting to your device, and send the log to us?

**Comment by zhongyu2013** [comment]
Never mind, I just set the platform manually and the problem is solved. Thank you for your assistance.

**Comment by Bargsteen** [comment]
I just had the exact same problem. 
I tried running `adb shell getprop` and it gave the following error: `error: more than one device/emulator`, which was accurate, as I had an emulator and a phone connected. After closing the emulator, I could run the adb command and the python error disappeared.

**Solution: make sure you only have _one_ device/emulator running**
