### ISSUE TITLE
android目录下执行build.sh失败

### ISSUE THREAD

**Issue by 1860Sonic** [XiaoMi/mace#372]
System information

* MacOS 10.14
* NDK r16b:
* cmake 3.6.0-rc2:
* Python version 2.7:
* Bazel version 0.22.0:

exampls/android目录下执行 ./build.sh static

clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

> Task :macelibrary:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':macelibrary:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Programing/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /WorkSpace/mace-master/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a --target mace_mobile_jni}
  [1/2] Building CXX object CMakeFiles/mace_mobile_jni.dir/src/main/cpp/image_classify.cc.o
  [2/2] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libmace_mobile_jni.so
  FAILED: : && /Programing/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=aarch64-none-linux-android21 --gcc-toolchain=/Programing/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Programing/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -std=c++11 -fopenmp -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libmace_mobile_jni.so -o ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libmace_mobile_jni.so CMakeFiles/mace_mobile_jni.dir/src/main/cpp/image_classify.cc.o  ../../../../src/main/cpp/model/arm64-v8a/mobilenet.a ../../../../src/main/cpp/lib/arm64-v8a/libmace.a -llog -latomic -lm && :
  CMakeFiles/mace_mobile_jni.dir/src/main/cpp/image_classify.cc.o: In function `mace::CreateMaceEngineFromCode(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, mace::MaceEngineConfig const&, std::__ndk1::shared_ptr<mace::MaceEngine>*)':
  /WorkSpace/mace-master/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:120: undefined reference to `mace::MaceEngine::Init(mace::NetDef const*, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, unsigned char const*)'

**Comment by lee-bin** [comment]
请确保你的安装版本跟https://mace.readthedocs.io/en/latest/installation/env_requirement.html一致。
MACE测试过的NDK版本包括15c/16/17b

**Comment by 1860Sonic** [comment]
> 请确保你的安装版本跟[https://mace.readthedocs.io/en/latest/installation/env_requirement.html一致。](https://mace.readthedocs.io/en/latest/installation/env_requirement.html%E4%B8%80%E8%87%B4%E3%80%82)
> MACE测试过的NDK版本包括15c/16/17b

ndk是r16b的

**Comment by lee-bin** [comment]
你可以按照MACE文档https://mace.readthedocs.io/en/latest/installation/using_docker.html尝试一下docker配置好的环境

**Comment by 1860Sonic** [comment]
解决了  原因：环境变量里的ndk配置的是16r 项目里的ndk配置的是19的
统一配置为16r 编译成功
