### ISSUE TITLE
MACE同时加载多个模型

### ISSUE THREAD

**Issue by ppl21847** [XiaoMi/mace#373]
我已经把两个模型放在一个yml配置文件中，已经生成一个mace_engine_factory.h，现在问题是单独跑每个模型没有问题，两个模型同时跑的时候，只能跑后初始化的模型，麻烦问一下 怎样同时加载两个模型 两个模型同时跑。

**Comment by liyinhgqw** [comment]
两个模型的名字是不是重复了？

**Comment by ppl21847** [comment]
> 两个模型的名字是不是重复了？

没有重复，我C语言不是很熟，CreateMaceEngineFromCode这个只能放cpp文件里 放到mace_engine_factory.h里就报multiple definition of `mace::CreateMaceEngineFromCode 错误。

**Comment by ppl21847** [comment]
我现在先调用CreateMaceEngineFromCode创建第一个模型，执行完第一个模型后再调用CreateMaceEngineFromCode创建第二个模型，再执行第二个模型，但是这样很耗时尤其是在GPU情况下，然后我直接CreateMaceEngineFromCode两个模型 按顺序跑模型的时候，只有后create的模型能跑，请问不能直接初始化两个模型吗？

**Comment by ppl21847** [comment]
可以同时初始化两个模型，因为我只有一个engine 所以导致上问题，更改这个问题后就只需初始化1次模型了。

**Comment by vealocia** [comment]
请问一下你在改动CreateEngineFromCode之后，运行模型的时候有没有出现过这样的bug：
Check failed: mapped_buf_ == nullptr buf has been already mapped。
还有就是是否可以分享一下你是如何改动这个函数以及在之后运行模型的。因为我在对函数进行改动之后，engine的运行总是会有BUG！谢谢！

**Comment by vealocia** [comment]
> 可以同时初始化两个模型，因为我只有一个engine 所以导致上问题，更改这个问题后就只需初始化1次模型了。
请问一下你在改动CreateEngineFromCode之后，运行模型的时候有没有出现过这样的bug：
Check failed: mapped_buf_ == nullptr buf has been already mapped。
还有就是是否可以分享一下你是如何改动这个函数以及在之后运行模型的。因为我在对函数进行改动之后，engine的运行总是会有BUG！谢谢！

**Comment by vealocia** [comment]
> 可以同时初始化两个模型，因为我只有一个engine 所以导致上问题，更改这个问题后就只需初始化1次模型了。

请问一下你在改动CreateEngineFromCode之后，运行模型的时候有没有出现过这样的bug：
Check failed: mapped_buf_ == nullptr buf has been already mapped。
还有就是是否可以分享一下你是如何改动这个函数以及在之后运行模型的。因为我在对函数进行改动之后，engine的运行总是会有BUG！谢谢！
