### ISSUE TITLE
converter.py fails first run if target is 'host'

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#374]
I'm using the provided docker image.

### Model deploy file (*.yml)
```yaml
library_name: test
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  test:
    model_file_path: /model/frozen_model.pb
    model_sha256_checksum: 77d382efd2a88f9ee5b23fcd71a4888d37daf914205adc0176c25d3245c7f26e
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,112,112,3
        output_tensors:
          - fc/add
        output_shapes:
          - 1,1,1,512
    obfuscate: 0
    runtime: cpu
    winograd: 0
```

### Describe the problem
If I set the target to 'host', everytime I run the model for the first time, I get an error (it seems like it's trying to access an adb device). If I run the model again, eveything works fine.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
3. python tools/converter.py run --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 935, in run_mace
    device_list = DeviceManager.list_devices(flags.device_yml)
  File "/mace/tools/device.py", line 998, in list_devices
    devices_list.extend(cls.list_adb_device())
  File "/mace/tools/device.py", line 967, in list_adb_device
    prop = sh_commands.adb_getprop_by_serialno(adb[0])
  File "/mace/tools/sh_commands.py", line 145, in adb_getprop_by_serialno
    outputs = sh.adb("-s", serialno, "shell", "getprop")
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_255: 

  RAN: /usr/bin/adb -s * daemon started successfully * shell getprop

  STDOUT:


  STDERR:
error: device not found
```

**Comment by nolanliou** [comment]
Which version of MACE did you use?

**Comment by gasgallo** [comment]
v0.10.0

**Comment by yejw5** [comment]
It seems broken in `adb` tool. Could you try to reinstall it?

**Comment by gasgallo** [comment]
I'm using the docker image that you provide and even after removing adb and reinstalling it, the problem is still there.

**Comment by yejw5** [comment]
Did you plugin one or more device(s) when run the `host` testing? I haven't reproduce the problem.

**Comment by gasgallo** [comment]
It happens both if I have some device plugged in or if nothing is plugged

**Comment by lu229** [comment]
@gasgallo this is the environment's problem, you can debug it in shell command. what is the output when you run "adb devices" in the shell?

**Comment by gasgallo** [comment]
adb seems fine.. Here's the results:
```
root@xxx:/mace# adb devices
adb server is out of date.  killing...
* daemon started successfully *
List of devices attached 

root@xxx:/mace# adb devices
List of devices attached 
23142d02	device
```
The first one is without devices connected.
The second one is with one device connected.

**Comment by lu229** [comment]
@gasgallo It seems that your environmant is unstable, the error is that:
when the MACE use python-sh to list the adb device, the adb server is out of date, so MACE get the this output:
**adb server is out of date.  killing...
* daemon started successfully *
List of devices attached**
in this scenario, MACE parse the string error and get the serialno '*', which is first characer of the second line.

When you run the MACE at the second time, the adb is well,which is the same as you run "adb devices" at the second time, and MACE work well.

**Comment by gasgallo** [comment]
Is it possible that a mismatch of ADB versions between the docker container and my local machine is causing this?

I'm working with the docker image provided in this repo, I didn't mess with ADB within the container using MACE image. I'll try with a a brand new container and see if it still happens.

**Comment by lu229** [comment]
@gasgallo If you use normal docker image, you will get this problem, for your local machine and the docker will compete for the adb connection, when the local machine connected, the connection on docker will lost. using MACE image will resolve this problem.
