### ISSUE TITLE
请问现在支持变长输入吗？

### ISSUE THREAD

**Issue by ppl21847** [XiaoMi/mace#377]
我们现在的模型是全卷积模型，输入不定长，但是demo给的在执行engine->Run 前会校验输入长度与模型长度是否相同，这就导致输入必须是模型的大小，请问支持不定长的输入吗？

**Comment by nolanliou** [comment]
转图的时候请指定最大的输入尺寸。目前是可以支持比这个尺寸小的输入的

**Comment by ppl21847** [comment]
> 转图的时候请指定最大的输入尺寸。目前是可以支持比这个尺寸小的输入的

您说的转图的时候指定最大的输入尺寸 是指模型输入时指定最大尺寸，后面
执行engine->Run前 只要输入图像超过最大尺寸 并且不再校验输入图像长度与模型长度是否相同？然后直接就可以运行engine->Run吗？

**Comment by yejw5** [comment]
`python tools/converter.py convert --config=...`这个命令是做转图的，将原生模型转成mace格式的pb或者.a，后面engine->Run的时候，输入要比转图时指定的小
