### ISSUE TITLE
Pytorch exported ONNX does not have node names

### ISSUE THREAD

**Issue by cnoco1at3** [XiaoMi/mace#383]
Have noticed the onnx converter expilicitly use node name in ONNX model for several operations, while ONNX model exported by Pytorch does not really have name attribute. I am currently doing a dirty fix by changing onnx_converter.py:232

from
`self.name = str(node.name)`
to
`self.name = str(node.name) if str(node.name) != '' else str(node.output[0])`

any idea or better approach? (I know it's probably pytorch's problem but also want to make sure this fix does not break things)

**Comment by yejw5** [comment]
@TonyMou Can you have a look?
