### ISSUE TITLE
关于使用caffe的reshape层和Permute层

### ISSUE THREAD

**Issue by ppl21847** [XiaoMi/mace#386]
MACE深度学习维度信息是BHWC，caffe是BCHW，我想请问一下原生caffe模型使用reshape层和permute层时 参数该怎么调？

**Comment by lydoc** [comment]
直接按照原来caffe的参数就可以。另外由于MACE在CPU上是按照BCHW的顺序计算，output时会将BCHW的顺序转为BHWC，所以output要避免使用4维输出的reshape和flatten。可能会出现维度错误。

**Comment by ppl21847** [comment]
> 直接按照原来caffe的参数就可以。另外由于MACE在CPU上是按照BCHW的顺序计算，output时会将BCHW的顺序转为BHWC，所以output要避免使用4维输出的reshape和flatten。避免会出现维度错误。

好的 谢谢。
