### ISSUE TITLE
请问mace的量化支持反卷积吗？

### ISSUE THREAD

**Issue by wdwwdwwdw** [XiaoMi/mace#387]
在使用Post training quantization量化模型时遇到两个问题
1 python tools/converter.py run --config tfmnv2_deconv2.yml --example --quantize_stat --input_dir /home/wang/tensors > range_log 该命令无法取得量化的范围信息， 去掉--example参数后反而可以，请问这样是否有问题？
2 convert量化模型通过，但是在run的时候报错operator.cc:274 Key not registered: Deconv2D0T_DT_UINT8。模型前半部分的卷积等op则没有报错。

**Comment by liyinhgqw** [comment]
抱歉，目前还没有支持。可以先用 resize_biliear 进行上采样

**Comment by kakaluote** [comment]
可否给些建议实现量化翻卷积，resize_biliear没有pytorch支持

**Comment by liyinhgqw** [comment]
可以参考现在卷积的实现，如果能划归成矩阵乘，就可以很简单的实现了.

resize_bilinear 的话，看看 https://github.com/pytorch/pytorch/commit/227c8f2654c5aa4dda319d7401d319bb4636be47 ？
