### ISSUE TITLE
Special optimization for conv1x1, conv3x3 ?

### ISSUE THREAD

**Issue by YonghaoHe** [XiaoMi/mace#389]
In the document, I cannot find the information. Is there any special optimization for conv1x1 and conv3x3 in this lib?
Thank you.

**Comment by nolanliou** [comment]
Yes

**Comment by YonghaoHe** [comment]
@nolanliou Thanks. Would you please give some more information ？Such as which operations are 
 specially optimized .

**Comment by summerspringwei** [comment]
for the r0.9, In directory 'kernels', their are two sub-directory named "arm" and "opencl". Kernels in directory "arm" are specially optimized for CPU with neon, while some kernels in directory "opencl" are specially optimized for GPU we can find that the conv2d1*1, cond2d1*7and some other operations like depthwise_conv2d are optimized.

**Comment by YonghaoHe** [comment]
@summerspringwei Thanks.
