### ISSUE TITLE
Does it support mobilenet ssd?

### ISSUE THREAD

**Issue by WeiboXu** [XiaoMi/mace#39]
From the benchmark result, it has the data about mobilenet_v2, Does it support mobilenet ssd? If not, is there any plan?

**Comment by llhe** [comment]
Not yet, it's in the future plan.

**Comment by chanchanzhang** [comment]
tflite already support mobilenet ssd, check this link https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

**Comment by xinqinglxl** [comment]
Meet the same problem, I am wondering if there is any progress about the support of mobilenet-ssd.
I tried with the mace/dev docker image and got the following error while converting caffe model to mace model.
Does it means mace have not support mobilenet-ssd yet, or do I got anything wrong about my model file?

> google.protobuf.text_format.ParseError: 1936:3 : Message type "caffe.LayerParameter" has no field named "permute_param".
> Traceback (most recent call last):
>   File "tools/converter.py", line 1595, in <module>
>     flags.func(flags)

**Comment by lydoc** [comment]
@xinqinglxl Mace has not supported mobilenet-ssd at this moment, we are working out soon.

**Comment by xinqinglxl** [comment]
@lydoc thanks for the reply, waiting for your good news.

**Comment by eviansplash** [comment]
BUMP - any updates? I believe ssd-mobilenet is very crucial. For now only the Tensorflow library allows this.

**Comment by lydoc** [comment]
@eviansplash Yes, we are doing the final work and will push it right away.

**Comment by Georg-W** [comment]
I would be interested in the SSD Mobilenet integration as well, will there be quantized support as well when you publish it?
谢谢你.

**Comment by chanchanzhang** [comment]
@lydoc 
Is it pushed yet?

**Comment by lydoc** [comment]
@chanchanzhang It will be pushed in the next few days.

**Comment by liyinhgqw** [comment]
@lydoc Have you pushed ssd model to model zoo?

**Comment by lydoc** [comment]
ssd mobilenet model has been pushed to model zoo now( https://github.com/XiaoMi/mace-models/tree/master/ssd-mobilenet-v1 )
