### ISSUE TITLE
能否调整最大频率，绑定大核

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#390]
hi,

请问安卓系统下，

1. mace是否支持调整最大频率？
2. mace是否支持绑定CPU大核？

这个是否需要root才能绑定大核，并调整频率？

感谢~

**Comment by liyinhgqw** [comment]
dup：
https://github.com/XiaoMi/mace/issues/395

**Comment by ysh329** [comment]
@liyinhgqw Thanks
