### ISSUE TITLE
请问一下mace/python/接口怎么用？

### ISSUE THREAD

**Issue by guispor7** [XiaoMi/mace#391]
1.mace.proto 是要编译一下才能有mace_pb2吧 ,不然from mace.proto import mace_pb2 报错。要怎么编译呢？
2.路径找不到
/mace# python mace/python/tools/converter.py
Traceback (most recent call last):
  File "mace/python/tools/converter.py", line 24, in <module>
    from mace.python.tools import model_saver
ImportError: No module named mace.python.tools
PYTHONPATH设置的是 /path/to/mace
谢谢关注

**Comment by nolanliou** [comment]
请使用tools/converter.py
