### ISSUE TITLE
Caffe 模型转MACEhou ,CPU可以使用，GPU初始化失败

### ISSUE THREAD

**Issue by ppl21847** [XiaoMi/mace#393]
大佬们，MACE GPU有不支持Caffe的层吗？为啥我的CPU可以跑，GPU初始化都不成功呢？

**Comment by nolanliou** [comment]
什么错误

**Comment by ppl21847** [comment]
> 什么错误

CreateMaceEngineFromCode 返回的 mace::MaceStatus create_engine_status.code() = 2，
显示MACE_OUT_OF_RESOURCES 是手机内存不够吗？

**Comment by liyinhgqw** [comment]
是不是有 N×C 或 W×C/4 超过 16384？

**Comment by ppl21847** [comment]
> 是不是有 N×C 或 W×C/4 超过 16384？

对，N*C 最大的是552675

**Comment by ppl21847** [comment]
> 是不是有 N×C 或 W×C/4 超过 16384？
下一版能把这个值调大吗？

**Comment by yejw5** [comment]
这是GPU硬件本身的限制
