### ISSUE TITLE
输入不定长数据后 输出错误。

### ISSUE THREAD

**Issue by ppl21847** [XiaoMi/mace#394]
现在我用的是输入不定长的模型，当长度变化时，后面就会出错，而且出现一次错误后，往后的会全部输出错误，有没有大佬遇到这个问题呀。

**Comment by nolanliou** [comment]
超出转图时设定的输入大小了吗？

**Comment by ppl21847** [comment]
> 超出转图时设定的输入大小了吗？

没有。

**Comment by ppl21847** [comment]
> 超出转图时设定的输入大小了吗？

当测试长度等于最大长度 和远小于最大长度的时候会出现这个问题。

**Comment by nolanliou** [comment]
什么错误呢

**Comment by ppl21847** [comment]
> 什么错误呢

我把模型和结构还有测试数据发你吧，怎么联系？

**Comment by liyinhgqw** [comment]
什么设备 cpu ？ gpu ？
