### ISSUE TITLE
Crop层的参数需要变化

### ISSUE THREAD

**Issue by ppl21847** [XiaoMi/mace#399]
MACE的输入维度信息是NHWC，原来caffe的顺序是NCHW，现在用到Crop层里参数有axis和offset ，转MACE模型的时候 这两个参数需要变化吗？

**Comment by nolanliou** [comment]
已经找到问题，我们会尽快解决，谢谢

**Comment by TonyMou** [comment]
@ppl21847 你的问题解决了吗？
