### ISSUE TITLE
link libc++ instead of gnustl with NDK 16b?

### ISSUE THREAD

**Issue by tensorbuffer** [XiaoMi/mace#403]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 host, arm64 bit & 32bit targets (can treat as two targets)
- **NDK version(e.g., 15c)**: 16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**: 0.10.0
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
Hello, 
In this link
https://mace.readthedocs.io/en/latest/installation/env_requirement.html
It says: "It will link libc++ instead of gnustl if NDK version >= r17b and bazel version >= 0.13.0"
We are using Bazel 0.13.0, NDK 16b so mace goes to gnustl. However our existing project is built with libc++ (not gnustl). We want to know how to build the libmace.so so that it can link with our project.
Currently there are lots of link error:
/opt/android_ndk_r16b/lib/arm64-v8a/cpu_gpu/libmace.so: undefined reference to `std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)'
[docker] /opt/amazon/android_ndk_r16b/lib/arm64-v8a/cpu_gpu/libmace.so: undefined reference to `std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long)'
/opt/android_ndk_r16b/lib/arm64-v8a/cpu_gpu/libmace.so: undefined reference to `std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by nolanliou** [comment]
You could change the line https://github.com/XiaoMi/mace/blob/master/mace/BUILD#L12
From 
```
 "crosstool_top": "//external:android/crosstool",
```
To
```
"crosstool_top": "@androidndk//:toolchain-libcpp",
```
(Not tested), better to use NDK 17b

**Comment by tensorbuffer** [comment]
Yes I did the change, however I then got compile failure ("cannot found -lpthread"). I removed all "pthread" from the build files in mace and and still the same error.
For the NDK17b, I was told that our platform does not support it.

**Comment by tensorbuffer** [comment]
It seems this is quite complicated since there's no answer.
For now I will continue with ndk 17, we may run to issues later but no other work around.
