### ISSUE TITLE
设置 gpu hint perf不生效？mali gpu

### ISSUE THREAD

**Issue by 92ypli** [XiaoMi/mace#404]
平台：mali-g31
安卓系统

用GPU跑，f16_f32和f32_f32时间一样，并没有加速。而且设置gpu hint perf为3，并没有用处，也不能加速，是什么情况？

**Comment by 92ypli** [comment]
还有，maligpu能f16运行吗？

**Comment by llhe** [comment]
Mali GPU不支持perf hint，支持fp16。

**Comment by 92ypli** [comment]
那怎么设置fp16来用gpu跑模型？

**Comment by liyinhgqw** [comment]
默认就是用 fp16, 可以参照 https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html 设置

**Comment by 92ypli** [comment]
那为什么我在yml里设置fp16_fp32和fp32_fp32时间一样？

**Comment by lu229** [comment]
@92ypli 对GPU来说，fp16_fp32和fp32_fp32在大部分时候都是以float32执行，所以时间上差不多，fp16_fp32可以减少模型体积。

**Comment by lu229** [comment]
#504 No, default storage is f16 bug computation is f32
