### ISSUE TITLE
model convert failed

### ISSUE THREAD

**Issue by bryanlinnan** [XiaoMi/mace#406]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **NDK version(e.g., 15c)**: r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4
- **MACE version (Use the command: git describe --long --tags)**:v0.10.0-0-g22e40d6-20190321
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.13

### Model deploy file (*.yml)
library_name: mobilenet-v1
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

### Describe the problem
try to convert model zoo model into mace model file, failed every time

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
--------------------------------------
         Common Configuration         
--------------------------------------
|        key        |     value      |
======================================
|       library_name|    mobilenet_v1|
--------------------------------------
|        target_abis| ['armeabi-v7a']|
--------------------------------------
|        target_socs|              []|
--------------------------------------
| model_graph_format|            file|
--------------------------------------
|  model_data_format|            file|
--------------------------------------

**********************************************
          Convert mobilenet_v1 model          
**********************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.162s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Traceback (most recent call last):
  File "/home/bryan/Bryan/Tool/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 23, in <module>
    from mace.proto import mace_pb2
  File "/home/bryan/Bryan/Tool/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/proto/mace_pb2.py", line 23, in <module>
    \x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x64ims\x18\x03 \x03(\x05\x12\x15\n\rmax_byte_size\x18\x04 \x01(\x05\x12+\n\tdata_type\x18\x05 \x01(\x0e\x32\x0e.mace.DataType:\x08\x44T_FLOAT\x12\x16\n\x0b\x64\x61ta_format\x18\x06 \x01(\x05:\x01\x31\"\x95\x01\n\nOutputInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x64ims\x18\x03 \x03(\x05\x12\x15\n\rmax_byte_size\x18\x04 \x01(\x05\x12+\n\tdata_type\x18\x05 \x01(\x0e\x32\x0e.mace.DataType:\x08\x44T_FLOAT\x12\x16\n\x0b\x64\x61ta_format\x18\x06 \x01(\x05:\x01\x31\"\xb4\x01\n\x06NetDef\x12\x1d\n\x02op\x18\x01 \x03(\x0b\x32\x11.mace.OperatorDef\x12\x1b\n\x03\x61rg\x18\x02 \x03(\x0b\x32\x0e.mace.Argument\x12\"\n\x07tensors\x18\x03 \x03(\x0b\x32\x11.mace.ConstTensor\x12#\n\ninput_info\x18\x64 \x03(\x0b\x32\x0f.mace.InputInfo\x12%\n\x0boutput_info\x18\x65 \x03(\x0b\x32\x10.mace.OutputInfo*Q\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0c\n\x08\x44T_FLOAT\x10\x01\x12\x0c\n\x08\x44T_UINT8\x10\x02\x12\x0b\n\x07\x44T_HALF\x10\x03\x12\x0c\n\x08\x44T_INT32\x10\x04*;\n\nMemoryType\x12\x0e\n\nCPU_BUFFER\x10\x00\x12\x0e\n\nGPU_BUFFER\x10\x01\x12\r\n\tGPU_IMAGE\x10\x02\x42\x02H\x03')
TypeError: __init__() got an unexpected keyword argument 'syntax'
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/bryan/Bryan/Tool/MACE/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=caffe --model_file=/home/bryan/Bryan/work/MACE/models/mobilenet_v1/mobilenet_deploy.prototxt --weight_file=/home/bryan/Bryan/work/MACE/models/mobilenet_v1/mobilenet.caffemodel --model_checksum=8e6a26b8f2c7cf7a066d571660cfd8a1544a5a25399df33ad499f3d733f16729 --weight_checksum=8d6edcd3dbd1356f2f19dd220c362c2ba8f44233a9b6c12ca6d0351cb0c446b6 --input_node=data --input_data_formats=NHWC --output_node=prob --output_data_formats=NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,224,224,3 --input_range= --output_shape=1,1000 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:

  STDERR:

**Comment by bryanlinnan** [comment]
i  have already build the mace library successfully, so the environment should be ok.

**Comment by lee-bin** [comment]
You write tensorflow in model deployment file whereas error log is caffe's.
Please be consistent.

**Comment by lee-bin** [comment]
The problem is caused by a higher version of protobuf(3.7), which should be 3.6.1.

**Comment by bryanlinnan** [comment]
yes, sovlved by change protobuf version, thanks
