### ISSUE TITLE
NNLIB与SNPE的性能比较

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#407]
你好，请问

1. mace的DSP实现完全基于Hexagon NN嘛
2. 有对SNPE与Hexagon的性能比较嘛

感谢~

**Comment by lee-bin** [comment]
MACE和SNPE的DSP是基于Hexagon NN的。关于性能，请参考https://github.com/XiaoMi/mobile-ai-bench/issues/24

**Comment by ysh329** [comment]
感谢~
