### ISSUE TITLE
which API to call libmace.so?

### ISSUE THREAD

**Issue by tensorbuffer** [XiaoMi/mace#408]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**: 17c
- **GCC version(if compiling for host, e.g., 5.4.0)**: NA
- **MACE version (Use the command: git describe --long --tags)**: 0.10.0
- **Python version(2.7)**:  2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
I have libmace.so but wonder how to use it.
There's mace_run that calls to ReadBinaryFile() etc.
However after I added it to libmace/mace_version_script.lds, I don't see this symbol is exported.
I also tried to add a c api (just like the one in tensorflow) but once I started to use the mace class member functions the API is not callable from outside (the elf shows it's not a function).

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
Only MACE_APIs declared in mace/public/mace.h are supposed to be called outside of MACE, so you can write your own code to read a binary file or just copy the MACE code to your project.

**Comment by tensorbuffer** [comment]
Great, thanks! Will try.
