### ISSUE TITLE
ssd mobilenet 运行报错

### ISSUE THREAD

**Issue by bryanlinnan** [XiaoMi/mace#409]
Before you open an issue, please make sure you have tried the following steps:

### System information
- **OS Platform and Distribution :Ubuntu 16.04
- **NDK version: r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4
- **MACE version : v0.10.0-0-g22e40d6-20190321
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.13

### Model deploy file (*.yml)
mace-models :  ssd-mobilenet-v1_caffe.yml

### Describe the problem
try to use ssd mobilenet v1, but it occurs error when in runtime

### To Reproduce
Steps to reproduce the problem:
config as below:
std::vector<std::string> input_names = {"data"};
std::vector<std::string> output_names = {"mbox_loc"};
const std::vector<std::vector<int64_t>> input_shapes{{1,300,300,3}};
const std::vector<std::vector<int64_t>> output_shapes{{1,7668}};

### Error information / logs
concat.cc:92 Check failed: input->dim(j) == input0->dim(j) Dimensions of inputs should equal except axis.

**Comment by bryanlinnan** [comment]
by the way , i try to use mobilenet v1 caffe version to run, how to modify the input and output config? i tried to use "data" as input with shape of (1,224,224,3), and "prob" as output with shape of (1,1000), it failed with error: output shape mismatch:[1,1000,1,1] != [1,1000]

**Comment by lydoc** [comment]
Do you use your customized prototxt for ssd? It seems that the axis in concat_param causes this problem, is it convenient for you to share your model?
For another question, you can change the prob shape to (1, 1000, 1, 1).

**Comment by lee-bin** [comment]
Feel free to reopen if the issue still exists.
