### ISSUE TITLE
DSP使用限制问题

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#410]
我看了[Frequently asked questions — MACE documentation](https://mace.readthedocs.io/en/latest/faq.html)的关于高通对DSP的使用限制，但是仍然有几个疑问：
> ## Why is MACE not working on DSP?   
> Running models on Hexagon DSP need a few prerequisites for DSP developers:
> - You need to make sure SOCs of your phone is manufactured by Qualcomm and has HVX supported.
> - You need a phone that disables secure boot (once enabled, cannot be reversed, so you probably can only get that type phones from manufacturers)（这个是在哪儿看到的呀）
> - You need to root your phone.（以及这一条）
> - You need to sign your phone by using testsig provided by Qualcomm. (Download Qualcomm Hexagon SDK first, plugin your phone to PC, run scripts/testsig.py)（还有这一条）
> - You need to push third_party/nnlib/v6x/libhexagon_nn_skel.so to /system/vendor/lib/rfsa/adsp/.  
> Then, there you go. You can run Mace on Hexagon DSP.

我跑mobile-ai-bench的SNPE的时候，也没有对手机签名，感谢期待答复~

**Comment by lee-bin** [comment]
SNPE是高通自家的，跟MACE不同

**Comment by ysh329** [comment]
呃呃呃，这些限制是在哪儿看到的呢

**Comment by lee-bin** [comment]
可以参考Hexagon_SDK目录下的docs/Tools_Signing.html

**Comment by ysh329** [comment]
好的，非常感谢！
