### ISSUE TITLE
New code release for xiaomi/nnlib

### ISSUE THREAD

**Issue by edgedlai** [XiaoMi/mace#412]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **NDK version(e.g., 15c)**: r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**:  2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Describe the problem
nnlib has new releases from https://source.codeaurora.org/quic/hexagon_nn/nnlib, but https://github.com/xiaomi/nnlib has not been updated for a while, does Mace have plan to merge the new nnlib and release the code changes?

**Comment by lee-bin** [comment]
Yes, we will try it. You can refer to this. https://github.com/XiaoMi/nnlib/issues/3

**Comment by edgedlai** [comment]
@lee-bin Thanks, so seems like it's already in your plan? Do you have a ETA for the release of updated xiaomi/nnlib?

**Comment by lee-bin** [comment]
Maybe next week, but no promise. :(

**Comment by edgedlai** [comment]
There will be great, looking forward to it :+1:

**Comment by lee-bin** [comment]
@edgedlai Updated to 02_06_00.

**Comment by edgedlai** [comment]
@lee-bin Thanks a lot, verified, works great.
