### ISSUE TITLE
link arm64-v8a code with libmace.so compiled with armeabi-v7a (for dsp)?

### ISSUE THREAD

**Issue by tensorbuffer** [XiaoMi/mace#413]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **NDK version(e.g., 15c)**:17c
- **GCC version(if compiling for host, e.g., 5.4.0)**:NA
- **MACE version (Use the command: git describe --long --tags)**:0.10.0
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.13.0

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem

We want to use DSP so I compiled libmace.so with armeabi-v7a
Now when I try to link our main project code (compiled with arm64-v8a) with libmace.so, the linker will say:
ld: skipping incompatible /opt/workspace/.../build/android_ndk_r17c/lib/armeabi-v7a/cpu_gpu_dsp/libmace.so when searching for -lmace
ld: cannot find -lmace

How to work around this issue, I tried to compile libmace with arm64-v8a but then dsp is not there.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
An arm64-v8a project can't be linked with an armeabi-v7a library. Use the same abi, i.e., armeabi-v7a.

**Comment by tensorbuffer** [comment]
We can't change our main project to armv7, that's out of our control (a very large project).
Is it possible to build armv8 with dsp(hexagon) support?

**Comment by lee-bin** [comment]
It's possible, so before we support that, you can use MACE `tools/converter.py run` to test if your device supports Hexagon DSP.
You can read more info from https://mace.readthedocs.io/en/latest/faq.html#why-is-mace-not-working-on-dsp

**Comment by tensorbuffer** [comment]
Yes, Hexagon DSP was tested with armeabi-v7a, and it works good, but not v8

**Comment by lee-bin** [comment]
Good, we are going to support it soon.

**Comment by lee-bin** [comment]
arm64-v8a has been supported, you can try the latest code.
