### ISSUE TITLE
Activation(ReLU) Ops not supported in DSP runtime?

### ISSUE THREAD

**Issue by edgedlai** [XiaoMi/mace#421]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **NDK version(e.g., 15c)**: 16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-129-gb05a95d-20190329
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.13

### Describe the problem
Cannot convert the quantized model due to "Unsupported op (Activation)". Does that mean that Activation(ReLU) Ops is not supported in DSP runtime? If Yes, then is there any plan to support standalone Activation(ReLU) Ops in DSP runtime?

raceback (most recent call last):
  File "./mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 380, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "./mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 220, in main
    output_graph_def = converter.run()
  File "./mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/hexagon_converter.py", line 129, in run
    self.convert_ops()
  File "./mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/hexagon_converter.py", line 147, in convert_ops
    raise Exception('Unsupported op: ', op)
Exception: ('Unsupported op: ', input: "InceptionResnetV1/Repeat/block35_1/add:0"
output: "InceptionResnetV1/Repeat/block35_1/Relu:0"
name: "InceptionResnetV1/Repeat/block35_1/Relu"
type: "Activation"
arg {
  name: "T"
  i: 2
}
arg {
  name: "framework_type"
  i: 0
}
arg {
  name: "activation"
  s: "RELU"
}
arg {
  name: "has_data_format"
  i: 1
}
output_shape {
  dims: 1
  dims: 11
  dims: 11
  dims: 256
}
quantize_info {
  scale: 0.16830182542987898
  zero_point: 0
  minval: 0.0
  maxval: 42.91696548461914
}
)

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=./quantized_model.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Exception: ('Unsupported op: ', input: "InceptionResnetV1/Repeat/block35_1/add:0"
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by liyinhgqw** [comment]
@lee-bin Could you take a look at it? It seems we could support it by removing standalone RELU and fold range information.

**Comment by lee-bin** [comment]
Could you provide the model file so that we can check it?

**Comment by edgedlai** [comment]
Thanks for the help. I will provide a simple pb file to reproduce this issue in one or two days.

**Comment by edgedlai** [comment]
I have fixed the issue by adjusting the model to remove the ReLU after Add, so that it can be fit for Mace conversion. Thanks for the help.
