### ISSUE TITLE
x86_64 vs arm64 performance

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#423]
Hi, 
I have device Intel Apollo lake with Ubuntu OS.
1. Does tensorflow model will be optimized in the same way for linux x86_64 Ubuntu 16 as for arm64 Android ? 
2. Does SSE SIMD on linux x86_64 will be supported.

Thanks

**Comment by lu229** [comment]
@llhe I think I can't answer these two question very well, please help to look at it.

**Comment by llhe** [comment]
No, MACE is not optimized for x86, so the performance should be poor. You can try TensorFlow with MKL support or OpenVINO.

**Comment by dimitryn** [comment]
Thanks
