### ISSUE TITLE
Exception: Mace does not support tensorflow op type XXX yet

### ISSUE THREAD

**Issue by xiaqing10** [XiaoMi/mace#428]
对于别人训练好的模型或者自己训练的模型,有些层不支持,请问如何修改呢?

**Comment by nolanliou** [comment]
https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html

**Comment by xiaqing10** [comment]
@nolanliou 相当于每个op ,我都得用C++来自己实现OP的功能,然后注册进去.
问题是,有些op的功能还不太好写...

**Comment by TonyMou** [comment]
@xiaqing10 你们的模型需要添加哪些Op?
