### ISSUE TITLE
'http_archive' is not define

### ISSUE THREAD

**Issue by GerrieWell** [XiaoMi/mace#429]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
Not save environment.
2. Have you ever read the document for your usage?
Yes.
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: osx 10.12
- **NDK version(e.g., 15c)**: 11c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 4.2
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-0-g22e40d6
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.24

### Describe the problem
compile error.
```
exciting!  mace git:(22e40d6) ✗  $ bazel build --config android --config optimization mace/libmace:libmace_dynamic --define neon=true --define openmp=true --define opencl=true --define hexagon=true --define quantize=true --cpu=armeabi-v7a

ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:14:1: name 'http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:24:1: name 'new_http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:35:1: name 'new_http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:46:1: name 'new_http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:57:1: name 'new_http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:68:1: name 'new_http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:80:1: name 'http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:89:1: name 'http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:98:1: name 'new_http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:115:1: name 'http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:144:1: name 'new_http_archive' is not defined
ERROR: /Users/gerrie/source/offical/mace/WORKSPACE:155:1: name 'new_http_archive' is not defined
```

### To Reproduce
Steps to reproduce the problem:
```bash
cd /path/to/mace
bash tools/build-standalone-lib.sh
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context

**Comment by lu229** [comment]
Please use bazel 0.13.1

**Comment by GerrieWell** [comment]
thx
