### ISSUE TITLE
请问编译bash tools/build-standalone-lib.sh出现错误

### ISSUE THREAD

**Issue by yangyangv8** [XiaoMi/mace#430]
ERROR: /home/deep_learing/mace-master/WORKSPACE:14:1: name 'http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:24:1: name 'new_http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:35:1: name 'new_http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:46:1: name 'new_http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:57:1: name 'new_http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:68:1: name 'new_http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:80:1: name 'http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:89:1: name 'http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:98:1: name 'new_http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:115:1: name 'http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:144:1: name 'new_http_archive' is not defined
ERROR: /home/deep_learing/mace-master/WORKSPACE:155:1: name 'new_http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: Skipping 'mace/libmace:libmace_dynamic': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.082s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by lu229** [comment]
Bazel的版本高了，请使用0.13.1版本
