### ISSUE TITLE
demo无法编译成功

### ISSUE THREAD

**Issue by weiweizhou** [XiaoMi/mace#433]
自己在ubuntu16.04上配置的环境和使用docker编译demo都出现同样问题.
请问这是要翻墙的原因吗
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.0.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
               > Connect to dl.google.com:443 [dl.google.com/216.58.199.110, dl.google.com/2404:6800:4005:802:0:0:0:200e] failed: Connection timed out (Connection timed out)

**Comment by lu229** [comment]
是网络问题，不过这个一般的网络都是可以访问的，绑定host试试看看？
dl.google.com  172.217.161.174
上面是我这边访问dl.google.com解析出来的IP地址。
