### ISSUE TITLE
hta

### ISSUE THREAD

**Issue by l1a0t1n9** [XiaoMi/mace#435]
where does the hta lib come from?

**Comment by lee-bin** [comment]
It's released internally from Qualcomm, and we are still working on it. Documents will be added after it's ready.

**Comment by l1a0t1n9** [comment]
is this lib compatible with qcom's full range of platforms? or are there multiple versions, like hexagon. v60/v65/v66, etc

**Comment by lee-bin** [comment]
There is only one version for all platforms now.

**Comment by l1a0t1n9** [comment]
thx.
