### ISSUE TITLE
get enum error when converting model to mace

### ISSUE THREAD

**Issue by gzydsmz** [XiaoMi/mace#437]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: android-ndk-r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:gcc version 5.4.0
- **MACE version (Use the command: git describe --long --tags)**:v0.10.0-0-g22e40d6
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Model deploy file (*.yml)
```
https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v2/mobilenet-v2.yml
```
### Describe the problem
```
get a enum.EnumBadKeyError when converting mobilenetv2
```
### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config=/mnt/mace/mace-models/mobilenet-v2/mobilenet-v2.yml
```

### Error information / logs
```
python tools/converter.py convert --config=/mnt/mace/mace-models/mobilenet-v2/mobilenet-v2.yml
Traceback (most recent call last):
  File "tools/converter.py", line 61, in <module>
    type=str)
  File "/usr/local/lib/python2.7/dist-packages/enum.py", line 199, in __init__
    raise EnumBadKeyError(key)
enum.EnumBadKeyError: Enumeration keys must be strings: [('tensorflow', 'tensorflow'), ('caffe', 'caffe'), ('onnx', 'onnx')]
```
### Additional context
enum version is enum-0.4.7

**Comment by lee-bin** [comment]
Duplicated with https://github.com/XiaoMi/mace/issues/38#issuecomment-402455388

**Comment by gzydsmz** [comment]
> Duplicated with [#38 (comment)](https://github.com/XiaoMi/mace/issues/38#issuecomment-402455388)

thanks

**Comment by gzydsmz** [comment]
BTW, where can I find the converted model by "tools/converter.py" ?

**Comment by lu229** [comment]
@gzydsmz https://github.com/XiaoMi/mace-models
