### ISSUE TITLE
hta runtime

### ISSUE THREAD

**Issue by iKess** [XiaoMi/mace#438]
hi, I tried to use hta runtime with mace as mace has mace third party.

but i got undefined reference error but it seem not to be a hta related issue. (fwrite_unlocked function.. seems ndk or sth issue?)

how can i resolve this issue?

If not, is there any way to try hta with mace?

thx in advance..! :)

-----------------------------------------------------------------------------------------
i attached error log to help you to understand!

available_socs:  {'msmnile'}
* Build //mace/tools/validation:mace_run_static with ABI arm64-v8a
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 17. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16]. Bazel will attempt to tr
eat the NDK as if it was r16. This may cause compilation and linkage problems. Please download a supported NDK version.
INFO: Analysed target //mace/tools/validation:mace_run_static (1 packages loaded).
INFO: Found 1 target...
ERROR: /home/ikess/Workspace/Xiaomi/mace/mace/tools/validation/BUILD.bazel:10:1: Linking of rule '//mace/tools/validation:mace_run_static' failed (Exit 1): clang failed: error executing command 
  (cd /home/ikess/.cache/bazel/_bazel_ikess/f7c109aeb76b39cc2569fdc86e3dfee5/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -o bazel-out/arm64-v8a-opt/bin/mace/tools/validation/mace_run_static '-Wl,-rpath,$ORIGIN/../../../_solib_arm64-v8a/_U_S_Sthird_Upart
y_Shta_Chta___Uthird_Uparty_Shta_Sarm64-v8a' -Lbazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/_U_S_Sthird_Uparty_Shta_Chta___Uthird_Uparty_Shta_Sarm64-v8a bazel-out/arm64-v8a-opt/bin/mace/tools/validation/_ob
js/mace_run_static/mace/tools/validation/mace_run.o bazel-out/arm64-v8a-opt/bin/external/com_github_gflags_gflags/libgflags_nothreads.a -Wl,-whole-archive bazel-out/arm64-v8a-opt/bin/mace/libmace/liblibmace
.lo -Wl,-no-whole-archive bazel-out/arm64-v8a-opt/bin/mace/ops/libops.a bazel-out/arm64-v8a-opt/bin/mace/ops/libinternal_ops.a bazel-out/arm64-v8a-opt/bin/mace/ops/libref_kernels.a bazel-out/arm64-v8a-opt/b
in/mace/ops/libarm_neon_kernels.a bazel-out/arm64-v8a-opt/bin/mace/ops/libcommon.a bazel-out/arm64-v8a-opt/bin/mace/core/libcore.a bazel-out/arm64-v8a-opt/bin/mace/codegen/libgenerated_version.a bazel-out/a
rm64-v8a-opt/bin/mace/proto/libmace_cc.a bazel-out/arm64-v8a-opt/bin/external/com_google_protobuf/libprotobuf_lite.a -Wl,-whole-archive bazel-out/arm64-v8a-opt/bin/mace/port/android/libport_android.lo -Wl,-
no-whole-archive -Wl,-whole-archive bazel-out/arm64-v8a-opt/bin/mace/port/linux_base/libport_linux_base.lo -Wl,-no-whole-archive bazel-out/arm64-v8a-opt/bin/mace/port/posix/libport_posix.a bazel-out/arm64-v
8a-opt/bin/mace/port/libport_base.a -Wl,-whole-archive bazel-out/arm64-v8a-opt/bin/mace/utils/libutils.lo -Wl,-no-whole-archive -lhta_controller -lhta_hexagon_runtime -lnpu bazel-out/arm64-v8a-opt/bin/mace/
public/libpublic.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a external/androidndk/ndk/sour
ces/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a '-fuse-ld=gold' -fopenmp -lm -lm -ldl -llog -static-libgcc -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_6
4 -target aarch64-none-linux-android -no-canonical-prefixes -Lexternal/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -pie -ldl -llog -lm -pie -ldl -llog -lm -Wl,--strip-all -Wl,--gc-sections -Wl
,--strip-all -Wl,--gc-sections '--sysroot=external/androidndk/ndk/platforms/android-23/arch-arm64')

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/_U_S_Sthird_Uparty_Shta_Chta___Uthird_Uparty_Shta_Sarm64-v8a/libhta_hexagon_runtime.so: error: undefined reference to 'fwrite_unlocked', version 'LIBC_P'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //mace/tools/validation:mace_run_static failed to build

**Comment by lee-bin** [comment]
We are still working on it to support HTA.
As for this particular issue, you can change `api_level` to 28 in file `WORKSPACE` to fix it.

**Comment by iKess** [comment]
thx for the quick reply!

i changed api_level=28 in WORKSPACE
but i still get same error, though..

seeing the log in build process, i got an warning "api level 28 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 26"

**Comment by iKess** [comment]
it seems kinda bazel version error?

which version of bazel shoud i use?

**Comment by iKess** [comment]
fixed with bazel 0.17.1 thanx to your help

but now it says "libhta_controller.so" not found..
even though i push it to /system/vendor/lib/rfsa/adsp/ 

can i try more or no hta support yet at all in mace?

thx in advance!

**Comment by lee-bin** [comment]
Well, if you want to try more, the directory should be like below.
`libhta_dsp_skel.so` in `/vendor/lib/rfsa/adsp/`
`libhta_controller.so`, `libhta_hexagon_runtime.so`, `libnpu.so` in `/vendor/lib64/` for arm64-v8a

**Comment by iKess** [comment]
thanks, i could see the result with mobilenetv1-quant model but i had to comment output byte size check assertion.

can i fix it so that i get 1byte datatype output?
because it shows not that fast latency and bigger output bytes might indicate possible computation..

thanks!

**Comment by lee-bin** [comment]
Sure, `output_tensor->raw_size()` should be changed to `output_tensor->size()`

**Comment by iKess** [comment]
Thank you for your kindness, it was very helpful :) !
