### ISSUE TITLE
When I run fast_style_transfer_scream model ,I met this error.Please help me.

### ISSUE THREAD

**Issue by lyp0413** [XiaoMi/mace#44]
lyp@lyp:~/mace-master/bazel-bin/mace/tools/validation$ ./mace_run_static --input_file=input/4.jpg
I mace/tools/validation/fast.cc:428] model name: fast_style_transfer_scream
I mace/tools/validation/fast.cc:429] mace version: unknown-20180705
I mace/tools/validation/fast.cc:430] input node: img_placeholder
I mace/tools/validation/fast.cc:431] input shape: 1,480,640,3
I mace/tools/validation/fast.cc:432] output node: add_37
I mace/tools/validation/fast.cc:433] output shape: 1,480,640,3
I mace/tools/validation/fast.cc:434] input_file: input/4.jpg
I mace/tools/validation/fast.cc:435] output_file: 2.txt
I mace/tools/validation/fast.cc:436] model_data_file: /home/lyp/mace-master/build/fast_style_transfer_scream/model/fast_style_transfer_scream.data
I mace/tools/validation/fast.cc:437] model_file: 
I mace/tools/validation/fast.cc:438] device: CPU
I mace/tools/validation/fast.cc:439] round: 1
I mace/tools/validation/fast.cc:440] restart_round: 1
I mace/tools/validation/fast.cc:441] gpu_perf_hint: 3
I mace/tools/validation/fast.cc:442] gpu_priority_hint: 3
I mace/tools/validation/fast.cc:443] omp_num_threads: -1
I mace/tools/validation/fast.cc:444] cpu_affinity_policy: 1
I mace/tools/validation/fast.cc:467] restart round 0
W mace/core/runtime/cpu/cpu_runtime.cc:140] Set OpenMP threads number failed: OpenMP not enabled.
I mace/core/mace.cc:127] Creating MaceEngine, MACE version: unknown-20180705
I mace/core/mace.cc:135] Initializing MaceEngine
I mace/tools/validation/fast.cc:263] Total init latency: 44.215 ms
I mace/tools/validation/fast.cc:311] Warm up run
F ./mace/core/tensor.h:143] Check failed: index < shape_.size() Dim out of range: 3 >= 0

**Comment by TonyMou** [comment]
Input file should be *.npy
`
import os, sys
import numpy as np
import scipy.misc

def get_img(src, img_size=False):
   img = scipy.misc.imread(src, mode='RGB') # misc.imresize(, (256, 256, 3))
   if not (len(img.shape) == 3 and img.shape[2] == 3):
       img = np.dstack((img,img,img))
   if img_size != False:
       img = scipy.misc.imresize(img, img_size)
   return img

in_path = sys.argv[1]
out_path = sys.argv[2]
img = get_img(in_path, (480, 640, 3))
img = (img - 128.0) / 128.0
img.astype(np.float32).tofile(out_path)

`
Use this python tool to convert your input.jpg to input.npy

**Comment by lyp0413** [comment]
@TonyMou  Even I use a npy file provided from http://cnbj1.fds.api.xiaomi.com/mace/inputs/chicago480x640.npy,it still occurs with the same error logs printed.

**Comment by TonyMou** [comment]
@lyp0413 did u change anything in the yaml file?

**Comment by lyp0413** [comment]
@TonyMou Yes, I changed the run time to GPU,because when I use 'GPU' option,I met with another error:
lyp@lyp:~/mace-master/bazel-bin/mace/tools/validation$ ./mace_run_static --input_file=input/5.npy
I mace/tools/validation/fast.cc:428] model name: fast_style_transfer_la_muse
I mace/tools/validation/fast.cc:429] mace version: unknown-20180705
I mace/tools/validation/fast.cc:430] input node: img_placeholder
I mace/tools/validation/fast.cc:431] input shape: 1,480,640,3
I mace/tools/validation/fast.cc:432] output node: add_37
I mace/tools/validation/fast.cc:433] output shape: 1,480,640,3
I mace/tools/validation/fast.cc:434] input_file: input/5.npy
I mace/tools/validation/fast.cc:435] output_file: 2.npy
I mace/tools/validation/fast.cc:436] model_data_file: /home/lyp/mace-master/build/fast_style_transfer_la_muse/model/fast_style_transfer_la_muse.data
I mace/tools/validation/fast.cc:437] model_file: /home/lyp/mace-master/build/fast_style_transfer_la_muse/model/fast_style_transfer_la_muse.pb
I mace/tools/validation/fast.cc:438] device: GPU
I mace/tools/validation/fast.cc:439] round: 1
I mace/tools/validation/fast.cc:440] restart_round: 1
I mace/tools/validation/fast.cc:441] gpu_perf_hint: 3
I mace/tools/validation/fast.cc:442] gpu_priority_hint: 3
I mace/tools/validation/fast.cc:443] omp_num_threads: -1
I mace/tools/validation/fast.cc:444] cpu_affinity_policy: 1
I mace/tools/validation/fast.cc:467] restart round 0
W mace/core/runtime/cpu/cpu_runtime.cc:140] Set OpenMP threads number failed: OpenMP not enabled.
I mace/core/mace.cc:336] Create MaceEngine from model pb
F mace/core/types.cc:59] Unsupported data type: 3

**Comment by TonyMou** [comment]
@lyp0413 Did u use these two commands to build and run (validate)?

```
python tools/converter.py build --config=/path/to/mace-models/fast-style-transfer/fast_style_transfer_scream.yml
python tools/converter.py run --config=/path/to/mace-models/fast-style-transfer/fast_style_transfer_scream.yml --validate
```

**Comment by lyp0413** [comment]
@TonyMou Yes,but when I run "...run...--validate" command ,it seems like no oprations:
lyp@lyp:~/mace-master$ python tools/converter.py run --config=models/fast-style-transfer/fast_style_transfer_la_muse.yml --validate
lyp@lyp:~/mace-master$ 
Is it correct?

**Comment by TonyMou** [comment]
@lyp0413 Could u paste your modified yml file here?

**Comment by lyp0413** [comment]
@TonyMou  runtime：CPU
library_name: fast_style_transfer_la_muse
target_abis: [armeabi-v7a, arm64-v8a]
embed_model_data: 0
build_type: proto
models: 
  fast_style_transfer_la_muse:
    platform: tensorflow
    model_file_path: http://cnbj1.fds.api.xiaomi.com/mace/miai-models/fast-style-transfer/la_muse.pb
    model_sha256_checksum: 2eb9d0b07c0e39e0d08bcb1258bf8394251c92552e5b30539abf4aa7a5d906aa
    subgraphs:
      - input_tensors: img_placeholder
        input_shapes: 1,480,640,3
        output_tensors: add_37
        output_shapes: 1,480,640,3
        validation_inputs_data:
          - http://cnbj1.fds.api.xiaomi.com/mace/inputs/chicago480x640.npy
    runtime: cpu
    limit_opencl_kernel_time: 0
    dsp_mode: 0
    obfuscate: 1
    winograd: 4


runtime：GPU
library_name: fast_style_transfer_la_muse
target_abis: [armeabi-v7a, arm64-v8a]
embed_model_data: 0
build_type: proto
models: 
  fast_style_transfer_la_muse:
    platform: tensorflow
    model_file_path: http://cnbj1.fds.api.xiaomi.com/mace/miai-models/fast-style-transfer/la_muse.pb
    model_sha256_checksum: 2eb9d0b07c0e39e0d08bcb1258bf8394251c92552e5b30539abf4aa7a5d906aa
    subgraphs:
      - input_tensors: img_placeholder
        input_shapes: 1,480,640,3
        output_tensors: add_37
        output_shapes: 1,480,640,3
        validation_inputs_data:
          - http://cnbj1.fds.api.xiaomi.com/mace/inputs/chicago480x640.npy
    runtime: gpu
    limit_opencl_kernel_time: 0
    dsp_mode: 0
    obfuscate: 1
    winograd: 4

**Comment by TonyMou** [comment]
@lyp0413 Did u plug any android device to your pc and enable the Developer Mode?

If you just want to build and run the model on pc, set `target_abis: [host]` and `runtime: cpu`

**Comment by lyp0413** [comment]
No ,I`m just doing a test on PC.
When I set to [host] & cpu ,it can run ,but with --validate,it occurs that:
---------------------------------------------------------------------------------------------------------------------------------
* Validate with tensorflow
2018-07-05 14:01:50.545224: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-05 14:01:50.545506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.835
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 7.25GiB
2018-07-05 14:01:50.545516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2018-07-05 14:01:50.545520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2018-07-05 14:01:50.545542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
2018-07-05 14:01:50.691320: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_img_placeholder_0, Variable). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_img_placeholder_0, Variable)]]
Traceback (most recent call last):
  File "tools/converter.py", line 1360, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1082, in run_mace
    run_specific_target(flags, configs, target_abi, None, None)
  File "tools/converter.py", line 1063, in run_specific_target
    caffe_env=flags.caffe_env)
  File "/home/lyp/mace-master/tools/sh_commands.py", line 841, in validate_model
    ",".join(input_nodes), ",".join(output_nodes))
  File "/home/lyp/mace-master/tools/validate.py", line 180, in validate
    output_names)
  File "/home/lyp/mace-master/tools/validate.py", line 112, in validate_tf_model
    output_values = session.run(output_nodes, feed_dict=input_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_img_placeholder_0, Variable). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_img_placeholder_0, Variable)]]

Caused by op u'Conv2D', defined at:
  File "tools/converter.py", line 1360, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1082, in run_mace
    run_specific_target(flags, configs, target_abi, None, None)
  File "tools/converter.py", line 1063, in run_specific_target
    caffe_env=flags.caffe_env)
  File "/home/lyp/mace-master/tools/sh_commands.py", line 841, in validate_model
    ",".join(input_nodes), ",".join(output_nodes))
  File "/home/lyp/mace-master/tools/validate.py", line 180, in validate
    output_names)
  File "/home/lyp/mace-master/tools/validate.py", line 93, in validate_tf_model
    tf.import_graph_def(input_graph_def, name="")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 308, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_img_placeholder_0, Variable). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_img_placeholder_0, Variable)]]
----------------------------------------------------------------------------------------------------------------------------------

**Comment by TonyMou** [comment]
@lyp0413 Which version of tensorflow are you using?

**Comment by lyp0413** [comment]
tensorflowgpu-1.1.0

**Comment by lyp0413** [comment]
@TonyMou  tensorflowgpu-1.1.0

**Comment by TonyMou** [comment]
@lyp0413 MACE now only supports tensorflow 1.6.0+. 

https://mace.readthedocs.io/en/latest/getting_started/how_to_build.html#environment-requirement

**Comment by lyp0413** [comment]
Thank u,I`ll upgrade my tf version,and try again.

**Comment by lyp0413** [comment]
@TonyMou 
Thank u,I`ll upgrade my tf version,and try again.

**Comment by TonyMou** [comment]
@lyp0413 No worries.
