### ISSUE TITLE
当手机不支持opencl时析构maceEngine导致空指针crash

### ISSUE THREAD

**Issue by f23505106** [XiaoMi/mace#442]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
yes
2. Have you ever read the document for your usage?
yes
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macos 10.14.4
- **NDK version(e.g., 15c)**:
android-ndk-r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
python 3.6
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
使用下面代码创建 mace engine，如果DeviceType == mace::GPU 但手机不支持opencl时
            mace::MaceStatus create_engine_status =
                            mace::CreateMaceEngineFromProto(model_pb,
                                                            pbLength,
                                                            model_data,
                                                            dataLength,
                                                            {ptr->mModelInfo.inputName},
                                                            {ptr->mModelInfo.outputName},
                                                            config,
                                                            &ptr->maceEngine);
回导致如下报错
05-16 11:00:27.213 25853-25853/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-16 11:00:27.213 25853-25853/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
05-16 11:00:27.213 25853-25853/? A/DEBUG: Revision: '11'
05-16 11:00:27.213 25853-25853/? A/DEBUG: ABI: 'arm'
05-16 11:00:27.213 25853-25853/? A/DEBUG: pid: 4045, tid: 4045, name: mace_run_static  >>> /data/local/tmp/mace_run/mace_run_static <<<
05-16 11:00:27.213 25853-25853/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
05-16 11:00:27.214 25853-25853/? A/DEBUG:     r0 00000000  r1 b6884134  r2 00000000  r3 0000007d
05-16 11:00:27.214 25853-25853/? A/DEBUG:     r4 be971744  r5 be971750  r6 000e67c8  r7 00000001
05-16 11:00:27.214 25853-25853/? A/DEBUG:     r8 00000000  r9 00000000  sl 00000000  fp be96fb70
05-16 11:00:27.214 25853-25853/? A/DEBUG:     ip b6882000  sp be96fb68  lr b6dc16ec  pc b6b43e30  cpsr a00f0010
05-16 11:00:27.217 784-913/? W/NativeCrashListener: Couldn't find ProcessRecord for pid 4045
05-16 11:00:27.233 25853-25853/? A/DEBUG: backtrace:
05-16 11:00:27.233 25853-25853/? E/DEBUG: AM write failed: Broken pipe
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #00 pc 0006de30  /data/local/tmp/mace_run/mace_run_static
bazel-out/armeabi-v7a-dbg/genfiles/external/opencl_clhpp/include/CL/cl2.hpp:8224
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #01 pc 002eb6e8  mace/mace/core/runtime/opencl/opencl_runtime.cc:439
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #02 pc 002e1dcc  mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:76
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #03 pc 002e12c0  mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:236
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #04 pc 002e1358  /data/local/tmp/mace_run/mace_run_static
mace/mace/core/runtime/opencl/gpu_device.cc:38
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #05 pc 002e1410  /data/local/tmp/mace_run/mace_run_static
mace/mace/core/runtime/opencl/gpu_device.cc:38
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #06 pc 00078930  /data/local/tmp/mace_run/mace_run_static
mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:76
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #07 pc 0006472c  /data/local/tmp/mace_run/mace_run_static
mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:236
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #08 pc 000674c8  /data/local/tmp/mace_run/mace_run_static
mace/mace/libmace/mace.cc:583
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #09 pc 00083eb8  /data/local/tmp/mace_run/mace_run_static
mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:76
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #10 pc 0006dfd4  /data/local/tmp/mace_run/mace_run_static
mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:236
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #11 pc 0006df74  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/9065035758729020618/execroot/mace/mace/libmace/mace.cc:793
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #12 pc 00084f54  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/9065035758729020618/execroot/mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:373
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #13 pc 0002edb4  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/1923289093345518292/execroot/mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:149
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #14 pc 0002ed4c  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/1923289093345518292/execroot/mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:666
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #15 pc 0002f764  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/1923289093345518292/execroot/mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:914
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #16 pc 0006e51c  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/9065035758729020618/execroot/mace/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:1023
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #17 pc 0006e304  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/9065035758729020618/execroot/mace/mace/libmace/mace.cc:840
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #18 pc 0002a1d4  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/1923289093345518292/execroot/mace/mace/tools/validation/mace_run.cc:245
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #19 pc 0002e364  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/1923289093345518292/execroot/mace/mace/tools/validation/mace_run.cc:516
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #20 pc 0002eca4  /data/local/tmp/mace_run/mace_run_static
/private/var/tmp/_bazel_fengguangtu/ba343ce82f68d639948af240710907bf/sandbox/1923289093345518292/execroot/mace/mace/tools/validation/mace_run.cc:531
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #21 pc 00017359  /system/lib/libc.so (__libc_init+44)
05-16 11:00:27.233 25853-25853/? A/DEBUG:     #22 pc 000290c0  /data/local/tmp/mace_run/mace_run_static

分析发现在构造opencl_runtime时执行opencl_runtime.cpp
OpenCLRuntime::OpenCLRuntime(
    std::shared_ptr<KVStorage> cache_storage,
    const GPUPriorityHint priority_hint,
    const GPUPerfHint perf_hint,
    std::shared_ptr<KVStorage> precompiled_binary_storage,
    std::shared_ptr<Tuner<uint32_t>> tuner):
    cache_storage_(cache_storage),
    precompiled_binary_storage_(precompiled_binary_storage),
    tuner_(tuner),
    is_opencl_avaliable_(false),
    is_profiling_enabled_(false),
    opencl_version_(CL_VER_UNKNOWN),
    gpu_type_(UNKNOWN) {
  std::vector<cl::Platform> all_platforms;
  cl::Platform::get(&all_platforms);
  if (all_platforms.empty()) **{//如果这里报错会导致成员command_queue_并不会被构造**
    LOG(ERROR) << "No OpenCL platforms found";
    return;
  }
  cl::Platform default_platform = all_platforms[0];
  std::stringstream ss;
  ss << default_platform.getInfo<CL_PLATFORM_NAME>()
     << ", " << default_platform.getInfo<CL_PLATFORM_PROFILE>() << ", "
     << default_platform.getInfo<CL_PLATFORM_VERSION>() << ", "
     << MaceVersion();
  platform_info_ = ss.str();
  VLOG(1) << "Using platform: " << platform_info_;

  // get default device (CPUs, GPUs) of the default platform
  std::vector<cl::Device> all_devices;
  default_platform.getDevices(CL_DEVICE_TYPE_ALL, &all_devices);
  if (all_devices.empty()) {
    LOG(ERROR) << "No OpenCL devices found";
    return;
  }

  bool gpu_detected = false;
  device_ = std::make_shared<cl::Device>();
  for (auto device : all_devices) {
    if (device.getInfo<CL_DEVICE_TYPE>() == CL_DEVICE_TYPE_GPU) {
      *device_ = device;
      gpu_detected = true;

      const std::string device_name = device.getInfo<CL_DEVICE_NAME>();
      gpu_type_ = ParseGPUType(device_name);

      const std::string device_version = device.getInfo<CL_DEVICE_VERSION>();
      opencl_version_ = ParseDeviceVersion(device_version);
      if (opencl_version_ == OpenCLVersion::CL_VER_UNKNOWN) {
        return;
      }

      VLOG(1) << "Using device: " << device_name;
      break;
    }
  }
  if (!gpu_detected) {
    LOG(ERROR) << "No GPU device found";
    return;
  }

  cl_command_queue_properties properties = 0;

  const char *profiling = getenv("MACE_OPENCL_PROFILING");
  if (IsTuning() ||
      (profiling != nullptr && strlen(profiling) == 1 && profiling[0] == '1')) {
    properties |= CL_QUEUE_PROFILING_ENABLE;
    is_profiling_enabled_ = true;
  }

  cl_int err;
  if (gpu_type_ == GPUType::QUALCOMM_ADRENO
          && opencl_version_ == OpenCLVersion::CL_VER_2_0) {
    std::vector<cl_context_properties> context_properties;
    context_properties.reserve(5);
    GetAdrenoContextProperties(&context_properties,
                               perf_hint,
                               priority_hint);
    context_ = std::shared_ptr<cl::Context>(
        new cl::Context({*device_}, context_properties.data(),
                        nullptr, nullptr, &err));
  } else {
#if CL_HPP_TARGET_OPENCL_VERSION >= 200
    if (is_profiling_enabled_ && gpu_type_ == GPUType::MALI) {
      std::vector<cl_context_properties> context_properties = {
          CL_CONTEXT_PLATFORM, (cl_context_properties)default_platform(),
          CL_PRINTF_CALLBACK_ARM, (cl_context_properties)OpenCLPrintfCallback,
          CL_PRINTF_BUFFERSIZE_ARM, 0x1000, 0
      };
      context_ = std::shared_ptr<cl::Context>(
          new cl::Context({*device_}, context_properties.data(),
                          nullptr, nullptr, &err));
    } else {
      context_ = std::shared_ptr<cl::Context>(
          new cl::Context({*device_}, nullptr, nullptr, nullptr, &err));
    }
#else
    context_ = std::shared_ptr<cl::Context>(
          new cl::Context({*device_}, nullptr, nullptr, nullptr, &err));
#endif
  }
  if (err != CL_SUCCESS) {
    LOG(ERROR) << "Failed to create OpenCL Context: "
               << OpenCLErrorToString(err);
    return;
  }

  command_queue_ = std::make_shared<cl::CommandQueue>(*context_,
                                                      *device_,
                                                      properties,
                                                      &err);
  if (err != CL_SUCCESS) {
    LOG(ERROR) << "Failed to create OpenCL CommandQueue: "
               << OpenCLErrorToString(err);
    return;
  }
在构造opencl_runtime出错后command_queue_并没有被初始话，而在析构函数里直接使用了这个变量导致 空指针异常
OpenCLRuntime::~OpenCLRuntime() {
    command_queue_->finish(); //这里直接使用没有初始化的指针导致crash
  built_program_map_.clear();
  // We need to control the destruction order, which has dependencies
  command_queue_.reset();
  context_.reset();
  device_.reset();
}
最简单的规避是在析构时判空
OpenCLRuntime::~OpenCLRuntime() {
  if(command_queue_.get() != nullptr)//增加判空
    command_queue_->finish();
  built_program_map_.clear();
  // We need to control the destruction order, which has dependencies
  command_queue_.reset();
  context_.reset();
  device_.reset();
}
经测试增加判空后就不会出现crash了

**Comment by nolanliou** [comment]
非常感谢，我们会尽快fix

**Comment by nolanliou** [comment]
Fixed on master.
