### ISSUE TITLE
mace的运行环境问题

### ISSUE THREAD

**Issue by AlpacaKnight** [XiaoMi/mace#448]
您好,请问mace对于Android的系统版本有具体要求么,比如必须运行在Android的某个版本以上?
(这是我们的某个客户提的问题,我试图解释但还是无法给出他们想要的答案,特来求助)

**Comment by yejw5** [comment]
应该是安卓7.0以上

**Comment by yejw5** [comment]
我们在WORKSPACE里指定api level为21，对应的应该是安卓5.0以上，参照：https://developer.android.com/studio/releases/platforms
