### ISSUE TITLE
Support Android NN API

### ISSUE THREAD

**Issue by maxim-gusarov** [XiaoMi/mace#449]
### Describe the problem
Have you tried to integrate or utilize [Android NN API](https://developer.android.com/ndk/guides/neuralnetworks) in MACE? If so, how does it compare with the regular MACE GPU inference? If not, do you have any plans to integrate it in the future?

**Comment by lu229** [comment]
@maxim-gusarov , we have not integrate Android NN API in MACE. We do not have such a plan in the near future.

**Comment by maxim-gusarov** [comment]
Got it, thanks!
