### ISSUE TITLE
Docker build android demo error

### ISSUE THREAD

**Issue by huayong** [XiaoMi/mace#45]
Docker could build model successfully in mace-models floder, but run build.sh in mace/exampls/android to build docs/getting_started/models/demo_app_models.yaml error.

error info:

************************************************
          Model mobilenet_v2 converted          
************************************************

************************************
          Building library          
************************************

* generate common source files...
generate common source files done
* Build //mace/tools/validation:mace_run_static with ABI arm64-v8a
INFO: Analysed target //mace/tools/validation:mace_run_static (23 packages loaded).
INFO: Found 1 target...
ERROR: /home/xiaomi/mace/mace/codegen/BUILD:8:1: C++ compilation of rule '//mace/codegen:generated_models' failed (Exit 4): aarch64-linux-android-gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/fa4ec98d408ae719cd72ee65a9d3e6e4/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-canonical-system-headers -O2 -g -DNDEBUG -MD -MF bazel-out/arm64-v8a-opt/bin/mace/codegen/_objs/generated_models/mace/codegen/models/mobilenet_v1/tensor_data.d '-frandom-seed=bazel-out/arm64-v8a-opt/bin/mace/codegen/_objs/generated_models/mace/codegen/models/mobilenet_v1/tensor_data.o' -iquote . -iquote bazel-out/arm64-v8a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/arm64-v8a-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/arm64-v8a-opt/genfiles/external/com_google_protobuf -iquote external/opencl_clhpp -iquote bazel-out/arm64-v8a-opt/genfiles/external/opencl_clhpp -iquote external/opencl_headers -iquote bazel-out/arm64-v8a-opt/genfiles/external/opencl_headers -iquote external/half -iquote bazel-out/arm64-v8a-opt/genfiles/external/half -Ibazel-out/arm64-v8a-opt/bin/external/opencl_headers/_virtual_includes/opencl20_headers -isystem external/com_google_protobuf/src -isystem bazel-out/arm64-v8a-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/arm64-v8a-opt/bin/external/com_google_protobuf/src '-std=c++11' -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c mace/codegen/models/mobilenet_v1/tensor_data.cc -o bazel-out/arm64-v8a-opt/bin/mace/codegen/_objs/generated_models/mace/codegen/models/mobilenet_v1/tensor_data.o)
aarch64-linux-android-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.
Target //mace/tools/validation:mace_run_static failed to build
INFO: Elapsed time: 318.051s, Critical Path: 87.93s
INFO: 109 processes, local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1348, in <module>
    flags.func(flags)
  File "tools/converter.py", line 888, in build_library
    flags.disable_openmp, flags.address_sanitizer)
  File "tools/converter.py", line 851, in generate_library
    tuning, enable_openmp, address_sanitizer)
  File "tools/converter.py", line 720, in build_specific_lib
    address_sanitizer=address_sanitizer
  File "/home/xiaomi/mace/tools/sh_commands.py", line 323, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/bazel build //mace/tools/validation:mace_run_static --config android --cpu=arm64-v8a --define neon=true --define openmp=true --define hexagon=false --config optimization

  STDOUT:

  STDERR:

**Comment by lee-bin** [comment]
Building demo app itself needs almost 6 GB RAM. So make sure you have enough RAM.

**Comment by lee-bin** [comment]
Just close this issue, if there are still problems, feel free to reopen it.
