### ISSUE TITLE
C# port for MACE to use in Unity

### ISSUE THREAD

**Issue by Praptobala** [XiaoMi/mace#450]
Hi,

Great thanks to making MACE as opensource!

Found a python port, but I wanted to build Unity crossplatform app.

Do you have any roadmap to create Unity C# port?\

Thanks

**Comment by llhe** [comment]
Do you mean mace/python? It's not python port, but tools for converting models.

There won't be a C# port recently, since we are not supporting X86 (with optimization) yet. For windows, is it a better solution with tensorflow or other full fledged frameworks?
