### ISSUE TITLE
在arm板上部署mobilenet-SSD时的报错

### ISSUE THREAD

**Issue by WeixiangXu** [XiaoMi/mace#453]
问题如下：
/tmp/data/mace_run/mace_run_static: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/data/mace_run/mace_run_static)

我在arm板子上查看strings /usr/lib/aarch64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

得到结果如下
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21

确实没有GLIBCXX_3.4.22

请问这个问题该如何解决？

**Comment by WeixiangXu** [comment]
补充一下提问，在我之前旧的MACE版本是没这个问题的，今天git clone了新的mace之后有这个问题。

**Comment by WeixiangXu** [comment]
最后使用旧版本MACE测试了……

**Comment by llhe** [comment]
你用哪个toolchain编译的？mace里面的linaro?
