### ISSUE TITLE
bash tools/build-standalone-lib.sh build fail

### ISSUE THREAD

**Issue by uikilin100** [XiaoMi/mace#455]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 14.04.5
- **NDK version(e.g., 15c)**:android-ndk-r18b
- **GCC version(if compiling for host, e.g., 5.4.0)**:android
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0
- **Python version(2.7)**: 3.4.3
- **Bazel version (e.g., 0.13.0)**:0.13

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
Build fail with following log

HI,

cted"' '-D__TIME__="redacted"' -c mace/core/memory_optimizer.cc -o bazel-out/k8-opt/bin/mace/core/_objs/core/mace/core/memory_optimizer.pic.o)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mace/core/types.h:22:0,
                 from ./mace/core/memory_optimizer.h:25,
                 from mace/core/memory_optimizer.cc:15:
external/half/include/half.hpp:275:8: error: missing space between '""' and suffix identifier
   half operator""_h(long double);
        ^
external/half/include/half.hpp:1086:24: error: missing space between '""' and suffix identifier
   friend half literal::operator""_h(long double);
                        ^
external/half/include/half.hpp:1199:15: error: missing space between '""' and suffix identifier
   inline half operator""_h(long double value) { return half(detail::binary, detail::float2half<half::round_style>(value)); }

**Comment by lu229** [comment]
@uikilin100 It seems that you compiler doesn't support c++11,  what is your compile command?  have you modified the code or build parameters?

**Comment by uikilin100** [comment]
> @uikilin100 It seems that you compiler doesn't support c++11, what is your compile command? have you modified the code or build parameters?

@lu229 Thanks, seems like that one of dynamic library build in script fail because c++11
