### ISSUE TITLE
fail to python tools/converter.py convert --config=../../models/model_deployment_file.yml

### ISSUE THREAD

**Issue by uikilin100** [XiaoMi/mace#457]
Could I convert model without phone plugin ?

**Comment by lu229** [comment]
@uikilin100  Ofcource you can, if you do not specify the  --target_socs parameter, you need not to connect the device.

**Comment by uikilin100** [comment]
I do not specify the --target_socs.
It looks like setting target_abis in yml development file still need sh command.
Does it support that converting model, build library and example_static without device plugin (only use target_abis information in yml file)?

**Comment by lu229** [comment]
@uikilin100 , Did you specify the --target_socs parameter in the yml file?  If you didn't, you can use the command to convert model without device plugin: 
python tools/converter.py convert --config=${CONF_FILE}

You can reference: https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#build-and-run-an-example-model

**Comment by uikilin100** [comment]
> @uikilin100 , Did you specify the --target_socs parameter in the yml file? If you didn't, you can use the command to convert model without device plugin:
> python tools/converter.py convert --config=${CONF_FILE}
> 
> You can reference: https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#build-and-run-an-example-model

I do not specify the --target_socs parameter in the yml file.
But I do reference the link you post, I have target_abis: [arm64-v8a] parameter in the yml file.
You could see in the tools/converter.py line 356, if I specify target_abis in yml file, it will execute line 358.

I finally go through all mace model deployment flow and have example.cc run in my phone.
But I need to mark out all adb commands to let "python tools/converter.py run --config=/path/to/your/model_deployment_file.yml" generate the input data, model, cmd file in my work station.

Is there a way that I could build example.cc directly using bazel without using tools/converter.py

**Comment by lu229** [comment]
@uikilin100 Yes, the line 358 of tools/converter.py will execute, but which doesn't matter, because the sh_commands.adb_get_all_socs() will return an empty array, and the converter will finally execute successfully without device plugin.

**Comment by uikilin100** [comment]
> @uikilin100 Yes, the line 358 of tools/converter.py will execute, but which doesn't matter, because the sh_commands.adb_get_all_socs() will return an empty array, and the converter will finally execute successfully without device plugin.

@lu229  Because my work station do not have ADV installed, I saw ADB is optional dependency in the environment requirements.
It's better that sh_commands.adb_get_all_socs could return an empty array if there is no adb sh command found.
