### ISSUE TITLE
Build library  error

### ISSUE THREAD

**Issue by hongsui169163** [XiaoMi/mace#46]
python tools/converter.py build --config=models/config.yaml
执行完这个后报错，无法编译通过，错误如下：
ERROR: /home/asd/log_07_01/xiaomi/mace-masternew/mace-master/mace/core/BUILD:19:1: C++ compilation of rule '//mace/core:core' failed (Exit 1): clang failed: error executing command 
  (cd /home/asd/.cache/bazel/_bazel_asd/aa66681cc04c699005bd8258b00b7111/execroot/mace && \
帮忙确认一下是哪里的问题，谢谢

**Comment by TonyMou** [comment]
1. 请确认安装环境： https://mace.readthedocs.io/en/latest/getting_started/how_to_build.html#
2. python tools/converter.py build --config=/path/to/your/model_deployment_file.yml

**Comment by hongsui169163** [comment]
找到原因了，是因为NDK的版本太新了，我用的是17b,编不过，换成16b可以编译通过了

**Comment by TonyMou** [comment]
@hongsui169163 是的，bazel目前还没支持到ndk 17以上
