### ISSUE TITLE
请问下mace是否只在安卓端做了加速处理？

### ISSUE THREAD

**Issue by powea000** [XiaoMi/mace#461]
mobilenetv3在树莓派上推理时间高达2秒。

**Comment by lydoc** [comment]
请问方便提供一下模型吗？我这边测试一下

**Comment by powea000** [comment]
> 请问方便提供一下模型吗？我这边测试一下；是GPU还是CPU？
> 另外有没有试过在Android设备上测试一下？mobilenetv3由于激活函数的原因，目前还没有做优化，可能会导致时间比较长。如果方便的话亦可以对比一下mobilenet v1/v2 在Android和树莓派的速度比较。



> 请问方便提供一下模型吗？我这边测试一下；是GPU还是CPU？
> 另外有没有试过在Android设备上测试一下？mobilenetv3由于激活函数的原因，目前还没有做优化，可能会导致时间比较长。如果方便的话亦可以对比一下mobilenet v1/v2 在Android和树莓派的速度比较。

模型怎么给你，没找到上传附件的选项。。

**Comment by lydoc** [comment]
可以直接拖上来原始的模型文件，abi是用的armhf吗？

**Comment by powea000** [comment]
> 可以直接拖上来原始的模型文件，abi是用的armhf吗？

是armhf
[1.zip](https://github.com/XiaoMi/mace/files/3285191/1.zip)

**Comment by lydoc** [comment]
我这边测试了一下是774ms，这个数据应该是正常的，mobilenetv2在330ms左右，mace中对5x5的卷积还需要继续优化，这部分占用了比较多的时间，你那边是不是用的不是最新的mace，可以用最新的master再测试一下。
