### ISSUE TITLE
opencl_binary_paths和opencl_parameter_file这两个文件是如何生成的？

### ISSUE THREAD

**Issue by powea000** [XiaoMi/mace#462]
按照https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html? 的说法，在model_deployment_file.yml上添加了target_socs: BCM2835，然后依次运行
python tools/converter.py convert --config=/path/to/model_deployment_file.yml和
python tools/converter.py run --config=/path/to/model_deployment_file.yml --validate。
前者是把模型打包成库文件，但是后者只是把前者生成的build文件打个包，并没有像官方手册上说的那样生成opencl的相关文件。

**Comment by lydoc** [comment]
https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#tuning-for-specific-soc-s-gpu

**Comment by powea000** [comment]
> https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#tuning-for-specific-soc-s-gpu
> 请问有插入设备，adb没有问题吗？

我们是嵌入式设备（树莓派），没有adb

**Comment by lydoc** [comment]
https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#run-you-model-on-the-embedded-device-arm-linux
嵌入式设备参考一下这个，需要指定一下device_yml
