### ISSUE TITLE
fail to build example.cc

### ISSUE THREAD

**Issue by uikilin100** [XiaoMi/mace#463]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by uikilin100** [comment]
I found there is no "python tools/converter.py build --config=docs/getting_started/models/demo_app_models.yaml" any more

I fail build example.cc using bazel directly
bazel build //mace/examples/cli:example_static --config android --cpu=arm64-v8a --define neon=true --define openmp=false --define opencl=true --define quantize=false --define hexagon=false --define hta=false --define apu=false --config optimization --config symbol_hidden

build error message:
mace/examples/cli/example.cc:355: error: undefined reference to 'mace::MaceTensor::data()'
mace/examples/cli/example.cc:363: error: undefined reference to 'mace::MaceEngine::Run(std::map<std::string, mace::MaceTensor, std::less<std::string>, std::allocator<std::pair<std::string const, mace::MaceTensor> > > const&, std::map<std::string, mace::MaceTensor, std::less<std::string>, std::allocator<std::pair<std::string const, mace::MaceTensor> > >*)'
mace/examples/cli/example.cc:373: error: undefined reference to 'mace::MaceTensor::data()'
mace/examples/cli/example.cc:387: error: undefined reference to 'mace::MaceEngineConfig::~MaceEngineConfig()'
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:0: error: undefined reference to 'mace::port::Logger::~Logger()'
mace/examples/cli/example.cc:185: error: undefined reference to 'mace::GPUContextBuilder::~GPUContextBuilder()'
mace/examples/cli/example.cc:286: error: undefined reference to 'mace::MaceTensor::~MaceTensor()'
mace/examples/cli/example.cc:275: error: undefined reference to 'mace::MaceTensor::~MaceTensor()'
mace/examples/cli/example.cc:387: error: undefined reference to 'mace::MaceEngineConfig::~MaceEngineConfig()'
mace/examples/cli/example.cc:395: error: undefined reference to 'mace::MaceVersion()'
mace/examples/cli/example.cc:416: error: undefined reference to 'mace::Split(std::string const&, char)'
mace/examples/cli/example.cc:417: error: undefined reference to 'mace::Split(std::string const&, char)'
mace/examples/cli/example.cc:418: error: undefined reference to 'mace::Split(std::string const&, char)'
mace/examples/cli/example.cc:419: error: undefined reference to 'mace::Split(std::string const&, char)'
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/tuple:1104: error: undefined reference to 'mace::MaceTensor::MaceTensor()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lydoc** [comment]
Which version of mace did you use?  Mace has been refactored in the new version, so please refer to the latest docs: https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html

**Comment by TonyMou** [comment]
It seems you need a mace library before building example.cc.
Suggest you use the `cmake` and `bazel` building shell tools under `tools/`. 
You can use `bash tools/bazel-build-standalone-lib.sh` to build a libmace.
This shell script will build libraries for all supported target os by default.
You can also modify this shell script for your using case to save some building time.

**Comment by uikilin100** [comment]
＠TonyMou I did use bash tools/build-standalone-lib.sh to build libmace.
After libmace library generated, I still have problem when I use bazel build example.cc
PS: I got the latest mace code, bazel-build-standalone-lib.sh seems rename to build-standalone-lib.sh. Probably there are some change between these two.
But if I use tools/converter.py run --config=/path/to/model --example.
It could correctly generate example_static.
I saw previous related issue when I create the issue, someone using "tools/converter.py" build to generate example_static, but I cannot see this build option is supported in convert.py.

**Comment by TonyMou** [comment]
Did you try the following commands:
```
python tools/converter.py convert --config=your_model_config.yml
python tools/converter.py run --config=your_model_config.yml --example
```
You'll find the example_static in mace/bazel_bin/examples after `run --example`.

**Comment by uikilin100** [comment]
@TonyMou I cannot directly use these tools/converter.py run command, since I need to build example.cc in workstation without adb.
I refine converter.py, mark out all adb commands, then have example_static, test data, test command generated.
But I am wonder if there is a why I could do these without modify the converter.py, such as directly use bazel build.
But it looks like doesnt work.

**Comment by lu229** [comment]
@uikilin100 There is no way to use bazel build directly, because there are a lot of logic in python code.

**Comment by uikilin100** [comment]
@lu229 yes, I did change some logic in python and got what I want.
Thanks, I will close the issue
