### ISSUE TITLE
mace build failed

### ISSUE THREAD

**Issue by chenjiaoAngel** [XiaoMi/mace#464]
Mace编译失败，日志如下：

用docker pull lite image, 步骤如下：
    1. docker pull registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite
    2. docker docker run -it --privileged=true -v /home/chenjiao04/mace:/tmp/mace -v /home/chenjiao04/mace-models:/tmp/mace-models registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev
    3. docker exec -it mace-dev /bin/bash
    4. cd mace
    5. bash  tools/bazel-build-standalone-lib.sh，出错信息如下：
![image](https://user-images.githubusercontent.com/38650344/59431863-797b6500-8e18-11e9-8cff-dd9989d1bb43.png)

Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: ndk16
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**: commit 190e268070a4c4669401ea2c1db49570406ab41c
- **Python version(2.7)**: 2,7
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by liyinhgqw** [comment]
Bazel has not supported NDK 19 yet.
Please use cmake to compile.

**Comment by chenjiaoAngel** [comment]
Now I set ANDROID_NDK_HOME=../android-ndk-r16b/
then bash tools/bazel-build-standalone-lib.sh，the error info is fllowing：
![image](https://user-images.githubusercontent.com/38650344/59575438-217d8080-90ee-11e9-9b66-e0a90bbde910.png)
2. sh ./tools/bazel-build-standalone-lib.sh, 很长时间都没有download完成
![image](https://user-images.githubusercontent.com/38650344/59575808-8d141d80-90ef-11e9-9414-37a47b21f2e5.png)

**Comment by llhe** [comment]
@chenjiaoAngel 用下面命令单独测试一下文件下载情况？

```sh
$ time wget https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
```

**Comment by chenjiaoAngel** [comment]
It doesn't success
![image](https://user-images.githubusercontent.com/38650344/59652940-8d311d80-91c2-11e9-8209-81a1848f4827.png)

**Comment by lu229** [comment]
@chenjiaoAngel Please execute the shell command and try again:
sudo apt-get install libssl-dev
