### ISSUE TITLE
run quanmodel  failed

### ISSUE THREAD

**Issue by sunzhe09** [XiaoMi/mace#465]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:18.10
- **NDK version(e.g., 15c)**:r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:0.11.o-rc1
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.13.1

### Model deploy file (*.yml)
library_name: mobilenet-v2-quantize-retrain
target_abis: [arm64-v8a,armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v2_quantize_retrain:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet_v2_1.0_224_quant_retrain.pb
    model_sha256_checksum: 1429c8e2a91b251c9fa0dae43dfa5817c5a798bd30284f8c0690e7569a8817f1
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        input_ranges:
          - -1.0,1.0
        output_tensors:
          - output
        output_shapes:
          - 1,1001
        validation_inputs_data: 
          - http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
    quantize: 1

### Describe the problem
crash  see it as log
 
### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```
python tools/converter.py  run  --config=./mace-models/mobilenet-v2/mobilenet-v2-quantize-retrain.yml  --round=50

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```
========================================================
     capability(CPU)        init      warmup     run_avg
========================================================
time          60.253      32.414      92.652      75.496
I mace/tools/validation/mace_run.cc:430] Write output file /data/local/tmp/mace_run/model_out_output with size 4004 done.
I mace/libmace/mace.cc:603] Destroying MaceEngine
Running finished!

Elapse time: 0.117592 minutes.
* Package libs for mobilenet-v2-quantize-retrain
Start packaging 'mobilenet-v2-quantize-retrain' libs into builds/mobilenet-v2-quantize-retrain/libmace_mobilenet-v2-quantize-retrain.tar.gz
builds/mobilenet-v2-quantize-retrain/_tmp/
builds/mobilenet-v2-quantize-retrain/_tmp/armeabi-v7a/
builds/mobilenet-v2-quantize-retrain/_tmp/armeabi-v7a/mace_run_static
builds/mobilenet-v2-quantize-retrain/_tmp/mobilenet_v2_quantize_retrain/
builds/mobilenet-v2-quantize-retrain/_tmp/mobilenet_v2_quantize_retrain/4f98b00eb51c1f35043184db3e60a269/
builds/mobilenet-v2-quantize-retrain/_tmp/mobilenet_v2_quantize_retrain/4f98b00eb51c1f35043184db3e60a269/PBDT00_sdm710/
builds/mobilenet-v2-quantize-retrain/_tmp/mobilenet_v2_quantize_retrain/4f98b00eb51c1f35043184db3e60a269/PBDT00_sdm710/armeabi-v7a/
builds/mobilenet-v2-quantize-retrain/_tmp/mobilenet_v2_quantize_retrain/4f98b00eb51c1f35043184db3e60a269/PBDT00_sdm710/armeabi-v7a/model_input_input
builds/mobilenet-v2-quantize-retrain/_tmp/mobilenet_v2_quantize_retrain/4f98b00eb51c1f35043184db3e60a269/PBDT00_sdm710/arm64-v8a/
builds/mobilenet-v2-quantize-retrain/_tmp/mobilenet_v2_quantize_retrain/4f98b00eb51c1f35043184db3e60a269/PBDT00_sdm710/arm64-v8a/model_input_input
builds/mobilenet-v2-quantize-retrain/_tmp/arm64-v8a/
builds/mobilenet-v2-quantize-retrain/_tmp/arm64-v8a/mace_run_static
builds/mobilenet-v2-quantize-retrain/model/
builds/mobilenet-v2-quantize-retrain/model/mobilenet_v2_quantize_retrain.pb
builds/mobilenet-v2-quantize-retrain/model/mobilenet_v2_quantize_retrain.data
/bin/tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow them.  Please, rearrange them properly.
/bin/tar: --exclude “builds/mobilenet-v2-quantize-retrain/_tmp” has no effect
/bin/tar: 由于前次错误，将以上次的错误状态退出
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1041, in run_mace
    configs[YAMLKeyword.library_name])
### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by liyinhgqw** [comment]
Please try our new master code

**Comment by sunzhe09** [comment]
I convert my self model,got another problem:
TypeError: [<HexagonOp.QuantizedAdd_8p8to8: 'QuantizedAdd_8p8to8'>] has type <type 'list'>, but expected one of: (<type 'str'>, <type 'unicode'>)
Traceback (most recent call last):
  File "tools/converter.py", line 1363, in <module>
    flags.func(flags)
  File "tools/converter.py", line 866, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 794, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))

**Comment by lee-bin** [comment]
You can try our new master code if your elementwise op type is `Add` or `Sub`.
