### ISSUE TITLE
Mace does not support caffe op type Deconvolution?

### ISSUE THREAD

**Issue by wykvictor** [XiaoMi/mace#47]
I test mace with a caffe model with layer Deconvolution inside, but the script "caffe_converter.py" seems not support Deconv?

**Comment by TonyMou** [comment]
The converter does not support caffe deconv layer yet. We will add it very soon.

**Comment by wykvictor** [comment]
@TonyMou Thanks! Very looking forward to your implementation. BTW, how about caffe Reshape layer?

**Comment by TonyMou** [comment]
@wykvictor https://mace.readthedocs.io/en/latest/getting_started/op_lists.html

**Comment by wykvictor** [comment]
@TonyMou Got it. 
Limited support of RESHAPE("only internal use of reshape in composed operations is supported") means that Reshape is not supported outside? For example, defined in caffe/tenserflow model definition?

**Comment by TonyMou** [comment]
already resolved in commit fdcd657bc54a7367663d7967e5a4907e0af50a43
