### ISSUE TITLE
Here is Performance Pose estimation using mace in android 

### ISSUE THREAD

**Issue by Nanamare** [XiaoMi/mace#470]
We confirmed the pose estimation performance using the mace library. (Mate 10, A2 Lite, Xiaomi Mi pad, Galaxy S8+, Galaxy S8, Galaxy S7m Galaxy S6)
[Here is the list](https://github.com/Nanamare/android_pose_estimation_mace)(https://github.com/Nanamare/android_pose_estimation_mace)

**Comment by lu229** [comment]
@Nanamare Good job! It's our pleasure.
