### ISSUE TITLE
bash tools/build-standalone-lib.sh failed

### ISSUE THREAD

**Issue by yangfei963158659** [XiaoMi/mace#471]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```
yangfei@ubuntu:~/mace$ bash tools/build-standalone-lib.sh 
build shared lib for armeabi-v7a + cpu_gpu_dsp
INFO: Analysed target //mace/libmace:libmace_dynamic (2 packages loaded).
INFO: Found 1 target...
ERROR: /home/yangfei/mace/mace/port/BUILD.bazel:30:1: C++ compilation of rule '//mace/port:port_base' failed (Exit 1): clang failed: error executing command 
  (cd /home/yangfei/.cache/bazel/_bazel_yangfei/2a5baa80c91068aec9fab52ca37cd357/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=21' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/mace/port/_objs/port_base/mace/port/env.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/mace/port/_objs/port_base/mace/port/env.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD -Wall -Wno-mismatched-tags -Wno-missing-braces -Wall -Wno-mismatched-tags -Wno-missing-braces -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystemexternal/androidndk/ndk/sysroot/usr/include -c mace/port/env.cc -o bazel-out/armeabi-v7a-opt/bin/mace/port/_objs/port_base/mace/port/env.o)

Use --sandbox_debug to see verbose messages from the sandbox
src/main/tools/linux-sandbox-pid1.cc:427: "execvp(external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang, 0x8d0940)": No such file or directory
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 2.534s, Critical Path: 0.26s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by lu229** [comment]
@yangfei963158659 Please fill in the [issue template](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md). What is your bazel version and ndk version?

**Comment by yangfei963158659** [comment]
bazel is 0.13.1，ndk is 15b


 
---Original---

**Comment by lu229** [comment]
@yangfei963158659 It seems that your environment has some problems, the bazel cannot find your ndk location, Please execute these two shell commands in your mace root directory to test:
_bazel info output_base|xargs -i ls -l {}/external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang_
_ls -s ${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang_
are the two files exist?

**Comment by yangfei963158659** [comment]
I have sovled this problem. I take mistake that I use android ndk for windows.Thank you

**Comment by lu229** [comment]
@yangfei963158659 Congratulations, Thanks for your reply.
