### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by yangfei963158659** [XiaoMi/mace#482]
Segmentation fault when I run deeplabv3 model on dsp,erorr info is following:

yangfei@ubuntu:~/Desktop/mace$ python tools/converter.py run --config=mace-models/test/test.yml 
* Build //mace/tools/validation:mace_run_static with ABI arm64-v8a
INFO: Analysed target //mace/tools/validation:mace_run_static (0 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 58.700s, Critical Path: 12.50s
INFO: 135 processes: 134 linux-sandbox, 1 local.
INFO: Build completed successfully, 137 total actions
Build done!

************************************************
          Run model model458 on PAFM00          
************************************************

* Run 'model458' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/model458/_tmp/model458/d247f8538d73710e4140802076e4f7da/PAFM00_sdm845/arm64-v8a/model_input_image to /data/local/tmp/mace_run
Push builds/model458/model/model458.data to /data/local/tmp/mace_run
Push third_party/nnlib/arm64-v8a/libhexagon_controller.so to /data/local/tmp/mace_run
Push builds/model458/model/model458.pb to /data/local/tmp/mace_run/model458.pb
Push builds/model458/_tmp/arm64-v8a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-model458-1561983424.37 to /data/local/tmp/mace_run/cmd_file-model458-1561983424.37
WARNING: linker: "/data/local/tmp/mace_run/mace_run_static" unused DT entry: type 0xf arg 0x718
Segmentation fault
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1031, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/home/yangfei/Desktop/mace/tools/device.py", line 714, in run_specify_abi
    output_config, runtime, tuning)
  File "/home/yangfei/Desktop/mace/tools/device.py", line 556, in run_model
    YAMLKeyword.model_file_path]
  File "/home/yangfei/Desktop/mace/tools/device.py", line 355, in tuning_run
    _err_to_out=True)
  File "/home/yangfei/Desktop/mace/tools/device.py", line 73, in exec_command
    sh.adb('-s', self.address, 'shell', command, *args, **kwargs)
  File "/home/yangfei/.local/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/yangfei/.local/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/home/yangfei/.local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/yangfei/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_139: 

  RAN: /usr/bin/adb -s 2cd2266f shell sh /data/local/tmp/mace_run/cmd_file-model458-1561983424.37

  STDOUT:

  STDERR:

Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
Please fill in the [issue template](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md).
You can run `adb logcat` to capture the log of segmentation fault.
