### ISSUE TITLE
Crash on concat layer execution.

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#483]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16
- **NDK version(e.g., 15c)**:
NDK 17
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
master
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
0.13

yml:

platform: tensorflow
    model_file_path: xxx
    model_sha256_checksum: xxxx
    subgraphs:
      - input_tensors:
          - dnet_input
        input_shapes:
          - 1,48,48,1
        output_tensors:
           - dnet_output/MaxPool
        output_shapes:
           - 1,1,1,218
    # cpu, gpu or cpu+gpu
    runtime: cpu
    winograd: 4

### Describe the problem
Hi , I converting tensorflow pb file to mace format. 

**Conversion log**:
```
cnn_model/act_1/Relu (Conv2D, index:0): [[1L, 46L, 46L, 32L]]
cnn_model/max_pooling2d_1/MaxPool (Pooling, index:1): [[1L, 23L, 23L, 32L]]
cnn_model/act_2/Relu (Conv2D, index:2): [[1L, 21L, 21L, 64L]]
cnn_model/max_pooling2d_2/MaxPool (Pooling, index:3): [[1L, 10L, 10L, 64L]]
cnn_model/act_3/Relu (Conv2D, index:4): [[1L, 8L, 8L, 128L]]
cnn_model/max_pooling2d_3/MaxPool (Pooling, index:5): [[1L, 4L, 4L, 128L]]
cnn_model/act_4/Relu (Conv2D, index:6): [[1L, 3L, 3L, 256L]]
cnn_model/d_net_features/Relu (FullyConnected, index:7): [[1L, 1L, 1L, 384L]]
cnn_model/flatten_1/Shape (Shape, index:8): [[4L]]
cnn_model/flatten_1/strided_slice (StridedSlice, index:9): [[]]
cnn_model/flatten_1/Reshape/shape (Stack, index:10): [[2L]]
cnn_model/flatten_1/Reshape (Reshape, index:11): [[1L, 384L]]
cnn_model/lm_dense/MatMul (MatMul, index:12): [[1L, 64L]]
cnn_model/lm_dense/BiasAdd (BiasAdd, index:13): [[1L, 64L]]
cnn_model/lm_activation/Relu (Activation, index:14): [[1L, 64L]]
cnn_model/lm_output/MatMul (MatMul, index:15): [[1L, 86L]]
cnn_model/lm_output/BiasAdd (BiasAdd, index:16): [[1L, 86L]]
reshape/Shape (Shape, index:17): [[2L]]
reshape/strided_slice (StridedSlice, index:18): [[]]
reshape/Reshape/shape (Stack, index:19): [[4L]]
**reshape/Reshape (Reshape, index:20): [[1L, 1L, 1L, 86L]]**
cnn_model/lm3d_dense/MatMul (MatMul, index:21): [[1L, 128L]]
cnn_model/lm3d_dense/BiasAdd (BiasAdd, index:22): [[1L, 128L]]
cnn_model/lm3d_activation/Relu (Activation, index:23): [[1L, 128L]]
cnn_model/lm3d_output/MatMul (MatMul, index:24): [[1L, 129L]]
cnn_model/lm3d_output/BiasAdd (BiasAdd, index:25): [[1L, 129L]]
reshape_1/Shape (Shape, index:26): [[2L]]
reshape_1/strided_slice (StridedSlice, index:27): [[]]
reshape_1/Reshape/shape (Stack, index:28): [[4L]]
**reshape_1/Reshape (Reshape, index:29): [[1L, 1L, 1L, 129L]]**
cnn_model/pose_dense/MatMul (MatMul, index:30): [[1L, 64L]]
cnn_model/pose_dense/BiasAdd (BiasAdd, index:31): [[1L, 64L]]
cnn_model/pose_activation/Relu (Activation, index:32): [[1L, 64L]]
cnn_model/pose_output/MatMul (MatMul, index:33): [[1L, 3L]]
cnn_model/pose_output/BiasAdd (BiasAdd, index:34): [[1L, 3L]]
reshape_2/Shape (Shape, index:35): [[2L]]
reshape_2/strided_slice (StridedSlice, index:36): [[]]
reshape_2/Reshape/shape (Stack, index:37): [[4L]]
**reshape_2/Reshape (Reshape, index:38): [[1L, 1L, 1L, 3L]]**
**concatenate/concat (Concat, index:39): [[1L, 1L, 1L, 218L]]**
dnet_output/MaxPool


```

On the android device I have a crash

05-24 07:43:57.713  2179  2179 F DEBUG   : ABI: 'arm64'
05-24 07:43:57.713  2179  2179 F DEBUG   : 
05-24 07:43:57.713  2179  2179 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-24 07:43:57.719  2179  2179 F DEBUG   : Abort message: 'concat.cc:93 Check failed: input->dim(j) == input0->dim(j) Dimensions of inputs should equal except axis.'
05-24 07:43:57.719  2179  2179 F DEBUG   :     x0   0000000000000000  x1   0000000000000873  x2   0000000000000006  x3   0000000000000008
05-24 07:43:57.719  2179  2179 F DEBUG   :     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000800000
05-24 07:43:57.719  2179  2179 F DEBUG   :     x8   0000000000000083  x9   0000000010000000  x10  0000007e74906f70  x11  0000000000000001
05-24 07:43:57.719  2179  2179 F DEBUG   :     x12  0000000000000002  x13  0000000000000002  x14  ffffffffffffffff  x15  0000325611aa4d04
05-24 07:43:57.719  2179  2179 F DEBUG   :     x16  000000562e72cfa8  x17  0000007f0b3b352c  x18  000000000000000c  x19  0000000000000862
05-24 07:43:57.720  2179  2179 F DEBUG   :     x20  0000000000000873  x21  0000000000000083  x22  0000007e69a75968  x23  000000000000000a
05-24 07:43:57.720  2179  2179 F DEBUG   :     x24  0000007e74906fc0  x25  0000007e74906fc0  x26  0000007e72122b38  x27  0000007e7490a588
05-24 07:43:57.720  2179  2179 F DEBUG   :     x28  0000007e72122cd8  x29  0000007e74906fb0  x30  0000007f0b368760
05-24 07:43:57.720  2179  2179 F DEBUG   :     sp   0000007e74906f70  pc   0000007f0b368788  pstate 0000000060000000
05-24 07:43:57.730  2179  2179 F DEBUG   :
05-24 07:43:57.730  2179  2179 F DEBUG   : backtrace:
05-24 07:43:57.730  2179  2179 F DEBUG   :     #00 pc 000000000001d788  /system/lib64/libc.so (abort+120)
05-24 07:43:57.730  2179  2179 F DEBUG   :     #01 pc 0000000000173580  /data/app/xxxxx==/lib/arm64/libmace.so (mace::logging::LogMessage::GenerateLogMessage()+848)

Please advise how to resolve it,
Thanks

**Comment by dimitryn** [comment]
![image](https://user-images.githubusercontent.com/36672340/60768562-fc1cda80-a0cd-11e9-9029-67ce99138521.png)

**Comment by lydoc** [comment]
Is it convenient for you to share this model and we can reproduce this issue?

**Comment by dimitryn** [comment]
https://drive.google.com/file/d/1qycskvcM579kAHPcupKc5wrvTrNhxkKw/view?usp=sharing

**Comment by lydoc** [comment]
I have checked your model and the output shape of dnet_output/MaxPool should be 1,1,1,228.
![image](https://user-images.githubusercontent.com/40634350/60855790-aa905f00-a237-11e9-9488-310e2820f394.png)

**Comment by dimitryn** [comment]
sorry , wrong model. updated with correct.
https://drive.google.com/open?id=1zd5BARs0QO8_kpaWWlYd5_7sMMCpLP8p

**Comment by lydoc** [comment]
This model's input shape should be 1,64,64,1. 
![image](https://user-images.githubusercontent.com/40634350/60873055-5356b280-a268-11e9-9dc3-a474233b4344.png)

**Comment by dimitryn** [comment]
ok, let say the input is 1,64,64,1 can you please confirm that concat is working on this model, thanks

**Comment by lydoc** [comment]
Yes, the model can be converted and run correctly. I do not reproduce your issue. which version of mace do you use? Could you try the latest master branch again?

**Comment by dimitryn** [comment]
I will test master

**Comment by dimitryn** [comment]
library convert output file  build with master branch model_graph_format: code model_data_format: code is now x4 times bigger size. I am converting 6 models . before it was ~70MB now it 310MB ?!

**Comment by lydoc** [comment]
Which two versions do you compare?

**Comment by dimitryn** [comment]
let's move to email, dimitry.nozik@intel.com

**Comment by dimitryn** [comment]
[mace_pull.txt](https://github.com/XiaoMi/mace/files/3372501/mace_pull.txt)
it's my pull request

**Comment by dimitryn** [comment]
concat working find on master
