### ISSUE TITLE
Hexagon DSP 编译nnlib后，运行生成的graph_app遇到的相关问题。

### ISSUE THREAD

**Issue by fearollchan** [XiaoMi/mace#484]
### System information
- **OS Platform and Distribution :Window 10
- **NDK version :r14b
- **Python version: 2.7 
    各位好！我最近初学Hexagon DSP, 在SDK中编译后nnlib后运行graph_app出现了run failed的问题。因为mace也是使用这个nnlib所以想要请教大家。
    先简要说明设备情况，手机是 IQOO （SDM855,该手机暂时不支持ROOT）。我在这个#Issues中看了各位的很多回答，比如 #198  #318 (以及[https://mace.readthedocs.io/en/latest/faq.html#why-is-mace-not-working-on-dsp](url)文档)。就涉及到ROOT和secure boot的一些权限。
 在SDM855及其以上，高通加入了Unsign PD 的方法（在调用RPC前的libcalculator_stub.c文件中加入一段官方提供的代码）使得CPU可以卸载未签名的.so文件到CDSP上执行，然后我使用该方法执行成功calculator这个例子（版本新增的Support for Signature-free compute processing特性）,不然也是提示签名文件的问题。类似的，我利用该方法对编译后的libhexagon_nn_stub.c进行处理，之后执行graph_app命令行，以及结果如下所示
`命令行：PD1824:/data/local/tmp/nntest $ ./graph_app --width 299 --height 299 --depth 3 --elementsize 1 --perfdump 1 /data/local/tmp/nntest/panda_299x299.dat`
`结果：return value from dspCV_initQ6() : 0
   node 66122 success
   node 66304 success
   node 66637 success
   Init graph done.
   Prepare f04390 success!
   hexagon/src/prepare.c:4276:WARN: ARCH-MISMATCH (compiled for v60 != actual v18)
   nn @ f04390: id=0x0 debug_level=0
   node @ f3bdf0: id=0x1024a type=0x0(INPUT) n_inputs=0 n_outputs=1 padding=0(NA)
   node @ f3bf40: id=0x10300 type=0x2(Nop) n_inputs=1 n_outputs=1 padding=0(NA)
   node @ f3c0d0: id=0x1044d type=0x1(OUTPUT) n_inputs=1 n_outputs=0 padding=0(NA)
   3 nodes total.
   11
   Using </data/local/tmp/nntest/panda_299x299.dat>
  filesize=268203 elementsize=1 height=299 width=299 depth=3
  Run!
  execute got err: -1
  output size=4096
  Rank,Softmax,index,string
  0,0.000000,1023,OVERFLOW!
  1,0.000000,1,kit fox
  2,0.000000,2,English setter
  3,0.000000,3,Siberian husky
  4,0.000000,4,Australian terrier
  run failed: -1`
  查看log如下：
`
--------- beginning of main
07-02 21:25:50.814   917   973 E ThermalEngine: vivo_thermal_parameter_config :VivoThermal:read type:1  buf: 1
07-02 21:25:50.814   917   973 E ThermalEngine:
07-02 21:25:51.739  2723  5644 I RMS-Reclaim: available=3137116KB, current watermark=1331200KB, last watermark=1331200KB, current stopline=800, last stopline=1000
07-02 21:25:51.739  2723  5644 I RMS-Reclaim: Reclaiming took : 1ms
07-02 21:25:53.529  2336  3083 D Settings/BW: ReadCodeTask:mStringNotifyCode: 0
07-02 21:25:53.529  2336  3083 D Settings/BW: ReadCodeTask:mNotifyCode: 0
07-02 21:25:53.665 23650 23650 V ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1724: Successfully opened fastrpc_shell_unsigned_3
07-02 21:25:53.687 23650 23650 V ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1870: Successfully created user PD on domain 3 (attrs 0x8)
07-02 21:25:53.713 23650 23650 V ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1006: remote_handle_open: Successfully opened handle 0xed2660 for hexagon_nn on domain 3
07-02 21:25:53.728 23650 23650 V ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1006: remote_handle_open: Successfully opened handle 0xed2c30 for dspCV on domain 3
07-02 21:25:53.768 23650 23650 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0xffffffff: remote_handle_invoke failed for handle 0xed2660, method 12 on domain 3 (sc 0xc020200)
07-02 21:25:53.768 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0xffffffff: remote_handle_invoke failed for handle 0x3, method 4 on domain 3 (sc 0x4020200)
07-02 21:25:53.768 23650 23651 E ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/listener_android.c:244:listener protocol failure ffffffff
07-02 21:25:53.769 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x27: remote_handle_invoke failed for handle 0x3, method 4 on domain 3 (sc 0x4020200)
07-02 21:25:53.769 23650 23651 E ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/listener_android.c:251::error: 39: 0 == (nErr = __QAIC_HEADER(adsp_listener_next2)( ctx, nErr, 0, 0, &ctx, &handle, &sc, inBufs, inBufsLen, &inBufsLenReq))
07-02 21:25:53.769 23650 23651 E ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/listener_android.c:333:Error 0x27: listener2 thread exited
07-02 21:25:53.769 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1925: Error 4b: adsp current process handle failed. domain 3
07-02 21:25:53.769 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x27: remote_handle_invoke failed for handle 0x0, method 0 on domain 3 (sc 0x20200)
07-02 21:25:53.769 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x2c: remote_handle_invoke failed for handle 0xffffffff, method 1 on domain 3 (sc 0x1000000)
07-02 21:25:53.769 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1925: Error 4b: adsp current process handle failed. domain 3
07-02 21:25:53.769 23650 23650 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x27: remote_handle_invoke failed for handle 0xed2660, method 6 on domain 3 (sc 0x6020100)
07-02 21:25:53.769 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x27: remote_handle_invoke failed for handle 0x0, method 0 on domain 3 (sc 0x20200)
07-02 21:25:53.769 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x2c: remote_handle_invoke failed for handle 0xffffffff, method 1 on domain 3 (sc 0x1000000)
07-02 21:25:53.770 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1925: Error 4b: adsp current process handle failed. domain 3
07-02 21:25:53.770 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x27: remote_handle_invoke failed for handle 0x0, method 0 on domain 3 (sc 0x20200)
07-02 21:25:53.770 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x2c: remote_handle_invoke failed for handle 0xffffffff, method 1 on domain 3 (sc 0x1000000)
07-02 21:25:53.770 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1925: Error 4b: adsp current process handle failed. domain 3
07-02 21:25:53.770 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x27: remote_handle_invoke failed for handle 0x0, method 0 on domain 3 (sc 0x20200)
07-02 21:25:53.770 23650 23651 D ./graph_app: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:925: Error 0x2c: remote_handle_invoke failed for handle 0xffffffff, method 1 on domain 3 (sc 0x1000000)`
--------------------------------------------------------------------------------------------------
对此我想请教下大家，
1)是否这个Unsigned PD方法只适用于纯计算呢，所以graph_app就不适用。
2)执行在DSP上执行nnlib是否只有满足ROOT，签名，Secure BOOT条件下才可以呢？（或者可能有其他方法，权限问题我暂时不好搞定）

问题有点长！Greatly Thanks in advanced !

**Comment by lu229** [comment]
问题1：从日志看，Unsigned PD方式是成功的，但是远程方法调用失败了：
remote_handle_invoke failed for handle 0xed2660, method 12 on domain 3 (sc 0xc020200)
从以往经验看，应该是function在dsp上运行出错了，具体什么错误当前日志无法判断
问题2：传统的方式，确实是的，可参见：[Why is MACE not working on DSP?](https://mace.readthedocs.io/en/latest/faq.html#why-is-mace-not-working-on-dsp)

**Comment by fearollchan** [comment]
> 问题1：从日志看，Unsigned PD方式是成功的，但是远程方法调用失败了：
> remote_handle_invoke failed for handle 0xed2660, method 12 on domain 3 (sc 0xc020200)
> 从以往经验看，应该是function在dsp上运行出错了，具体什么错误当前日志无法判断
> 问题2：传统的方式，确实是的，可参见：[Why is MACE not working on DSP?](https://mace.readthedocs.io/en/latest/faq.html#why-is-mace-not-working-on-dsp)

谢谢您的解答！由于官方的诊断信息工具mini-dm的驱动安装失败，暂时看不到更多的诊断信息。

**Comment by apivovarov** [comment]
Related to https://github.com/XiaoMi/mace/issues/581
