### ISSUE TITLE
can not set dynamic symbols to debug mode using CMakeLists.txt

### ISSUE THREAD

**Issue by peyer** [XiaoMi/mace#486]
### Describe the problem
I just compiled dynamic symbols with cmake option (-DCMAKE_BUILE_TYPE=Debug), but when I used readelf to check the debug info of dynamic symbols, it got none!
How to set dynamic symbols to debug mode using CMakeLists.txt ?

**Comment by lu229** [comment]
@peyer Please turn off the MACE_ENABLE_OPT_SIZE switch in mace/CMakeLists.txt, and try again.
option(MACE_ENABLE_OPT_SIZE    "whether to build with optimized binary size" OFF)

**Comment by peyer** [comment]
@lu229 Yes, it worked, thansk!
