### ISSUE TITLE
convert error

### ISSUE THREAD

**Issue by VirginianBlue** [XiaoMi/mace#487]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Linux Ubuntu 18.04
- **NDK version(e.g., 15c)**:  
16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 
7.4.0
- **MACE version (Use the command: git describe --long --tags)**: 
latest
- **Python version(2.7)**:  
2.7
- **Bazel version (e.g., 0.13.0)**: 
0.13.0

### Model deploy file (*.yml)
```yaml
library_name: model
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  model:
    platform: onnx
    model_file_path: /home/virginian/virginian/mace/model/model_opt.onnx
    model_sha256_checksum: 8ec219eb2d10d2c94a87d406c0f8fc5698d0e39adeca737634670b7dccded2e4
    subgraphs:
      - input_tensors: data
        output_tensors: output
        input_shapes: 1,1,64,64
        output_shapes: 1,3755
        backend: pytorch
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 1
```

### Describe the problem
convert failed. And how to know the input_tensors name and outpu_ tensors name. The onnx model is converted from pytorch. There are no node names in pytorch.  I suspect this error is about the input_tensors name, it's seems like the name "data" doesn't match the real input[0] name.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.215s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
('onnx model IR version: ', 3L)
('constains ops domain: ', u'', 'version:', 9L)
Fold activation: [u'67'](Conv2D)
Fold activation: [u'71'](Conv2D)
Fold activation: [u'74'](Conv2D)
Fold activation: [u'81'](Conv2D)
Fold activation: [u'88'](Conv2D)
Traceback (most recent call last):
  File "/home/virginian/virginian/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 422, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/virginian/virginian/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 231, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/home/virginian/virginian/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 137, in run
    changed = transformer()
  File "/home/virginian/virginian/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 982, in transform_global_conv_to_fc
    producer = self._producer[op.input[0]]
KeyError: u'0'
Traceback (most recent call last):
  File "tools/converter.py", line 1363, in <module>
    flags.func(flags)
  File "tools/converter.py", line 866, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 794, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/virginian/virginian/mace/mace/tools/sh_commands.py", line 553, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=onnx --model_file=/home/virginian/virginian/mace/model/model_opt.onnx --weight_file= --model_checksum=8ec219eb2d10d2c94a87d406c0f8fc5698d0e39adeca737634670b7dccded2e4 --weight_checksum= --input_node=data --input_data_types=float32 --input_data_formats=NHWC --output_node=output --output_data_types=float32 --output_data_formats=NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=model --input_shape=1,1,64,64 --input_range= --output_shape=1,3755 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_large_weights=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=1 --output_dir=mace/codegen/models/model --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:


```

### Additional context
In pytorch code, the input_shape is [1,1,64,64] and output_shape is [1,3755]. And I use torch.onnx._export to convert pytroch model to onnx model.

**Comment by TonyMou** [comment]
@VirginianBlue could you provide a test model for this issue?

**Comment by VirginianBlue** [comment]
> @VirginianBlue could you provide a test model for this issue?


[model_opt.zip](https://github.com/XiaoMi/mace/files/3380152/model_opt.zip)

**Comment by TonyMou** [comment]
![Screenshot from 2019-07-11 14-56-24](https://user-images.githubusercontent.com/10102271/61028780-2206ef80-a3ec-11e9-99b6-6bea4bc6e3b9.png)

Modify the 'input_tensors' and 'output_tensors' in your .yml file.

```
subgraphs:
      - input_tensors: 0
        output_tensors: 107
        input_shapes: 1,1,64,64
        output_shapes: 1,3755
```

**Comment by VirginianBlue** [comment]
> ![Screenshot from 2019-07-11 14-56-24](https://user-images.githubusercontent.com/10102271/61028780-2206ef80-a3ec-11e9-99b6-6bea4bc6e3b9.png)
> 
> Modify the 'input_tensors' and 'output_tensors' in your .yml file.
> 
> ```
> subgraphs:
>       - input_tensors: 0
>         output_tensors: 107
>         input_shapes: 1,1,64,64
>         output_shapes: 1,3755
> ```

Thank you for that. But how can I get such this thing if I have to use another model file? That really makes me  confused.

**Comment by TonyMou** [comment]
https://lutzroeder.github.io/netron/

**Comment by VirginianBlue** [comment]
> https://lutzroeder.github.io/netron/

Thank you!  It's really helpful. And my problem has been solved.
