### ISSUE TITLE
Mace execution performance vs tflite on arm cpu

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#488]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Target platrform Android 8.1 
- **NDK version(e.g., 15c)**:
NDK 17
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
master
- **Pyton version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
0.13

Hi, I am running during my flow on every frame several different models converted from tensorflow, on RK3328 with Android 8.1.
I using one yml file and code/code conversion for all models.
Models that run > 100ms are stable between frames. a small change in performance.
Small models < 20ms, are not stable. I have or x2 faster or x2 x5 x6  slower. 
With TFlite I don't experience such behaviour.
Example log performance :

![image](https://user-images.githubusercontent.com/36672340/61028611-c0ca2680-a3c1-11e9-9961-83a9080be522.png)

using/unusing  SetCPUThreadPolicy have no effect on stability.
Maybe it related to model architecture ?!

Example model:
https://drive.google.com/open?id=1zd5BARs0QO8_kpaWWlYd5_7sMMCpLP8p

**Comment by lydoc** [comment]
We do not have RK3328 so that maybe we cannot reproduce this issue. Could you use --omp_num_threads and --cpu_affinity_policy and try again? You can refer to this doc. https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#useful-commands

**Comment by dimitryn** [comment]
is not the same if I use MaceStatus SetCPUThreadPolicy?

**Comment by lydoc** [comment]
It should be the same.... But I mean you can run these models by python tools to prevent other potential problems.
