### ISSUE TITLE
OpenCL allocates twice as much as expected 

### ISSUE THREAD

**Issue by herbakamil** [XiaoMi/mace#490]
https://github.com/XiaoMi/mace/blob/3e4dc0df353327c1bf6a916740c3bf3d9c0272f0/mace/core/runtime/opencl/opencl_allocator.cc#L88

I've described it [here](https://stackoverflow.com/questions/56990325/new-climage2d-allocates-twice-as-much-as-expected) hoping someone will explain me but no answer.

I would expect that with data type half and CL_RGBA we'll need 8 bytes per pixel. But adb shell dumpsys meminfo shows that we need around 16. Why is it so? Is it related to some setting chosen in MACE?

**Comment by liyinhgqw** [comment]
It seems like `dumpsys` double counts gfx memory usage for some devices. You may use` top` to check if the total memory usage is consistent with what `dumpsys` shows.

**Comment by herbakamil** [comment]
These are statistics during peak of my model run (first 3 from top, rest from dumpsys)

VIRT | RES | SHR | Native heap | Graphics
-- | -- | -- | -- | --
439 | 335 | 322 | 11 | 650

or after some optimizations:

VIRT | RES | SHR | Native heap | Graphics
-- | -- | -- | -- | --
404 | 290 | 275 | 13 | 532

I agree that top shows something that matches my calculations for the memory requirements more but I'd expect that dumpsys is more accurate than top. I've tested memory on different phones and it's quite often that the memory is more than expected. On some other phone graphics and rss is around 550 which matches assumption that we need 16 bytes per image pixel - not 2

Can you provide some sources argumenting to use top instead of dumpsys? When I search over the web people usually suggest the opposite.

**Comment by liyinhgqw** [comment]
I found this link https://groups.google.com/a/chromium.org/forum/#!topic/graphics-dev/5VnWUyNW0Fc
```
(Some devices report another category called "Graphics".  You should ignore that one if you see it, it double-counts a part of GL mtrack.)
```
