### ISSUE TITLE
量化模型mobilenet v1运行错误

### ISSUE THREAD

**Issue by WeixiangXu** [XiaoMi/mace#494]
follow the doc: https://mace.readthedocs.io/en/latest/user_guide/quantization_usage.html, 经过第4步之后得到量化的模型mobilenetv1.pb .data
在板子上运行时：
 Key not registered: Reshape0T_DT_UINT8

**Comment by yejw5** [comment]
用的哪个模型，是MACE最新的代码吗？

**Comment by WeixiangXu** [comment]
> 用的哪个模型，是MACE最新的代码吗？
- 模型：https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v1/mobilenet-v1.yml
- MACE version: v0.11.0-rc0-0-g2d650b6

**Comment by yejw5** [comment]
如果使用master的代码可以运行吗？

**Comment by maminglang1991** [comment]
我这边也遇到类似的Key not registered: BufferTransform2T_DT_INT32，
请问你解决了么？

**Comment by WeixiangXu** [comment]
没有解决

**Comment by lee-bin** [comment]
https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v1/mobilenet-v1-quantize-friendly.yml
这个模型适合Post training quantization，可以用master代码尝试一下 @WeixiangXu

**Comment by fivenick** [comment]
> https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v1/mobilenet-v1-quantize-friendly.yml
> 这个模型适合Post training quantization，可以用master代码尝试一下 @WeixiangXu

我用自己的模型，转换没问题，但在手机上跑也会出现“Key not registered: Splice0T_DT_UINT8, op type is: Splice”，不知该怎么解决。
Splice操作mace是支持的，也看到了源码，但量化后怎么就出现了没注册的类型呢？
