### ISSUE TITLE
BufferTransform2T_DT_INT32

### ISSUE THREAD

**Issue by maminglang1991** [XiaoMi/mace#500]

**Comment by maminglang1991** [comment]
: net_def_adapter.cc:348 Op vespcn_bicu_sr/conv2d_transpose/Shape fall back to CPU
07-29 17:28:02.143 28212 28247 I MACE    : net_def_adapter.cc:348 Op vespcn_bicu_sr/conv2d_transpose/strided_slice fall back to CPU
07-29 17:28:02.143 28212 28247 I MACE    : net_def_adapter.cc:348 Op vespcn_bicu_sr/conv2d_transpose/strided_slice_1 fall back to CPU
07-29 17:28:02.143 28212 28247 I MACE    : net_def_adapter.cc:348 Op vespcn_bicu_sr/conv2d_transpose/mul fall back to CPU
07-29 17:28:02.143 28212 28247 I MACE    : net_def_adapter.cc:348 Op vespcn_bicu_sr/conv2d_transpose/strided_slice_2 fall back to CPU
07-29 17:28:02.143 28212 28247 I MACE    : net_def_adapter.cc:348 Op vespcn_bicu_sr/conv2d_transpose/mul_1 fall back to CPU
07-29 17:28:02.143 28212 28247 I MACE    : net_def_adapter.cc:348 Op vespcn_bicu_sr/conv2d_transpose/stack fall back to CPU
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 BufferTransform2T_DT_FLOAT
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 Shape0T_DT_FLOAT
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 StridedSlice0T_DT_INT32
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 StridedSlice0T_DT_INT32
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 ScalarMath0T_DT_INT32
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 StridedSlice0T_DT_INT32
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 ScalarMath0T_DT_INT32
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 Stack0T_DT_INT32
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 BufferTransform2T_DT_FLOAT
07-29 17:28:02.145 28212 28247 I MACE    : operator.cc:324 BufferTransform2T_DT_INT32
07-29 17:28:02.145 28212 28247 F MACE    : operator.cc:326 Key not registered: BufferTransform2T_DT_INT32

**Comment by maminglang1991** [comment]
tensorflow 模型，未做量化
library_name: vespcn
target_abis: [arm64-v7a]
embed_model_data: 1
model_graph_format: code
model_data_format: code
models:
  espcn:
    platform: tensorflow
    model_file_path: ./frozen_model.pb
    model_sha256_checksum: 4cc8325685a76521c65e762a4b1bc4a21ba444c63ace29191cb024548d9819a3
    subgraphs:
      - input_tensors:
          - images_input
        input_shapes:
          - 1,960,960,3
        output_tensors:
          - espcn_drrn_sr/Relu_4
        output_shapes:
          - 1,3840,3840,1
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

**Comment by lu229** [comment]
@maminglang1991 这个问题不是很好解决，是否方便将你的模型给我们测试一下呢？
