### ISSUE TITLE
slow performance on RK3399

### ISSUE THREAD

**Issue by agodlin** [XiaoMi/mace#501]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Android 8.1
- **NDK version(e.g., 15c)**:
NDK 20
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
master
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
0.13

### Model deploy file (*.yml)
My model is mobilenet_v2.

### Describe the problem
processors on the board. 
Dual-core ARM Cortex-A72 MPCore processor and Quad-core ARM Cortex-A53 MPCor

pb model run around 70ms and converted Model to Mace 
run around 600 ms when setting AFFINITY_BIG_ONLY
run around 1000 ms when setting AFFINITY_LITTLE_ONLY 
run around 2000 ms when setting AFFINITY_HIGH_PERFORMANCE 

*This was not an Issue when using RK3328 which have just 4 regular cores. 

when i changed AFFINITY_LITTLE_ONLY the time was 1000ms
and if using AFFINITY_HIGH_PERFORMANCE the 

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
We have also noticed this problem recently, for different machines have different core numbers、frequencies and schedule strategies, resulting in such problems on few machines.  we will optimize this strategy in the near future. For the time being, you can use AFFINITY_BIG_ONLY.

**Comment by agodlin** [comment]
@lu229 the problem is AFFINITY_BIG_ONLY give very poor results. using tensorflow or tensorflow lite i am getting much better results as i mentioned (600 ms with Mace and 70ms with tensorflow)

strange that on RK3328 i am getting better performance with Mace over tensroflow. 

i guess it is due to core difference, RK3328 have only 4 "big cores" while RK3399 have 2 "big core" and 4 "small cores". i was expecting Mace to utilize better all cores. 

any time frame on when this will be optimized ?

**Comment by lu229** [comment]
@agodlin What is your os on rk3399? we have a rk3399 device with arm linux os, on which I run the mobilenet_v2 and get the time 86ms. 
MACE diabled schedule strategy on arm linux os, Is your os Android?

**Comment by agodlin** [comment]
@lu229 yes i am using Android 8.1

**Comment by lu229** [comment]
@agodlin It seems that rk3399 runs very slowly after setting the scheduling strategy, which is why we previously disabled the scheduling strategy on Linux OS of rk3399. 
You can disable the scheduling strategy on Android Os of rk3399 by overridding the SchedSetAffinity method in the /mace/mace/port/android/env.cc,  just as we did in the /mace/mace/port/linux/env.cc
