### ISSUE TITLE
Hi, default opencl precision is fp16 in benchmark docs?

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#504]
Hi,

I did benchmark as [doc about benchmark](https://mace.readthedocs.io/en/latest/user_guide/benchmark.html), but not sure whether  fp16 is the default precision.

Thanks  in advance.

**Comment by lu229** [comment]
The data type used for specified runtime. [fp16_fp32, fp32_fp32] for GPU, default is fp16_fp32, [fp32] for CPU and [uint8] for DSP.
Please reference: https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#deployment-file

**Comment by ysh329** [comment]
@lu229 fp16 on gpu, fp32 on cpu?

**Comment by lu229** [comment]
@ysh329 no,gpu model is stored using fp16, and  computation using fp32 on gpu and cpu.

**Comment by ysh329** [comment]
eh, I found a comment as below:


> 默认就是用 fp16, 可以参照 https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html 设置

_Originally posted by @liyinhgqw in https://github.com/XiaoMi/mace/issues/404#issuecomment-475142766_

@liyinhgqw

**Comment by lu229** [comment]
@ysh329 What he means was that the default storage is fp16.

**Comment by ysh329** [comment]
thanks lu 👍
