### ISSUE TITLE
Hi, why does mace use default fp16 type in arm

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#505]
Hi, I found mace used 3rd-party lib [half: Half-precision floating-point library](http://half.sourceforge.net/) on cpu.

Why does mace use arm fp16, ref:
1. [Using the GNU Compiler Collection (GCC): Half-Precision](
https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html)  
2. [Using the GNU Compiler Collection (GCC): ARM Options](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html). 

![image](https://user-images.githubusercontent.com/7320657/62525575-3c58af80-b86a-11e9-90bd-9882336dc855.png)

THanks in advance.

**Comment by lu229** [comment]
@ysh329 It is used for GPU computation. Please reference: https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#deployment-file

**Comment by ysh329** [comment]
eh, I found gpu support half type. Does this library used for fp16 model storage?

**Comment by lu229** [comment]
yes, it is mainly used for fp16 model storage.
