### ISSUE TITLE
APK运行DSP提示libhexagon_nn_skel.so找不到的解决方法

### ISSUE THREAD

**Issue by CrazyKing5023** [XiaoMi/mace#506]
问题：
vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:Error 45 :fopen fail libhexagon_nn_skel.so no such file 
解决方法：
1、如果是二进制可执行程序，模型运行在DSP硬件平台，需要设置DSP库的环境变量，如下：
 export ADSP_LIBRARY_PATH="<path_to_dsp_skel>;/system/lib/rfsa/adsp;/system/vendor/lib/rfsa/adsp;/dsp"

2、如果是把动态库集成到APK中，模型运行在DSP硬件平台，需要设置DSP库的环境变量，方法如下：
首先在JAVA应用层获取APP安装路径的位置：
application.getApplicationInfo().nativeLibraryDir
然后通过下面的方法，在JAVA初始化的时候设置环境变量
 bool SetAdspLibraryPath(std::string nativeLibPath) {
    std::stringstream path;
    path << nativeLibPath << ";/system/lib/rfsa/adsp;/system/vendor/lib/rfsa/adsp;/dsp";

    return setenv("ADSP_LIBRARY_PATH", path.str().c_str(), 1 /*override*/) == 0;
}

**Comment by lu229** [comment]
@CrazyKing5023  你的问题是?

**Comment by CrazyKing5023** [comment]
问题已经解决，使用上面的解决方法，方便他人

**Comment by Tianpapa** [comment]
谢谢！帮大忙了！
