### ISSUE TITLE
Mac Android example gradlew build

### ISSUE THREAD

**Issue by hena1-wb** [XiaoMi/mace#51]
Packaging Done!

-------------------------------------------------------------
                           Library
-------------------------------------------------------------
|      key       |                  value                   |
=============================================================
| library package| builds/mobilenet/libmace_mobilenet.tar.gz|
-------------------------------------------------------------

> Configure project :app
Observed package id 'platforms;android-26' in inconsistent location '/Users/xxx/Library/Android/sdk/platforms/android-8.0.0' (Expected '/Users/xxx/Library/Android/sdk/platforms/android-26')
Already observed package id 'platforms;android-26' in '/Users/xxx/Library/Android/sdk/platforms/android-26'. Skipping duplicate at '/Users/xxx/Library/Android/sdk/platforms/android-8.0.0'

> Task :app:compileAppDebugJavaWithJavac
注: /Users/xxx/Downloads/mace/mace/examples/android/app/src/main/java/com/xiaomi/mace/demo/camera/CameraApiLessM.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

> Task :macelibrary:generateJsonModelDebug
-- Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- FILE URL = /Users/xxx/Downloads/mace/mace/examples/android/macelibrary
-- FILE URL =
CMake Error at CMakeLists.txt:28 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
-- Configuring incomplete, errors occurred!
See also "/Users/xxx/Downloads/mace/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':macelibrary:generateJsonModelDebug'.
> Build command failed.
  Error while executing process /Users/xxx/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/xxx/Downloads/mace/mace/examples/android/macelibrary -B/Users/xxx/Downloads/mace/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/xxx/Downloads/mace/mace/examples/android/macelibrary/build/intermediates/cmake/debug/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk-bundle -DCMAKE_CXX_FLAGS=-std=c++14 -fopenmp -DCMAKE_TOOLCHAIN_FILE=/Users/xxx/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/xxx/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja}
  -- Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
  -- Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
  -- Check for working CXX compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- FILE URL = /Users/xxx/Downloads/mace/mace/examples/android/macelibrary
  -- FILE URL =
  CMake Error at CMakeLists.txt:28 (set_target_properties):
    set_target_properties called with incorrect number of arguments.

  -- Configuring incomplete, errors occurred!
  See also "/Users/xxx/Downloads/mace/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
38 actionable tasks: 35 executed, 3 up-to-date

**Comment by lee-bin** [comment]
请确认是否有mace的静态库生成
`mace/examples/android/macelibrary/src/main/cpp/lib/arm64-v8a/libmace_mobilenet.a`
另外是不是采用build.sh构建的呢？
```sh
cd mace/exampls/android
./build.sh
```

**Comment by hena1-wb** [comment]
@lee-bin 有静态库生成 
mace/examples/android/macelibrary/src/main/cpp/lib/arm64-v8a/libmace_mobilenet.a   197.3Mb
是采用build.sh构建的

生成目录如下：
├── include
│   └── mace
│   └── public
│   ├── mace_engine_factory.h
│   ├── mace.h
│   ├── mace_runtime.h
│   ├── mobilenet_v1.h
│   └── mobilenet_v2.h
├── lib
│   └── arm64-v8a
│   └── libmace_mobilenet.a
├── libmace_mobilenet.tar.gz
├── model
└── _tmp
├── arm64-v8a_e2a4c8972fefd2c3d18824a4b1c58ed9
│   ├── benchmark_model_static
│   └── example_static
│   └── mace_run_static
├── mobilenet_v1
│   └── f330dec17e45a8626cfb225ddce95051
│   ├── general
│      └── arm64-v8a
└── mobilenet_v2
└── d4e627ce1b15ed6f96aefffe315a8dc8
├── general
│   └── arm64-v8a
│   └── model_input_input

**Comment by lee-bin** [comment]
> -- FILE URL = /Users/xxx/Downloads/mace/mace/examples/android/macelibrary
-- FILE URL =
CMake Error at CMakeLists.txt:28 (set_target_properties):

从错误信息看是
[file(GLOB static_file ${CMAKE_SOURCE_DIR}/src/main/cpp/lib/arm64-v8a/*.a)](https://github.com/XiaoMi/mace/blob/3523c9e901dc18c946f25b639d5b02e6045603f3/mace/examples/android/macelibrary/CMakeLists.txt#L17)
没有匹配libmace_mobilenet.a
你可以将CMakeLists.txt中的*.a直接改成libmace_mobilenet.a尝试一下。

**Comment by hena1-wb** [comment]
@lee-bin 试了 还是同样的错误
CMake Error at CMakeLists.txt:28 (set_target_properties):
set_target_properties called with incorrect number of arguments.
28行是 set_target_properties(mace_mobile_lib PROPERTIES IMPORTED_LOCATION ${tmpstr})

**Comment by lee-bin** [comment]
已修复，请见 0e5f81a0ff1bde0a52593c4970582575e6777387
