### ISSUE TITLE
docker android demo build error

### ISSUE THREAD

**Issue by tinalazy** [XiaoMi/mace#513]
Run ./build.sh dynamic in docker.

Get Error
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1148, in <module>
    flags.func(flags)
  File "tools/converter.py", line 847, in convert_func
    build_model_lib(configs, flags.address_sanitizer, flags.debug_mode)
  File "tools/converter.py", line 744, in build_model_lib
    debug_mode=debug_mode
  File "/home/mace/tools/sh_commands.py", line 326, in bazel_build
    *bazel_args)
  File "/root/.pyenv/versions/2.7.12/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_
REPOSITORY                                              TAG                 IMAGE ID            CREATED             SIZE
registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev   latest              7a6f93037892        2 months ago        20.7GB

env
ANDROID_NDK_VERSION=r19c 

all file keep same as git hub & docker

**Comment by yejw5** [comment]
Can you show your host PC environments

**Comment by PuAnysh** [comment]
some suggestion:
1.increase swap space
2.change ANDROID_NDK_VERSION from r19c to r16b

**Comment by tinalazy** [comment]
sry 4 that .
I USED DOCKER IMGAES TO DO THIS. I KNOWN WHAT'S GOING ON . BUT IT'S STILL A BUG.

**Comment by lu229** [comment]
The logs is too few and can not find the problem, please provide more logs and show your host PC environments.
