### ISSUE TITLE
How to use an jpg as input to run the model?

### ISSUE THREAD

**Issue by VirginianBlue** [XiaoMi/mace#515]
My code:

> std::string img_input= path_img;
std::ifstream in_file(img_input, std::ios::in | std::ios::binary);
in_file.read(reinterpret_cast<char *>(buffer_in.get()),input_size * sizeof(float));
in_file.close();
inputs["input"] = mace::MaceTensor(input_shapes, buffer_in);
engine->Run(inputs, &outputs);

It will crash when "engine->Run(inputs, &outputs)"
path_img is path of "xxx.jpg"
All code by cpp

**Comment by lu229** [comment]
@VirginianBlue You need read file and get the tensor data, perhaps you can reference: [imagenet_preprocessor.cc](https://github.com/XiaoMi/mobile-ai-bench/blob/master/aibench/benchmark/imagenet/imagenet_preprocessor.cc)

**Comment by VirginianBlue** [comment]
> @VirginianBlue You need read file and get the tensor data, perhaps you can reference: [imagenet_preprocessor.cc](https://github.com/XiaoMi/mobile-ai-bench/blob/master/aibench/benchmark/imagenet/imagenet_preprocessor.cc)

An error occurred when I used cv::dnn::blobFromImage.
`error:no member named 'dnn' in namespace 'cv'` 
My opencv is opencv-3.4.3-android-sdk.

**Comment by lu229** [comment]
@VirginianBlue perhaps you need compile opencv version which include dnn module, while you can use any library (such as opencv) or API to read the image file and construct the tensor data.
