### ISSUE TITLE
 build library and test tools error

### ISSUE THREAD

**Issue by raninbowlalala** [XiaoMi/mace#52]
Hi, I downloaded  deeplab-v3-plus-mobilenet-v2.yml from https://github.com/XiaoMi/mace-models. I want to test the model runtime, but when I run the command like below: 
`python tools/converter.py build --config=mace/models/deeplab-v3-plus/deeplab-v3-plus-mobilenet-v2.yml`
I got the error message:

```
-------------------------------------------------
               Common Configuration
-------------------------------------------------
|       key       |            value            |
=================================================
|     library_name| deeplab-v3-plus-mobilenet-v2|
-------------------------------------------------
|      target_abis| ['armeabi-v7a', 'arm64-v8a']|
-------------------------------------------------
|      target_socs|                           []|
-------------------------------------------------
|       build_type|                         code|
-------------------------------------------------
| embed_model_data|                            0|
-------------------------------------------------
|       linkshared|                            0|
-------------------------------------------------
|           Tuning|                         True|
-------------------------------------------------

* Genearte mace engine creator source
Genearte mace engine creator source done!

**************************************************************
          Convert deeplab_v3_plus_mobilenet_v2 model
**************************************************************

Downloading model, please wait ...
Model downloaded successfully.
ERROR: [Model Converter] model file sha256checksum not match
```

Can you help me? Thank you!

**Comment by raninbowlalala** [comment]
@TonyMou No, I didn't

**Comment by TonyMou** [comment]
Use sha256sum path/to/your/model/file to generate the sha256checksum code

**Comment by llhe** [comment]
Please manually download the file and check the checksum using `sha256sum`.

Make sure you local network has no strange proxy settings.

Close this since the file is valid and the everyday CI is passing.

**Comment by raninbowlalala** [comment]
@TonyMou @llhe That works for me. Thank you very much.

**Comment by raninbowlalala** [comment]
@TonyMou  I run "python tools/converter.py build --config=mace/models/deeplab-v3-plus/deeplab-v3-plus-mobilenet-v2.yml" successfully, and I want to run "python tools/converter.py run --config=mace/models/deeplab-v3-plus/deeplab-v3-plus-mobilenet-v2.yml -validate" but no responses. I have already plug a phone and open the developer mode.
