### ISSUE TITLE
rpcmem function calls for dsp?

### ISSUE THREAD

**Issue by tensorbuffer** [XiaoMi/mace#520]
Hello,
This is a general question. 
In Hexagon SDK (APIs_FastRPC.html) there's example to use rpcmem_init(), rpcmem_alloc(). I wonder why these function calls are not used in mace? Is it because there's no buffers needed in mace?
We currently run into memory related error due to "not enough memory in FastRPC Heap to allocate memory for stack allocation and thread creation in the userPD on DSP" (error code 80000402)

A related question, is that I see in core/allocator.h, memalign() is used for hexagon, which is not physically continuous memory. Will that cause problem?

**Comment by lu229** [comment]
@tensorbuffer MACE use hexagon-nn instead of FastRPC directly. we havn't encountered this problem on CDSP, Is your demo running on CDSP?
The second question, I have ever used FastRPC without memalign, I don't think memalign can cause this problem unless you allocated a very big memery.

**Comment by lu229** [comment]
@tensorbuffer yes hexagon-nn also use fastrpc, I means mace used the nnlib's API. perhaps you can reference the [nnlib use in MACE](https://github.com/XiaoMi/mace/tree/master/mace/core/runtime/hexagon)

**Comment by lu229** [comment]
@tensorbuffer I don't know. In theory if use ION to allocate memory, memory is shared by CPU and DSP.  Maybe it is not heap size but other errors cause this problem?
