### ISSUE TITLE
mace for Android on x86-64

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#522]
Hi , Is that possible to build mace to run on Android OS and TARGET_ABI=x86-64 and OpenCL=true?
Thanks.

**Comment by llhe** [comment]
@dimitryn It's possible with x86-64 ABI to run only on GPU, as long as you don't need optimized x86 kernels. However, there may be OpenenCL compatibility issue because we haven't tested this flow.

**Comment by dimitryn** [comment]
thanks
