### ISSUE TITLE
C++ compilation of rule '//mace/codegen:generated_models' 

### ISSUE THREAD

**Issue by yuepingma** [XiaoMi/mace#524]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by zmguahy** [comment]
i have a question like this,too. actually, i've setted the environment variable ANDROID_NDK_HOME and check it right,but it still can't work. Anyone encounter and know this ?
in target '//external:android/crosstool': no such package '@androidndk//': Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME  environment variable must be set.

**Comment by lu229** [comment]
Please fill in the [issue template](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md), otherwise we don't know what's your problem.

**Comment by yejw5** [comment]
@zmguahy You can create an issue and fill with [issue template](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md). The more detailed reproduction steps is helpful for address the source.

@yuepingma If no more updating, we can not analyze the problem. If needed, feel free to reopen this issue.
