### ISSUE TITLE
mace/examples/android 目录下，执行bash文件 . ./build.sh dynamic 报错

### ISSUE THREAD

**Issue by yaopu** [XiaoMi/mace#527]

**Comment by yaopu** [comment]
Loading:
Loading: 0 packages loaded
ERROR: /home/yao/Code/Latest_Code/work_job/Mace/researh_mace/research_mace/WORKSPACE:14:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: Skipping '//mace/proto:mace_py': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 1.363s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by lu229** [comment]
@yaopu As we communicated on QQ, this is due to the higher viersion of bazel, please use the version 0.13.0
