### ISSUE TITLE
opencl计算时导致UI卡顿问题

### ISSUE THREAD

**Issue by 18810579179** [XiaoMi/mace#532]
您好：

问下当使用opencl计算时，会导致UI卡顿， 卡顿直至opencl计算完成。卡顿包括秒表，显示界面等。mace表示有防止卡顿的策略的。（如何解决深度学习模型的推理计算对图形渲染的干扰带来的卡顿问题，小米则采用了离线 Tuning 并自动进行细粒度 Kernel 拆分的形式来解决。）

想问下卡顿是因为opencl计算时单个kernel耗时过大的原因还是opencl整个计算还是过长？还是其他原因

谢谢

**Comment by 18810579179** [comment]
补充下，卡顿时长和opencl所有kernel计算总时长差不多。

**Comment by 18810579179** [comment]
再补充下，将单个kernel拆分不到每个kernel不超过15ms，但是总耗时有3s。还是会卡顿3s左右。是不是可以理解卡顿不是单个kernel耗时过大导致的？

**Comment by yejw5** [comment]
可以先测试GPUPerfHint和GPUPriorityHint设置为较低级别。以及尝试文档里的方案：https://mace.readthedocs.io/en/latest/faq.html?highlight=limit_opencl_kernel_time#why-is-the-ui-getting-poor-responsiveness-when-running-model-with-gpu-runtime

**Comment by 18810579179** [comment]
按照你的步骤试了，GPUPerfHint和GPUPriorityHint设置为较低级别。并且将单个kernel拆分不到每个kernel不超过12ms。卡顿现象很少了，只是偶尔还是会卡顿一下（大约几十ms的量级）。为什么单个kernel已经不超过12ms还是会偶感卡顿？

**Comment by 18810579179** [comment]
按照你的步骤试了，GPUPerfHint和GPUPriorityHint设置为较低级别。并且将单个kernel拆分不到每个kernel不超过12ms。卡顿现象很少了，只是偶尔还是会卡顿一下（大约几十ms的量级）。为什么单个kernel已经不超过12ms还是会偶感卡顿？

plus:使用的是小米手机

**Comment by lu229** [comment]
@18810579179 如QQ群沟通：
如果可以接受降低性能，可以再设一个参数opencl_window_size，可参见上面@yejw5 贴出的链接。
这个问题的根本原因是手机上的GPU硬件对任务调度做得不好导致的(做的好的GPU加limit  _time参数之后不会有这个问题)，加opencl_window_size这个参数之后会从上层去进行调度和限制任务的执行，所以性能会下降。
