### ISSUE TITLE
运行model zoo 自带的yolo例子，出现了错误，但是测试了mobile-v1 没有错误

### ISSUE THREAD

**Issue by jiguanglu** [XiaoMi/mace#533]
[Before]([url]([url](url
![1568858629936](https://user-images.githubusercontent.com/16578290/65207649-deec8b00-dac4-11e9-900b-0df5ffda9f6d.jpg)
))) you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by yejw5** [comment]
贴一下更完整的log？顺便把模板里的环境和复现步骤加一下？

**Comment by jiguanglu** [comment]
**System information：**

- OS Platform and Distribution (Linux Ubuntu 16.04):
- NDK version(15rc):
- GCC version(if compiling for host, e.g., 5.4.0):
- MACE version (Use the command: git describe --long --tags):
        git clone https://github.com/XiaoMi/mace.git
        git clone https://github.com/XiaoMi/mace-models.git
- Python version(2.7):
- Bazel version (0.13.0):


**Model deploy file (*.yml)：**
     mace/mace-models/yolo-v3/yolo-v3.yam

**problem:**
     1. cd /path/to/mace
     2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file




**### Error information / logs**


INFO: Build completed successfully, 6 total actions

Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
('output keys: ', ['conv2d_75/BiasAdd:0', 'conv2d_59/BiasAdd:0', 'conv2d_67/BiasAdd:0'])
Traceback (most recent call last):
  File "tools/converter.py", line 1347, in <module>
    flags.func(flags)
  File "tools/converter.py", line 854, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 783, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/jiguang/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/home/jiguang/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.SignalException_SIGKILL: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=builds/downloads/f48e3744a54fb9bef5e313cfef77f3b5.pb --weight_file= --model_checksum=cbdd9a23588a42af95cf510e458f4decc3b1c0a3d6d6ab22e2b4f3d43ff961aa --weight_checksum= --input_node=input_1:0 --input_data_types=float32 --input_data_formats=NHWC --output_node=conv2d_59/BiasAdd:0,conv2d_67/BiasAdd:0,conv2d_75/BiasAdd:0 --output_data_types=float32,float32,float32 --output_data_formats=NHWC,NHWC,NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=yolo_v3 --input_shape=1,416,416,3 --input_range= --output_shape=1,13,13,255:1,26,26,255:1,52,52,255 --check_shape= --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/yolo_v3 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:

**Comment by yejw5** [comment]
机器配置是？

**Comment by jiguanglu** [comment]
我是在mac os下使用VM ware 安装的ubuntu16.04
处理器：2.3GHz intelCore i9
显卡： Radeon Pro 560x 4GB
            intel UHD Graphics 630

**Comment by yejw5** [comment]
那分配的内存是不是不大

**Comment by jiguanglu** [comment]
感谢您的回答。
嗯，我也查到了这个问题，以前是分配的2G，现在改了8G，看看结果如何。
我会及时跟您反馈。
