### ISSUE TITLE
onnx_converter.py转换模型出错

### ISSUE THREAD

**Issue by Wuqiman** [XiaoMi/mace#536]
我把一个onnx模型转换成mace时，在onnx_converter.py 197行   "to": lambda x: data_type.onnx2tf(x)
onnx_attr_translator = {
    "axis": lambda x: int(x),
    "axes": lambda x: [int(a) for a in x],
    "dtype": lambda x: data_type.onnx2tf(x),
    "keepdims": lambda x: bool(x),
    "to": lambda x: data_type.onnx2tf(x),
}
中遇到 “global name 'data_type' is not defined”这个错误，请问如何解决？

**Comment by lu229** [comment]
@Wuqiman 如QQ上沟通，是否方面share一下你的onnx模型，我们这边看一下？

**Comment by Wuqiman** [comment]
你好，附近是我的onnx模型，麻烦了~



985712452@qq.com
 
发件人： 卢旭辉
发送时间： 2019-09-26 09:09
收件人： XiaoMi/mace
抄送： Wuqiman; Mention
主题： Re: [XiaoMi/mace] onnx_converter.py转换模型出错 (#536)
@Wuqiman 如QQ上沟通，是否方面share一下你的onnx模型，我们这边看一下？
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


-----------------------------------------------------------
以下文件通过foxmail发给您。保存时间有限制，请及时提取。
onnx_model.zip (41.3 M) (有效时间到: 2019/10/26 9:14:27)
链接: http://mail.qq.com/cgi-bin/ftnExs_download?k=20616530b21d589c21a6a50a4762014e015407005750560548075207034f0757550748510053024c06515c070052035157025c54616c330e0b0f1d6f0c0d5704094f1f5911620e1532&t=exs_ftn_download&code=eae0ab3a

**Comment by lu229** [comment]
@Wuqiman 还有yml文件也请贴一下

**Comment by Wuqiman** [comment]
你好，附近是对应的yml文件，麻烦了



985712452@qq.com
 
发件人： 卢旭辉
发送时间： 2019-09-26 09:24
收件人： XiaoMi/mace
抄送： Wuqiman; Mention
主题： Re: [XiaoMi/mace] onnx_converter.py转换模型出错 (#536)
@Wuqiman 还有yml文件也请贴一下

**Comment by lu229** [comment]
@Wuqiman github上看不到你附件贴的yml文件，直接贴上来吧

**Comment by Wuqiman** [comment]
library_name: mobilenet-v2_1_0
target_abis: [arm64]
model_graph_format: file
model_data_format: file
models:
  mobilenet:
    platform: onnx
    # model_file_path: "/home/retinanet_mv2_right_finetune.onnx"
    # model_sha256_checksum: 5097e3cf47813f7f7729fba1d5db2937c4f866b852e2b3b6e5be4eee9077fb34
    model_file_path: "/home/retinanet_mv2_right_finetune_opt.onnx"
    model_sha256_checksum: c6c228b20ebd7338d38fc5b9eac4045a794e20440b674ee59a1e37595d31bde6
    subgraphs:
      - input_tensors:  
          - "0"
        output_tensors: 
          - "776"
          - "806"
          - "836"
          - "866"
          - "896"
          - "777"
          - "807"
          - "837"
          - "867"
          - "897"
        input_shapes: 
          - 1,480,480,3
        output_shapes: 
          - 1,60,60,18
          - 1,30,30,18
          - 1,15,15,18
          - 1,8,8,18
          - 1,4,4,18
          - 1,60,60,24
          - 1,30,30,24
          - 1,15,15,24
          - 1,8,8,24
          - 1,4,4,24
        backend: pytorch
    runtime: cpu
    winograd: 0

**Comment by Wuqiman** [comment]
我在mace里面添加了unsample算子的onnx转换代码，还有floor算子，然后重新编译了mace

**Comment by lu229** [comment]
@Wuqiman 这个模型在我这边报错：
Traceback (most recent call last):
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 816, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR)
  File "tools/python/convert.py", line 75, in convert
    mace_model = convert_model(model_conf)
  File "tools/python/convert.py", line 180, in convert_model
    output_graph_def = converter.run()
  File "tools/python/transform/onnx_converter.py", line 463, in run
    self.convert_ops(graph_def)
  File "tools/python/transform/onnx_converter.py", line 546, in convert_ops
    self._op_converters[node.op_type](node)
  File "tools/python/transform/onnx_converter.py", line 956, in convert_eltwise
    value_arg.f = const_tensor.float_data[0]
IndexError: list index (0) out of range
我这边看了一下，ONNX模型看起来不合法？比如其中有个Mul OP，其输入应该是697和698，但实际上，模型里面只输入了697，没有698，类似的情况还有很多。

**Comment by Wuqiman** [comment]
比如其中有个Mul OP，其输入应该是697和698，但实际上，模型里面只输入了697，没有698，类似的情况还有很多。这部分的操作是在做上采样~从pytorch转过来，就是这样的呢

**Comment by TonyMou** [comment]
我在check这个问题

**Comment by TonyMou** [comment]
@Wuqiman  这个Patch应该能解决你的问题.欢迎提交新加算子．
[e4a14c7163b51b42fc2b8458866753f8e81ff175.zip](https://github.com/XiaoMi/mace/files/3655740/e4a14c7163b51b42fc2b8458866753f8e81ff175.zip)

**Comment by Wuqiman** [comment]
> @Wuqiman 这个Patch应该能解决你的问题.欢迎提交新加算子．
> [e4a14c7163b51b42fc2b8458866753f8e81ff175.zip](https://github.com/XiaoMi/mace/files/3655740/e4a14c7163b51b42fc2b8458866753f8e81ff175.zip)

已经解决了~非常感谢

**Comment by jiguanglu** [comment]
> 我把一个onnx模型转换成mace时，在onnx_converter.py 197行 "to": lambda x: data_type.onnx2tf(x)
> onnx_attr_translator = {
> "axis": lambda x: int(x),
> "axes": lambda x: [int(a) for a in x],
> "dtype": lambda x: data_type.onnx2tf(x),
> "keepdims": lambda x: bool(x),
> "to": lambda x: data_type.onnx2tf(x),
> }
> 中遇到 “global name 'data_type' is not defined”这个错误，请问如何解决？

  @TonyMou 您好，看到您的模型里有很多的output_shape, 请问您是如何修改的image_classify.cc 文件？ example文件里都是一个输出。能否给提点建议呢？

**Comment by TonyMou** [comment]
@jiguanglu 多个输出和一个输出是类似的，创建多个Tensor，根据name来读输出．

**Comment by jiguanglu** [comment]
@TonyMou 能否加个微信，我想请教一下如何做。我的微信：23124264，希望能向您学习。

**Comment by TonyMou** [comment]
你可以加入ＱＱ交流群，有问题都会第一时间回复的．

**Comment by jiguanglu** [comment]
@TonyMou 我已经加入了qq群了，这个问题我也提过，但是回答的模棱两可啊，我主要是不是特别会android，所以，大佬，加个微信吧，我必有重谢啊。

**Comment by Wuqiman** [comment]
调用mace run接口的时候，出现这个错误：./mace/core/tensor.h Unknown type: 3，可以麻烦帮忙推测出现问题的原因吗？

**Comment by Wuqiman** [comment]
> @Wuqiman 这个模型在我这边报错：
> Traceback (most recent call last):
> File "tools/converter.py", line 1151, in 
> flags.func(flags)
> File "tools/converter.py", line 816, in convert_func
> convert.convert(configs, MODEL_CODEGEN_DIR)
> File "tools/python/convert.py", line 75, in convert
> mace_model = convert_model(model_conf)
> File "tools/python/convert.py", line 180, in convert_model
> output_graph_def = converter.run()
> File "tools/python/transform/onnx_converter.py", line 463, in run
> self.convert_ops(graph_def)
> File "tools/python/transform/onnx_converter.py", line 546, in convert_ops
> self._op_converters[node.op_type](node)
> File "tools/python/transform/onnx_converter.py", line 956, in convert_eltwise
> value_arg.f = const_tensor.float_data[0]
> IndexError: list index (0) out of range
> 我这边看了一下，ONNX模型看起来不合法？比如其中有个Mul OP，其输入应该是697和698，但实际上，模型里面只输入了697，没有698，类似的情况还有很多。

调用mace run接口的时候，出现这个错误：./mace/core/tensor.h Unknown type: 3，可以麻烦帮忙推测出现问题的原因吗？

**Comment by Wuqiman** [comment]
> > @Wuqiman 这个Patch应该能解决你的问题.欢迎提交新加算子．
> > [e4a14c7163b51b42fc2b8458866753f8e81ff175.zip](https://github.com/XiaoMi/mace/files/3655740/e4a14c7163b51b42fc2b8458866753f8e81ff175.zip)
> 
> 已经解决了~非常感谢

@TonyMou 调用mace run接口的时候，出现这个错误：./mace/core/tensor.h Unknown type: 3，可以麻烦帮忙推测出现问题的原因吗？

**Comment by Wuqiman** [comment]
> > > @Wuqiman 这个Patch应该能解决你的问题.欢迎提交新加算子．
> > > [e4a14c7163b51b42fc2b8458866753f8e81ff175.zip](https://github.com/XiaoMi/mace/files/3655740/e4a14c7163b51b42fc2b8458866753f8e81ff175.zip)
> > 
> > 
> > 已经解决了~非常感谢
> 
> @TonyMou 调用mace run接口的时候，出现这个错误：./mace/core/tensor.h Unknown type: 3，可以麻烦帮忙推测出现问题的原因吗？


[0001-resize-op.zip](https://github.com/XiaoMi/mace/files/3666685/0001-resize-op.zip)

**Comment by lu229** [comment]
如QQ沟通，是因为cast算子中使用了half类型引起。
