### ISSUE TITLE
How to build library with local model

### ISSUE THREAD

**Issue by peyer** [XiaoMi/mace#54]
@llhe, thanks to your wonderful work firstly. 
I have some local caffemodel waiting for transformation, how can I just compile MACE+MODEL without download and md5 check?

**Comment by llhe** [comment]
@peyer 
1. you can just switch the http url to a local file path (absolute path or relative to the work dir)
2. to generate the sha256 checksum, you can use `sha256sum model-file-name` command

**Comment by peyer** [comment]
@llhe Thanks, I will try your suggestion

**Comment by llhe** [comment]
Just close this issue, if there are still problems, fell free to reopen it.
