### ISSUE TITLE
运行mtk apu 出错

### ISSUE THREAD

**Issue by huanyingjun** [XiaoMi/mace#540]
在mt6779的机器上运行apu的时候报错，找不到libapu-platform.so，尝试把third_party/apu/mt6779/libapu-platform.so  push到手机的/data/local/tmp/mace_run中，这个错解决，但是出现
[VpuStreamlmp] open vpu fail, return -1, errno（13）:Permission denied

请问是否还需要对手机做什么额外的配置吗？

**Comment by lydoc** [comment]
看起来是apu的权限问题，dev/vpu 这里的权限正常吗？设置为777试试？

**Comment by huanyingjun** [comment]
@lydoc
手机没有root，没法设置777。。。。
另外请问下一下 libapu-frontend.so 和 libapu-platform.so 是由MTK提供的吗？

**Comment by lydoc** [comment]
是的

**Comment by huanyingjun** [comment]
@lydoc
改777后上面的问题解决，又出现新的错:

E neuron : ERROR: Command run failed!! Result = 1 xrpStatus = 0
E neuron : ERROR: Device Error: Input alignment requirements are not satisfied
E neuron : ERROR: Failed to run model inference, bad state
F MACE : apu_wrapper.cc:263: Check failed: ret == true neuron run model failed

请问这个该怎么解决？

**Comment by lydoc** [comment]
可能和具体模型以及op有关系，现在APU支持的模型和op有限。
