### ISSUE TITLE
mace roadmap

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#542]
大家好，每次都在这里提问哈，非常感谢mace的同学~

我感觉目前mace在端上的支持已经很完善了，也很早的支持了dsp，整体很成熟。

**Comment by ysh329** [comment]
有下一步的roadmap，支持计划嘛，比方更多硬件、更多端上后端、端上训练、更低精度等等

**Comment by llhe** [comment]
短期
* 完善异构计算的支持
* 新硬件的适配和优化
* 代码持续优化，工具链完善

中长期
* 联邦学习，端上训练
* 其他
