### ISSUE TITLE
Why float16 percision slower than float32 percision sometimes?

### ISSUE THREAD

**Issue by pengcuo** [XiaoMi/mace#546]
Benchmark                                                  Time(ns) Iterations Input(MB/s)     GMACPS
-----------------------------------------------------------------------------------------------------
MACE_BM_CONV_2D_1_1024_7_7_K1x1S1D1_SAME_1024_float_GPU     2059405        514      97.46      24.95
MACE_BM_CONV_2D_1_1024_7_7_K1x1S1D1_SAME_1024_half_GPU      1809739        522      55.45      28.39
MACE_BM_CONV_2D_1_128_56_56_K1x1S1D1_SAME_128_float_GPU     3340422        308     480.67      15.38
MACE_BM_CONV_2D_1_128_56_56_K1x1S1D1_SAME_128_half_GPU      3162378        267     253.86      16.25
MACE_BM_CONV_2D_1_160_17_17_K7x1S1D1_SAME_192_float_GPU     2608875        534      70.90      23.82
MACE_BM_CONV_2D_1_160_17_17_K7x1S1D1_SAME_192_half_GPU      2589572        622      35.71      24.00
MACE_BM_CONV_2D_1_192_17_17_K1x7S1D1_SAME_192_float_GPU     2796380        266      79.37      26.67
MACE_BM_CONV_2D_1_192_17_17_K1x7S1D1_SAME_192_half_GPU      2842725        447      39.04      26.23
MACE_BM_CONV_2D_1_192_17_17_K7x1S1D1_SAME_192_float_GPU     2630442        661      84.38      28.35
MACE_BM_CONV_2D_1_192_17_17_K7x1S1D1_SAME_192_half_GPU      2653841        675      41.82      28.10
MACE_BM_CONV_2D_1_32_256_256_K15x1S1D1_SAME_2_float_GPU     4783279        154    1753.74      13.15
MACE_BM_CONV_2D_1_32_256_256_K15x1S1D1_SAME_2_half_GPU      3846870        192    1090.32      16.35
MACE_BM_CONV_2D_1_32_256_256_K1x15S1D1_SAME_2_float_GPU     4620527        182    1815.51      13.62
MACE_BM_CONV_2D_1_32_256_256_K1x15S1D1_SAME_2_half_GPU      3724729        181    1126.07      16.89
MACE_BM_CONV_2D_1_32_256_256_K3x3S1D2_VALID_32_float_GPU   13461762         63     623.14      43.48
MACE_BM_CONV_2D_1_32_256_256_K3x3S1D2_VALID_32_half_GPU    12749897         68     328.97      45.90
MACE_BM_CONV_2D_1_32_256_256_K3x3S1D4_VALID_32_float_GPU   13223148         61     634.39      42.87
MACE_BM_CONV_2D_1_32_256_256_K3x3S1D4_VALID_32_half_GPU    12564812         69     333.81      45.11
MACE_BM_CONV_2D_1_32_34_34_K3x3S1D1_VALID_32_float_GPU      1437272        790     102.95       6.57
MACE_BM_CONV_2D_1_32_34_34_K3x3S1D1_VALID_32_half_GPU       1558987        751      47.46       6.05
MACE_BM_CONV_2D_1_3_128_128_K3x3S1D1_SAME_16_float_GPU      2122228        531      92.64       3.34
MACE_BM_CONV_2D_1_3_128_128_K3x3S1D1_SAME_16_half_GPU       2127571        715      46.20       3.33
MACE_BM_CONV_2D_1_3_224_224_K3x3S2D1_SAME_32_float_GPU      2628154        423     229.10       4.12
MACE_BM_CONV_2D_1_3_224_224_K3x3S2D1_SAME_32_half_GPU       2676008        506     112.50       4.05
MACE_BM_CONV_2D_1_3_224_224_K3x3S2D1_VALID_32_float_GPU     2557629        372     235.42       4.16
MACE_BM_CONV_2D_1_3_224_224_K3x3S2D1_VALID_32_half_GPU      2648196        514     113.68       4.02
MACE_BM_CONV_2D_1_3_256_256_K3x3S1D1_SAME_16_float_GPU      4131815        151     190.34       6.85
MACE_BM_CONV_2D_1_3_256_256_K3x3S1D1_SAME_16_half_GPU       4383996        253      89.69       6.46
MACE_BM_CONV_2D_1_3_480_480_K1x1S1D1_VALID_3_float_GPU      2445746        279    1130.45       0.85
MACE_BM_CONV_2D_1_3_480_480_K1x1S1D1_VALID_3_half_GPU       1954221        407     707.39       1.06
MACE_BM_CONV_2D_1_3_64_64_K3x3S1D1_SAME_16_float_GPU        1406809        801      34.94       1.26
MACE_BM_CONV_2D_1_3_64_64_K3x3S1D1_SAME_16_half_GPU         1417983        763      17.33       1.25
MACE_BM_CONV_2D_1_64_32_31_K15x1S1D1_SAME_128_float_GPU     3307764        356      76.77      36.85
MACE_BM_CONV_2D_1_64_32_31_K15x1S1D1_SAME_128_half_GPU      3337877        310      38.04      36.52
MACE_BM_CONV_2D_1_64_32_31_K1x15S1D1_SAME_128_float_GPU     3482425        275      72.92      35.00
MACE_BM_CONV_2D_1_64_32_31_K1x15S1D1_SAME_128_half_GPU      3395032        315      37.40      35.90
MACE_BM_CONV_2D_1_64_32_31_K5x5S1D1_SAME_128_float_GPU      4476059        203      56.74      45.39
MACE_BM_CONV_2D_1_64_32_31_K5x5S1D1_SAME_128_half_GPU       3753660        215      33.83      54.12
MACE_BM_CONV_2D_1_64_32_31_K7x7S1D1_SAME_128_float_GPU      6826828        122      37.20      58.33
MACE_BM_CONV_2D_1_64_32_31_K7x7S1D1_SAME_128_half_GPU       6568144        160      19.33      60.63
MACE_BM_CONV_2D_1_64_32_31_K7x7S2D1_SAME_128_float_GPU      3610949        253      70.33      28.46
MACE_BM_CONV_2D_1_64_32_31_K7x7S2D1_SAME_128_half_GPU       3480650        254      36.48      29.52
MACE_BM_CONV_2D_1_64_32_31_K7x7S3D1_SAME_128_float_GPU      2825350        409      89.88      17.19
MACE_BM_CONV_2D_1_64_32_31_K7x7S3D1_SAME_128_half_GPU       2708080        339      46.89      17.94
MACE_BM_CONV_2D_1_64_32_32_K1x1S1D1_VALID_128_float_GPU     1849990        762     141.70       4.53
MACE_BM_CONV_2D_1_64_32_32_K1x1S1D1_VALID_128_half_GPU      1480001        757      88.56       5.67
MACE_BM_CONV_2D_1_64_32_32_K3x3S1D1_SAME_128_float_GPU      2976556        360      88.07      25.36
MACE_BM_CONV_2D_1_64_32_32_K3x3S1D1_SAME_128_half_GPU       2950716        395      44.42      25.59
MACE_BM_CONV_2D_1_64_32_32_K5x5S1D1_SAME_128_float_GPU      4477394        198      58.55      46.84
MACE_BM_CONV_2D_1_64_32_32_K5x5S1D1_SAME_128_half_GPU       3461502        261      37.87      60.59
MACE_BM_CONV_2D_1_64_33_31_K1x1S1D1_VALID_128_float_GPU     1653053        703     158.43       5.07
MACE_BM_CONV_2D_1_64_33_31_K1x1S1D1_VALID_128_half_GPU      1453927        867      90.06       5.76
MACE_BM_CONV_2D_1_64_33_31_K3x3S1D1_SAME_128_float_GPU      2933030        429      89.29      25.72
MACE_BM_CONV_2D_1_64_33_31_K3x3S1D1_SAME_128_half_GPU       2914942        344      44.92      25.87
MACE_BM_CONV_2D_1_64_64_64_K15x1S1D1_SAME_2_float_GPU       1925123        593     544.68       4.09
MACE_BM_CONV_2D_1_64_64_64_K15x1S1D1_SAME_2_half_GPU        1213292        674     432.12       6.48
MACE_BM_CONV_2D_64_32_34_34_K3x3S1D1_VALID_32_float_GPU    11703171         76     809.18      51.61
MACE_BM_CONV_2D_64_32_34_34_K3x3S1D1_VALID_32_half_GPU     10624061         82     445.68      56.85

**Comment by pengcuo** [comment]
并且 Half 的加速效果，平均貌似 15 % 左右都不到...

**Comment by lu229** [comment]
@pengcuo 这里的fp16，只是指模型的输入输出数据是fp16，实际运算使用的还是使用fp32，所以没有速度差异。

**Comment by lu229** [comment]
@pengcuo ，经@yejw5 提醒，我这边说得不准确，模型的存储使用的是fp16，实际计算过程中数据的存储也是使用的fp16，计算使用的是fp32，由于内存存取速度的加快，实际计算速度是有加快的。
不过现在的代码是有问题的，@yejw5 正在修复，修复完之后会同步上来

**Comment by pengcuo** [comment]
首先非常感谢您回复～
我的核心疑问点在于这里，我用 fp16 去做存储，那么带宽的压力就会减轻一半，这个对于带宽压力吃紧的嵌入式 SoC 中会有很大的提升。但实际上并没有提升一倍，平均貌似连 15% 都不到。
再次感谢小米公司的开源，比某汤天天在外面开源库群里秀优越感强一百倍。

**Comment by pengcuo** [comment]
根据阿姆达尔定律来讲，最高理论的提升没有两倍，毕竟计算还有耗时。但问题又来了，读取数据和计算不是可以排流水的么。只有 15% 的提升，甚至有些情况还会更慢，这个我就不明白了

**Comment by pengcuo** [comment]
@lu229

**Comment by lu229** [comment]
@pengcuo 目前线上的代码有问题， @yejw5 在修复，到时再测试看看吧～

**Comment by yejw5** [comment]
@pengcuo 但是实现过程，还是需要区分算子的瓶颈是在计算还是IO上吧。我这边测试模型大体提升也是在15%左右

**Comment by pengcuo** [comment]
CNN 计算中 GEMM 或者 卷积 运算 从理论上来讲肯定是计算瓶颈。但问题是 一个 FLOAT32  ALU 是可以拆成两个 FLOAT16 ALU，相当于原来只能计算一个 FLOAT32 的计算单元，现在可以同时支持计算两个 FLOAT16 单元。并且我们还没有考虑带宽压力减半的情况。

**Comment by pengcuo** [comment]
所以只能提升 15%， 这个就让我很困惑。

**Comment by pengcuo** [comment]
我之前写过 3x3 的卷积，影响中能够有接近一倍（不到一倍）的提升，假如我把 data 的数据类型（image2d）从 FP32 改成 FP16.

**Comment by yejw5** [comment]
我们只用了fp16存储，计算用的仍然是fp32

**Comment by pengcuo** [comment]
所以结论就是：GEMM 或者卷积是 计算密集性的任务，并不会限制在带宽上。采用 FP32 去计算（这部分和原来一致），FP16 对带宽减少的收益并不会对整体有很大的提升？

**Comment by yejw5** [comment]
从测试结果看，应该是在15%左右的提升

**Comment by pengcuo** [comment]
好的，明白了。感谢 yejw5 回复我这么多条信息。

**Comment by pengcuo** [comment]
这个 issue 我关闭啦，再次感谢。

**Comment by pengcuo** [comment]
好像我关不了，拜托你们关吧。

**Comment by yejw5** [comment]
客气了
