### ISSUE TITLE
Convert Mace  back to Tensorflow

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#548]
Hi ,
I know it probably impossible, but is their way convert mace model back to TensorFlow?
Thanks.

**Comment by yejw5** [comment]
Mace model is simplified TF model format, and only used in mace. We haven't considered that it can be converted back.

**Comment by dimitryn** [comment]
@yejw5  I need to run something fast on x86_64 with a single thread .  and since mace optimizes graph better then TensorFlow it could run faster.

**Comment by yejw5** [comment]
Mace have supported x86_64, but no optimization...
