### ISSUE TITLE
最新版本caffe模型convert的时候老是报错

### ISSUE THREAD

**Issue by kingLCH** [XiaoMi/mace#549]
File "tools/python/transform/transformer.py", line 1356, in sort_by_execution
    output_nodes.extend(self._option.output_nodes)
AttributeError: 'dict_keys' object has no attribute 'extend'

**Comment by lee-bin** [comment]
Please fill in the [ISSUE_TEMPLATE.md](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)

**Comment by kingLCH** [comment]
docker直接拉的环境，python版本是3.6，环境应该没啥问题，就是老提示这个错误，莫不是python版本是2.7才行

**Comment by lu229** [comment]
@kingLCH  Please fill in the [ISSUE_TEMPLATE.md](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)
