### ISSUE TITLE
 lack the include file of 'CL/opencl.h'

### ISSUE THREAD

**Issue by jinliang20000** [XiaoMi/mace#55]
log:
bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp/include/CL/cl2.hpp:506:10:  fatalerror: 'CL/opencl.h' file no found
#include <CL/opencl.h>

**Comment by jinliang20000** [comment]
python tools/converter.py build  --config=mace-models/mobilenet-v2/mobilenet-v2.yml
-------------------------------------------------
               Common Configuration
-------------------------------------------------
|       key       |            value            |
=================================================
|     library_name|                 mobilenet-v2|
-------------------------------------------------
|      target_abis| ['armeabi-v7a', 'arm64-v8a']|
-------------------------------------------------
|      target_socs|                           []|
-------------------------------------------------
|       build_type|                         code|
-------------------------------------------------
| embed_model_data|                            0|
-------------------------------------------------
|       linkshared|                            0|
-------------------------------------------------
|           Tuning|                         True|
-------------------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!
...

**Comment by jinliang20000** [comment]
jinliang@guest-Super-Server:mace$ python tools/converter.py build  --config=mace-models/mobilenet-v2/mobilenet-v2.yml
-------------------------------------------------
               Common Configuration
-------------------------------------------------
|       key       |            value            |
=================================================
|     library_name|                 mobilenet-v2|
-------------------------------------------------
|      target_abis| ['armeabi-v7a', 'arm64-v8a']|
-------------------------------------------------
|      target_socs|                           []|
-------------------------------------------------
|       build_type|                         code|
-------------------------------------------------
| embed_model_data|                            0|
-------------------------------------------------
|       linkshared|                            0|
-------------------------------------------------
|           Tuning|                         True|
-------------------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

**Comment by jinliang20000** [comment]
How can I fix this problem? ,Thanks

**Comment by llhe** [comment]
Is this fixed?
