### ISSUE TITLE
性能测试疑问

### ISSUE THREAD

**Issue by zuoshaobo** [XiaoMi/mace#553]
用--validate  运行
python tools/python/run_model.py --config ./mace-models/xx/xx.yml --validate --target_abi arm64-v8a --round 100
打印出来是：
I /Users/chison/chison_work/mace/mace/tools/mace_run.cc:404] 1st warm up run latency: 210.866 ms
I /Users/chison/chison_work/mace/mace/tools/mace_run.cc:412] Run model
I /Users/chison/chison_work/mace/mace/tools/mace_run.cc:474] Average latency: 3.58266 ms

用--benchmark打印出来是：
I /Users/chison/chison_work/mace/mace/utils/statistics.cc:344] -----------------------------------------------------------------------
I /Users/chison/chison_work/mace/mace/utils/statistics.cc:344]                          Summary of Ops' Stat
I /Users/chison/chison_work/mace/mace/utils/statistics.cc:344] -----------------------------------------------------------------------
I /Users/chison/chison_work/mace/mace/utils/statistics.cc:344] | round | first(ms) | curr(ms) | min(ms) | max(ms) | avg(ms) |    std |
I /Users/chison/chison_work/mace/mace/utils/statistics.cc:344] -----------------------------------------------------------------------
I /Users/chison/chison_work/mace/mace/utils/statistics.cc:344] |   100 |     0.390 |    0.617 |   0.390 |   0.635 |   0.617 | 28.307 |
I /Users/chison/chison_work/mace/mace/utils/statistics.cc:344] -----------------------------------------------------------------------
平均是0.617 ms
和上述的3.58266 ms 相差很多，这是为什么呢？

**Comment by lu229** [comment]
请按这个模板[ISSUE_TEMPLATE.md](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)填写issue, 有利于我们诊断问题.
这是GPU运行的?

**Comment by zuoshaobo** [comment]
是的，gpu运行的

**Comment by lu229** [comment]
多出来的时间用于CPU和GPU的内存同步了.

**Comment by zuoshaobo** [comment]
好的 谢谢
