### ISSUE TITLE
windows 下运行

### ISSUE THREAD

**Issue by zuoshaobo** [XiaoMi/mace#554]
请问下 mace可以移植到windows下，用intel gpu的opencl 推理吗？opencl是1.2的版本

**Comment by lu229** [comment]
@zuoshaobo 我们没有尝试过, 理论上应该可以, 但由于没有做针对性优化, 效率可能不会好.

**Comment by zuoshaobo** [comment]
> @zuoshaobo 我们没有尝试过, 理论上应该可以, 但由于没有做针对性优化, 效率可能不会好.

好的 谢谢
