### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by zuoshaobo** [XiaoMi/mace#556]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
library_name: xxxx
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  level_1:
    platform: tensorflow
    model_file_path: 1.pb
    model_sha256_checksum: d3824784d6b65c204b817ca9b2cf9bedeff1f52901b1a6fe5e47e8905033bb39
    subgraphs:
      - input_tensors:
          - Placeholder
        input_shapes:
          - 1,256,512,1
        output_tensors:
          - Mul
        output_shapes:
          - 1,256,512,1
    runtime: gpu
    obfuscate: 0
    winograd: 2
  level_2:
    platform: tensorflow
    model_file_path: 2.pb
    model_sha256_checksum: 4900151af57d36ea1e4cf93185bce779c3d407ab31381ff3db579c8c4ba97dc6
    subgraphs:
      - input_tensors:
          - Placeholder
        input_shapes:
          - 1,256,512,1
        output_tensors:
          - Mul
        output_shapes:
          - 1,256,512,1
    runtime: gpu
    obfuscate: 0
    winograd: 2

### Describe the problem
gpu的推理方式，测试场景是两个模型来回切换运行，测试发现有内存泄漏的问题，设备是华为，手机是970的，平板是980的，采用android studio中自带的profile工具，经过测试发现：
 case 0:
      net_def = mace::level_1::CreateNet();
      **engine->reset(new mace::MaceEngine(config));**
      model_data = mace::level_1::LoadModelData();
      status = (*engine)->Init(net_def.get(), input_nodes, output_nodes,
                               model_data);
      break;
    case 1:
      net_def = mace::level_2::CreateNet();
      **engine->reset(new mace::MaceEngine(config));**
      model_data = mace::level_2::LoadModelData();
      status = (*engine)->Init(net_def.get(), input_nodes, output_nodes,
                               model_data);
      break;

**new mace::MaceEngine(config)这边有泄漏，因为网络结构一样，权重不同我改成如下：** 
case 0:
      net_def = mace::level_1::CreateNet();
      **if(flag==0)
        engine->reset(new mace::MaceEngine(config));**
      model_data = mace::level_1::LoadModelData();
      status = (*engine)->Init(net_def.get(), input_nodes, output_nodes,
                               model_data);
      flag=1;
      break;
    case 1:
      net_def = mace::level_2::CreateNet();
      **//engine->reset(new mace::MaceEngine(config));**
      model_data = mace::level_2::LoadModelData();
      status = (*engine)->Init(net_def.get(), input_nodes, output_nodes,
                               model_data);
      break;
每次都用同一个MaceEngine就可以，以后只调用init初始化当前的权重就行
奇怪的是小米的平台却没有这个问题，而且只在GPU推理的情况存在，cpu没有泄露
### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@zuoshaobo , 是指engine泄漏了么?  内存泄漏的问题可能只能通过调试来发现问题, 我们这边也没有什么好办法, 可以跟踪一下这个指针被哪些对象持有了, 可能是由于华为手机的OPENCL驱动有什么不同, 导致间接持有了engine指针.

**Comment by yejw5** [comment]
最好也发一下mace的代码commit号
