### ISSUE TITLE
对mace框架的疑问

### ISSUE THREAD

**Issue by yyqgood** [XiaoMi/mace#562]
你好，我最近在研究mace框架，现在有以下疑惑请帮忙解答：
1. 使用bazel编译工具，每次编译需要重新下载且编译速度过慢；后期的mace-kit框架是否会使用主流的cmake编译方式，且wiki对应更新？
2. mace依赖的外部库要严格依赖于某一个版本兼容性值得商榷；后期的mace-kit框架是否会考虑这块兼容性？
3. 目标检测模型支持比较少，目前看到的有：ssd-mobilenet-v1和yolo-v3，后期的mace-kit框架是否会支持更多的目标检测模型？
4. 目前，只支持基于camera的图像分类Android demo的支持，后期mace-kit框架是否会支持基于图片和camera的分类/检测的Android demo？
期待你的回复，谢谢！

**Comment by lydoc** [comment]
谢谢你的建议，目前最新的mace已支持cmake编译，后期mace kit也支持cmake。目前还未支持更多的检测模型，也欢迎PR和建议。mace kit会支持基于图片的的分类、检测demo。

**Comment by yyqgood** [comment]
很高兴收到你的回复。方便透露下mace kit大概什么时间开源吗？

**Comment by lydoc** [comment]
coming soon

**Comment by yyqgood** [comment]
再次感谢，期待！
