### ISSUE TITLE
About mace and tvm?

### ISSUE THREAD

**Issue by idealboy** [XiaoMi/mace#564]
Now, I want to select a better inference framework on arm chip-set, and the input  origion model is un-certain. And I think my main application scenario is focus on cpu, but sometimes with mali-gpu.

thank you!
 
what is the main difference between mace and tvm? advantage or disadvantage?

（１）I think, mace is good for cpu/dsp supporting, although this function is on going with tvm.

（２）Tvm's fontend supports tf/mxnet/pytorch/caffe, and so on, but mace will use onnx to support others, is there plan for supporting pytorch/mxnet? 
 
（３)  I think the principle about the IR is similar for most of the frameworks(convert graph to self-format, optimize the graph and operator with fusion, optimize the memory, optimize the dataflow or tensor), are there some astonishing news in mace?

  (4) About the backend,  is mace's performence better on qualcomm chip? what is the main difference between mace and snpe?

thank you very much!

**Comment by lu229** [comment]
@idealboy Thanks for your attention to mace. I haven't done much research on TVM. I'll try my best to answer your questions.
I think the main difference between mace and TVM is the optimization of operators. Mace adopts manual optimization and TVM adopts automatic optimization by compiling technology.
(1) Yes, we have  cooperation with qualcomm and support for DSP. As you said, tvm is on going.
2. Yes, pytorch/mxnet are supported by onnx. In the near future, we have no plan to directly support them.
3. We have paid attention to and studied IR, but there is no news at present.
4. With communicating with Qualcomm, we may do good in Qualcomm chips. Snpe is a deep learning framework of Qualcomm, which only supports Snapdragon's  SoCs. Mace support multiple chips, and snpe is also integrated in mace.
