### ISSUE TITLE
Can give me a example code how to user kaldi model ?

### ISSUE THREAD

**Issue by uouo111845** [XiaoMi/mace#567]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
Hi
I have kaldi model and I want to deploy asr on iphone and android phone.
I successfully deploy the Mobilenet example on my phone but I still don't know how to do with the kaldi model.
Could you give me an example of speech recognition ?

Thanks a lot.

**Comment by TonyMou** [comment]
We will release an opensource project MACE-Kit soon, Which contains the fully implementation and deployment of kaldi's asr model on arm cpu.

**Comment by shaheenkdr** [comment]
@TonyMou How easy would it be to adjust the MACE Kaldi libraries for mobile as well as for a large server grade GPU system ? Does the performance auto increase respect to Android and a server system? Or how complicated would it be to optimize the Onnx GPU decoding for kaldi models in PC?

**Comment by lu229** [comment]
@uouo111845 We has released the project [MACE-Kit](https://github.com/XiaoMi/mace-kit)

**Comment by lu229** [comment]
@shaheenkdr It's simple for mobile devices, you can refer to the [MACE documents](https://mace.readthedocs.io/en/latest/), but it's difficult for servers. MACE is developed for mobile devices, and there is no optimization for server devices.
