### ISSUE TITLE
generate huge  binary file

### ISSUE THREAD

**Issue by mhsszm** [XiaoMi/mace#568]
In FAQ:
    When compiling the model into C++ code, the final binary may contains extra debug symbols, they usually take a lot of space. Try to strip the shared library or binary and make sure you are following best practices to reduce the size of an ELF binary, including disabling C++ exception, disabling RTTI, avoiding C++ iostream, hidden internal functions etc. In most cases, the expected overhead should be less than {model weights size in float32}/2 + 3MB.
   When compiling mobilenet-v1 into C++ code, the size is 30M bigger than before.
   do you have examples to reduce binary file to {model weights size in float32}/2 + 3MB ? or how to reduce binary file?

**Comment by lu229** [comment]
@mhsszm what is your compile command? please fill in the [ISSUE_TEMPLATE.md](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)

**Comment by mhsszm** [comment]
@lu229  dorker env:
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 5.4.0-6ubuntu1~16.04.11
    NDK version(e.g., 15c):android-ndk-r15c
    GCC version(if compiling for host, e.g., 5.4.0): Ubuntu 5.4.0-6ubuntu1~16.04.11
    MACE version (Use the command: git describe --long --tags):v0.12.0-20-gd7533c4
    Python version(2.7): Python 2.7.12 (default, Sep  4 2019, 09:12:02)
    Bazel version (e.g., 0.13.0): Build label: 0.16.0
#Steps to reproduce the problem:
file
'''
model_graph_format: file                                                        
model_data_format: file
'''
cd /mace
python tools/converter.py convert --config=mace-models/mobilenet-v1/mobilenet-v1.yml

'''
root@oeasy:/mace# ll build/mobilenet-v1/model/
total 8276
drwxr-xr-x 2 root root    4096 Dec  5 01:57 ./
drwxr-xr-x 3 root root    4096 Dec  5 01:57 ../
-rw-r--r-- 1 root root 8444124 Dec  5 01:57 mobilenet_v1.data
-rw-r--r-- 1 root root   16463 Dec  5 01:57 mobilenet_v1.pb
'''

code  
'''
model_graph_format: code                                                        
model_data_format: code
'''

python tools/converter.py convert --config=mace-models/mobilenet-v1/mobilenet-v1.yml

'''
root@oeasy:/mace# ll build/mobilenet-v1/model/armeabi-v7a/
total 29920
drwxr-xr-x 2 root root     4096 Dec  5 02:02 ./
drwxr-xr-x 4 root root     4096 Dec  5 02:02 ../
-r-xr-xr-x 1 root root 30626004 Dec  5 02:02 mobilenet-v1.a*
'''

**Comment by lu229** [comment]
@mhsszm The file size of mobilenet-v1.a is not important, which is not the size of the model. You can test the size increment after linking it to so or bin, which should be far less than 30m.

**Comment by mhsszm** [comment]
@lu229  the app is too big when i use mobilenet-v1.a  in android system.

**Comment by lu229** [comment]
@mhsszm You can test the size increment between linking mobilenet-v1.a to *.so file and not linking.

**Comment by yejw5** [comment]
@mhsszm https://stackoverflow.com/a/3108436/4243591
