### ISSUE TITLE
Error, convert GRU model from tensorflow

### ISSUE THREAD

**Issue by garymmi** [XiaoMi/mace#569]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**: r18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: git clone 
- **Python version(2.7)**:  Python 3.5.2
- **Bazel version (e.g., 0.13.0)**:0.13.1

### Model deploy file (*.yml)
```
library_name: mymodel
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mymodel:
    platform: tensorflow
    model_file_path: /home/ted/mace/mymodel.pb
    model_sha256_checksum: b7c8c12ed211196c635c69b29a1aab58c8e3a61623a287a5197b1c094245aac2
    subgraphs:
      - input_tensors:
          - net_input
        input_shapes:
          - 1,29,13
        output_tensors:
          - net_output
        output_shapes:
          - 1,1
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
......
```

### Describe the problem
I trained a keras model, then covert to tensorflow (.pb)
when I run  tools/converter.py convert --config_file=mymodel.yml, the error is as below log
my keras's network is
        model = Sequential()
        model.add(GRU(
            params.recurrent_units=20, activation='linear',
            input_shape=(pr.n_features=29, pr.feature_size=13), dropout=0.2, name='net'
        ))
        model.add(Dense(1, activation='sigmoid'))

my tensorflow version is 1.8.0
How to solve the error?
Thanks

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd ~/mace
2. python tools/converter.py convert --config_file=mymodel.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
{'target_abis': ['armeabi-v7a', 'arm64-v8a'], 'library_name': 'mymodel', 'models': {'mymodel': {'model_file_path': '/home/ted/mace/mymodel.pb', 'model_sha256_checksum': 'b7c8c12ed211196c635c69b29a1aab58c8e3a61623a287a5197b1c094245aac2', 'runtime': 'cpu', 'platform': 'tensorflow', 'obfuscate': 0, 'subgraphs': [{'output_tensors': ['net_output'], 'input_tensors': ['net_input'], 'output_shapes': ['1,1'], 'input_shapes': ['1,29,13']}], 'nnlib_graph_mode': 0, 'winograd': 0, 'limit_opencl_kernel_time': 0}}, 'model_data_format': 'file', 'model_graph_format': 'file'}
{'input_tensors': ['net_input'], 'model_file_path': '/home/ted/mace/mymodel.pb', 'output_shapes': ['1,1'], 'model_sha256_checksum': 'b7c8c12ed211196c635c69b29a1aab58c8e3a61623a287a5197b1c094245aac2', 'runtime': 'cpu', 'input_shapes': ['1,29,13'], 'platform': 'tensorflow', 'obfuscate': 0, 'nnlib_graph_mode': 0, 'output_tensors': ['net_output'], 'winograd': 0, 'limit_opencl_kernel_time': 0}
{'output_data_types': [1], 'input_tensors': ['net_input'], 'model_file_path': '/home/ted/mace/mymodel.pb', 'output_shapes': [[1, 1]], 'model_sha256_checksum': 'b7c8c12ed211196c635c69b29a1aab58c8e3a61623a287a5197b1c094245aac2', 'runtime': <DeviceType.CPU: 0>, 'input_data_formats': [<DataFormat.NHWC: 1>], 'output_data_formats': [<DataFormat.NHWC: 1>], 'input_shapes': [[1, 29, 13]], 'platform': <Platform.TENSORFLOW: 0>, 'obfuscate': 0, 'input_data_types': [1], 'nnlib_graph_mode': 0, 'data_type': 3, 'output_tensors': ['net_output'], 'winograd': 0, 'input_ranges': [[-1.0, 1.0]], 'limit_opencl_kernel_time': 0}
Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
output keys:  dict_keys(['net_output'])
Traceback (most recent call last):
  File "/home/ted/mypy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/ted/mypy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ted/mypy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'net/while/Merge_1' has inputs from different frames. The input 'net/while/NextIteration_1' is in frame ''. The input 'net/while/Enter_1' is in frame 'net/while/while_context'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 816, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR)
  File "tools/python/convert.py", line 75, in convert
    mace_model = convert_model(model_conf)
  File "tools/python/convert.py", line 168, in convert_model
    option, conf["model_file_path"])
  File "tools/python/transform/tensorflow_converter.py", line 321, in __init__
    self.update_output_shapes(session)
  File "tools/python/transform/tensorflow_converter.py", line 388, in update_output_shapes
    feed_dict=self._placeholders)
  File "/home/ted/mypy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ted/mypy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ted/mypy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ted/mypy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'net/while/Merge_1' has inputs from different frames. The input 'net/while/NextIteration_1' is in frame ''. The input 'net/while/Enter_1' is in frame 'net/while/while_context'.
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@garymmi Can this model run on tensorflow? From the code point of view, tensorflow made an error in processing the model.

**Comment by garymmi** [comment]
yes, i can use python to call tensorflow api to load the model and predict the result

**Comment by lu229** [comment]
@garymmi Is it convenient for you to share you model and yml file? if so I can check what happened.

**Comment by garymmi** [comment]
thank you
please download my model and yml here
[mymodel.zip](https://drive.google.com/open?id=1kTAtiDF-znQNpFMpnuSetZq6vZ67qhH0)

**Comment by lu229** [comment]
@garymmi , This error is reported by tensorflow, perhaps you can reference this [stackoverflow](https://stackoverflow.com/questions/42564698/invalidargumenterror-the-node-has-inputs-from-different-frames) and modify the model.
Please feel free to communicate if there are any questions.

**Comment by yejw5** [comment]
@garymmi It seems that the model even doesn't work on tensorflow?

**Comment by garymmi** [comment]
> @garymmi It seems that the model even doesn't work on tensorflow?

it can work, i use below code to do inference
`with tf.Session() as sess:
   f = gfile.FastGFile(GRAPH_PB_PATH, 'rb')
   graph_def = tf.GraphDef()
   # Parses a serialized binary message into the current message.
   graph_def.ParseFromString(f.read())
   f.close()

   sess.graph.as_default()
   # Import a serialized TensorFlow `GraphDef` protocol buffer
   # and place into the current default `Graph`.
   tf.import_graph_def(graph_def)
   #print([n.name for n in tf.get_default_graph().as_graph_def().node])
   predict = sess.graph.get_tensor_by_name("import/net_output:0")
   result = sess.run(predict, feed_dict = {'import/net_input:0': feat})
   print(result)`

**Comment by garymmi** [comment]
> @garymmi It seems that the model even doesn't work on tensorflow?

It can work , i use below code to do inference
with tf.Session() as sess:
   f = gfile.FastGFile(GRAPH_PB_PATH, 'rb')
   graph_def = tf.GraphDef()
   # Parses a serialized binary message into the current message.
   graph_def.ParseFromString(f.read())
   f.close()

   sess.graph.as_default()
   # Import a serialized TensorFlow `GraphDef` protocol buffer
   # and place into the current default `Graph`.
   tf.import_graph_def(graph_def)
   #print([n.name for n in tf.get_default_graph().as_graph_def().node])
   predict = sess.graph.get_tensor_by_name("import/net_output:0")
   result = sess.run(predict, feed_dict = {'import/net_input:0': feat})
   print(result)

**Comment by garymmi** [comment]
> @garymmi It seems that the model even doesn't work on tensorflow?

i can work , i use the code as below image to do inference
[my code](https://imgur.com/4UsU22l)

**Comment by lee-bin** [comment]
@garymmi MACE does not support while_loop. You might unroll the loop first.

**Comment by garymmi** [comment]
> @garymmi MACE does not support while_loop. You might unroll the loop first.

Thank for your help, i add unroll=true when train GRU model
when convert the model , new error happen

Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
output keys:  dict_keys(['net_output'])
File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
File "tools/converter.py", line 816, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR)
File "tools/python/convert.py", line 75, in convert
    mace_model = convert_model(model_conf)
File "tools/python/convert.py", line 181, in convert_model
    output_graph_def = converter.run()
File "tools/python/transform/tensorflow_converter.py", line 333, in run
    self.convert_ops(session)
File "tools/python/transform/tensorflow_converter.py", line 396, in convert_ops
    % tf_op.type)
File "tools/python/utils/util.py", line 76, in mace_check
    for line in traceback.format_stack():
ERROR: tools/python/transform/tensorflow_converter.py:396: Mace does not support tensorflow op type ZerosLike yet

**Comment by lee-bin** [comment]
As it says, MACE does not support op ZerosLike. You may consider replacing it or [Adding a new Op](https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html)
