### ISSUE TITLE
winograd [0, 2 ,4] 三个取值，各代表什么意思？

### ISSUE THREAD

**Issue by akbarxie** [XiaoMi/mace#57]
配置文件中，winograd 可以取0,2，4 三个取值，
各代表什么意思？？

**Comment by samsun639** [comment]
我的理解： 
0: 关闭
2: 卷积核2x2
4: 卷积核4x4

4比2 快。

**Comment by TonyMou** [comment]
0：不用winograd;
2：用2x2的winograd
4：用4x4的winograd
详细内容可以参考winograd convolution论文。

**Comment by akbarxie** [comment]
ok

**Comment by samsun639** [comment]
@TonyMou  谢谢 。 我刚看论文了， 2×2 和 4×4 代表output tiles。
