### ISSUE TITLE
 tools/build-standalone-lib.sh failed 

### ISSUE THREAD

**Issue by lizhxixi** [XiaoMi/mace#570]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(15rc)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(3.6.8): 
- **Bazel version ( 0.13.1):

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2.bash tools/build-standalone-lib.sh
```

### Error information / logs
Please include the **full** log and/or traceback here.
bash ./tools/bazel-build-standalone-lib.sh 
build shared lib for armeabi-v7a + cpu_gpu_dsp
INFO: Analysed target //mace/libmace:libmace_dynamic (30 packages loaded).
INFO: Found 1 target...
ERROR: /home/lzx/MACE/mace/mace/core/BUILD.bazel:23:1: C++ compilation of rule '//mace/core:core' failed (Exit 1): clang failed: error executing command 
  (cd /home/lzx/.cache/bazel/_bazel_lzx/de5b0c825a6dcc50c2929014c1ae8537/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=21' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/mace/core/_objs/core/mace/core/device_context.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/mace/core/_objs/core/mace/core/device_context.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/armeabi-v7a-opt/genfiles/external/com_google_protobuf -iquote external/half -iquote bazel-out/armeabi-v7a-opt/genfiles/external/half -iquote external/opencl_clhpp -iquote bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp -iquote external/opencl_headers -iquote bazel-out/armeabi-v7a-opt/genfiles/external/opencl_headers -iquote external/gemmlowp -iquote bazel-out/armeabi-v7a-opt/genfiles/external/gemmlowp -Ibazel-out/armeabi-v7a-opt/bin/include/_virtual_includes/public_headers -Ibazel-out/armeabi-v7a-opt/bin/external/opencl_clhpp/_virtual_includes/opencl_clhpp -Ibazel-out/armeabi-v7a-opt/bin/external/opencl_headers/_virtual_includes/opencl20_headers -isystem external/com_google_protobuf/src -isystem bazel-out/armeabi-v7a-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/src '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD -Wall -Wno-mismatched-tags -Wno-missing-braces -Wall -Wno-mismatched-tags -Wno-missing-braces -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers -DMACE_ENABLE_OPENCL -DMACE_ENABLE_QUANTIZE -DMACE_ENABLE_HEXAGON -DMACE_ENABLE_NEON '-mfpu=neon-fp16' '-mfloat-abi=softfp' '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystemexternal/androidndk/ndk/sysroot/usr/include -c mace/core/device_context.cc -o bazel-out/armeabi-v7a-opt/bin/mace/core/_objs/core/mace/core/device_context.o)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from mace/core/device_context.cc:15:
In file included from ./mace/core/device_context.h:24:
./mace/utils/tuner.h:51:24: error: no member named 'stoi' in namespace 'std'
    window_size = std::stoi(str_size);
                  ~~~~~^
1 error generated.
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 14.551s, Critical Path: 13.17s
INFO: 1 process, linux-sandbox.
FAILED: Build did NOT complete successfully

### Additional context
I look over the previous similar problems and then use :
bazel info output_base|xargs -i ls -l {}/external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
(1)、ls -s ${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
show below:
-rwxr-xr-x 1 root root 62049832 7月  21  2017 /home/lzx/.cache/bazel/_bazel_lzx/de5b0c825a6dcc50c2929014c1ae8537/external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
(2）、 bazel info output_base|xargs -i ls -l {}/external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
show below:
60596 /opt/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang


the two files exist and i cant find where the problem is.

**Comment by lu229** [comment]
@lizhxixi 请使用master主线代码, 这个问题已经解决了
