### ISSUE TITLE
Trouble getting started w/ docker lite

### ISSUE THREAD

**Issue by pgaston** [XiaoMi/mace#574]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 18.04
- **NDK version(e.g., 15c)**:  n.a.
- **GCC version(if compiling for host, e.g., 5.4.0)**:   gcc version 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.12.0-26-gfc973e7d
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**:  n.a.

### Model deploy file (*.yml)
default from tutorial - but didn't get that far

### Describe the problem
Just trying to get started.   I performed per the instructions (as best I could):
- have docker 'lite' image - docker pull registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite
- Created container with the following command ...
- Clear workspace
**QUESTION** - where is the mace git project?    Not here.   Where should I put it?   
(/container/path is what I did - so /container/path/mace is now the git clone)
- ran default - RUNTIME=GPU bash tools/cmake/cmake-build-armeabi-v7a.sh
**FAILED** - 
```
CMAKE_VERSION: 3.11.3
CMake Error at /usr/local/share/cmake-3.11/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file:
  /opt/android-ndk-r12b/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```
- tried to run what I really want - linux for an 820 board
```
/container/path/mace# RUNTIME=GPU bash tools/cmake/cmake-build-aarch64-linux-gnu.sh
CMAKE_VERSION: 3.11.3
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_C_COMPILER:

    /bin/aarch64-linux-gnu-gcc

  is not a full path to an existing compiler tool.
```

Wondering if there is a simple step I missed.    Thanks!

### To Reproduce
Steps to reproduce the problem:
- follow instructions (perhaps missing something critical!)

**Comment by lu229** [comment]
Could not find toolchain file:
  /opt/android-ndk-r12b/build/cmake/android.toolchain.cmake
===============================================
The problem here is that cmake cannot find the path of Android NDK r12c. Have you modified the environment variable of Android NDK? The default NDK version is not r12c and there is no r12c in the docker.

**Comment by pgaston** [comment]
Thanks.    This is a clean use of the docker 'lite'.     I then downloaded the full docker for mace-dev and things worked better.    Not there yet.    Opening another ticket.    Seems like the target environment is stuck.    Probably a num-num mistake - or hopefully missed some simple command...

**Comment by lu229** [comment]
@pgaston You can follow the document step by step, it will be ok.
https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html

**Comment by pgaston** [comment]
Thanks!
