### ISSUE TITLE
执行python tools/converter.py convert --config_file=/path/to/your/model_deployment_file 报错

### ISSUE THREAD

**Issue by zjd1988** [XiaoMi/mace#576]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **NDK version(e.g., 15c)**:  17c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: 0.12.0
- **Python version(2.7)**:  3.5
- **Bazel version (e.g., 0.13.0)**: 0.26.0

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
执行模型转换时报错，
python tools/converter.py convert --config_file=/path/to/your/model_deployment_file

应该是因为python3和python2的版本问题错误导致，python3时，keys()返回的是dict_keys对象，没有extend属性，python2返回的是list对象，有extend属性

### To Reproduce
Steps to reproduce the problem:

1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file

### Error information / logs
Please include the **full** log and/or traceback here.
![企业微信截图_15762243708763](https://user-images.githubusercontent.com/7134030/70782727-ac4fe700-1dc2-11ea-8ef9-73846773219a.png)

Exception has occurred: AttributeError
'dict_keys' object has no attribute 'extend'
  File "/home/xj-zjd/work_space/self_work/mace_code/mace-0.12.0/tools/python/transform/transformer.py", line 1359, in sort_by_execution
    output_nodes.extend(self._option.output_nodes)
  File "/home/xj-zjd/work_space/self_work/mace_code/mace-0.12.0/tools/python/transform/transformer.py", line 137, in run
    changed = transformer()
  File "/home/xj-zjd/work_space/self_work/mace_code/mace-0.12.0/tools/python/convert.py", line 184, in convert_model
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/home/xj-zjd/work_space/self_work/mace_code/mace-0.12.0/tools/python/convert.py", line 75, in convert
    mace_model = convert_model(model_conf)
  File "/home/xj-zjd/work_space/self_work/mace_code/mace-0.12.0/tools/python/convert.py", line 279, in <module>
    convert(conf, flags.output)

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
抱歉， 请使用python2, 或者使用最新master代码， 已修复这个问题。

**Comment by zjd1988** [comment]
哦，好的，谢谢啦！
