### ISSUE TITLE
Exception: errorcode: 134

### ISSUE THREAD

**Issue by QingyueMeng** [XiaoMi/mace#578]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
yes
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Mac OS Mojave 10.14.6)**:
- **NDK version(16b)**:
- **GCC version(4.2.1)**:
- **MACE version (v0.12.0-26-gfc973e7d)**:
- **Python version(2.7)**: 
- **Bazel version (0.13.0)**:

### Model deploy file (*.yml)
```yaml
library_name: humanPose
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  humanPose:
    platform: caffe
    model_file_path: examples/caffemodels/mnasnet_192x144_1031_3.prototxt
    weight_file_path: examples/caffemodels/mnasnet_192x144_1031_3.caffemodel
    model_sha256_checksum: ef2f3c7955f69c276684b4e0f731a0ee8101d73b9df534a9c92ab05763c0b072
    weight_sha256_checksum: 4d18246a687e25e015e66343e8107ce8e1f0799eb0678a5d229d03e1d6c622f2
    subgraphs:
      - input_tensors:
          - blob1
        input_shapes:
          - 1,192,144,3
        output_tensors:
          - cat_blob4
        output_shapes:
          - 1,24,18,32
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/python/run_model.py --config examples/android/mnasnet.yml  --benchmark
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
CMD> adb -s HP18XODBNJ shell sh /data/local/tmp/mace_run/humanPose/cmd.sh
Aborted

Traceback (most recent call last):
  File "tools/python/run_model.py", line 379, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 77, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 86, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 204, in run_model_for_device
    device_ids=flags.target_socs)
  File "/Users/mengqingyue/work/code/mace/tools/python/run_target.py", line 57, in run_target
    dev.run(device_target)
  File "/Users/mengqingyue/work/code/mace/tools/python/utils/device.py", line 199, in run
    target_dir + "/cmd.sh"))
  File "/Users/mengqingyue/work/code/mace/tools/python/utils/device.py", line 58, in execute
    raise Exception("errorcode: %s" % p.returncode)
Exception: errorcode: 134
```

### Additional context
您好，我使用mace转换了mnasnet，但当想对转换的模型进行验证时，发生了上面错误，请问是什么情况呢？

**Comment by lu229** [comment]
@QingyueMeng 这个日志看不到真正的原因，烦请贴一下crash时adb logcat的日志，可参考：[debug-with-crash](https://mace.readthedocs.io/en/latest/development/how_to_debug.html#debug-with-crash)

**Comment by QingyueMeng** [comment]
> @QingyueMeng 这个日志看不到真正的原因，烦请贴一下crash时adb logcat的日志，可参考：[debug-with-crash](https://mace.readthedocs.io/en/latest/development/how_to_debug.html#debug-with-crash)

重新运行了之后报了下面的错误
`
B000000119358A:mace mengqingyue$ python tools/converter.py run --config=examples/android/mnasnet.yml  --debug_mode
CMD> bazel version
Build label: 0.13.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 23 11:16:40 2018 (1527074200)
Build timestamp: 1527074200
Build timestamp as int: 1527074200

CMD> bazel build //mace/proto:mace_py
Loading:
Loading: 0 packages loaded
INFO: Analysed target //mace/proto:mace_py (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 0.589s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
Loading:
Loading: 0 packages loaded
INFO: Analysed target //third_party/caffe:caffe_py (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 0.366s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py tools/python/py_proto

tools/converter.py:336: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
* Build //mace/tools:mace_run_static with ABI arm64-v8a
('build', '//mace/tools:mace_run_static', '--config', 'android', '--cpu=arm64-v8a', '--define', 'neon=true', '--define', 'openmp=false', '--define', 'opencl=true', '--define', 'quantize=false', '--define', 'hexagon=false', '--define', 'hta=false', '--define', 'apu=false', '--config', 'debug', '--per_file_copt=mace/tools/mace_run.cc@-DMODEL_GRAPH_FORMAT_CODE')
INFO: Analysed target //mace/tools:mace_run_static (4 packages loaded).
INFO: Found 1 target...
INFO: From Executing genrule @opencl_clhpp//:gen_opencl_clhpp:
/var/folders/1_/g8l4z5hn7678jcmmt9t8ypf859x2cl/T/opencl-clhpp-build.XXXXXXXXXX.u62KWsJW /private/var/tmp/_bazel_mengqingyue/2e8c7d756d8aa82d1f5c1c14f36a2a9a/sandbox/2935096414039554338/execroot/mace
/var/folders/1_/g8l4z5hn7678jcmmt9t8ypf859x2cl/T/opencl-clhpp-build.XXXXXXXXXX.u62KWsJW/build /var/folders/1_/g8l4z5hn7678jcmmt9t8ypf859x2cl/T/opencl-clhpp-build.XXXXXXXXXX.u62KWsJW /private/var/tmp/_bazel_mengqingyue/2e8c7d756d8aa82d1f5c1c14f36a2a9a/sandbox/2935096414039554338/execroot/mace
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /var/folders/1_/g8l4z5hn7678jcmmt9t8ypf859x2cl/T/opencl-clhpp-build.XXXXXXXXXX.u62KWsJW/build
Scanning dependencies of target generate_clhpp
[100%] Rebuilding cl.hpp ...
[100%] Built target generate_clhpp
Scanning dependencies of target generate_cl2hpp
[100%] Rebuilding cl2.hpp ...
[100%] Built target generate_cl2hpp
/var/folders/1_/g8l4z5hn7678jcmmt9t8ypf859x2cl/T/opencl-clhpp-build.XXXXXXXXXX.u62KWsJW /private/var/tmp/_bazel_mengqingyue/2e8c7d756d8aa82d1f5c1c14f36a2a9a/sandbox/2935096414039554338/execroot/mace
/private/var/tmp/_bazel_mengqingyue/2e8c7d756d8aa82d1f5c1c14f36a2a9a/sandbox/2935096414039554338/execroot/mace
installing to bazel-out/arm64-v8a-dbg/genfiles/external/opencl_clhpp
Target //mace/tools:mace_run_static up-to-date:
  bazel-bin/mace/tools/mace_run_static
INFO: Elapsed time: 425.395s, Critical Path: 18.76s
INFO: 395 processes: 394 darwin-sandbox, 1 local.
INFO: Build completed successfully, 422 total actions
('build', '//mace/tools:mace_run_static', '--config', 'android', '--cpu=arm64-v8a', '--define', 'neon=true', '--define', 'openmp=false', '--define', 'opencl=true', '--define', 'quantize=false', '--define', 'hexagon=false', '--define', 'hta=false', '--define', 'apu=false', '--config', 'debug', '--per_file_copt=mace/tools/mace_run.cc@-DMODEL_GRAPH_FORMAT_CODE')
Build done!

Traceback (most recent call last):
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 938, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/Users/mengqingyue/work/code/mace/tools/device.py", line 601, in run_specify_abi
    self.clear_data_dir()
  File "/Users/mengqingyue/work/code/mace/tools/device.py", line 89, in clear_data_dir
    sh_commands.clear_phone_data_dir(self.address, PHONE_DATA_DIR)
  File "/Users/mengqingyue/work/code/mace/tools/sh_commands.py", line 119, in clear_phone_data_dir
    "rm -rf %s" % phone_data_dir)
  File "/Library/Python/2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Library/Python/2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/Library/Python/2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/Library/Python/2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /Users/mengqingyue/Library/Android/sdk/platform-tools/adb -s HP18XODBNJ shell rm -rf /data/local/tmp/mace_run

  STDOUT:


  STDERR:
error: device 'HP18XODBNJ' not found
`

**Comment by lu229** [comment]
@QingyueMeng ，这次的错误与上次不一样， 这次是：error: device 'HP18XODBNJ' not found，手机的连接出问题了，拔掉或者重启后再连接再试试

**Comment by QingyueMeng** [comment]
> @QingyueMeng 这个日志看不到真正的原因，烦请贴一下crash时adb logcat的日志，可参考：[debug-with-crash](https://mace.readthedocs.io/en/latest/development/how_to_debug.html#debug-with-crash)、

[log.txt](https://github.com/XiaoMi/mace/files/3977496/log.txt)

请问是这个log么？

**Comment by lu229** [comment]
@QingyueMeng 是这个log，但是这个log里面没有任何crash的信息，请重新抓取有crash信息的log
