### ISSUE TITLE
Mac 下可以不用docker进行android平台的交叉编译吗？

### ISSUE THREAD

**Issue by xiaoyaozhuzi** [XiaoMi/mace#58]
如题，想要在mac下交叉编译可以在android上运行的库应该怎么操作，有什么教程吗？

**Comment by lee-bin** [comment]
目前还没有精力提供Mac下编译的官方文档。可以参考#42，#51，欢迎贡献代码和文档

**Comment by wykvictor** [comment]
楼主有啥Update，期待分享。
我尝试mac下用Docker都有很多坑，最后放弃转Ubuntu了～
Mac的Docker可以正常交叉编译mace，但是在docker里通过adb连接android手机会出问题，网上一些解决方案是在mac先安装虚拟机，太繁琐了

**Comment by llhe** [comment]
Mac上可以手动安装依赖，docker不是必须，应该是可以走通的，可以试试。先关掉，有问题可以reopen.
