### ISSUE TITLE
Android demo

### ISSUE THREAD

**Issue by CheungBH** [XiaoMi/mace#584]
Hello. I wonder where I can get the latest version of the android demo. When I am trying to run the android demo in the "examples", some errors occur. 

![image](https://user-images.githubusercontent.com/39186017/71655586-5db6bc80-2d72-11ea-8f0c-bd41332590bf.png)

Since this problem is caused by Android Studio, I wonder whether there are any latest version of updated android demo.

**Comment by lu229** [comment]
@CheungBH  The online version is the latest, the warning does not affect the compilation result, it seems that your compilation has been successful?

**Comment by CheungBH** [comment]
Yes. But when I ran this app on the mobile phone, another error occurs.
![image](https://user-images.githubusercontent.com/39186017/71796171-6fef6e00-3084-11ea-8e34-092be46b8f2f.png)

**Comment by lu229** [comment]
@CheungBH please reference [readme](https://github.com/XiaoMi/mace/tree/master/examples/android) and build the lib first.
