### ISSUE TITLE
No file "libmace.a" and "libmace.so"

### ISSUE THREAD

**Issue by CheungBH** [XiaoMi/mace#585]
Hello.
![image](https://user-images.githubusercontent.com/39186017/71655652-b4bc9180-2d72-11ea-892a-a74c1ef1014b.png)

When I converting the "mobilenet v1" mobile successfully, I found that I can not find the "libmace.a" and "libmace.so" files.

![image](https://user-images.githubusercontent.com/39186017/71655686-e9304d80-2d72-11ea-8cfb-4c692c41b9e8.png)

Since I saw the structure in the official documents that "LIBMACE" files, I wonder where I can find them.

**Comment by lu229** [comment]
@CheungBH please reference [build-mace-into-a-library](https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#build-mace-into-a-library)
