### ISSUE TITLE
dsp下的不支持BatchNorm，但是在nnlib的ops表中其实是有QuantizedBatchNorm_8x8p32to8等这些算子的，这个是目前convert.py还在开发这个功能，还是说实现上有什么问题

### ISSUE THREAD

**Issue by DavinFun** [XiaoMi/mace#588]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
主要是性能上考虑，目前支持的是BatchNorm与前面的Conv/FC等融合的操作。如果确实需要单独的BatchNorm，我们欢迎开发者贡献这块的转换代码。

**Comment by DavinFun** [comment]
现在nnlib的ops表中的QuantizedBatchNorm_8x8p32to8等这些算子是不是DSP主核运行的？主核主频有点低，可能会很慢，我看对应函数上没有加hvx后标

**Comment by lee-bin** [comment]
主要是考虑到融合算子之后会快很多，暂未遇到必须单独支持BatchNorm的情况，因此还未测试过QuantizedBatchNorm_8x8p32to8这个算子的性能。
