### ISSUE TITLE
How to generate inception_v3_q_2015.pb for DSP runtime?  

### ISSUE THREAD

**Issue by samsun639** [XiaoMi/mace#59]
I used below command to generated pb for DSP runtime. The generated graph is not the same as XiaoMi official one(https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception_v3_q_2015.pb).

 ~/tensorflow/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
    --in_graph=inception-v3.pb \
    --out_graph=inception-v3_dsp.pb \
    --inputs='input' \
    --outputs='InceptionV3/Predictions/Reshape_1' \
    --transforms='strip_unused_nodes(type=float, shape="1,299,299,3")
        strip_unused_nodes(type=float, shape="1,299,299,3")
        remove_nodes(op=Identity, op=CheckNumerics)
        fold_constants(ignore_errors=true)
        fold_batch_norms
        fold_old_batch_norms
        backport_concatv2
        quantize_weights(minimum_size=2)
        quantize_nodes
        strip_unused_nodes
        sort_by_execution_order'

And my generated pb has problem when run in DSP runtime:
**InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input' with dtype float and shape [?,299,299,3]
	 [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[?,299,299,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]**

While XiaoMi's official pb(inception_v3_q_2015.pb) is ok to run . 
So how can I generate the pb like inception_v3_q_2015.pb?

Thanks!

**Comment by llhe** [comment]
You need to freeze your model first.

**Comment by llhe** [comment]
Placeholder should be removed by using freeze_graph tool, close this first, feel free to reopen it if you still have problem.
