### ISSUE TITLE
高通GPU能够设置context 优先级，但是未看到MALI GPU有相关的设置，是因为mali gpu不支持吗？

### ISSUE THREAD

**Issue by zjd1988** [XiaoMi/mace#596]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@zjd1988 各个芯片一般会支持设置任务优先级的指令，但是否支持以OpenCL的标准方式是不确定的，目前Mali系列的很少支持，高通的多一些。

**Comment by zjd1988** [comment]
@lu229 谢谢大佬回复，我最近也查了查arm的最新opencl手册，（opencl 2.1之后）发现只支持相同context下的commandqueue的优先级设置，没有看到不同context之间的优先级的设置。

**Comment by zjd1988** [comment]
@lu229  之所以问这个问题，是因为现在网络推理过程中，发现渲染会出现卡顿现象。（可能设置context 想着设置context优先级会不会有所改善）

**Comment by lu229** [comment]
@zjd1988 可以参考各个芯片厂商的opencl手册。不过如果只是需要解决渲染的卡顿问题，这个mace已经解决了，可以参考：[Why is the UI getting poor responsiveness when running model with GPU runtime?](https://mace.readthedocs.io/en/latest/faq.html#why-is-the-ui-getting-poor-responsiveness-when-running-model-with-gpu-runtime)

**Comment by zjd1988** [comment]
@lu229  嗯嗯，谢谢，我看下。
