### ISSUE TITLE
Generating run-time for openCL on linux

### ISSUE THREAD

**Issue by pgaston** [XiaoMi/mace#598]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
  Ubuntu 18.04 laptop, target is Qualcomm 820 w/ Adreno 530, Hexagon DSP
  target is running minimal linux
- **NDK version(e.g., 15c)**: n.a.
- **GCC version(if compiling for host, e.g., 5.4.0)**:  
  gcc version 5.4.0, in mace-dev docker, **however** I changed this to use
  gcc version 4.9.3 to match my target environment with it's libOpenCL.so
  being 32 bit
- **MACE version (Use the command: git describe --long --tags)**: v0.12.0-26-gfc973e7
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**:  n.a.

### Model deploy file (*.yml)
n.a.

### Describe the problem
Trying to build runtime c++ code so I can deploy on target (under ROS.)    Following instructions, e.g.,"Refer to mace/tools/mace_run.cc for full usage. "     (https://mace.readthedocs.io/en/latest/user_guide/advanced_usage_cmake.html)

My thought is to recompile mace_run.cc independently of the full mace build.    The following steps are then simple -- reduce mace_run.cc into just what I need and integrate with ROS.

Problem:
Everything links fine except gflags.    The linker finds the file, the file gflags.a contains the symbols - but it won't link.

### To Reproduce
Steps to reproduce the problem:
```Run mace docker environment.    mace and my folder are at the same level under /container/path inside the docker environment
1. mace_run.cc is copied outside of the mace folder structure, say to /container/path/FDROS/mace_run.cc
2. Run the following command.   
/usr/bin/arm-linux-gnueabi-g++-4.9  \
  mace_run.cc -std=c++11  \
  -march=armv7-a -mfloat-abi=softfp -mfpu=neon-vfpv4 \
  -I /container/path/mace/mace/mace/include/ \
  -I /container/path/mace/mace/mace \
  -L /container/path/mace/mace/mace/build/cmake-build/arm-linux-gnueabihf/install/lib \
  -L /container/path/mace/mace/mace/build/cmake-build/arm-linux-gnueabihf/third_party/install/gflags/lib \
  -lgflags -lgenerated_opencl_kernel -lproto -lprotobuf-lite \
  -lmace -lcore -lmodel -lops -lport_linux -lport_linux_base -lutils -lport_posix -lport_base -lpthread
3. View the error
```

### Error information / logs
Please include the **full** log and/or traceback here.
```
root@619a1c4cffeb:/container/path/FDROS/src# /usr/bin/arm-linux-gnueabi-g++-4.9  \
>   mace_run.cc -std=c++11  \
>   -march=armv7-a -mfloat-abi=softfp -mfpu=neon-vfpv4 \
>   -I /container/path/mace/mace/mace/include/ \
>   -I /container/path/mace/mace/mace \
>   -L /container/path/mace/mace/mace/build/cmake-build/arm-linux-gnueabihf/install/lib \
>   -lgflags -lgenerated_opencl_kernel -lproto -lprotobuf-lite \
>   -lmace -lcore -lmodel -lops -lport_linux -lport_linux_base -lutils -lport_posix -lport_base -lpthread
/tmp/ccpMbT6k.o: In function `__static_initialization_and_destruction_0(int, int)':
mace_run.cc:(.text+0x5644): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
mace_run.cc:(.text+0x56fc): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
mace_run.cc:(.text+0x57b4): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
mace_run.cc:(.text+0x586c): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
mace_run.cc:(.text+0x5924): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/tmp/ccpMbT6k.o:mace_run.cc:(.text+0x59dc): more undefined references to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
collect2: error: ld returned 1 exit status
```

### Thanks!!!

**Comment by lu229** [comment]
@pgaston Where is the gflag library from? Is it compiled with the same compiler as mace_run.cc? perhaps you can see if there is a slight difference between the symbols in mace_run.o and gflag Library. In addition, you can refer to [this issue](https://github.com/gflags/gflags/issues/203).

**Comment by pgaston** [comment]
The gflag library is the same one that mace built when I do the full build.   And mace_run was sucessfully built at that time, and runs on the target.   So go figure.

All this said, never mind as my target doesn't need gflags.    I'll either hard code or get parameters from a config file.

As always, thanks for your wonderful and timely help!
