### ISSUE TITLE
如何使用另外的自己的tensorflow模型

### ISSUE THREAD

**Issue by hongsui169163** [XiaoMi/mace#60]
HI:
    如题，我手上有一个模型，我看贵司提供的yaml
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
   会做一下checksum，我们如果用我们自己的模型，就无法通过编译。
    请问如何添加我们自己的模型训练数据进去？感谢

**Comment by TonyMou** [comment]
#54
