### ISSUE TITLE
Question about hexagon DSP libhexagon_controller.so 

### ISSUE THREAD

**Issue by huanyingjun** [XiaoMi/mace#600]
hello
Mace DSP is based on hexagon nnlib, what is libhexagon_controller.so used for? 
where is the source code for libhexagon_controller.so ?

thanks very much.

**Comment by lee-bin** [comment]
@huanyingjun 
libhexagon_controller.so is used to link with MACE to call stub routine of nnlib.
You can find more info from [here](https://github.com/XiaoMi/nnlib).

**Comment by huanyingjun** [comment]
@lee-bin 
感谢您的回复
用mace跑DSP需要手机有root权限并将libhexagon_nn_skel.so  push到 /system/vendor/lib/rfsa/adsp/

我对比了tflite，tflite hexagon delegate不需要手机root权限，可以将libhexagon_nn_skel.so push到手机的任意目录，然后在代码进行相应设置就可以了。
Mace是否也可以增加类似功能？这样调式DSP会方便很多。

tflite 设置DSP路径代码
![dsp](https://user-images.githubusercontent.com/29744812/75125045-05ef5e80-56ee-11ea-998f-a64ed6e19688.PNG)

**Comment by lee-bin** [comment]
可以的，用ADSP_LIBRARY_PATH设置libhexagon_nn_skel.so目录即可。

**Comment by huanyingjun** [comment]
thanks
