### ISSUE TITLE
MACE on Linux takes too much time

### ISSUE THREAD

**Issue by Volcanoscar** [XiaoMi/mace#604]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 1804
- **NDK version(e.g., 15c)**:16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:7.4
- **MACE version (Use the command: git describe --long --tags)**:v0.11.0-rc0-0-g2d650b67
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Describe the problem
The same model takes quite a long time running on Linux than running on a mobile device. Say it takes 30ms on MSM636 while taking unbelievably 3000+ms on Linux(PC).

**Comment by gasgallo** [comment]
Currently MACE is not optimized for `x86` architecture.

See https://github.com/XiaoMi/mace/issues/423.
