### ISSUE TITLE
Asking about terms in MACE RUN

### ISSUE THREAD

**Issue by ramawidrap** [XiaoMi/mace#608]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Describe the problem
I would like to ask about the terms in this screen shoot.
1. What is total init latency and the difference between create init latency and create mace engine latency
2.what is warm up latency and time in 1st warm up latency
3.what is average latency ? is it the average of inference time for run the model?
4.what is time in the capability(CPU) in that screenshoot show time 29.017

![image](https://user-images.githubusercontent.com/36231029/77044197-8f463800-69f1-11ea-9326-9db7f5641500.png)

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py run --config_file=/path/to/your/model_deployment_file
```

**Comment by lee-bin** [comment]
1. `total init latency` and `create mace engine latency` are basically the same thing, except a trivial retrying mechanism for `total init latency` if creating mace engine failed.
2. They are the same thing, which is the first inference time to run the model.
3. Yes. Generally, `run_avg` should be faster than `warmup` as some overhead, e.g., some memory allocation, etc., is bypassed after the first run. Maybe the model was run too many rounds continuously that heated the device too much, or it was racing resources with other applications.
4.  The `capability` time is the inference time of a small model (created in mace_run.cc) to get a grasp of device capability.

**Comment by ramawidrap** [comment]
hei thankyou for ansnwer but i got different problem.

when i ran tools/bazel-build-standalone-lib.sh i found problem

could u reply this issue https://github.com/XiaoMi/mace/issues/610? 
thankyou!! @lee-bin

**Comment by lee-bin** [comment]
@ramawidrap  See comment in https://github.com/XiaoMi/mace/issues/610#issuecomment-601582068.
