### ISSUE TITLE
Open input file failed

### ISSUE THREAD

**Issue by lyp0413** [XiaoMi/mace#61]
Can anyone help me,thank u!
----------------------------------------------------------------------------------------------------------------------------
cloud@cloud-System-Product-Name:~/lyp/mace/bazel-bin/mace/tools/validation$ ./mace_run_static 
I mace/tools/validation/mace_run.cc:420] model name: fast_style_transfer_scream
I mace/tools/validation/mace_run.cc:421] mace version: v0.8.1-85-g4c24c63-20180710
I mace/tools/validation/mace_run.cc:422] input node: img_placeholder
I mace/tools/validation/mace_run.cc:423] input shape: 1,480,640,3
I mace/tools/validation/mace_run.cc:424] output node: add_37
I mace/tools/validation/mace_run.cc:425] output shape: 1,480,640,3
I mace/tools/validation/mace_run.cc:426] input_file: /home/cloud/lyp/mace/bazel-bin/mace/tools/validation/chicago.npy 
I mace/tools/validation/mace_run.cc:427] output_file: 
I mace/tools/validation/mace_run.cc:428] model_data_file: /home/cloud/lyp/mace/builds/fast_style_transfer_scream/model/fast_style_transfer_scream.data
I mace/tools/validation/mace_run.cc:429] model_file: /home/cloud/lyp/mace/builds/fast_style_transfer_scream/model/fast_style_transfer_scream.pb
I mace/tools/validation/mace_run.cc:430] device: CPU
I mace/tools/validation/mace_run.cc:431] round: 1
I mace/tools/validation/mace_run.cc:432] restart_round: 1
I mace/tools/validation/mace_run.cc:433] gpu_perf_hint: 3
I mace/tools/validation/mace_run.cc:434] gpu_priority_hint: 3
I mace/tools/validation/mace_run.cc:435] omp_num_threads: -1
I mace/tools/validation/mace_run.cc:436] cpu_affinity_policy: 1
I mace/tools/validation/mace_run.cc:459] restart round 0
W mace/core/runtime/cpu/cpu_runtime.cc:145] Set OpenMP threads number failed: OpenMP not enabled.
I mace/core/mace.cc:379] Create MaceEngine from model pb
I mace/core/mace.cc:165] Creating MaceEngine, MACE version: v0.8.1-85-g4c24c63-20180710
I mace/core/mace.cc:233] Loading Model Data
I mace/core/mace.cc:173] Initializing MaceEngine
I mace/tools/validation/mace_run.cc:265] Total init latency: 43.999 ms
I mace/tools/validation/mace_run.cc:290] Open input file failed
I mace/core/mace.cc:252] Destroying MaceEngine

**Comment by nolanliou** [comment]
最好使用`tools/converter.py`来运行，因为参数较多。具体运行命令请参考converter.py

**Comment by llhe** [comment]
@lyp0413 is this resolved?

**Comment by lyp0413** [comment]
@llhe yes,but I still have a question.
When I use fast-nerual-transfer model,I find the input values provided as 'chicago.npy' is between[-1,1],while the output values is between[-22.5,277.5].
I wanna know the meaning of the output values.
Thank U.

**Comment by TonyMou** [comment]
the output  values are pixel values of the output image.

**Comment by lyp0413** [comment]
@TonyMou  So why exist values out of range [0,255]

**Comment by TonyMou** [comment]
because input is [-1, 1], Use this python code after inference:

`np.clip(out_data, 0, 255).astype(np.uint8)`

**Comment by llhe** [comment]
@lyp0413 You can read the code here https://github.com/lengstrom/fast-style-transfer for more details.

**Comment by lyp0413** [comment]
ok thank U @llhe @TonyMou
