### ISSUE TITLE
Problem when run bash tools/bazel-build-standalone-lib.sh 

### ISSUE THREAD

**Issue by ramawidrap** [XiaoMi/mace#610]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOs Catalina 10.15.3
- **NDK version(e.g., 15c)**: r15c
- **MACE version : v0.12.0-0-ga610d506
- **Python :  2.7
- **Bazel version : 0.13.0

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
Help me solve this issue. i found this problem when i run this command bash tools/bazel-build-standalone-lib.sh. i nneed libmace.a and libmace.so to deploy to android. the shared library success to generate but when generate shared library to produce libmace.a i found the error. Eventually, i just have libmace.so and libmace.a doesn't generated.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2.bash tools/bazel-build-standalone-lib.sh 
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
installing to bazel-out/armhf-opt/genfiles/external/opencl_clhpp
ERROR: /Users/ramaputra/Documents/Work/skripsi/mace/mace/ops/BUILD.bazel:184:1: C++ compilation of rule '//mace/ops:internal_ops' failed (Exit 1): arm-linux-gnueabihf-gcc failed: error executing command
  (cd /private/var/tmp/_bazel_ramaputra/ccd9e570a2acd90e1179e4fb17779fae/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  tools/arm_compiler/linaro_linux_gcc/arm-linux-gnueabihf-gcc '--sysroot=external/gcc_linaro_7_3_1_arm_linux_gnueabihf/arm-linux-gnueabihf/libc' -U_FORTIFY_SOURCE -fstack-protector -fPIE '-fdiagnostics-color=always' -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -isystem external/gcc_linaro_7_3_1_arm_linux_gnueabihf/arm-linux-gnueabihf/include/c++/7.3.1/arm-linux-gnueabihf -isystem external/gcc_linaro_7_3_1_arm_linux_gnueabihf/arm-linux-gnueabihf/include/c++/7.3.1 -isystem external/gcc_linaro_7_3_1_arm_linux_gnueabihf/include/c++/7.3.1/arm-linux-gnueabihf -isystem external/gcc_linaro_7_3_1_arm_linux_gnueabihf/include/c++/7.3.1 -MD -MF bazel-out/armhf-opt/bin/mace/ops/_objs/internal_ops/mace/ops/matmul.pic.d '-frandom-seed=bazel-out/armhf-opt/bin/mace/ops/_objs/internal_ops/mace/ops/matmul.pic.o' -fPIC -iquote . -iquote bazel-out/armhf-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armhf-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/armhf-opt/genfiles/external/com_google_protobuf -iquote external/half -iquote bazel-out/armhf-opt/genfiles/external/half -iquote external/opencl_clhpp -iquote bazel-out/armhf-opt/genfiles/external/opencl_clhpp -iquote external/opencl_headers -iquote bazel-out/armhf-opt/genfiles/external/opencl_headers -iquote external/gemmlowp -iquote bazel-out/armhf-opt/genfiles/external/gemmlowp -iquote external/tflite -iquote bazel-out/armhf-opt/genfiles/external/tflite -Ibazel-out/armhf-opt/bin/include/_virtual_includes/public_headers -Ibazel-out/armhf-opt/bin/external/opencl_clhpp/_virtual_includes/opencl_clhpp -Ibazel-out/armhf-opt/bin/external/opencl_headers/_virtual_includes/opencl20_headers -isystem external/com_google_protobuf/src -isystem bazel-out/armhf-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/armhf-opt/bin/external/com_google_protobuf/src '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD '-mfloat-abi=hard' '-mfpu=neon' -Wno-ignored-attributes -Wno-unused-function -Wno-sequence-point -Wno-implicit-fallthrough '-mfloat-abi=hard' '-mfpu=neon' -Wno-ignored-attributes -Wno-unused-function -Wno-sequence-point -Wno-implicit-fallthrough -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers -DMACE_ENABLE_NEON -DMACE_ENABLE_OPENCL -DMACE_ENABLE_QUANTIZE -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mace/ops/matmul.cc -o bazel-out/armhf-opt/bin/mace/ops/_objs/internal_ops/mace/ops/matmul.pic.o)
tools/arm_compiler/linaro_linux_gcc/arm-linux-gnueabihf-gcc: line 3: /private/var/tmp/_bazel_ramaputra/ccd9e570a2acd90e1179e4fb17779fae/execroot/mace/external/gcc_linaro_7_3_1_arm_linux_gnueabihf/bin/arm-linux-gnueabihf-gcc: cannot execute binary file
tools/arm_compiler/linaro_linux_gcc/arm-linux-gnueabihf-gcc: line 3: /private/var/tmp/_bazel_ramaputra/ccd9e570a2acd90e1179e4fb17779fae/execroot/mace/external/gcc_linaro_7_3_1_arm_linux_gnueabihf/bin/arm-linux-gnueabihf-gcc: Undefined error: 0
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 7.989s, Critical Path: 2.01s
INFO: 1 process, local.
FAILED: Build did NOT complete successfully
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
If you only want to deploy to android devices, you can comment out the other ABIs in `tools/bazel-build-standalone-lib.sh` and only build `arm64-v8a` or `armeabi-v7a`. And you don't need both shared libraries and static libraries to deploy, just select one format is OK.
For example, if you need to deploy to devices with ABI: `arm64-v8a`, runtime: `GPU`, and shared library, you can just keep this part: `build shared lib for arm64-v8a + cpu_gpu` and comment out all the other builds.

**Comment by ramawidrap** [comment]
whats the difference between shared and static ?

**Comment by lee-bin** [comment]
They provide the same functionality.

**Comment by ramawidrap** [comment]
hey i succed generate static library. but i found new issue got error like this

/Users/ramaputra/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:373: error: undefined reference to 'mace::MaceEngine::~MaceEngine()'

**Comment by ramawidrap** [comment]
> hey i succed generate static library. but i found new issue got error like this
> 
> /Users/ramaputra/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:373: error: undefined reference to 'mace::MaceEngine::~MaceEngine()'

i get this issue after i try to deploy my code model to android

**Comment by ramawidrap** [comment]
sorry for asking to many question. i get new error like this
ninja: error: '../../../../src/main/cpp/lib/armeabi-v7a/libmace.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmace_mobile_jni.so', missing and no known rule to make it

**Comment by lee-bin** [comment]
You can refer to [examples/android](https://github.com/XiaoMi/mace/tree/master/examples/android) and  [examples/android/build.sh](https://github.com/XiaoMi/mace/blob/master/examples/android/build.sh) to generate and copy the required files.
