### ISSUE TITLE
Maybe you guys made a spell mistake

### ISSUE THREAD

**Issue by Charleshzhang** [XiaoMi/mace#613]
https://github.com/XiaoMi/mace/blob/master/tools/python/transform/onnx_converter.py

in convert_reduce:

line 1286

"if 'axes' in node.attrs:"

I think maybe it should be "axis"?

maybe the onnx supported model never used this part of logic, so no problem found till now

**Comment by lee-bin** [comment]
I don't think it's misspelled. Here is the ONNX [docs](https://github.com/onnx/onnx/blob/rel-1.5.0/docs/Operators.md#ReduceMean).
```
axes : list of ints
A list of integers, along which to reduce. The default is to reduce over all the dimensions of the input tensor.
```

**Comment by Charleshzhang** [comment]
> I don't think it's misspelled. Here is the ONNX [docs](https://github.com/onnx/onnx/blob/rel-1.5.0/docs/Operators.md#ReduceMean).
> 
> ```
> axes : list of ints
> A list of integers, along which to reduce. The default is to reduce over all the dimensions of the input tensor.
> ```

OK got it, seems it's onnx's fault. lol.
Have a nice day.

**Comment by lee-bin** [comment]
That's not ONNX's fault either, `axes` is the plural for `axis`.

**Comment by Charleshzhang** [comment]
> That's not ONNX's fault either, `axes` is the plural for `axis`.

8说了，老铁，我是丈育
