### ISSUE TITLE
Cannot use quantization tool for cmake users

### ISSUE THREAD

**Issue by tqcheng** [XiaoMi/mace#614]
when I run following command, 
For CMake users:
python tools/python/run_model.py --config ../mace-models/inception-v3/inception-v3.yml
  --quantize_stat --input_dir /path/to/directory/of/input/tensors > range_log

it display some error：
ERROR: unknown command line flag 'quantize_stat'

**Comment by lee-bin** [comment]
@tqcheng  Thanks, before we change that, you can use bazel first.
