### ISSUE TITLE
Resize bicubic kernel: support for half_pixel_centers argument

### ISSUE THREAD

**Issue by chiraggirdhar95** [XiaoMi/mace#616]
Current OPENCL kernel for resize bicubic kernel doesn't support the argument  "half_pixel_centers", 
https://www.tensorflow.org/api_docs/python/tf/raw_ops/ResizeBicubic

**Comment by lu229** [comment]
@chiraggirdhar95 yes it is not supported for we seldom use this argument, welcome to contribute code.
