### ISSUE TITLE
加载arm64-v8a libmace.so, 编译CPP文件时出现 ld.lld: error: undefined symbol: mace::MaceTensor::MaceTensor

### ISSUE THREAD

**Issue by wth0928** [XiaoMi/mace#617]
### System information
- **Linux Ubuntu 18.04**:
- **NDK version(e.g., 18b/17c)**:
- **GCC versiongcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0**:
- **MACE versionv 0.12.0-44-g46d3bd53**:
- **Python version(Python 2.7.17)**:
- **Bazel version (0.13.1)**:
 
### Describe the problem
执行./tools/bazel-build-standalone-lib.sh 并且生成 arm64-v8a/libmace.so
然后在Android HAL层尝试写一个C++文件，加载arm64-v8a/libmace.so调用MACE相关函数，但是出现了ld.lld err
 
### To Reproduce
Steps to reproduce the problem:
1.cd /path/to/mace
2. ./tools/bazel-build-standalone-lib.sh
3. cp libmace.so
4. make mace_test

### Error information / logs

ld.lld: error: undefined symbol: mace::CreateMaceEngineFromProto(unsigned char const*, unsigned long, unsigned char const*, unsigned long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, mace::MaceEngineConfig const&, std::__1::shared_ptr<mace::MaceEngine>*)
>>> referenced by mace_mode_test.cpp:110 (vendor/pvendor/proprietary/touch/rawdata_hostprocess/mace_mode_test.cpp:110)
>>> out/target/product/u/obj/EXECUTABLES/mace_test_intermediates/mace_mode_test.o:(Create_Mace_Engine(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<long, std::__1::allocator<long> > const&, std::__1::vector<mace::DataFormat, std::__1::allocator<mace::DataFormat> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<long, std::__1::allocator<long> > const&, std::__1::vector<mace::DataFormat, std::__1::allocator<mace::DataFormat> > const&, float))

### Additional context
C++ code：

void Create_Mace_Engine(const std::vector<std::string> &input_names,
                        const std::vector<int64_t> &input_shapes,
                        const std::vector<DataFormat> &input_data_formats,
                        const std::vector<std::string> &output_names,
                        const std::vector<int64_t> &output_shapes,
                        const std::vector<DataFormat> &output_data_formats,
                        float cpu_capability) {
  int64_t t0 = NowMicros();
  MaceEngineConfig config(device_type);
  status = config.SetCPUThreadPolicy(4, static_cast<CPUAffinityPolicy >(AFFINITY_HIGH_PERFORMANCE));
  if (status != MaceStatus::MACE_SUCCESS) {
    LOG(WARNING) << "Set openmp or cpu affinity failed.";
  }
//read pb file
  std::unique_ptr<mace::port::ReadOnlyMemoryRegion> model_graph_data = make_unique<mace::port::ReadOnlyBufferMemoryRegion>();
  if (MODEL_PB_FILE_PATH != "") {
    auto fs = GetFileSystem();
    status = fs->NewReadOnlyMemoryRegionFromFile(MODEL_PB_FILE_PATH,
        &model_graph_data);
    if (status != MaceStatus::MACE_SUCCESS) {
      LOG(FATAL) << "Failed to read file: " << MODEL_PB_FILE_PATH;
    }
  }
//read data file
  std::unique_ptr<mace::port::ReadOnlyMemoryRegion> model_weights_data = make_unique<mace::port::ReadOnlyBufferMemoryRegion>();
  if (MODEL_DATA_FILE_PATH != "") {
    auto fs = GetFileSystem();
    status = fs->NewReadOnlyMemoryRegionFromFile(MODEL_DATA_FILE_PATH,
        &model_weights_data);
    if (status != MaceStatus::MACE_SUCCESS) {
      LOG(FATAL) << "Failed to read file: " << MODEL_DATA_FILE_PATH;
    }
  }
//create mace engine
  if (model_graph_data == nullptr || model_weights_data == nullptr) {
    LOG(INFO) << "Please specify model graph file and model data file";
    return;
  }
  create_engine_status = CreateMaceEngineFromProto(reinterpret_cast<const unsigned char *>(model_graph_data->data()), model_graph_data->length(),
                                                  reinterpret_cast<const unsigned char *>(model_weights_data->data()),model_weights_data->length(),
                                                  input_names,output_names,config,&engine);
  int64_t t1 = NowMicros();
  if (create_engine_status != MaceStatus::MACE_SUCCESS) {
    LOG(ERROR) << "Create engine runtime error, retry ... errcode: " << create_engine_status.information();
  } else {
    double create_engine_millis = (t1 - t0) / 1000.0;
    LOG(INFO) << "Create Mace Engine latency: " << create_engine_millis << " ms";
  }
  //set input tensor size and output tensor size
  LOG(INFO) << "input tensor and output tensor size is: " << input_count << ", " << output_count;
  for (size_t i = 0; i < input_count; ++i) {
    int64_t input_size = std::accumulate(input_shapes.begin(), input_shapes.end(), 4, std::multiplies<int64_t>());
    if(input_size != NODE_SIZE)
      LOG(ERROR) << "Create engine runtime error, input tensor size: " << input_size << "not match diff data size: " << NODE_SIZE;
    inputs_size[input_names[i]] = input_size;
    auto buffer_in = std::shared_ptr<float>(new float[input_size], std::default_delete<float[]>());
    inputs[input_names[i]] = mace::MaceTensor(input_shapes, buffer_in,input_data_formats[i]);
  }
  for (size_t i = 0; i < input_count; ++i) {
    int64_t output_size = std::accumulate(output_shapes.begin(), output_shapes.end(), 4,std::multiplies<int64_t>());
    auto buffer_out = std::shared_ptr<float>(new float[output_size], std::default_delete<float[]>());
    outputs[output_names[i]] = mace::MaceTensor(output_shapes, buffer_out,output_data_formats[i]);
  }
  return;
}

Android.mk

include $(CLEAR_VARS)
LOCAL_MODULE:= libmace
LOCAL_SRC_FILES :=  ./lib64/libmace.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_VENDOR_MODULE           := true
LOCAL_MODULE_TAGS             := optional
LOCAL_C_INCLUDES              := $(LOCAL_PATH)/include
LOCAL_SHARED_LIBRARIES := \
    libutils libhardware liblog libcutils libmace

LOCAL_MODULE:= mace_test
LOCAL_SRC_FILES:= \
   mace_mode_test.cpp

LOCAL_CPPFLAGS += -std=c++11
LOCAL_CPPFLAGS += -fPIC -Wl,-z,notext -fPIE
LOCAL_CPPFLAGS += -DTF_LITE_DISABLE_X86_NEON
LOCAL_CPPFLAGS += -DNAMESPACE_FOR_HASH_FUNCTIONS=farmhash
LOCAL_CPPFLAGS += -Wall
LOCAL_CPPFLAGS += -Werror
LOCAL_CPPFLAGS += -Wextra
LOCAL_CPPFLAGS += -Wno-unused-function
LOCAL_CPPFLAGS += -Wno-unused-lambda-capture
LOCAL_CPPFLAGS += -Wno-unused-local-typedef
LOCAL_CPPFLAGS += -Wno-unused-parameter
LOCAL_CPPFLAGS +=  -Wno-unused-private-field
LOCAL_CPPFLAGS += -Wno-unused-variable
LOCAL_CPPFLAGS += -Wno-invalid-partial-specialization
LOCAL_CPPFLAGS += -Wno-mismatched-tags
#LOCAL_LDLIBS += -pthread
#LOCAL_LDLIBS += -lrt
LOCAL_LDLIBS += -ldl
LOCAL_LDLIBS += -v
LOCAL_MODULE_PATH:= $(TARGET_OUT_VENDOR)/bin

LOCAL_MODULE_TAGS := optional

include  $(BUILD_EXECUTABLE)

**Comment by wth0928** [comment]
@lee-bin 能帮忙看下么

**Comment by lu229** [comment]
@wth0928 运行./tools/bazel-build-standalone-lib.sh时编译mace时, ndk的版本是多少?

**Comment by wth0928** [comment]
@lu229 NDK 版本我试过了r15c, r17c, r18b。都是一样的错误

**Comment by lu229** [comment]
@wth0928 看起来不是NDK版本的问题，那需要调试了。
目前看, HAL层使用的是libc++, 你可以使用NDK里面的工具nm来查看一下so里面的导出函数, 例如: `nm -D libmace.so|grep CreateMaceEngineFromProto`，然后看一下libmace.so里面的函数和错误日志里的函数有什么区别。

**Comment by wth0928** [comment]
只能看到so库中存在 CreateMaceEngineFromProto 函数
```
(mace) ui-group@uigroup-OptiPlex-9020:~/ML-project/android-ndk/android-ndk-r18b$ ./toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/aarch64-linux-android/bin/nm -D ~/ML-project/mace/build/lib/arm64-v8a/cpu_gpu/libmace.so|grep CreateMaceEngineFromProto
00000000000807bc T _ZN4mace25CreateMaceEngineFromProtoEPKhmS1_mRKNSt6__ndk16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEESD_RKNS_16MaceEngineConfigEPNS2_10shared_ptrINS_10MaceEngineEEE
0000000000080a6c T _ZN4mace25CreateMaceEngineFromProtoERKNSt6__ndk16vectorIhNS0_9allocatorIhEEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS2_IcEEEERKNS1_ISB_NS2_ISB_EEEESH_RKNS_16MaceEngineConfigEPNS0_10shared_ptrINS_10MaceEngineEEE

```

**Comment by lee-bin** [comment]
@wth0928  目前NDK默认linker不是lld，https://developer.android.com/ndk/downloads/revision_history
你的代码是采用的lld链接的吗？

**Comment by wth0928** [comment]
从编译log来看，应该是lld链接。我参看最新NDK修改下试试，多谢
@lee-bin

**Comment by lee-bin** [comment]
@wth0928 都用lld问题就解决了吗？

**Comment by wth0928** [comment]
@lee-bin 还在研究，感觉是要在编译libmace.so 时配置LOCAL_LDFLAGS += -fuse-ld=ld.lld
但是只是使用r21版本NDK编译mace会报错
`ERROR: /home/ui-group/ML-project/mace/mace/codegen/BUILD.bazel:59:1: C++ compilation of rule '//mace/codegen:generated_version' failed (Exit 1): clang failed: error executing command
  (cd /home/ui-group/.cache/bazel/_bazel_ui-group/8382b57bc05d881fe27e543adaa4fca6/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=21' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/mace/codegen/_objs/generated_version/mace/codegen/version/version.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/mace/codegen/_objs/generated_version/mace/codegen/version/version.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD -Wall -Wno-mismatched-tags -Wno-missing-braces -Wall -Wno-mismatched-tags -Wno-missing-braces -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/android/support/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c bazel-out/armeabi-v7a-opt/genfiles/mace/codegen/version/version.cc -o bazel-out/armeabi-v7a-opt/bin/mace/codegen/_objs/generated_version/mace/codegen/version/version.o)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/armeabi-v7a-opt/genfiles/mace/codegen/version/version.cc:21:66: error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]
const char *MaceVersion() { return "MACEVER-v0.12.0-44-g46d3bd5" + 8; }
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
bazel-out/armeabi-v7a-opt/genfiles/mace/codegen/version/version.cc:21:66: note: use array indexing to silence this warning
const char *MaceVersion() { return "MACEVER-v0.12.0-44-g46d3bd5" + 8; }
                                                                 ^
                                   &                             [  ]
1 error generated.
Target //mace/libmace:libmace_dynamic failed to build
`

**Comment by lu229** [comment]
@wth0928  可以先改下代码, 将`+8`去掉, 不影响功能

**Comment by wth0928** [comment]
仔细看了下NDK的修订记录，使用r20b 版本的NDK进行编译，mace CMakeLists.txt做了如下修改：
```
(mace) ui-group@uigroup-OptiPlex-9020:~/ML-project/mace$ git diff CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 17fa7ec3..f0e2f5d4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -26,7 +26,6 @@ if(MACE_ENABLE_CCACHE)
     set(CMAKE_C_COMPILER_LAUNCHER   ccache)
   endif(CCACHE_FOUND)
 endif(MACE_ENABLE_CCACHE)
-
 # TODO make these flags well defined and organized
 # TODO enable sanitizer
 set(MACE_CC_FLAGS "${MACE_CC_FLAGS} -fPIC")
@@ -120,6 +119,7 @@ if(MACE_ENABLE_OBFUSCATE)
   add_definitions(-DMACE_OBFUSCATE_LITERALS)
 endif(MACE_ENABLE_OBFUSCATE)

+set(MACE_LINKER_FLAGS "${MACE_LINKER_FLAGS} -fuse-ld=lld")
 if(NOT MSVC)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${MACE_CODE_CC_FLAGS} ${MACE_CC_FLAGS}")
   set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${MACE_LINKER_FLAGS}")
```
基于Android Q code的Cpp文件链接arm64-v8a/libmace.so，仍然会报错。不知道是不是我修改CMakeLists有问题
```
clang version 8.0.12 for Android NDK
Snapdragon LLVM ARM Compiler 8.0.12 for Android NDK (based on llvm.org 7.0+)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /home/wangtonghui/Code_backup/j2-dev/vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/bin
 "/home/wangtonghui/Code_backup/j2-dev/vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/bin/ld.lld" -pie -EL --fix-cortex-a53-843419 -z now -z relro --hash-style=gnu --hash-style=both --enable-new-dtags --eh-frame-hdr -m aarch64linux -dynamic-linker /system/bin/linker64 -o out/target/product/umi/obj/EXECUTABLES/mace_test_intermediates/LINKED/mace_test -L/home/wangtonghui/Code_backup/j2-dev/vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/lib/clang/8.0.12/lib/linux/aarch64 -dynamic-linker /system/bin/linker64 --gc-sections -z nocopyreloc out/soong/.intermediates/bionic/libc/crtbegin_dynamic/android_arm64_armv8-a_kryo300_vendor/crtbegin_dynamic.o out/target/product/umi/obj/EXECUTABLES/mace_test_intermediates/mace_mode_test.o --whole-archive --no-whole-archive out/target/product/umi/obj/STATIC_LIBRARIES/libclang_rt.ubsan_minimal-aarch64-android.vendor_intermediates/libclang_rt.ubsan_minimal-aarch64-android.vendor.a prebuilts/clang/host/linux-x86/clang-r353983c/lib64/clang/9.0.3/lib/linux//libclang_rt.builtins-aarch64-android.a out/target/product/umi/obj/STATIC_LIBRARIES/libatomic_intermediates/libatomic.a out/target/product/umi/obj/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a -z noexecstack -z relro -z now --build-id=md5 --warn-shared-textrel --fatal-warnings --no-undefined-version --exclude-libs libgcc.a --exclude-libs libgcc_stripped.a --hash-style=gnu --icf=safe -z max-page-size=4096 --pack-dyn-relocs=none -execute-only --exclude-libs libclang_rt.ubsan_minimal-aarch64-android.a --no-undefined out/target/product/umi/obj/SHARED_LIBRARIES/libutils.vendor_intermediates/libutils.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/libhardware.vendor_intermediates/libhardware.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/liblog.vendor_intermediates/liblog.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/libcutils.vendor_intermediates/libcutils.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/libmace_intermediates/libmace.so out/target/product/umi/obj/SHARED_LIBRARIES/libdl.vendor_intermediates/libdl.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/libc++.vendor_intermediates/libc++.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/libc.vendor_intermediates/libc.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/libm.vendor_intermediates/libm.vendor.so out/target/product/umi/obj/SHARED_LIBRARIES/libdl.vendor_intermediates/libdl.vendor.so out/soong/.intermediates/bionic/libc/crtend_android/android_arm64_armv8-a_kryo300_vendor/obj/bionic/libc/arch-common/bionic/crtend.o
ld.lld: error: undefined symbol: mace::CreateMaceEngineFromProto(unsigned char const*, unsigned long, unsigned char const*, unsigned long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, mace::MaceEngineConfig const&, std::__1::shared_ptr<mace::MaceEngine>*)
>>> referenced by mace_mode_test.cpp:110 (vendor/xiaomi/proprietary/touch/rawdata_hostprocess/mace_mode_test.cpp:110)
>>>               out/target/product/umi/obj/EXECUTABLES/mace_test_intermediates/mace_mode_test.o:(Create_Mace_Engine(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<long, std::__1::allocator<long> > const&, std::__1::vector<mace::DataFormat, std::__1::allocator<mace::DataFormat> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<long, std::__1::allocator<long> > const&, std::__1::vector<mace::DataFormat, std::__1::allocator<mace::DataFormat> > const&, float))
```

**Comment by lu229** [comment]
@wth0928 ld.lld: error: undefined symbol: mace::CreateMaceEngineFromProto(unsigned char const*, unsigned long, unsigned char const*, unsigned long, 
我看源代码里这个函数的第二个参数和第四个参数, 都是有const修饰的, 你这里是改了源码?

**Comment by wth0928** [comment]
这块code参考 mace_run.cc写的，没有做修改
```
//read pb file
  std::unique_ptr<mace::port::ReadOnlyMemoryRegion> model_graph_data = make_unique<mace::port::ReadOnlyBufferMemoryRegion>();
  if (MODEL_PB_FILE_PATH != "") {
    auto fs = GetFileSystem();
    status = fs->NewReadOnlyMemoryRegionFromFile(MODEL_PB_FILE_PATH,
        &model_graph_data);
    if (status != MaceStatus::MACE_SUCCESS) {
      LOG(FATAL) << "Failed to read file: " << MODEL_PB_FILE_PATH;
    }
  }

//read data file
  std::unique_ptr<mace::port::ReadOnlyMemoryRegion> model_weights_data = make_unique<mace::port::ReadOnlyBufferMemoryRegion>();
  if (MODEL_DATA_FILE_PATH != "") {
    auto fs = GetFileSystem();
    status = fs->NewReadOnlyMemoryRegionFromFile(MODEL_DATA_FILE_PATH,
        &model_weights_data);
    if (status != MaceStatus::MACE_SUCCESS) {
      LOG(FATAL) << "Failed to read file: " << MODEL_DATA_FILE_PATH;
    }
  }
//create mace engine
  if (model_graph_data == nullptr || model_weights_data == nullptr) {
    LOG(INFO) << "Please specify model graph file and model data file";
    return;
  }
  create_engine_status = CreateMaceEngineFromProto(reinterpret_cast<const unsigned char *>(model_graph_data->data()), model_graph_data->length(),
                                                  reinterpret_cast<const unsigned char *>(model_weights_data->data()),model_weights_data->length(),
                                                  input_names,output_names,config,&engine);
```

**Comment by wth0928** [comment]
看起来直接编译出来的libmace.so 使用android P的code去链接也会报错。跟NDK版本以及链接器类型无关
```
Target: aarch64--linux-android
Thread model: posix
Snapdragon LLVM ARM Compiler 6.0.9 for Android NDK (based on llvm.org 6.0)
clang version 6.0.9 for Android NDK
InstalledDir: /home/wang/Code_backup/P-dev/vendor/qcom/proprietary/llvm-arm-toolchain-ship/6.0/bin
Found candidate GCC installation: /usr/lib/gcc-cross/aarch64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc-cross/aarch64-linux-gnu/7.5.0
Selected GCC installation: /usr/lib/gcc-cross/aarch64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
"prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin/ld.gold" -pie --fix-cortex-a53-843419 -z relro --enable-new-dtags --eh-frame-hdr -m aarch64linux -dynamic-linker /system/bin/linker64 -o out/target/product/tu/obj/EXECUTABLES/mace_test_intermediates/LINKED/mace_test -L/home/wang/Code_backup/dev/vendor/qcom/proprietary/llvm-arm-toolchain-ship/6.0/lib/clang/6.0.9/lib/linux/aarch64 -dynamic-linker /system/bin/linker64 --gc-sections -z nocopyreloc -rpath-link=out/target/product/tu/obj/lib out/target/product/tu/obj/lib/crtbegin_dynamic.vendor.o out/target/product//obj/EXECUTABLES/mace_test_intermediates/mace_mode_test.o --whole-archive --no-whole-archive out/target/product/tu/obj/STATIC_LIBRARIES/libclang_rt.ubsan_minimal-aarch64-android.vendor_intermediates/libclang_rt.ubsan_minimal-aarch64-android.vendor.a out/target/product/tu/obj/STATIC_LIBRARIES/libcompiler_rt-extras.vendor_intermediates/libcompiler_rt-extras.vendor.a out/target/product/tu/obj/STATIC_LIBRARIES/libatomic_intermediates/libatomic.a out/target/product/tu/obj/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a -z noexecstack -z relro -z now --build-id=md5 --warn-shared-textrel --fatal-warnings --no-undefined-version -m aarch64_elf64_le_vec --hash-style=gnu --icf=safe --exclude-libs libclang_rt.ubsan_minimal-aarch64-android.a --no-undefined out/target/product/tu/obj/lib/libutils.vendor.so out/target/product/tu/obj/lib/libhardware.vendor.so out/target/product/tu/obj/lib/liblog.vendor.so out/target/product/tu/obj/lib/libcutils.vendor.so out/target/product/tu/obj/lib/libmace.so out/target/product/tu/obj/lib/libdl.vendor.so out/target/product/tu/obj/lib/libc++.vendor.so out/target/product/tu/obj/lib/libc.vendor.so out/target/product/tu/obj/lib/libm.vendor.so out/target/product/tu/obj/lib/libdl.vendor.so out/target/product/tu/obj/lib/crtend_android.vendor.o
vendor/<vendor>/proprietary/touch/hostprocessing/mace_mode_test.cpp:106: error: undefined reference to 'mace::CreateMaceEngineFromProto(unsigned char const*, unsigned long, unsigned char const*, unsigned long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, mace::MaceEngineConfig const&, std::__1::shared_ptr<mace::MaceEngine>*)'
vendor/Pvendor/proprietary/touch/hostprocessing/mace_mode_test.cpp:128: error: undefined reference to 'mace::MaceTensor::MaceTensor(std::__1::vector<long, std::__1::allocator<long> > const&, std::__1::shared_ptr<void>, mace::DataFormat)'
vendor/Pvendor/proprietary/touch/hostprocessing/mace_mode_test.cpp:134: error: undefined reference to 'mace::MaceTensor::MaceTensor(std::__1::vector<long, std::__1::allocator<long> > const&, std::__1::shared_ptr<void>, mace::DataFormat)'
vendor/Pvendor/proprietary/touch/hostprocessing/mace_mode_test.cpp:144: error: undefined reference to 'mace::MaceEngine::Run(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mace::MaceTensor, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mace::MaceTensor> > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mace::MaceTensor, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mace::MaceTensor> > >*)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
17:03:28 ninja failed with: exit status 1
```

**Comment by lu229** [comment]
@wth0928 如果方便的话, 把你的demo放到网盘里, 我们看看?

**Comment by wth0928** [comment]
@lu229 相关code我提交到小米内部gerrit了，change ID 884420

**Comment by lu229** [comment]
@wth0928 这个项目我没有权限,  您是小米员工, 可以飞书联系我(luxuhui), 我们会高优先级支持.

**Comment by wth0928** [comment]
> @wth0928 这个项目我没有权限, 您是小米员工, 可以飞书联系我(luxuhui), 我们会高优先级支持.

好的

**Comment by lu229** [comment]
@wth0928 如邮件沟通，发现问题是由于android源码编译工具链和android ndk编译工具链不同，导致生成的符号链接不一致导致，建议尝试使用android ndk去编译HAL层代码．

**Comment by wth0928** [comment]
NDK的libc++的C++11命名空间为std::__ndk1
NDK的gnustl的C++11命名空间为std
安卓系统的libc++的C++11命名空间为std::__1

C++lib 库不匹配引起的问题
