### ISSUE TITLE
[Question] Compiled model size increases 4 - 5 times comparing between v0.12.0 and v0.11.0-rc0

### ISSUE THREAD

**Issue by mexeniz** [XiaoMi/mace#619]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu16.04 (MACE Docker image)
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- **MACE version (Use the command: git describe --long --tags)**: 0.12.0 (commit: `90d4b860d573fae8bcdcd986884861e18eec18c9`)
- **Python version(2.7)**: 3.6
- **Bazel version (e.g., 0.13.0)**: [0.16.0]
- **CMake version**: 3.16.0

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
I have a question about a size of a compiled model library. The size of a model library compiled with `v0.12.0` increases significantly by 4x-5x.
2 Caffe and 3 Tensorflow models are converted into the compiled library. Here is the table showing the size of libraries compiled with `v0.12.0` and `v0.11.0-rc0`.

|  Target ABI | Library size (v0.11.0-rc0) | Library size (v0.12.0) |
|:-----------:|:--------------------------:|:----------------------:|
| armeabi-v7a |             94M            |          387M          |
|  arm64-v8a  |             96M            |          504M          |

Is it a normal result in `v0.12.0`?

PS. The compile libraries work fine.

**Comment by lu229** [comment]
@mexeniz I have two questions:
1, what is your compile commands when you compile the v0.11.0-rc0 and v0.12.0? 
2, what is the mean of library, .so file or .a file?

**Comment by mexeniz** [comment]
@lu229 
1. I used the same commands in v0.11.0-rc0 and v0.12.0.
```
python tools/converter.py --config=/path/to/config.yml --target_abis=armeabi-v7a
python tools/converter.py --config=/path/to/config.yml --target_abis=arm64-v8a
```
2. Sorry to mention that. It's .a file.

**Comment by lu229** [comment]
@mexeniz I test this [mini model](https://github.com/XiaoMi/mace-models/blob/master/micro-models/har-cnn/har-cnn.yml) and find no difference. I know there are much difference between cmake and bezel build, perhaps you have used cmake to build v0.12.0?

**Comment by mexeniz** [comment]
@lu229 I still used `tools/converter.py` to build my model library, because of the compatibility of my pipeline. `tools/python/converter.py` provides me different output files, so the current pipeline needs an update. Btw, is a library built by bazel, when I ran `tools/converter.py`?

In addition, I used `tools/bazel-build-standalone-lib.sh` to build a static mace library.

**Comment by lu229** [comment]
@mexeniz Yes it is built by bazel when you ran `tools/converter.py`, it seems that you were always using the bazel. It is convenient for you to share your model and yml files? I will check the problem.

**Comment by mexeniz** [comment]
@lu229 Sure, I'll share the models, when they're ready.

**Comment by mexeniz** [comment]
@lu229 Please model and `yml` file in [here](https://drive.google.com/drive/folders/1SbTwSfQjkKPTkhVYbGfBJh1Y6KLr_PCi?usp=sharing). In addition, the model is also tested with `v0.13.0`

- with MACE `v0.11.0-rc0`:
```bash
ls -alh macelibrary/model/arm64-v8a/"
total 69M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user  69M apr  8 14:48 libmodel.a
```
```bash
ls -alh macelibrary/model/armeabi-v7a/"
total 69M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user  69M apr  8 14:48 libmodel.a
```
- with MACE `v0.13.0`:
```bash
ls -alh macelibrary/model/arm64-v8a/"
total 134M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user  134M apr  8 14:48 libmodel.a
```
```bash
ls -alh macelibrary/model/armeabi-v7a/"
total 112M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user  112M apr  8 14:48 libmodel.a
```

**Comment by lu229** [comment]
@mexeniz My computor's memory is too small and the model is too big,  which resulting in compilation failture, however, I did not find problems in compiling the other small models. I want to confirm with you that, the yml file is the same when you use the different mace version? especially the  data_type setting in yml file?

**Comment by mexeniz** [comment]
@lu229 I confirm that the model and the yml file are correct. Sorry, it requires a lot of memory during conversion. Typically, the conversion of this model consumes approximately 11-12 GB. It sometimes failed on my 16GB RAM laptop too.

**Comment by mexeniz** [comment]
@lu229 Btw, a smaller model will be prepared. Please wait.

**Comment by mexeniz** [comment]
@lu229 Please find a model and `yml` file at [here](https://drive.google.com/drive/folders/1xRhqdsBff_sZVvu21iB4P2-I-yCfP4XY?usp=sharing)
- with MACE `v0.11.0-rc0`:
```bash
ls -alh macelibrary/model/arm64-v8a/"
total 6,0M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user 6,0M apr  8 14:48 libmodel.a
```
```bash
ls -alh macelibrary/model/armeabi-v7a/"
total 5,4M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user 5,4M apr  8 14:48 libmodel.a
```
- with MACE `v0.13.0`:
```bash
ls -alh macelibrary/model/arm64-v8a/"
total 77M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user  77M apr  8 14:48 libmodel.a
```
```bash
ls -alh macelibrary/model/armeabi-v7a/"
total 52M
drwxr-xr-x 2 user user 4,0K apr  8 14:48 .
drwxr-xr-x 4 user user 4,0K apr  8 14:48 ..
-rwxr-xr-x 1 user user  52M apr  8 14:48 libmodel.a
```

**Comment by lu229** [comment]
@mexeniz No need to prepare, thanks for your help, I have compiled your model with v0.13.0 on another computer and got the libmodel.a, I got a size of 93M, I used the followed commands to unzip the library file and got the object files, and found no problems, because the tensor_data.o in the library file got to 66M, perhaps you can also use the commands to check your library file and found the difference:
$ cd build/libmodel/model/arm64-v8a/
$ $ANDROID_NDK_HOME/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar -x ./libmodel.a
$ ls *.o

**Comment by mexeniz** [comment]
@lu229 Thank you. I will try that.

**Comment by lu229** [comment]
@mexeniz Sorry, I actually get a different size with v0.11.0, I will trace and solve this problem, thanks for your help!

**Comment by lu229** [comment]
@mexeniz I have found the cause of the problem, it is because we delete the strip command after v0.12.0 which was used to strip the symbols in the library. As you know, we will finally strip the symbols in the final so file, so there is no need to strip the library files. If you still want to reduce the static library file's size, you can use the strip command in the shell, for example:
$ $ANDROID_NDK_HOME/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip -s ./libmodel.a
and you will get a smaller library.

**Comment by mexeniz** [comment]
@lu229 Thank you very much for your investigation! 

I've tried this method. Now, I get a smaller library.

**Comment by mexeniz** [comment]
Actually, I need the static library for Android development. Using `-s` option causes Android compilation fail.
Then, I tried using `--strip-debug` option instead and it worked fine. 

PS. the stripped library size is a little bit bigger than one with `-s` option.

**Comment by lu229** [comment]
@mexeniz Thanks for your feedback! Sorry I did not check the compilation~

**Comment by mexeniz** [comment]
@lu229 No problem, any idea why I can compile Android app with all-symbols-tripped static library (the one before `v0.12.0`), while its size is the same as the size of manually stripped static library? 

|  MACE version | Strip option | Library size | Remark |
|:-----------:|:--------------------------:|:----------------------:|:----------------------:|
| v0.11.0-rc0 |             -            |          96M          | Works fine |
|  v0.12.0  |             -s   (--strip-all)         |          96M         | Error: `error adding symbols: Archive has no index; run ranlib to add one Android` |
| v0.12.0 |             --strip-debug            |          114M          | Works fine |

**Comment by lu229** [comment]
@mexeniz How about using this command:
$ $ANDROID_NDK_HOME/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip -x ./libmodel.a
this is the command used in v0.11.0

**Comment by lu229** [comment]
@mexeniz Normally symbols in static libraries should not be stripped, we only need to remove symbols in so files and app binaries.

**Comment by mexeniz** [comment]
@lu229 Thank you very much! I think we can close this issue now.
