### ISSUE TITLE
[Windows] Compile issue due to W4996

### ISSUE THREAD

**Issue by LoSealL** [XiaoMi/mace#623]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10.18363.720
- **NDK version(e.g., 15c)**: N/A
- **GCC version(if compiling for host, e.g., 5.4.0)**: VS2019
- **MACE version (Use the command: git describe --long --tags)**: v0.12.0-51-gd0ddb683
- **Python version(2.7)**: 3.6.8
- **Bazel version (e.g., 0.13.0)**: N/A (CMake 3.15.2)

### Describe the problem
```
error C2220: the following warning is treated as an error:
warning C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.
```
### To Reproduce
Steps to reproduce the problem:
```bash
cmake ${MACE_SRC} -DMACE_ENABLE_CCACHE=OFF -DMACE_ENABLE_BENCHMARKS=ON -DMACE_ENABLE_TESTS=ON -DMACE_ENABLE_OPENCL=ON
cmake --build . --target extern_gtest
```

**Comment by lu229** [comment]
@LoSealL We don't support compilation on windows os, Please use Ubuntu or MAC and refer to the [documents](https://mace.readthedocs.io/en/latest/installation/env_requirement.html#environment-requirement).
