### ISSUE TITLE
deconv hexagon_converter.py padding issue

### ISSUE THREAD

**Issue by joye** [XiaoMi/mace#624]
https://github.com/XiaoMi/mace/blob/446bb57c2e1c916d31a3760c377afad0b8dd85a3/tools/python/transform/hexagon_converter.py#L467

The padding formula is calculated for 'same' mode seems wrong.

**Comment by lee-bin** [comment]
@joye What do you think it should be calculated?

**Comment by joye** [comment]
I think for conv2d calculation; 

output = (input - kernel + 2 * padding) / stride + 1

so 
  padding = [(output - 1) * stride - input + kernel] / 2

as deconv2d, input is swapped with output, so 

  padding = [(input - 1) * stride - output + kernel] / 2

this padding should be deconv's output pad; 
if the padding is deconv's input pad,  using this webpage 
http://deeplearning.net/software/theano/tutorial/conv_arithmetic.html

I think the input_pad = kernel - output_pad - 1; so for input or output padding, not the same as the formula. Please correct me if I'm wrong.

**Comment by lee-bin** [comment]
@joye You are right, output shape should be used to calculate the padding. We will fix it soon.

**Comment by lee-bin** [comment]
@joye It's fixed in https://github.com/XiaoMi/mace/commit/27757d888d60a8790501f49fa47692802c49509a
