### ISSUE TITLE
关于新加入caffe模型数据后显示数据的问题

### ISSUE THREAD

**Issue by hongsui169163** [XiaoMi/mace#63]
HI：
    贵司自带的tensorflow对应的cachelabel.txt里面都是固定的字符。如果我在贵司的基础上加入caffe的模型数据，我这个模型数据的识别字符，比如是人名，并不在cachelabel里面，如何添加对应的字符到cachelabel.txt里面？并在识别到后，正确显示对应的字符？

**Comment by baijunhui** [comment]
直接把cachelabel.txt里的数据替换成你自己的数据就可以,然后重新运行下app

**Comment by llhe** [comment]
这个就需要自己改模型和app的逻辑了，跟mace关系不太大。
