### ISSUE TITLE
v0.13.0 CMake build fails during conversion

### ISSUE THREAD

**Issue by muendelezaji** [XiaoMi/mace#631]
When following the guide to [build using CMake](https://mace.readthedocs.io/en/v0.13.0/user_guide/basic_usage_cmake.html), the process fails when trying to convert the Mobilenet v1 model in order to do a test run.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.6
- **NDK version(e.g., 15c)**: 19.0.5232133
- **GCC version(if compiling for host, e.g., 5.4.0)**: N/A
- **MACE version (Use the command: git describe --long --tags)**: v0.13.0-0-g9a06864a
- **Python version(2.7)**: Python 3.7.7
- **Bazel version (e.g., 0.13.0)**: N/A

### Model deploy file (*.yml)
```yaml
library_name: mobilenet-v1
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

### Describe the problem
When following the guide to [build using CMake](https://mace.readthedocs.io/en/v0.13.0/user_guide/basic_usage_cmake.html), I get the following error when trying to convert the Mobilenet v1 model in order to do a test run.

### Steps to reproduce
```bash
1. cd /Users/admin/xiaomi/mace
2. pip install -r setup/requirements.txt -r setup/optionals.txt  # inside virtualenv
3. tools/clear_workspace.sh --expunge
4. RUNTIME=GPU bash tools/cmake/cmake-build-arm64-v8a.sh
5. python tools/python/convert.py --config ../mace-models/mobilenet-v1/mobilenet-v1.yml
```

### Error information / logs
```bash
$ python tools/python/convert.py --config ../mace-models/mobilenet-v1/mobilenet-v1.yml
CMD> bazel version
/bin/sh: bazel: command not found
/bin/sh: bazel: command not found
WARNING: /Users/admin/xiaomi/mace/tools/python/py_proto/__init__.py:29: No bazel, use cmake.
Traceback (most recent call last):
  File "tools/python/convert.py", line 25, in <module>
    from micro_converter import MicroConverter
  File "/Users/admin/xiaomi/mace/tools/python/micro_converter.py", line 19, in <module>
    from micro.graph_builder import GraphBuilder
  File "/Users/admin/xiaomi/mace/tools/python/micro/graph_builder.py", line 15, in <module>
    from py_proto import micro_mem_pb2
ImportError: cannot import name 'micro_mem_pb2' from 'py_proto' (/Users/admin/xiaomi/mace/tools/python/py_proto/__init__.py)
```

A grep for `micro_mem_pb2` in the mace folder came up with these:
```bash
$ grep -rI 'micro_mem_pb2' .
./tools/python/micro/graph_builder.py:from py_proto import micro_mem_pb2
./tools/python/micro/graph_builder.py:        graph = micro_mem_pb2.Graph()
./tools/python/py_proto/__init__.py:            "cp -f bazel-genfiles/mace/proto/micro_mem_pb2.py %s" % cwd)
```
But `bazel-genfiles` does not exist since I am using CMake. Any suggestions?

**Comment by lu229** [comment]
@muendelezaji In the `./tools/python/py_proto/__init__.py`, you can see the code `device.execute("bazel build //mace/proto:micro_mem_py")`, which is used to gen the `bazel-genfiles/mace/proto/micro_mem_pb2.py` with bezel. perhaps you need to install the bazel first

**Comment by muendelezaji** [comment]
Thanks for the reply. Does this mean I will need bazel even when doing the "CMake build" approach?

**Comment by lu229** [comment]
@muendelezaji Yes, we will optimize this in the future
