### ISSUE TITLE
model benchmark的一些疑问

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#634]
hi，mace的小伙伴(*´▽｀)ノノ，我基于文档做model的benchmark，我想测出非tunning情况下，gpu的最强力的caffe模型耗时。

![image](https://user-images.githubusercontent.com/7320657/80713782-9602b780-8b26-11ea-9fd2-6d23dce2a345.png)

但是有几个问题：

1. VLOG和LOG的潜在性能影响。根据model benchmark操作，发现有好多log，比方INFO级别的LOG，这个对性能有影响吧，即使VLOG不走也会有调用开销和重载<<的执行等开销；
2. 提供的release预编译库，也是带LOG和VLOG的吗？
3. 模型的整体耗时，是上图红框最下面那个嘛？我设置了跑100次；
4. 这个如何设置CPU高性能模式呢；
5. 为了测出最佳的opencl性能，我还需要做哪些操作呀。

**Comment by lu229** [comment]
@ysh329 回复如下：
1，如微信沟通，我们之前的测试，VLOG不用在关键代码时，对性能的影响应该可以忽略，后面我这边会再次确认一下。
2，带
3，是的
4，可使用`mace.h`中的`SetCPUThreadPolicy`方法设置AFFINITY_HIGH_PERFORMANCE
5，可以tuning，可参考：[Tuning for specific SoC's GPU](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#tuning-for-specific-soc-s-gpu)

**Comment by ysh329** [comment]
哇哦~ mace，很强！
