### ISSUE TITLE
运行onnx模型出错:Check failed: input0->dim(rank_diff + i) == 1 || input1->dim(i) == 1 || input0->dim(rank_diff + i) == input1->dim(i)

### ISSUE THREAD

**Issue by luckymingjia** [XiaoMi/mace#635]
### System information
- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **NDK version(17c)**:
- **GCC version(5.4.0)**:
- **MACE version (Use the command: git clone https://github.com/XiaoMi/mace.git)**:
- **Python version(3.6)**: 
- **Bazel version (0.13.0)**:

### Model deploy file (*.yml)
library_name: pose
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  pose: # model tag, which will be used in model loading and must be specific.
    platform: onnx
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /path/to/your/pose_opt.onnx
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum: sha256sum path/to/your/pb/file
    model_sha256_checksum: d0932b84745b43fc3cfd3a22426f64da54671286366f138ebeb84999812765ab
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,256,192
        output_tensors:
          - conv5_fwd
        output_shapes:
          - 1,33,64,48
    # cpu, gpu or cpu+gpu
    runtime: cpu+gpu
    winograd: 0

### Describe the problem
我把原始的onnx模型通过bazel编译成为mace的静态库，模型转换成功了，原始的模型我通过onnxruntime测试过，运行正常，我的模型输入是1x3x256x192,输出是1x33x64x48，我使用同样的输入输出在安卓中调用测试，模型加载就出现闪退。我观察转换后的模型的HTML文件，发现很多层的输出都是通道的值在最后一维，如下：

0 | relu0_fwd | Conv2D | 1,128,96,64 |  
1 | pool0_fwd | Pooling | 1,64,48,64 |  
2 | conv1_fwd | Conv2D | 1,64,48,256 |  
3 | bottleneck0_relu0 | Conv2D | 1,64,48,64 |  
4 | bottleneck0_relu1 | Conv2D | 1,64,48,64 |  
5 | bottleneck0_conv2_fwd | Conv2D | 1,64,48,256 |  
6 | selayer0_pool0_fwd | Pooling | 1,1,1,256
。。。
220 | duc1_pixelshuffle0_reshape2 | Reshape | 1,128,64,48 |  
221 | conv5_fwd | Conv2D | 1,64,48,33
所以我把安卓调用的输入输出维数修改为1x256x192x3 和1x64x48x33，模型可以加载，但是运行的时候出现以下错误：
2020-05-06 21:45:11.898 31009-31170/com.xiaomi.mace.demo A/MACE: eltwise.cc:976 Check failed: input0->dim(rank_diff + i) == 1 || input1->dim(i) == 1 || input0->dim(rank_diff + i) == input1->dim(i) Element-Wise op only support tail dimensions broadcast
2020-05-06 21:45:11.903 31009-31170/com.xiaomi.mace.demo A/MACE: eltwise.cc:976 backtrace:
2020-05-06 21:45:11.903 31009-31170/com.xiaomi.mace.demo A/MACE: eltwise.cc:976  pc 0x7751d5026c _ZN4mace4port10AndroidEnv18GetBackTraceUnsafeEi
2020-05-06 21:45:11.903 31009-31170/com.xiaomi.mace.demo A/MACE: eltwise.cc:976  pc 0x7751d55c00 _ZN4mace4port6Logger13DealWithFatalEv
2020-05-06 21:45:11.903 31009-31170/com.xiaomi.mace.demo A/MACE: eltwise.cc:976  pc 0x7751d55b90 _ZN4mace4port6Logger18GenerateLogMessageEv
2020-05-06 21:45:11.903 31009-31170/com.xiaomi.mace.demo A/MACE: eltwise.cc:976  pc 0x7751d55fe0 _ZN4mace4port6LoggerD2Ev
2020-05-06 21:45:11.903 31009-31170/com.xiaomi.mace.demo A/MACE: eltwise.cc:976  pc 0x7751d56168 _ZN4mace4port6LoggerD1Ev
然后闪退，不知道是否跟输入维数的顺序有关，还是有其他的问题？
### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python  tools/converter.py convert --config=path/to/your/pose.yml --target_abis=arm64-v8a

**Comment by lee-bin** [comment]
@luckymingjia 可以根据文档[Advanced usage for Bazel users](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#deployment-file)在yml中设置一下输入输出格式

**Comment by luckymingjia** [comment]
@lee-bin 我根据文档在yml中改成NCHW，
- input_tensors:
          - data
        input_shapes:
          - 1,3,256,192
        input_data_formats:
          - NCHW
        output_tensors:
          - conv5_fwd
        output_shapes:
          - 1,33,64,48
        output_data_formats:
          - NCHW    
但是我看了生成的HTML文件，好像生成的模型没有改变，

0 | relu0_fwd | Conv2D | 1,128,96,64 |  
1 | pool0_fwd | Pooling | 1,64,48,64 |  
2 | conv1_fwd | Conv2D | 1,64,48,256 |  
3 | bottleneck0_relu0 | Conv2D | 1,64,48,64 |  
4 | bottleneck0_relu1 | Conv2D | 1,64,48,64 |  
5 | bottleneck0_conv2_fwd | Conv2D | 1,64,48,256 |  
6 | selayer0_pool0_fwd | Pooling | 1,1,1,256
。。。
220 | duc1_pixelshuffle0_reshape2 | Reshape | 1,128,64,48 |  
221 | conv5_fwd | Conv2D | 1,64,48,33

安卓测试跟原来报错一样。

**Comment by lee-bin** [comment]
@luckymingjia 目前看yml设置成了NCHW，那么在运行时输入输出的数据改成NCHW了吗？

**Comment by luckymingjia** [comment]
@lee-bin 改了以后 maceMobilenetCreateEngine返回0 模型加载应该成功了 但是在运行maceMobilenetClassify的时候这一步
// run model
  mace_context.engine->Run(inputs, &outputs); 
直接闪退了 参考的代码 是安卓example的image_classify.cc

**Comment by lee-bin** [comment]
@luckymingjia 贴一下完整日志吧

**Comment by luckymingjia** [comment]
@lee-bin 我用这个命令运行了一下 python tools/converter.py run --config=/path/to/your/pose.yml --validate 打印了下面的信息：
Generate input file:  build/pose/_tmp/pose/84c48d3286404cb4e06ba5bca0b0846e/COL-AL10_kirin970/arm64-v8a/model_input_data
Generate input file done.
* Run 'pose' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push build/pose/_tmp/pose/84c48d3286404cb4e06ba5bca0b0846e/COL-AL10_kirin970/arm64-v8a/model_input_data to /data/local/tmp/mace_run
Push build/pose/_tmp/arm64-v8a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-pose-1588848534.17716 to /data/local/tmp/mace_run/cmd_file-pose-1588848534.17716
I mace/tools/mace_run.cc:530] model name: pose
I mace/tools/mace_run.cc:531] mace version: v0.13.0-4-g27757d8
I mace/tools/mace_run.cc:532] input node: data
I mace/tools/mace_run.cc:533] input shape: 1,3,256,192
I mace/tools/mace_run.cc:534] output node: conv5_fwd
I mace/tools/mace_run.cc:535] output shape: 1,33,64,48
I mace/tools/mace_run.cc:536] input_file: /data/local/tmp/mace_run/model_input
I mace/tools/mace_run.cc:537] output_file: /data/local/tmp/mace_run/model_out
I mace/tools/mace_run.cc:538] input dir:
I mace/tools/mace_run.cc:539] output dir:
I mace/tools/mace_run.cc:540] model_data_file:
I mace/tools/mace_run.cc:541] model_file:
I mace/tools/mace_run.cc:542] device: CPU
I mace/tools/mace_run.cc:543] round: 1
I mace/tools/mace_run.cc:544] restart_round: 1
I mace/tools/mace_run.cc:545] gpu_perf_hint: 3
I mace/tools/mace_run.cc:546] gpu_priority_hint: 3
I mace/tools/mace_run.cc:547] omp_num_threads: -1
I mace/tools/mace_run.cc:548] cpu_affinity_policy: 1
I mace/tools/mace_run.cc:551] limit_opencl_kernel_time: 0
I mace/tools/mace_run.cc:556] opencl_queue_window_size: 0
I mace/libmace/mace.cc:504] Creating MaceEngine, MACE version: v0.13.0-4-g27757d8
I mace/libmace/mace.cc:559] Initializing MaceEngine
I mace/libmace/mace.cc:706] Destroying MaceEngine
I mace/tools/mace_run.cc:599] restart round 0
I mace/libmace/mace.cc:504] Creating MaceEngine, MACE version: v0.13.0-4-g27757d8
I mace/libmace/mace.cc:559] Initializing MaceEngine
I mace/tools/mace_run.cc:272] Create Mace Engine latency: 390.437 ms
I mace/tools/mace_run.cc:279] Total init latency: 390.599 ms
I mace/tools/mace_run.cc:373] Warm up run
F mace/ops/eltwise.cc:976] Check failed: input0->dim(rank_diff + i) == 1 || input1->dim(i) == 1 || input0->dim(rank_diff + i) == input1->dim(i) Element-Wise op only support tail dimensions broadcast
F mace/ops/eltwise.cc:976] backtrace:
F mace/ops/eltwise.cc:976]  pc 0x6316961454
F mace/ops/eltwise.cc:976]  pc 0x631696471c
F mace/ops/eltwise.cc:976]  pc 0x63169646ac
F mace/ops/eltwise.cc:976]  pc 0x6316964afc
F mace/ops/eltwise.cc:976]  pc 0x6316964c7c
F mace/ops/eltwise.cc:976]  pc 0x631680f630
F mace/ops/eltwise.cc:976]  pc 0x631680dd28
F mace/ops/eltwise.cc:976]  pc 0x631690b548
F mace/ops/eltwise.cc:976]  pc 0x63167dcd24
F mace/ops/eltwise.cc:976]  pc 0x63166ec988
F mace/ops/eltwise.cc:976]  pc 0x63166f0114
F mace/ops/eltwise.cc:976]  pc 0x63166f08cc
F mace/ops/eltwise.cc:976]  pc 0x7943800054 __libc_init
Aborted
跟之前的一样，所以我有点怀疑生成的模型没变化，麻烦您看看这个有没有用！

**Comment by lee-bin** [comment]
@luckymingjia 方便上传个模型文件我们测试下吗

**Comment by luckymingjia** [comment]
@lee-bin 之前发给你同事了，我在QQ里跟他说了，他转发给你。

**Comment by lee-bin** [comment]
Fixed in https://github.com/XiaoMi/mace/commit/2530c7eef635eecc59da0ac1a4e7a87c986d42e1
