### ISSUE TITLE
模型转换错误

### ISSUE THREAD

**Issue by fangliangs** [XiaoMi/mace#636]
![1588840478(1)](https://user-images.githubusercontent.com/13034999/81272971-cdbab380-9080-11ea-8f9f-5f02cbef50b7.png)
这是kears的Unet网络转.bp后打印的节点
![1588840340(1)](https://user-images.githubusercontent.com/13034999/81273073-f2af2680-9080-11ea-96ba-1fdea1206680.png)
![1588840385(1)](https://user-images.githubusercontent.com/13034999/81273158-12464f00-9081-11ea-93e5-b3016ea8ba46.png)
报错You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,480,480,3]
![1588840264(1)](https://user-images.githubusercontent.com/13034999/81273278-3bff7600-9081-11ea-9aeb-331f9cc7d416.png)
训练的模型在pc上没有问题(.bp和tflite也可以)
但是安卓上GPU模式无法加载.tflite文件,卡在那边不报错
模型文件放在网盘里了
[https://pan.baidu.com/s/1ZwmYT_hKq4hA-TFzB-niIQ](url)
提取码：2agm

**Comment by lu229** [comment]
@fangliangs Please upload the yml file, we will check this problem.
