### ISSUE TITLE
onnx转mace

### ISSUE THREAD

**Issue by chenloveheimei** [XiaoMi/mace#639]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:18.04
- **NDK version(e.g., 15c)**:r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:7.5.0
- **MACE version (Use the command: git describe --long --tags)**:v0.13.0-0-g9a06864a
- **Python version(2.7)**: 3.6.7
- **Bazel version (e.g., 0.13.0)**:0.13.0

### Model deploy file (*.yml)
```yaml
library_name: segment
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  segment:
    platform: onnx
    model_file_path: /media/long/data/Long/program/morpho/ubuntu/test/Semantic_Human_Matting/ckpt/human_matting/model/segment.onnx
    model_sha256_checksum: 438d6943f6a914f2bf7aa562d55b9541189e19b619ba2613797ea97d66199cf1
    subgraphs:
      - input_tensors: data
        output_tensors: m_net
        input_data_formats: NCHW
        output_data_formats: NCHW
        input_shapes: 1,3,224,224
        output_shapes: 1,1,224,224
        backend: pytorch
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
```

### Describe the problem
运行后./build.sh dynamic ,报错一个floor op不支持,但是这个是pytorch转onnx,onnx自己转出这个floor的,如果我要修改pytorch的哪里,onnx才不会用这个floor呢?

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
long@long-Ubuntu:~/soft/mace/examples/android$ ./build.sh dynamic
~/soft/mace ~/soft/mace/examples/android
CMD> bazel version
Build label: 0.13.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 18 21:33:40 +50297 (1525078013620)
Build timestamp: 1525078013620
Build timestamp as int: 1525078013620

CMD> bazel build //mace/proto:mace_py
Loading:
Loading: 0 packages loaded
INFO: Analysed target //mace/proto:mace_py (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 0.179s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py tools/python/py_proto

CMD> bazel build //mace/proto:micro_mem_py
Loading:
Loading: 0 packages loaded
INFO: Analysed target //mace/proto:micro_mem_py (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:micro_mem_py up-to-date:
bazel-genfiles/mace/proto/micro_mem_pb2.py
INFO: Elapsed time: 0.255s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/micro_mem_pb2.py tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
Loading:
Loading: 0 packages loaded
INFO: Analysed target //third_party/caffe:caffe_py (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 0.136s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py tools/python/py_proto

tools/python/utils/config_parser.py:58: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(s)
{'library_name': 'segment', 'target_abis': ['armeabi-v7a', 'arm64-v8a'], 'model_graph_format': 'code', 'model_data_format': 'code', 'models': {'segment': {'platform': 'onnx', 'model_file_path': '/media/long/data/Long/program/morpho/ubuntu/test/Semantic_Human_Matting/ckpt/human_matting/model/segment.onnx', 'model_sha256_checksum': '4a7abb07f20c0d5f98e28020b5c92714d9764239fe649bedfcb5f60a203b1485', 'subgraphs': [{'input_tensors': 'data', 'output_tensors': 'm_net', 'input_data_formats': 'NCHW', 'output_data_formats': 'NCHW', 'input_shapes': '1,3,224,224', 'output_shapes': '1,1,224,224', 'backend': 'pytorch'}], 'runtime': 'cpu+gpu', 'limit_opencl_kernel_time': 0, 'nnlib_graph_mode': 0, 'obfuscate': 0}}}
* Generate mace engine creator source
Generate mace engine creator source done!

{'platform': <Platform.ONNX: 2>, 'model_file_path': '/media/long/data/Long/program/morpho/ubuntu/test/Semantic_Human_Matting/ckpt/human_matting/model/segment.onnx', 'model_sha256_checksum': '4a7abb07f20c0d5f98e28020b5c92714d9764239fe649bedfcb5f60a203b1485', 'runtime': <DeviceType.CPU_GPU: 100>, 'limit_opencl_kernel_time': 0, 'nnlib_graph_mode': 0, 'obfuscate': 0, 'input_tensors': ['data'], 'output_tensors': ['m_net'], 'input_data_formats': [<DataFormat.NCHW: 2>], 'output_data_formats': [<DataFormat.NCHW: 2>], 'input_shapes': [[1, 3, 224, 224]], 'output_shapes': [[1, 1, 224, 224]], 'backend': 'pytorch', 'data_type': 3, 'input_data_types': [1], 'input_ranges': [[-1.0, 1.0]], 'output_data_types': [1]}
Transform model to one that can better run on device
onnx model IR version:  4
constains ops domain:   version: 9
File "tools/converter.py", line 1176, in <module>
    flags.func(flags)
File "tools/converter.py", line 827, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR, flags.enable_micro)
File "tools/python/convert.py", line 78, in convert
    mace_model = convert_model(model_conf, quantize_stat)
File "tools/python/convert.py", line 190, in convert_model
    output_graph_def = converter.run()
File "tools/python/transform/onnx_converter.py", line 477, in run
    self.convert_ops(graph_def)
File "tools/python/transform/onnx_converter.py", line 559, in convert_ops
    % node.op_type)
File "tools/python/utils/util.py", line 76, in mace_check
    for line in traceback.format_stack():
ERROR: tools/python/transform/onnx_converter.py:559: Mace does not support onnx op type Floor yet

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
@chenloveheimei MACE还未支持floor，这是一个eltwise操作，可以按文档[Adding a new Op](https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html)添加一下支持:)

**Comment by chenloveheimei** [comment]
> @chenloveheimei MACE还未支持floor，这是一个eltwise操作，可以按文档[Adding a new Op](https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html)添加一下支持:)

ERROR: tools/python/transform/onnx_converter.py:561: Mace does not support onnx op type Exp yet

**Comment by lee-bin** [comment]
@chenloveheimei 同样需要添加下Exp算子，也是eltwise

**Comment by chenloveheimei** [comment]
> @chenloveheimei 同样需要添加下Exp算子，也是eltwise

我那样子添加对不对呢?需要按照攻略里面,添加ops.cc那些吗?

**Comment by chenloveheimei** [comment]
> @chenloveheimei 同样需要添加下Exp算子，也是eltwise

ERROR: tools/python/transform/onnx_converter.py:563: Mace does not support onnx op type ReduceSum yet

**Comment by lee-bin** [comment]
@chenloveheimei reduce_sum 是一个reduce操作，C++实现已经有了，可以只添加convert。对于另外两个算子需要添加C++实现。实现完成后可以发一个PR，我们可以看看。

**Comment by chenloveheimei** [comment]
> @chenloveheimei reduce_sum 是一个reduce操作，C++实现已经有了，可以只添加convert。对于另外两个算子需要添加C++实现。实现完成后可以发一个PR，我们可以看看。

ok,我添加了之后,又报错了
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "/home/long/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
File "/home/long/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
File "/home/long/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "/home/long/soft/mace/tools/converter.py", line 1176, in <module>
    flags.func(flags)
File "/home/long/soft/mace/tools/converter.py", line 827, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR, flags.enable_micro)
File "tools/python/convert.py", line 78, in convert
    mace_model = convert_model(model_conf, quantize_stat)
File "tools/python/convert.py", line 190, in convert_model
    output_graph_def = converter.run()
File "tools/python/transform/onnx_converter.py", line 483, in run
    self.convert_ops(graph_def)
File "tools/python/transform/onnx_converter.py", line 566, in convert_ops
    self._op_converters[node.op_type](node)
File "tools/python/transform/onnx_converter.py", line 796, in convert_deconv
    "not support convtranspose with output_padding yet.")
File "tools/python/utils/util.py", line 76, in mace_check
    for line in traceback.format_stack():
ERROR: tools/python/transform/onnx_converter.py:796: not support convtranspose with output_padding yet.

**Comment by chenloveheimei** [comment]
> reduce_sum

![image](https://user-images.githubusercontent.com/30176962/81557310-55c0f600-93be-11ea-9079-db113ed3d1a4.png)
floor这个c++我看了是有添加的,是这个类吗?还是其他类

**Comment by lee-bin** [comment]
> > @chenloveheimei reduce_sum 是一个reduce操作，C++实现已经有了，可以只添加convert。对于另外两个算子需要添加C++实现。实现完成后可以发一个PR，我们可以看看。
> 
> ok,我添加了之后,又报错了
> File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/long/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/no_wheels/debugpy/**main**.py", line 45, in
> cli.main()
> File "/home/long/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 430, in main
> run()
> File "/home/long/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 267, in run_file
> runpy.run_path(options.target, run_name=compat.force_str("**main**"))
> File "/usr/lib/python3.6/runpy.py", line 263, in run_path
> pkg_name=pkg_name, script_name=fname)
> File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/long/soft/mace/tools/converter.py", line 1176, in
> flags.func(flags)
> File "/home/long/soft/mace/tools/converter.py", line 827, in convert_func
> convert.convert(configs, MODEL_CODEGEN_DIR, flags.enable_micro)
> File "tools/python/convert.py", line 78, in convert
> mace_model = convert_model(model_conf, quantize_stat)
> File "tools/python/convert.py", line 190, in convert_model
> output_graph_def = converter.run()
> File "tools/python/transform/onnx_converter.py", line 483, in run
> self.convert_ops(graph_def)
> File "tools/python/transform/onnx_converter.py", line 566, in convert_ops
> self._op_converters[node.op_type](node)
> File "tools/python/transform/onnx_converter.py", line 796, in convert_deconv
> "not support convtranspose with output_padding yet.")
> File "tools/python/utils/util.py", line 76, in mace_check
> for line in traceback.format_stack():
> ERROR: tools/python/transform/onnx_converter.py:796: not support convtranspose with output_padding yet.

目前还未处理这种情况



> > reduce_sum
> 
> ![image](https://user-images.githubusercontent.com/30176962/81557310-55c0f600-93be-11ea-9079-db113ed3d1a4.png)
> ![image](https://user-images.githubusercontent.com/30176962/81557408-8143e080-93be-11ea-99d9-da561772756a.png)
> 
> floor和exph这个c++我看了是有添加的,是这个类吗?还是其他类

这不是mace的算子，是自定义的math库函数
