### ISSUE TITLE
build standalone example problem-please help

### ISSUE THREAD

**Issue by jinliang20000** [XiaoMi/mace#64]
step1:       ./tools/build-standalone-lib.sh
step2:       bazel build -c opt //mace/tools/validation:mace_run_shared   --crosstool_top=//external:android/crosstool
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain   
 --cpu=armeabi-v7a

error:
INFO: Analysed target //mace/tools/validation:mace_run_shared (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/jin/.cache/bazel/_bazel_jin/a3f59ecb60f05ce8c358d64d54b08647/external/com_google_protobuf/BUILD:271:1: Executing genrule @com_google_protobuf//:generate_js_well_known_types_embed failed (Exit 126): bash failed: error executing command

/bin/bash: bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/js_embed: cannot execute binary file: Exec format error

**Comment by jinliang20000** [comment]
NDK-version is r16b

**Comment by nolanliou** [comment]
please pull the latest code.
