### ISSUE TITLE
Build engine for host

### ISSUE THREAD

**Issue by GisellWu** [XiaoMi/mace#642]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information 
- **(registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite)**
- **OS Platform and Distribution: Ubuntu 16.04.4**:
- **NDK version: r19c**
- **GCC version: 5.4.0**
- **MACE version: v0.13.0-21-gab7499a**
- **Python version: 3.6.3**:
- **Bazel version: 0.16.0**

### Describe the problem
I want to build engine for host, but error occurred while compiling. 

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. bash tools/cmake/cmake-build-host.sh
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
......
[  2%] Built target gflags_gflags
[  4%] Built target extern_gtest
[  6%] Built target protobuf
[  8%] Built target protoc_bin
[  8%] Built target caffe_proto_src
[ 11%] Built target eigen3
[ 13%] Built target opencl_headers
[ 16%] Built target half
[ 18%] Built target opencl_clhpp
[ 21%] Built target tflite
[ 24%] Built target gemmlowp
[ 24%] Checking if re-generation is required
[ 25%] Built target version_src
[ 26%] Built target generated_version
[ 27%] Checking if re-generation is required
[ 27%] Built target opencl_kernel_src
[ 27%] Built target generated_opencl_kernel
[ 28%] Built target utils
[ 29%] Built target port_base
[ 30%] Built target port_posix
[ 30%] Built target port_linux_base
[ 31%] Built target port_linux
[ 32%] Built target proto
[ 38%] Built target core
[ 39%] Built target model_shared
[ 39%] Built target model
[ 60%] Built target ops
[ 61%] Built target mace
[ 62%] Built target mace_static
[ 63%] Built target mace_proto_py
[ 64%] Built target mace_run
[ 64%] Built target mace_cc_test_utils
[ 85%] Built target mace_cc_test
[100%] Built target mace_cc_benchmark
Install the project...
-- Install configuration: ""
-- Up-to-date: /mace/build/cmake-build/host/install/lib/libprotobuf-lite.a
CMake Error at cmake_install.cmake:45 (file):
  file INSTALL cannot find "/mace/third_party/rpcmem//rpcmem.a": No such file
  or directory.


Makefile:81: recipe for target 'install' failed
make: *** [install] Error 1

```

**Comment by lee-bin** [comment]
@GisellWu You can try this [patch](https://github.com/lee-bin/mace/commit/a0b50700d369e86b74b0deeb92b0e5c6e783cb61).

**Comment by GisellWu** [comment]
> @GisellWu You can try this [patch](https://github.com/lee-bin/mace/commit/a0b50700d369e86b74b0deeb92b0e5c6e783cb61).

It works. Thanks :)
