### ISSUE TITLE
Feature requests for ISCAS Summer 2020

### ISSUE THREAD

**Issue by lu229** [XiaoMi/mace#643]
[Open Source Promotion Plan - Summer 2020](https://isrc.iscas.ac.cn/summer2020/#/index)项目列表

(以下四个项目的开源协议均为: [Apache License 2.0](https://github.com/XiaoMi/mace/blob/master/LICENSE)).

项目一
-----------
1. 项目标题：移植MACE Micro到微控制器芯片
2. 项目描述：相对于手机等移动设备而言，微控制器是小型、低能耗的计算设备，经常嵌入在只需要进行基本运算的硬件中，包括家用电器和物联网设备等。每年都有数十亿个微控制器被生产出来。MACE新增微控制器（MACE Micro）支持，以全面支持手机与IoT设备超低功耗推理场景。具体使用可参考[文档](https://mace.readthedocs.io/en/latest/micro-controllers/basic_usage.html).
本项目的内容为将MACE Micro移植到某款微控制器芯片，包括但不限于ST、Ambiq等厂商生产的微控制器芯片，MACE Micro不依赖于任何操作系统、文件系统以及运行时的支持，具有良好的可移植性。
3. 项目难度：高
4. 项目社区导师：卢旭辉
5. 导师联系方式：luxuhui@xiaomi.com
6. 项目产出要求：
   - MACE Micro在微控制器芯片上进行AI推理
7. 项目技术要求：
   - 基本的 Linux 命令
   - Git
   - 熟练使用Python C++，扎实的基本功
   - 了解深度学习相关原理
8. 相关的开源软件仓库列表：
   - https://github.com/XiaoMi/mace
   - https://github.com/XiaoMi/mace-models

项目二
-----------
1. 项目标题：基于MACE Micro实现唤醒词识别功能Demo
2. 项目描述：基于MACE Micro，利用Google的唤醒词识别模型，实现一个能在微控制器上运行的语音识别的Demo。
3. 项目难度：高
4. 项目社区导师：卢旭辉
5. 导师联系方式：luxuhui@xiaomi.com
6. 项目产出要求：
   - 基于MACE Micro在微控制器芯片上实现唤醒词识别功能
7. 项目技术要求：
   - 基本的 Linux 命令
   - Git
   - 熟练使用Python C++，扎实的基本功
   - 了解深度学习相关原理
8. 相关的开源软件仓库列表：
   - https://github.com/XiaoMi/mace
   - https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech

项目三
-----------
1. 项目标题：帮助MACE支持Tensorflow2.0模型
2. 项目描述：MACE支持了Tensorflow的1.x版本训练的模型的推理，MACE开发了一个Tensorflow1.x模型到MACE专有模型的转换器。本项目的内容为，参考Tensorflow1.x模型到MACE专有模型的转换器代码，开发一个Tensorflow2.0模型到MACE专有模型的转换器。
3. 项目难度：高
4. 项目社区导师：李滨
5. 导师联系方式：libin11@xiaomi.com
6. 项目产出要求：
   - 完成MACE的Tensorflow2.0模型转换器
7. 项目技术要求：
   - 基本的 Linux 命令
   - Git
   - 熟练使用Python C++，扎实的基本功
   - 了解深度学习相关原理
8. 相关的开源软件仓库列表：
   - https://github.com/XiaoMi/mace
   - https://github.com/tensorflow/tensorflow

项目四
-----------
1. 项目标题：帮助MACE支持Pytorch模型
2. 项目描述：MACE通过支持ONNX标准交换格式，间接支持了Pytorch训练的模型的推理，但模型的两次转换造成了不必要的转换开销。本项目的内容为，参考其他框架模型到MACE专有模型的转换器代码，开发一个Pytorch模型到MACE专有模型的转换器。
3. 项目难度：高
4. 项目社区导师：李滨
5. 导师联系方式：libin11@xiaomi.com
6. 项目产出要求：
   - 完成MACE的Pytorch模型转换器
7. 项目技术要求：
   - 基本的 Linux 命令
   - Git
   - 熟练使用Python C++，扎实的基本功
   - 了解深度学习相关原理
8. 相关的开源软件仓库列表：
   - https://github.com/XiaoMi/mace
   - https://pytorch.org/

**Comment by tianrking** [comment]
老师今年还有项目可以参与嘛
