### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by LovelyBuggies** [XiaoMi/mace#646]
## System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Catalina
- **NDK version(e.g., 15c)**: r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: Apple clang version 11.0.3 (clang-1103.0.32.29)
- **MACE version (Use the command: git describe --long --tags)**: v0.13.0-0-g9a06864a
- **Python version(2.7)**: 3.7.6
- **Bazel version (e.g., 0.13.0)**: 3.1.0

### Model deploy file (*.yml)

mace-models/mobilenet-v2/mobilenet-v2.yml

### Describe the problem

I am using MacOS to build Mace and meet the problem. I follow the manual install guide and use corresponding commands to install bazel, Andriod NDK, and extra tools. But when I try to [build an example model](https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#build-and-run-an-example-model) with `python3 tools/converter.py convert --config=/../mace-models/mobilenet-v2/mobilenet-v2.yml`, an error is thrown: 

```bash
ERROR: /Users/nino/bazel/mace/WORKSPACE:144:1: name 'new_http_archive' is not defined
ERROR: /Users/nino/bazel/mace/WORKSPACE:155:1: name 'new_http_archive' is not defined
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.104s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: tools/python/py_proto/__init__.py:43: Failed in proto files' building
```

Can we set up Mace on OSX? And could you please give me some suggestions to deal with it?

**Comment by lee-bin** [comment]
Please use bazel 0.13. https://github.com/XiaoMi/mace/issues/429

**Comment by LovelyBuggies** [comment]
I changed my bazel to 0.13.0 release, it still doesn't work.

```bash
$ python3 tools/converter.py convert --config=/../mace-models/mobilenet-v2/mobilenet-v2.yml
CMD> bazel version
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
..............
Build label: 0.13.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 18 18:05:23 +50297 (1525078001123)
Build timestamp: 1525078001123
Build timestamp as int: 1525078001123

CMD> bazel build //mace/proto:mace_py
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
currently loading: mace/proto
Loading: 0 packages loaded
currently loading: mace/proto
Loading: 0 packages loaded
currently loading: mace/proto
Loading: 0 packages loaded
currently loading: mace/proto
Loading: 0 packages loaded
currently loading: mace/proto
Loading: 0 packages loaded
currently loading: mace/proto
Loading: 0 packages loaded
currently loading: mace/proto
Analyzing: target //mace/proto:mace_py (1 packages loaded)
Analyzing: target //mace/proto:mace_py (2 packages loaded)
Analyzing: target //mace/proto:mace_py (2 packages loaded)
ERROR: /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/external/local_config_cc/BUILD:50:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-armeabi-v7a: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
ERROR: While resolving toolchains for target @com_google_protobuf//:protos_python_genrule: Analysis of target '@local_config_cc//:cc-compiler-armeabi-v7a' failed; build aborted
ERROR: Analysis of target '//mace/proto:mace_py' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-armeabi-v7a' failed; build aborted
INFO: Elapsed time: 22.505s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded)


ERROR: tools/python/py_proto/__init__.py:43: Failed in proto files' building
```

**Comment by lee-bin** [comment]
Maybe you can follow the advice from the error log and `try: "bazel clean --expunge"`.

**Comment by LovelyBuggies** [comment]
> Maybe you can follow the advice from the error log and `try: "bazel clean --expunge"`.

Yeah, I tried. But it did not work.

**Comment by lee-bin** [comment]
This is a possible solution. https://stackoverflow.com/questions/45276830/xcode-version-must-be-specified-to-use-an-apple-crosstool

**Comment by LovelyBuggies** [comment]
Thanks for your help. I think it may solve the problem before. But there is another error: `TypeError: __init__() got an unexpected keyword argument 'serialized_options'`.

**Comment by lee-bin** [comment]
This seems like a protobuf version issue. 3.6.1 works fine. By the way, we don't test Mac OS much. Ubuntu16/18 is our main platform.

**Comment by LovelyBuggies** [comment]
Okay, I will have a try using 3.6.1 by conda env.

**Comment by LovelyBuggies** [comment]
> This seems like a protobuf version issue. 3.6.1 works fine. By the way, we don't test Mac OS much. Ubuntu16/18 is our main platform.

@lee-bin Thanks, I solved it. Btw, I can offer a macOS setup guide [here](https://github.com/XiaoMi/mace/blob/master/docs/installation/manual_setup.rst) for you if expected.

**Comment by lee-bin** [comment]
@LovelyBuggies It would be great if you could do that. As MACE provides a lot of convert/build/test/benchmark/validate tools, if we are going to offer a MacOS setup guide, we may need to make sure these tools work fine. So, it may take some time to complete that.

**Comment by LovelyBuggies** [comment]
>  if we are going to offer a MacOS setup guide, we may need to make sure these tools work fine

Yeah, I see.

**Comment by LovelyBuggies** [comment]
There is a problem when I am building the MACE library: 

```bash
$ bash tools/bazel-build-standalone-lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static]
build shared lib for armeabi-v7a + cpu_gpu_dsp
ERROR: in target '//external:android/crosstool': no such package '@androidndk//': /opt/android-ndk-r15c (No such file or directory)
INFO: Elapsed time: 0.154s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

As I am testing in MacOS, I used the corresponding commands to install NDK, and not sure whether I am doing it in the right way. My directory tree is like this (level==2):

```bash
.
├── bazel-0.13.0-installer-darwin-x86_64.sh
├── mace
│   ├── BUILD.bazel
│   ├── CMakeLists.txt
│   ├── ISSUE_TEMPLATE.md
│   ├── JOBS.md
│   ├── ... ...
│   ├── README.md
│   ├── build
│   ├── docs
│   ├── examples
│   ├── include
│   ├── micro
│   └── tools
├── mace-models
│   ├── LICENSE
│   ├── README.md
│   ├── convolutional-pose-machines
│   ├── ... ...
│   ├── ssd-mobilenet-v1
│   ├── vgg16
│   └── yolo-v3
└── opt
    └── android-ndk-r15c
```

, where unzipped NDK is in the `opt` folder and I applied the `export` commands in that directory. I have no idea why `ndk-r15c (No such file or directory)`.

By the way, I think there is a typo in the documentation: 

```diff
- bash bazel_build_standalone_lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static] 
+ bash bazel-build-standalone-lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static] 
```

**Comment by lee-bin** [comment]
@LovelyBuggies 
1. You are using different versions of documents and codes, please read the corresponding version of the document according to the codes. So, there is no typo.
2. Are all the files in the root directory?  You can execute `pwd` in `android-ndk-r15c` directory and `echo $ANDROID_NDK_HOME` to confirm.

**Comment by LovelyBuggies** [comment]
Thanks. I correct the ANDROID_NDK_HOME to the right absolution path. But I got no idea why this happens.

```bash
$ bash tools/bazel-build-standalone-lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static]
build shared lib for armeabi-v7a + cpu_gpu_dsp
Starting local Bazel server and connecting to it...
.............
write version v0.13.0-0-g9a06864 to /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/external/local_version_config/gen/version
Generate OpenCL kernel done.
INFO: Analysed target //mace/libmace:libmace_dynamic (34 packages loaded).
INFO: Found 1 target...
INFO: From Executing genrule @opencl_clhpp//:gen_opencl_clhpp:
/var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
/var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v/build /var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v/build
Scanning dependencies of target generate_clhpp
[100%] Rebuilding cl.hpp ...
[100%] Built target generate_clhpp
Scanning dependencies of target generate_cl2hpp
[100%] Rebuilding cl2.hpp ...
[100%] Built target generate_cl2hpp
/var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
/private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
installing to bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(arenastring.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(io_win32.o) has no symbols
INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(gzip_stream.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(error_listener.o) has no symbols
ERROR: /Users/nino/bazel/mace/mace/utils/BUILD.bazel:33:1: C++ compilation of rule '//mace/utils:utils' failed (Exit 1): clang failed: error executing command 
  (cd /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang '-D__ANDROID_API__=21' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -Ibazel-out/armeabi-v7a-opt/bin/include/_virtual_includes/public_headers '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD -Wall -Wno-mismatched-tags -Wno-missing-braces -Wall -Wno-mismatched-tags -Wno-missing-braces -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers -DMACE_ENABLE_NEON '-mfpu=neon' '-mfloat-abi=softfp' '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystemexternal/androidndk/ndk/sysroot/usr/include -c mace/utils/string_util.cc -o bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.o)

Use --sandbox_debug to see verbose messages from the sandbox
src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang, ...)": No such file or directory
Target //mace/libmace:libmace_dynamic failed to build
INFO: Elapsed time: 65.706s, Critical Path: 16.46s
INFO: 165 processes: 164 darwin-sandbox, 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by LovelyBuggies** [comment]
After discussing with @lee-bin, we decide not to explore MACE on Mac, so this issue should be closed.

**Comment by xiezheng1995** [comment]
> Thanks. I correct the ANDROID_NDK_HOME to the right absolution path. But I got no idea why this happens.
> 
> $ bash tools/bazel-build-standalone-lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static]
> build shared lib for armeabi-v7a + cpu_gpu_dsp
> Starting local Bazel server and connecting to it...
> .............
> write version v0.13.0-0-g9a06864 to /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/external/local_version_config/gen/version
> Generate OpenCL kernel done.
> INFO: Analysed target //mace/libmace:libmace_dynamic (34 packages loaded).
> INFO: Found 1 target...
> INFO: From Executing genrule @opencl_clhpp//:gen_opencl_clhpp:
> /var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
> /var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v/build /var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
> -- The C compiler identification is AppleClang 11.0.0.11000033
> -- The CXX compiler identification is AppleClang 11.0.0.11000033
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v/build
> Scanning dependencies of target generate_clhpp
> [100%] Rebuilding cl.hpp ...
> [100%] Built target generate_clhpp
> Scanning dependencies of target generate_cl2hpp
> [100%] Rebuilding cl2.hpp ...
> [100%] Built target generate_cl2hpp
> /var/folders/xv/hslh3bw930j5zspnrr09_0nh0000gn/T/opencl-clhpp-build.XXXXXXXXXX.XOW6Dc6v /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
> /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/sandbox/8816552556928731772/execroot/mace
> installing to bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp
> INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(arenastring.o) has no symbols
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(io_win32.o) has no symbols
> INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(gzip_stream.o) has no symbols
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(error_listener.o) has no symbols
> ERROR: /Users/nino/bazel/mace/mace/utils/BUILD.bazel:33:1: C++ compilation of rule '//mace/utils:utils' failed (Exit 1): clang failed: error executing command 
>   (cd /private/var/tmp/_bazel_nino/e674586b25ee2b12cdb3ffc1154b3dad/execroot/mace && \
>   exec env - \
>     PWD=/proc/self/cwd \
>   external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang '-D__ANDROID_API__=21' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -Ibazel-out/armeabi-v7a-opt/bin/include/_virtual_includes/public_headers '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD -Wall -Wno-mismatched-tags -Wno-missing-braces -Wall -Wno-mismatched-tags -Wno-missing-braces -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers -DMACE_ENABLE_NEON '-mfpu=neon' '-mfloat-abi=softfp' '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystemexternal/androidndk/ndk/sysroot/usr/include -c mace/utils/string_util.cc -o bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.o)
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang, ...)": No such file or directory
> Target //mace/libmace:libmace_dynamic failed to build
> INFO: Elapsed time: 65.706s, Critical Path: 16.46s
> INFO: 165 processes: 164 darwin-sandbox, 1 local.
> FAILED: Build did NOT complete successfully

+1
