### ISSUE TITLE
MACE 在移动端 支持输入数据shape不确定对模型吗？

### ISSUE THREAD

**Issue by baiyu8534** [XiaoMi/mace#647]
我的tensorflow模型输入的数据必须是不定长的数据，因为要输入文件，对文件处理后，生成对应对文件。
因为文件类型，用户输入对文件肯定是不一样对
而且要根据源文件经过模型处理后生成文件

tflite模型只支持确定shape对数据输入

请问MACE可以转换输入数据shape不确定对tensorflow模型吗？

或者MACE可以在移动端实现支持不确定shape对数据输入对模型？

望解答！谢谢！！🙏🙏🙏🙏🙏

**Comment by lydoc** [comment]
输入需要的最大shape就可以

**Comment by baiyu8534** [comment]
@lydoc 谢谢！
这样的方法也可行，需要限制用户输入的文件的大小
tensorflow rnn模型可以转化成MACE需要的模型吗？
或者我使用MACE重新训练我的模型
