### ISSUE TITLE
mace.cc:308 Check failed: fd >= 0 Failed to open model data file , error code: No such file or directory

### ISSUE THREAD

**Issue by javaDuQing** [XiaoMi/mace#65]
11898-11937/com.xiaomi.mace.demo E/ContentCatcherManager: failed to get ContentCatcherService.
07-11 14:11:59.185 11898-11938/com.xiaomi.mace.demo W/linker: "/data/app/com.xiaomi.mace.demo-aGTa5xelI0087NRLnm7eBA==/lib/arm64/libmace_mobile_jni.so" unused DT entry: type 0xf arg 0x4839f
07-11 14:11:59.192 11898-11938/com.xiaomi.mace.demo E/image_classifyttrs: openmp result: 0, threads: 2, cpu: 1
07-11 14:11:59.192 11898-11938/com.xiaomi.mace.demo E/image_classify attrs: gpu perf: 3, priority: 3
07-11 14:11:59.192 11898-11938/com.xiaomi.mace.demo I/APPModel: maceMobilenetSetAttrs result = 0
07-11 14:11:59.192 11898-11938/com.xiaomi.mace.demo E/image_classify attrs: device: 0
07-11 14:11:59.192 11898-11938/com.xiaomi.mace.demo A/MACE: mace.cc:308 Check failed: fd >= 0 Failed to open model data file , error code: No such file or directory
07-11 14:11:59.192 11898-11938/com.xiaomi.mace.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11938 (jniThread)
07-11 14:11:59.210 11898-11942/com.xiaomi.mace.demo D/OpenGLRenderer: HWUI GL Pipeline

**Comment by lee-bin** [comment]
拉下最新代码尝试一下。

**Comment by llhe** [comment]
这个错误就是模型文件找不到，文件打开失败，https://github.com/XiaoMi/mace/blob/v0.8.1/mace/core/mace.cc#L306。

需要把模型文件传到手机上，并指定model_data_file变量。

**Comment by javaDuQing** [comment]
@llhe 感谢回答，请问模型文件是执行命令`python tools/converter.py build --config=models/config.yaml`之后的生成的下面的文件吗，我使用的是0.8.1的代码

![_20180712095539](https://user-images.githubusercontent.com/19592267/42608388-0a7ed84c-85ba-11e8-9997-4c2dbdfe2f46.png)

**Comment by llhe** [comment]
是的，你可以参考这一段：https://mace.readthedocs.io/en/stable/getting_started/how_to_build.html#deployment。

另外master的工具和文档有较大的改动，后边需要注意。
