### ISSUE TITLE
Adreno 330 support?

### ISSUE THREAD

**Issue by pgaston** [XiaoMi/mace#652]
You guys are awesome - my CNN works great at roughly 18 fps on the Qualcomm 820/Adreno 530.   Thanks!

So good, that I've been asked to see if there is anyway I can get this to work on the Qualcomm 801/Adreno 330.    (Who knows, next it will be an Intel 80286 or something :) )

This is just a crazy reach out - I've had no luck googling - or trolling through Qualcomm.

A - Ever hear of anyone deploying to an Adreno 330?
B - On Linux?
C - Any chance you could hook me up?    The libOpenCL.so is not out there...

Thanks again for a great tool!
(Though I think I have to check out the Alibaba tool soon...)

**Comment by lu229** [comment]
@pgaston 
A: We have not deployed to an `Adreno 330`. bug if the phone's OS supports OpenCL 1.1, MACE can work.
B: MACE support arm-Linux, please refer to [this document](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#run-you-model-on-the-embedded-device-arm-linux).
C: Perhaps you should communicate to the OS developer and find the path of libOpenCL.so, generally speaking, you can refer to [this code](https://github.com/XiaoMi/mace/blob/master/mace/core/runtime/opencl/opencl_wrapper.cc#L303).

**Comment by pgaston** [comment]
Thanks.    Sounds like a wild goose chase.

Best!
