### ISSUE TITLE
缺少micro_mem_pb2

### ISSUE THREAD

**Issue by Qingyang-Liu** [XiaoMi/mace#653]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:5.4.0
- **MACE version (Use the command: git describe --long --tags)**:0.13.0
- **Python version(2.7)**: 3.6
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
我按照官方的手册第五章cmake用户基本操作，进行模型转换的时候，使用现有模型库中的mobilenetv1。
输入的命令python tools/python/convert.py --config ../mace-models/mobilenet-v1/mobilenet-v1.yml
但是得到的是一个ImportError：cannot import name 'mirco_mem_pb2'
我看了一下，这个应该在py_proto下面有，但是目前只有mace_pb2和caffe_pb2。
求助如何解决

**Comment by lu229** [comment]
@Qingyang-Liu 如QQ群沟通，需要安装按照文档安装bazel

**Comment by Qingyang-Liu** [comment]
> @Qingyang-Liu 如QQ群沟通，需要安装按照文档安装bazel

是的，安装后可以生成需要的文件了。
