### ISSUE TITLE
Error when trying to run model test or benchmark

### ISSUE THREAD

**Issue by JustasZJ** [XiaoMi/mace#657]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.4
- **NDK version(e.g., 15c)**: r19c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.13.0-31-ga2bcf2c
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**: 0.16.0

### Model deploy file (config.yml)
```yaml
models:
  model:
    platform: onnx
    model_file_path: /model-sim.onnx
    model_sha256_checksum: 121fee77cddad78492e64d58730f665160397aa6d8e9828b3a509b8a97f74f8b
    subgraphs:
      - input_tensors:
          - input.1
        input_shapes:
          - 1,3,112,112
        output_tensors:
          - 744
        output_shapes:
          - 1,512
    runtime: cpu
```

### Describe the problem
I am unable to run test/benchmark for a model converted from onnx.

### To Reproduce
Steps to reproduce the problem:
```bash
1. Create a docker container as described here https://mace.readthedocs.io/en/latest/installation/using_docker.html .
2. Clone MACE from github.
3. Follow the steps described in https://mace.readthedocs.io/en/latest/user_guide/basic_usage_cmake.html until "Model Test and Benchmark" section.
4. cd /path/to/mace
5. Run python tools/python/run_model.py --config ../config.yml --benchmark
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
/bin/sh: 1: /opt/android-ndk-r19c/ndk-depends: not found


Traceback (most recent call last):
  File "tools/python/run_model.py", line 379, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 77, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 86, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 204, in run_model_for_device
    device_ids=flags.target_socs)
  File "/mace/tools/python/run_target.py", line 51, in run_target
    device_target = dev.install(target_obj, install_dir, install_deps=True)
  File "/mace/tools/python/utils/device.py", line 167, in install
    self.install_common_libs_for_target(target, install_dir)
  File "/mace/tools/python/utils/device.py", line 174, in install_common_libs_for_target
    + target.path)
  File "/mace/tools/python/utils/device.py", line 60, in execute
    raise Exception("errorcode: %s" % p.returncode)
Exception: errorcode: 127

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@JustasZJ As a temp solution, please try this command in your docker: `cp /opt/android-ndk-r18b/ndk-depends /opt/android-ndk-r19c/`

**Comment by JustasZJ** [comment]
Thank you for your response. It seems that the docker doesn't contain /opt/android-ndk-r18b (only android-ndk-r19c).

**Comment by lu229** [comment]
@JustasZJ Are you using the lite edition image? you can use the full edition, or you can copy an `ndk-depends` from an old version ndk on the local machine.

**Comment by JustasZJ** [comment]
@lu229 Yes, I was using the lite edition image. Tested on full edition now with the fix, but I am getting a similar error:
```
/opt/android-ndk-r19c/ndk-depends: 3: /opt/android-ndk-r19c/ndk-depends: /opt/android-ndk-r19c/prebuilt/linux-x86_64/bin/ndk-depends: not found


Traceback (most recent call last):
  File "tools/python/run_model.py", line 379, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 77, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 86, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 204, in run_model_for_device
    device_ids=flags.target_socs)
  File "/mace/tools/python/run_target.py", line 51, in run_target
    device_target = dev.install(target_obj, install_dir, install_deps=True)
  File "/mace/tools/python/utils/device.py", line 167, in install
    self.install_common_libs_for_target(target, install_dir)
  File "/mace/tools/python/utils/device.py", line 174, in install_common_libs_for_target
    + target.path)
  File "/mace/tools/python/utils/device.py", line 60, in execute
    raise Exception("errorcode: %s" % p.returncode)
Exception: errorcode: 127
```

**Comment by JustasZJ** [comment]
Ok, running
`cp android-ndk-r18b/prebuilt/linux-x86_64/bin/ndk-depends /opt/android-ndk-r19c/prebuilt/linux-x86_64/bin`
seems to have fixed the problem now.
