### ISSUE TITLE
DSP runtime, HEXAGON only support HWIO/HWIM filter

### ISSUE THREAD

**Issue by ridingstar623** [XiaoMi/mace#659]
Hi,
我在convert model to DSP runtime的时候遇到了title提到的问题，我的flow是这样的：
Pytorch -> ONNX -> MACE
但是pytorch的卷积操作默认输出了OIHW格式，然后在https://github.com/XiaoMi/mace/blob/master/tools/python/transform/transformer.py#L1170 报错。请问都有哪些方法可以跑通呢？目前考虑了：
1. 尝试从pytorch转换onnx的时候输出HWIO格式的filter
2. 在transformer.py改code, 把OIHW transpose成HWIO
想请教一下哪一种（或者别的方法）会好一些，先谢谢了。

Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
@ridingstar623 目前DSP仅针对TensorFlow做了支持，想支持PyTorch的话上面两种方式都可以尝试一下

**Comment by ridingstar623** [comment]
@lee-bin 谢谢及时回复！我刚接触到这个领域，我看到现有的代码都是采取的根据不同的filter format进行transpose的做法，所以这个是更推荐的路线是吗？是不是近期MACE没有计划支持Pytorch + DSP呢？再次感谢！

**Comment by lee-bin** [comment]
@ridingstar623 是的。
