### ISSUE TITLE
转onnx mv2 分类模型出错

### ISSUE THREAD

**Issue by Wuqiman** [XiaoMi/mace#663]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```
library_name: appraiserM
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  fingerTips:
    platform: "onnx"
    model_file_path:mv2_0.25.onnx
    model_sha256_checksum: 3255f9270d49beda284bb343c3f02639296b164ce9b60e8dcb0e20cad5e4f4b1
    subgraphs:
      - input_tensors:
          - 0
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - "467"
        output_shapes:
          - 1,1000
        backend: pytorch
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 816, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR)
  File "tools/python/convert.py", line 75, in convert
    mace_model = convert_model(model_conf)
  File "tools/python/convert.py", line 184, in convert_model
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "tools/python/transform/transformer.py", line 139, in run
    changed = transformer()
  File "tools/python/transform/transformer.py", line 996, in transform_global_conv_to_fc
    input_shape = producer.output_shape[0].dims
IndexError: list index (0) out of range

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@Wuqiman I checked your model and `yml` files and found no errors, perhaps you can try the latest code on the master branch?
