### ISSUE TITLE
[Model Converter] ERROR: error loading package 'mace/proto'

### ISSUE THREAD

**Issue by groovemaxRong** [XiaoMi/mace#668]
Hello.

I'm trying to convert the mace model, but it fails.

What can I do to fix a problem?

Thanks for your attention.

Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:  v0.13.0-0-g9a06864
- **Python version(2.7)**:  Python 2.7.16 :: Anaconda
- **Bazel version (e.g., 0.13.0)**: bazel release 0.22.0

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```python3 tools/converter.py convert --config=mace-models/mobilenet-v2/mobilenet-v2.yml
CMD> bazel version
INFO: Invocation ID: 07bb23e2-367f-4b20-900e-cd57e7b55f5c
Build label: 0.22.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 12:58:08 2019 (1548680288)
Build timestamp: 1548680288
Build timestamp as int: 1548680288

CMD> bazel build //mace/proto:mace_py
INFO: Invocation ID: c4126b15-7b77-4d0e-8201-0ec154698aad
Loading:
Loading: 0 packages loaded
ERROR: Skipping '//mace/proto:mace_py': error loading package 'mace/proto': Encountered error while reading extension file 'protobuf.bzl': no such package '@com_google_protobuf//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'mace/proto': Encountered error while reading extension file 'protobuf.bzl': no such package '@com_google_protobuf//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 0.067s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)


ERROR: tools/python/py_proto/__init__.py:43: Failed in proto files' building
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
Please use an older version of bazel, e.g., 0.13.0

**Comment by groovemaxRong** [comment]
Thank you for your help.
