### ISSUE TITLE
conversion from onnx v11 not working

### ISSUE THREAD

**Issue by davidenitti** [XiaoMi/mace#677]
conversion from onnx v11 is not working

### System information
- **OS Platform and Distribution: 19.10
- **NDK version: r15c
- **GCC version : gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
- **MACE version: v0.13.0-0-g9a06864a
- **Python version: 3.7.5
- **Bazel version: 0.13.1

### Model deploy file (*.yml)
```
library_name: model
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  resnet_model:
    platform: onnx
    model_file_path: Conv2dnet_v11.onnx
    model_sha256_checksum: 8f398e6edfac752ef60a2f694c70b74a3fde330cd0bfb77df8a35da877c17b05
    subgraphs:
      - input_tensors:
          - input
          - input2
        input_shapes:
          - "1,20,1000,1000"
          - 1,3,1000,1000
        output_tensors:
          - output
        output_shapes:
          - 1,3,1000,1000
        input_data_formats:
          - NCHW
          - NCHW
        backend: pytorch
    runtime: cpu+gpu
    winograd: 0
......
```

### Describe the problem
conversion from onnx v11 is not working, it says "Attribute starts required!"

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config=Conv2dnet_v11.yml
```

### Error information / logs

```bash
/home/davide/mace/mace/Conv2dnet_v11.yml
tools/python/utils/config_parser.py:58: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(s)
{'library_name': 'model', 'target_abis': ['arm64-v8a'], 'model_graph_format': 'file', 'model_data_format': 'file', 'models': {'resnet_model': {'platform': 'onnx', 'model_file_path': 'Conv2dnet_v11.onnx', 'model_sha256_checksum': '8f398e6edfac752ef60a2f694c70b74a3fde330cd0bfb77df8a35da877c17b05', 'subgraphs': [{'input_tensors': ['input', 'input2'], 'input_shapes': ['1,20,1000,1000', '1,3,1000,1000'], 'output_tensors': ['output'], 'output_shapes': ['1,3,1000,1000'], 'input_data_formats': ['NCHW', 'NCHW'], 'backend': 'pytorch'}], 'runtime': 'cpu+gpu', 'winograd': 0}}}
{'platform': <Platform.ONNX: 2>, 'model_file_path': 'Conv2dnet_v11.onnx', 'model_sha256_checksum': '8f398e6edfac752ef60a2f694c70b74a3fde330cd0bfb77df8a35da877c17b05', 'runtime': <DeviceType.CPU_GPU: 100>, 'winograd': 0, 'input_tensors': ['input', 'input2'], 'input_shapes': [[1, 20, 1000, 1000], [1, 3, 1000, 1000]], 'output_tensors': ['output'], 'output_shapes': [[1, 3, 1000, 1000]], 'input_data_formats': [<DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>], 'backend': 'pytorch', 'data_type': 3, 'input_data_types': [1, 1], 'input_ranges': [[-1.0, 1.0], [-1.0, 1.0]], 'output_data_types': [1], 'output_data_formats': [<DataFormat.NHWC: 1>]}
Transform model to one that can better run on device
onnx model IR version:  6
constains ops domain:   version: 11
File "tools/converter.py", line 1177, in <module>
    flags.func(flags)
File "tools/converter.py", line 828, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR, flags.enable_micro)
File "tools/python/convert.py", line 78, in convert
    mace_model = convert_model(model_conf, quantize_stat)
File "tools/python/convert.py", line 190, in convert_model
    output_graph_def = converter.run()
File "tools/python/transform/onnx_converter.py", line 477, in run
    self.convert_ops(graph_def)
File "tools/python/transform/onnx_converter.py", line 560, in convert_ops
    self._op_converters[node.op_type](node)
File "tools/python/transform/onnx_converter.py", line 1331, in convert_slice
    mace_check('starts' in node.attrs, "Attribute starts required!")
File "tools/python/utils/util.py", line 76, in mace_check
    for line in traceback.format_stack():
ERROR: tools/python/transform/onnx_converter.py:1331: Attribute starts required!
```

**Comment by lu229** [comment]
@davidenitti One `Slice` operator in the ONNX model doesn't have the `starts` attribution, it seems that the ONNX model is not valid? you can refer to this [document](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#slice-11).

**Comment by davidenitti** [comment]
@lu229 I convert the models from pytorch and every model with version 11 does not work. with version 9 I have no problems, but I need version 11. So I don't think the model is not valid, I run also onnx.checker.check_model.
maybe the slice operator without start means start=0?

**Comment by lu229** [comment]
@davidenitti I checked the [document](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#slice-11) and it does not specify the default value of `starts`,  perhaps you can use this [tool](build/bb_sep_vovnet_fpn/_tmp/arm64-v8a/) to open your model and check is there a `starts` in the `Slice` operator?

**Comment by davidenitti** [comment]
> @davidenitti I checked the [document](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#slice-11) and it does not specify the default value of `starts`, perhaps you can use this [tool](build/bb_sep_vovnet_fpn/_tmp/arm64-v8a/) to open your model and check is there a `starts` in the `Slice` operator?

thanks for the help, but the link you sent me does not work.

**Comment by lu229** [comment]
> > @davidenitti I checked the [document](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#slice-11) and it does not specify the default value of `starts`, perhaps you can use this [tool](build/bb_sep_vovnet_fpn/_tmp/arm64-v8a/) to open your model and check is there a `starts` in the `Slice` operator?
> 
> thanks for the help, but the link you sent me does not work.

Sorry, I pasted an error URL, it is this [tool](https://lutzroeder.github.io/netron/).

**Comment by davidenitti** [comment]
I think is this that fails but it contains the starts in the slice. so I don't understand why it fails:
```
  %26 : Tensor = onnx::Shape(%21)
  %27 : Tensor = onnx::Constant[value={0}]()
  %28 : Tensor = onnx::Constant[value={0}]()
  %29 : Tensor = onnx::Constant[value={2}]()
  %30 : Tensor = onnx::Slice(%26, %28, %29, %27)
```

**Comment by lu229** [comment]
> I think is this that fails but it contains the starts in the slice. so I don't understand why it fails:
> 
> ```
>   %26 : Tensor = onnx::Shape(%21)
>   %27 : Tensor = onnx::Constant[value={0}]()
>   %28 : Tensor = onnx::Constant[value={0}]()
>   %29 : Tensor = onnx::Constant[value={2}]()
>   %30 : Tensor = onnx::Slice(%26, %28, %29, %27)
> ```

Is it convenient for you to share your model and yml? if so I can check it.

**Comment by davidenitti** [comment]
@lu229 here you are, it's a really simple net, with just a resize layer
[tempnet_v11.zip](https://github.com/XiaoMi/mace/files/5274722/tempnet_v11.zip)

**Comment by davidenitti** [comment]
@lu229 here you are, it's a simple model with just a resize.
[tempnet_v11.zip](https://github.com/XiaoMi/mace/files/5274761/tempnet_v11.zip)
thanks

**Comment by lu229** [comment]
@davidenitti Sorry, I find the problem, it is because we did support the new version of Slice OP, you can apply this [patch](https://github.com/lu229/repository/blob/master/issue677.patch) to support it.
By the way, the `Resize` Op is not support by MACE for its `sizes` input is not const, perhaps you need to make it const.
