### ISSUE TITLE
Hourglass network from pytorch1.6 onnx1.7 v11 is not working

### ISSUE THREAD

**Issue by perrywu1989** [XiaoMi/mace#678]
System information
**OS Platform and Distribution: 19.10
**NDK version: r17c
**MACE version: master
**Python version: 3.5
**Bazel version: 0.13.1

Model deploy file (*.yml)
library_name: pose2d
target_abis: [armeabi-v7a]
model_graph_format: code
model_data_format: code
models:
  pose2d:
    platform: onnx
    model_file_path: /home/wufangyin/projects/mace-models/vrhand/pose2d.onnx
    model_sha256_checksum: 0d64c6ba4d0337eb66f97154fc01f3e82b3ebcc43578bd451248ba8c4d26808b
    subgraphs:
      - input_tensors: input
        output_tensors: output
        input_shapes: 1,256,256,1
        output_shapes: 1,64,64,22
        backend: pytorch
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 1

{'output_data_types': [1], 'data_type': 3, 'output_data_formats': [<DataFormat.NHWC: 1>], 'nnlib_graph_mode': 0, 'input_shapes': [[1, 256, 256, 1]], 'input_data_types': [1], 'platform': <Platform.ONNX: 2>, 'input_ranges': [[-1.0, 1.0]], 'output_tensors': ['output'], 'runtime': <DeviceType.CPU: 0>, 'model_sha256_checksum': '0d64c6ba4d0337eb66f97154fc01f3e82b3ebcc43578bd451248ba8c4d26808b', 'output_shapes': [[1, 64, 64, 22]], 'model_file_path': '/home/wufangyin/projects/mace-models/vrhand/pose2d.onnx', 'input_tensors': ['input'], 'input_data_formats': [<DataFormat.NHWC: 1>], 'backend': 'pytorch', 'limit_opencl_kernel_time': 0, 'obfuscate': 1}
Transform model to one that can better run on device
onnx model IR version:  6
constains ops domain:   version: 11
File "tools/python/convert.py", line 243, in <module>
    convert(conf, flags.output, flags.enable_micro)
File "tools/python/convert.py", line 78, in convert
    mace_model = convert_model(model_conf, quantize_stat)
File "tools/python/convert.py", line 196, in convert_model
    output_graph_def = converter.run()
File "/home/wufangyin/projects/mace/tools/python/transform/onnx_converter.py", line 485, in run
    self.convert_ops(graph_def)
File "/home/wufangyin/projects/mace/tools/python/transform/onnx_converter.py", line 567, in convert_ops
    % node.op_type)
File "/home/wufangyin/projects/mace/tools/python/utils/util.py", line 76, in mace_check
    for line in traceback.format_stack():
ERROR: /home/wufangyin/projects/mace/tools/python/transform/onnx_converter.py:567: Mace does not support onnx op type Resize yet

![image](https://user-images.githubusercontent.com/29011669/93851371-91f85180-fce2-11ea-9828-e47d6aa6cdc5.png)
![image](https://user-images.githubusercontent.com/29011669/93851401-9f154080-fce2-11ea-984e-a94a3d3dae32.png)

**Comment by lu229** [comment]
@perrywu1989 Yes the `Resize` operator for ONNX is not supported yet, perhaps you can support it by adding the op-convert code to `/mace/tools/python/transform/onnx_converter.py`.

**Comment by perrywu1989** [comment]
> @perrywu1989 Yes the `Resize` operator for ONNX is not supported yet, perhaps you can support it by adding the op-convert code to `/mace/tools/python/transform/onnx_converter.py`.

请问下，我能理解为是这个onnx_converter.py没跟新转换，但是mace已经支持了么

**Comment by perrywu1989** [comment]
> @perrywu1989 Yes the `Resize` operator for ONNX is not supported yet, perhaps you can support it by adding the op-convert code to `/mace/tools/python/transform/onnx_converter.py`.

其实我想使用的就是普通的双线性上采样，这应该是一个很基础的操作，还是因为pytorch版本或ONNX版本太高，造成的op没注册？

**Comment by perrywu1989** [comment]
@lu229 谢谢回复

**Comment by lu229** [comment]
> > @perrywu1989 Yes the `Resize` operator for ONNX is not supported yet, perhaps you can support it by adding the op-convert code to `/mace/tools/python/transform/onnx_converter.py`.
> 
> 请问下，我能理解为是这个onnx_converter.py没跟新转换，但是mace已经支持了么

是这样, 目前mace是支持resize_nearest_neighbor的, 代码在: /mace/mace/ops/resize_nearest_neighbor.cc, 我看Resize算子比较类似, 也许可以转换过来, 不过有些边角条件可能需要做一下转换.

**Comment by lu229** [comment]
> > @perrywu1989 Yes the `Resize` operator for ONNX is not supported yet, perhaps you can support it by adding the op-convert code to `/mace/tools/python/transform/onnx_converter.py`.
> 
> 其实我想使用的就是普通的双线性上采样，这应该是一个很基础的操作，还是因为pytorch版本或ONNX版本太高，造成的op没注册？

双线性上采样mace是支持的, 也许你可以用Upsample这个算子?这个算子对应到mace就是resize_bilinear
