### ISSUE TITLE
Runtime issue

### ISSUE THREAD

**Issue by davidenitti** [XiaoMi/mace#679]
### System information
- **OS Platform and Distribution: 19.10
- **NDK version: r15c
- **GCC version : gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
- **MACE version: v0.13.0-0-g9a06864a
- **Python version: 3.7.5
- **Bazel version: 0.13.1

### Describe the problem
the std of the runtime is higher then expected (in Summary of Ops' Stat). it's bigger then max_runtime - min_runtime , which is statistically impossible.
I also do not understand why avg time in Summary of Ops' Stat (205.684 ms) is completely different from run_avg (419.188 ms) as showed below. what cause the difference?

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config=net.yml ; python tools/converter.py run --config=net.yml --benchmark --round 10
```

### Error information / logs

```bash
========================================================
     capability(CPU)        init      warmup     run_avg
========================================================
time          17.995     341.633     867.844     419.188

[...]

I mace/utils/statistics.cc:344]                           Summary of Ops' Stat
I mace/utils/statistics.cc:344] ------------------------------------------------------------------------
I mace/utils/statistics.cc:344] | round | first(ms) | curr(ms) | min(ms) | max(ms) | avg(ms) |     std |
I mace/utils/statistics.cc:344] ------------------------------------------------------------------------
I mace/utils/statistics.cc:344] |    10 |   206.023 |  205.643 | 205.249 | 206.579 | 205.684 | 362.571 |
I mace/utils/statistics.cc:344] ------------------------------------------------------------------------
I mace/utils/statistics.cc:344]

```

**Comment by lu229** [comment]
Option `--benchmark` is only used to stat the op's performance, the model's `run_avg` is not only the time sumary of the operators', which contains the other times, for example, the time consumed by data copying from CPU mem to GPU mem.

**Comment by davidenitti** [comment]
@lu229 is the time to copy the data optimizable in an application? if I use an image in input, are the data in float32 or uint8 in the benchmark?

**Comment by lu229** [comment]
> @lu229 is the time to copy the data optimizable in an application? if I use an image in input, are the data in float32 or uint8 in the benchmark?

@davidenitti Maybe you can optimize it by reducing the switching between GPU and CPU， The data is computed by float32 if you did not quantize the model.

**Comment by davidenitti** [comment]
@lu229 thank you very much, another question what is BufferTransform that appears as an operation that takes a lot of time?

**Comment by lu229** [comment]
> @lu229 thank you very much, another question what is BufferTransform that appears as an operation that takes a lot of time?

BufferTransform is the op that converts the data between GPU Image and CPU Buffer.
