### ISSUE TITLE
[Bug] some bad case in broadcast add

### ISSUE THREAD

**Issue by perrywu1989** [XiaoMi/mace#680]
pytorch two tensors add
size:BCHW, one size is [B,1,1,1], and the other one is [B,4,1,1]

run_model output error:
Check failed: (input0->dim_size() == 4) && ((input1->dim_size() == 0) || (input1->dim_size() == 4 && input1->dim(1) == input0->dim(1) && (input1->dim(0) == input0->dim(0) || input1->dim(0) == 1)) || (input1->dim_size() == 1 && input1->dim(0) == input0->dim(1))) only support broadcast channel dimension

i think it should modify the broadcast condition in eltwise.cc:

    if (has_data_format_) {
      MACE_CHECK(
          (input0->dim_size() == 4) &&
              ((input1->dim_size() == 0) ||
                  (input1->dim_size() == 4 &&
                      input1->dim(1) == input0->dim(1) &&
                      (input1->dim(0) == input0->dim(0) ||
                          input1->dim(0) == 1)) ||
                  (input1->dim_size() == 1 &&
                      input1->dim(0) == input0->dim(1))),
          "only support broadcast channel dimension");
    }

**Comment by lu229** [comment]
@perrywu1989  We only support channel dimension' broadcast, in the two tensors, the first one's channel is not equal to the second one's channel, so it abort.

**Comment by perrywu1989** [comment]
@lu229 可能是我理解有误，channel dim的broadcast，难道不是可以对channel上进行broadcast么，所以两个tensor的channal可以不同

![image](https://user-images.githubusercontent.com/29011669/93955335-16e67800-fd82-11ea-8104-bab05c60b67a.png)

**Comment by perrywu1989** [comment]
@lu229 谢谢指导

**Comment by lu229** [comment]
> @lu229 可能是我理解有误，channel dim的broadcast，难道不是可以对channel上进行broadcast么，所以两个tensor的channal可以不同
> 
> ![image](https://user-images.githubusercontent.com/29011669/93955335-16e67800-fd82-11ea-8104-bab05c60b67a.png)

你说得对，这里确实容易引起误解，我们改一下~
