### ISSUE TITLE
not find rpcmem.a when build using cmake-build-host.sh

### ISSUE THREAD

**Issue by i4oolish** [XiaoMi/mace#681]
### System information
- **OS Platform and Distribution (Linux Ubuntu 16.04.6)**:
- **NDK version(r21)**:
- **GCC version(5.4.0)**:
- **MACE version (v0.13.0-0-g9a06864)**:
- **Python version(3.6.12)**: 
- **Bazel version ( 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
When I use cmake-build-host.sh to build the mace, it failed.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. ./tools/cmake/cmake-build-host.sh
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
[100%] Built target mace_cc_benchmark
Install the project...
-- Install configuration: ""
-- Installing: /home/test/mace/build/cmake-build/host/install/lib/libprotobuf-lite.a
CMake Error at cmake_install.cmake:45 (file):
  file INSTALL cannot find
  "/home/test/mace/third_party/rpcmem//rpcmem.a".


Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by lu229** [comment]
@i4oolish Sorry it is a bug in 0.13.0, please use the `master` branch which has resolved this problem.

**Comment by i4oolish** [comment]
@lu229 Hi, lu. Could you tell me the PR which fixed this problem, or what can i do to fix it. As I do not want to checkout to master branch. What i want to do is quickly fixed this issue on the current branch. 
Thanks for you help~

**Comment by lu229** [comment]
@i4oolish Sorry, it's too long ago so that I forgot about it. The interface of the `master` branch did not change, maybe you can consider it?

**Comment by i4oolish** [comment]
@lu229 I have successfully build on master branch, thanks for you help~
