### ISSUE TITLE
convert生成的build floder为相同名称

### ISSUE THREAD

**Issue by perrywu1989** [XiaoMi/mace#682]
onnx-pose2dcoord.yml 为什么这个yml，在build里生成的名字是pose2d，我以前确实也convert过onnx-pose2d.yml，但是脚本应该不会缓存把，而且模型ONNX和输出维度都改变了

library_name: pose2dcoord
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  pose2d:
    platform: onnx
    model_file_path: /home/wufangyin/projects/mace-models/vrhand/pose2dcoord.onnx
    model_sha256_checksum: 881bac89f94deee95cf42f951f6f628269af3bf6e693881164977591a636124e
    subgraphs:
      - input_tensors: input
        output_tensors: output
        input_shapes: 1,256,256,1
        output_shapes: 1,22,2,1
        backend: pytorch
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

**Comment by lee-bin** [comment]
可以看下文件修改时间，看是以前还是现在生成的。
