### ISSUE TITLE
DSP error:  HEXAGON only support HWIO/HWIM filter format.

### ISSUE THREAD

**Issue by davidenitti** [XiaoMi/mace#683]
### System information
- **OS Platform and Distribution: 19.10
- **NDK version: r15c
- **GCC version : gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
- **MACE version: v0.13.0-0-g9a06864a
- **Python version: 3.7.5
- **Bazel version: 0.13.1

### Describe the problem
converting a model to dsp does not work

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config=net.yml 
```

the model is here:
[tempnet_v9.zip](https://github.com/XiaoMi/mace/files/5275376/tempnet_v9.zip)

### Error information / logs

```
Transform model to one that can better run on device
onnx model IR version:  6
constains ops domain:   version: 9
Transform fake quantize
Fold conv and bn: Conv_2(Conv2D)
Fold activation: Conv_2(Conv2D)
Transpose filters to HWIO/HWIM
File "tools/converter.py", line 1177, in <module>
    flags.func(flags)
File "tools/converter.py", line 828, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR, flags.enable_micro)
File "tools/python/convert.py", line 78, in convert
    mace_model = convert_model(model_conf, quantize_stat)
File "tools/python/convert.py", line 193, in convert_model
    output_graph_def, quantize_activation_info = mace_transformer.run()
File "tools/python/transform/transformer.py", line 140, in run
    changed = transformer()
File "tools/python/transform/transformer.py", line 1169, in transpose_filters
    "HEXAGON only support HWIO/HWIM filter format.")
File "tools/python/utils/util.py", line 76, in mace_check
    for line in traceback.format_stack():
ERROR: tools/python/transform/transformer.py:1169: HEXAGON only support HWIO/HWIM filter format.
```

**Comment by lee-bin** [comment]
We only support the TensorFlow model for Hexagon DSP now. Other model formats may need some changes to convert.

**Comment by davidenitti** [comment]
I'm coverting from onnx (from pytorch) is there a way to make it run?

**Comment by lee-bin** [comment]
You can try to transpose the filter format from OIHW to HWIO around [here](https://github.com/XiaoMi/mace/blob/63feaf5055bab6a081d36edfab8f963a624899aa/tools/python/transform/transformer.py#L1183), as Hexagon DSP needs HWIO filter format.

**Comment by eudora-jia** [comment]
@lee-bin  hello,  can you give  me your patch  about how to convert ONNX to DSP runtime model?? 3Q

**Comment by lee-bin** [comment]
@eudora-jia https://github.com/lee-bin/test/blob/onnx/onnx.diff
