### ISSUE TITLE
Mace does not support onnx op type Tdnn yet

### ISSUE THREAD

**Issue by groovemaxRong** [XiaoMi/mace#686]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
Hi, i'm trying to convert the kaldi model with tdnn component to mace, but it fails during the convert process. How can i fix this convertion error, thanks.
...
...
Transform model to one that can better run on device
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: Scale was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
('onnx model IR version: ', 7L)
('constains ops domain: ', u'ai.kaldi.dnn', 'version:', 7L)
File "/path/to/mace/tools/converter.py", line 1176, in <module>
    flags.func(flags)
File "/path/to/mace/tools/converter.py", line 827, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR, flags.enable_micro)
File "tools/python/convert.py", line 78, in convert
    mace_model = convert_model(model_conf, quantize_stat)
File "tools/python/convert.py", line 190, in convert_model
    output_graph_def = converter.run()
File "tools/python/transform/onnx_converter.py", line 477, in run
    self.convert_ops(graph_def)
File "tools/python/transform/onnx_converter.py", line 559, in convert_ops
    % node.op_type)
File "tools/python/utils/util.py", line 76, in mace_check
    for line in traceback.format_stack():
ERROR: tools/python/transform/onnx_converter.py:559: Mace does not support onnx op type Tdnn yet

### To Reproduce
Steps to reproduce the problem:
```bash
python2 /path/to/mace/tools/converter.py convert --config=model.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@groovemaxRong Yes, it hasn't been supported yet. I saw a developer using an alternative method, perhaps you can try: He modified the model definition file(final.config) of Kaldi, and the definition of `tdnn` is transformed into an equivalent `affine`(which has been supported), and then uses the transformed definition file to train the network in Kaldi.

**Comment by groovemaxRong** [comment]
@lu229 okay, thanks
