### ISSUE TITLE
get max RAM and GPU memory used

### ISSUE THREAD

**Issue by davidenitti** [XiaoMi/mace#687]
Is there a way to have the maximum RAM and GPU memory used on android by the MACE model inference?

### System information
- **OS Platform and Distribution: 19.10
- **NDK version: r15c
- **GCC version : gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
- **MACE version: v0.13.0-0-g9a06864a
- **Python version: 3.7.5
- **Bazel version: 0.13.1

**Comment by lu229** [comment]
@davidenitti Why do you want to use the maximum RAM and GPU memory?

**Comment by davidenitti** [comment]
I want to estimate the maximum memory (the peak usage) required by a model (if it's cpu model only cpu memory, if it's gpu model cpu and gpu memory).
