### ISSUE TITLE
How To Read Mace Model Weight In Text Format

### ISSUE THREAD

**Issue by groovemaxRong** [XiaoMi/mace#688]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### Describe the problem
Hi, i am using the mace to build some kaldi project in android platform, but it turns out that the result is quite different from that in linux platform without mace.

The debug steps i had done is:
1) check the input wav pcm data and it's right.
2) check the kaldi feature pipeline in both mace based kaldi project in android and kaldi project in linux, and it's right.
3) use the offical built mace model and the offical build kaldi asr project code, and it's right. The decode result is the same as the text.
4) check the mace network output for each frame, but it's quite different. So i'm wondering there might be somethings wrong.

The place that may have bug:
1). model convertion process. kaldi -> onnx -> mace.
2). the code that i write use the MaceComputer to compute the acoutic loglike.

The information i want to know(checking whether the kaldi -> onnx -> mace is right):
1) how can i print the weight from the MaceComputer? 
- std::shared_ptr<mace::MaceEngine> engine_;
  there is a member in mace.cc::MaceEngine:  std::unique_ptr<port::ReadOnlyMemoryRegion> model_data_
- void *model_weights_data_;
2) how can i print the weight and model struct from the model.data and model.pb file?
- something like nnet-copy --binary=false model.data model.data.txt 

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
@groovemaxRong 
1. The model weights can be printed in this [method](https://github.com/XiaoMi/mace/blob/63feaf5055bab6a081d36edfab8f963a624899aa/mace/core/workspace.cc#L120). MACE supports several data types, so you may need some time to know which exact type do you use. You may set VLOG level to 3 to help debugging.
2. Text model can be found in `mace/codegen/models/model_name/model/model_name` after conversion. If text model data is needed, [these lines of code](https://github.com/XiaoMi/mace/blob/63feaf5055bab6a081d36edfab8f963a624899aa/tools/python/utils/convert_util.py#L78) need to be commented out, as the model data is extracted from the model struct before storage.

**Comment by groovemaxRong** [comment]
@lee-bin I comment out the code and get the text model data. Thanks for your help.
