### ISSUE TITLE
Kaldi Android: MaceComputer's nnet outpus isn't the same as Kaldi NnetComputer

### ISSUE THREAD

**Issue by groovemaxRong** [XiaoMi/mace#689]
### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
Hi, i am using the mace to build some kaldi project in android platform, but it turns out that the result is quite different from that in linux platform without mace.

The debug steps i had done is:
1. Check the input wav pcm data and feature pipleline in both mace based kaldi project in android and kaldi project in linux, and it's right.
2. The converted mace model weight, and it's the same as the kaldi model weight.
3. Use the offical built mace model and the offical build kaldi asr project code, and it's right. The decode result is the same as the text.

The information i want to know:
1. Why the MaceComputer's nnet outputs isn't the same as Kaldi NnetComputer?
- given the same model and config, the same input feature and config
2. I also try using the offical build kaldi asr project code except using my feature config and model, but the MaceComputer's nnet outputs is also the same as the mace based kaldi project i write. That may mean the way i combining the mace and kaldi is right, but the nnet output is still quite different from the Kaldi NnetComputer.

Thanks.

The detailed log:
1. the input feature and nnet output
```
- here i only print some frames and dimensions to better clarify this issue.
...
Matrix<BaseFloat> output;
computer_->GetOutput(&output);
// debug
KALDI_LOG << "nnet out";
for(size_t i = 0; i < 20; ++i){
  KALDI_LOG << output(15, i);
}
...
- The mace based kaldi project's input feature (from input_features_->GetFrame())
AdvanceChunk():mace-decodable-online-looped.cc:132) input feature
AdvanceChunk():mace-decodable-online-looped.cc:137) 1.66497
AdvanceChunk():mace-decodable-online-looped.cc:137) 0.298115
AdvanceChunk():mace-decodable-online-looped.cc:137) 3.35621
AdvanceChunk():mace-decodable-online-looped.cc:177) nnet out
AdvanceChunk():mace-decodable-online-looped.cc:179) -3.32336
AdvanceChunk():mace-decodable-online-looped.cc:179) 1.12159
AdvanceChunk():mace-decodable-online-looped.cc:179) 1.67782
- The linux kaldi project 's input feature (from input_features_->GetFrame())
AdvanceChunk():decodable-online-looped.cc:173) input feature
AdvanceChunk():decodable-online-looped.cc:178) 1.66497
AdvanceChunk():decodable-online-looped.cc:178) 0.298116
AdvanceChunk():decodable-online-looped.cc:178) 3.35621
AdvanceChunk():decodable-online-looped.cc:232) nnet out
AdvanceChunk():decodable-online-looped.cc:234) -2.92612
AdvanceChunk():decodable-online-looped.cc:234) 0.332591
AdvanceChunk():decodable-online-looped.cc:234) 0.31575
```
2. the model weight
```
- the mace version  model weight
  ...
  data_type: DT_HALF
  float_data: 2.63805103302
  float_data: 1.23130202293
  float_data: -0.0862819701433
  float_data: 0.010600999929
  float_data: -0.541815519333
  float_data: -0.247513398528
  float_data: -0.371077686548
  ...
- the kaldi version model weight
...
2.638051 1.231302 -0.08628197 0.010601 -0.5418155 -0.2475134 -0.3710777 ...
...
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@groovemaxRong Sorry for the late reply. 
This problem need debug, perhaps you can first debug the correctness between `mace` and `onnx`, you can refer to this [document](https://mace.readthedocs.io/en/latest/development/how_to_debug.html#debug-correctness).

**Comment by groovemaxRong** [comment]
@lu229 Okay, i get it  and thanks for your reply.

**Comment by groovemaxRong** [comment]
@lu229 Hi, i follow your instrution to validate the mace model. But the ```python tools/converter.py run --config=${CONF_FILE} --validate --layers 0:-1``` did't output the validate file in build/your_model/model/runtime_in_yaml/log.csv.
And i want to know how to get the log.csv file so i can check the acc.

The debug steps i had done is:
1. validate the fake test input data
    the test data generate by /path/to/kaldi-onnx/tools/generate_inputs.py has a right nnet output by nnet3-compute
    and the data does exist in the storage dir
2. check the yml file
    - subgraphs:
          ...
          validation_inputs_data:
            - $datadir/test_input.npy
          validation_outputs_data:
            - $datadir/kaldi_output.npy
          ...
3. try --validate | --validate --layers 0:-1, and the command parameter behind python tools/converter.py is 'run', not 'convert'
4. the command is run successfully and i can get the weight and .pb file
```
mace/tools/converter.py:339: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
* Package libs for first_nnet
Start packaging 'test' libs into build/test/libmace_first_nnet.tar.gz
build/test/model/
build/test/model/test.data
build/test/model/test.pb
Packaging Done!

----------------------------------------------------------------------
                               Library
----------------------------------------------------------------------
|          key           |                   value                   |
======================================================================
| MACE Model package Path| build/test/libmace_test.tar.gz|
```

**Comment by lu229** [comment]
@groovemaxRong Please plugin phone with your computer, and don't specify the socs in `yml` file,

**Comment by groovemaxRong** [comment]
@lu229 Thanks for your reply, and i'm using the mace way to debug the model, but it fails with some problems.

### The debug steps i had done is:
1. use the whole model to run the debug code, and it run successfully but the mace output is not right.
2. use the kaldi nnet-am-copy edit to modify the output from the input side, and the kaldi nnet-compute can process well, but the mace output is empty with some check failed information, which is comfusing.

### To Reproduce
I have packed the model and test script in the zip file. Do remember to add the `pwd` in the command line because i use the pushd command.
[test_for_mace.zip](https://github.com/XiaoMi/mace/files/5398802/test_for_mace.zip)

```bash
1. chmod 755 ./prepare_onnx_test.sh
2. ./prepare_onnx_test.sh final.mdl `pwd`/data `pwd`/model
```

### The Log Message
[log.log](https://github.com/XiaoMi/mace/files/5398827/log.log)

```
* Run 'first_nnet' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
I mace/tools/mace_run.cc:530] model name: first_nnet
I mace/tools/mace_run.cc:531] mace version: v0.13.0-0-g9a06864
I mace/tools/mace_run.cc:532] input node: input
I mace/tools/mace_run.cc:533] input shape: 1,53,43
I mace/tools/mace_run.cc:534] output node: output.affine
I mace/tools/mace_run.cc:535] output shape: 1,17,120
I mace/tools/mace_run.cc:536] input_file: build/first_nnet/_tmp/first_nnet/63b78d407b79dbaa6e420a82fff7481d/host/model_input
I mace/tools/mace_run.cc:537] output_file: build/first_nnet/_tmp/first_nnet/63b78d407b79dbaa6e420a82fff7481d/host/model_out
I mace/tools/mace_run.cc:538] input dir:
I mace/tools/mace_run.cc:539] output dir:
I mace/tools/mace_run.cc:540] model_data_file: build/first_nnet/model/first_nnet.data
I mace/tools/mace_run.cc:541] model_file: build/first_nnet/model/first_nnet.pb
I mace/tools/mace_run.cc:542] device: CPU
I mace/tools/mace_run.cc:543] round: 1
I mace/tools/mace_run.cc:544] restart_round: 1
I mace/tools/mace_run.cc:545] gpu_perf_hint: 3
I mace/tools/mace_run.cc:546] gpu_priority_hint: 3
I mace/tools/mace_run.cc:547] omp_num_threads: -1
I mace/tools/mace_run.cc:548] cpu_affinity_policy: 1
I mace/libmace/mace.cc:500] Creating MaceEngine, MACE version: v0.13.0-0-g9a06864
I mace/libmace/mace.cc:539] Initializing MaceEngine
I mace/libmace/mace.cc:682] Destroying MaceEngine
I mace/tools/mace_run.cc:599] restart round 0
I mace/libmace/mace.cc:953] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:500] Creating MaceEngine, MACE version: v0.13.0-0-g9a06864
I mace/libmace/mace.cc:539] Initializing MaceEngine
I mace/tools/mace_run.cc:272] Create Mace Engine latency: 31.436 ms
I mace/tools/mace_run.cc:279] Total init latency: 46.731 ms
I mace/tools/mace_run.cc:373] Warm up run
F mace/ops/splice.cc:68] Check failed: forward_indexes_[i] < input_chunk && forward_indexes_[i] >= 0  forward index:53 input shape:1,53,43
F mace/ops/splice.cc:68] backtrace:
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x5c22ab]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x5c5505]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x5c5f00]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x5c5f54]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x479974]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x47ade8]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x5a5c4f]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x4399f2]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x43a3d7]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x4101cf]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x412f31]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x407d19]
F mace/ops/splice.cc:68]  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f5bd74c1830]
F mace/ops/splice.cc:68]  build/first_nnet/_tmp/host/mace_run_static() [0x409b49]

```

**Comment by lu229** [comment]
@groovemaxRong Sorry for the late replay, I'm very busy these days. I converted and run your model and found no problems.
the commands are:
python tools/converter.py convert --config=${CONF_FILE}
python tools/converter.py run --config=${CONF_FILE} --validate

The result is:
Pull /data/local/tmp/mace_run/model_out_output_affine to build/first_nnet/_tmp/first_nnet/628dd01a507a63fc2e6b02511b9adae2/Andromeda_msmnile/armeabi-v7a
output.affine MACE VS ONNX similarity: 0.999999952023911 , sqnr: 10115947.350050507 , pixel_accuracy: 1.0
******************************************
          Similarity Test Passed          
******************************************

**Comment by groovemaxRong** [comment]
@lu229 Okay, thanks for your reply. I find the bug is my kaldi-onnx code may be changed during my debug process and now the test result is right. And thanks again for your help.
