### ISSUE TITLE
I don't know how to apply the newly trained model (.pb) to Android PoseMace.

### ISSUE THREAD

**Issue by chartores** [XiaoMi/mace#690]
I don't know how to apply the newly trained model (.pb) to Android. to Android PoseMace.

train.py -> xxx.meta / xxx.index / xxx.data -> gen_frozen_pb .py -> xxx.pb -> [Mace Library]converter.py -> mace.model???

Is it correct to follow the steps below?

For mobile phone performance, it must be driven by the mace library app.

. pb file and then how to apply it to Android.

**Comment by lu229** [comment]
@chartores We have the tool to convert the model(.pb), please refer to the [document](https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html), before you convert model, make sure you have installed the environment  or you can use the docker, please refer to the [document](https://mace.readthedocs.io/en/latest/installation/env_requirement.html#).

**Comment by chartores** [comment]
@lu229  
Training and testing on the PC is already done through the environment settings. But I don't know how to apply the newly trained deep learning model to Android.
(I know that it can be applied by converting to a "Mace" model instead of "TFlite", but I don't know how to do it directly.)
Which part of the document site can I refer to?

使用环境设置已经完成了PC上的培训和测试。 但是我不知道如何将新训练的深度学习模型应用于Android。
（我知道可以通过转换为“ Mace”模型而不是“ TFlite”来应用它，但是我不知道如何直接执行。）
我可以参考文档网站的哪一部分？

**Comment by lu229** [comment]
@chartores 可以参考我们的android例子：https://github.com/XiaoMi/mace/tree/master/examples/android

**Comment by chartores** [comment]
@lu229  
谢谢您的好回答Thank you for your kind answer. If you can't excuse me, I wonder one last thing. Can you take a look at the question issue?
如果您不能原谅我，我对最后一件事很好奇。 您能看一下问题吗？

**Comment by lu229** [comment]
@chartores 已回复，我们可以在那个issue里继续交流
