### ISSUE TITLE
Error: ./mace/core/runtime/hexagon/hexagon_allocator.h:30:3: error: unknown type name 'Rpcmem'

### ISSUE THREAD

**Issue by zhchin** [XiaoMi/mace#694]
Hi,

I followed the instruction on [https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html](https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html) and tried to enable DSP support but found an error:

$ bash tools/bazel_build_standalone_lib.sh -abi=arm64-v8a -runtime=CPU,GPU,DSP
...
Use --sandbox_debug to see verbose messages from the sandbox
In file included from mace/core/runtime/hexagon/hexagon_device.cc:15:
In file included from ./mace/core/runtime/hexagon/hexagon_device.h:22:
./mace/core/runtime/hexagon/hexagon_allocator.h:30:3: error: unknown type name 'Rpcmem'
  Rpcmem *rpcmem() override;
  ^
./mace/core/runtime/hexagon/hexagon_allocator.h:33:3: error: unknown type name 'Rpcmem'
  Rpcmem rpcmem_;
  ^
mace/core/runtime/hexagon/hexagon_device.cc:46:10: error: cannot initialize return object of type 'mace::Allocator *' with an rvalue of type 'std::unique_ptr<mace::HexagonAllocator, std::default_delete<mace::HexagonAllocator> >::pointer' (aka 'mace::HexagonAllocator *')
  return allocator_.get();
         ^~~~~~~~~~~~~~~~
3 errors generated.

Could you let me know how to fix this?

**Comment by lu229** [comment]
@zhchin What is the mace version? Please use the v1.0.0?

**Comment by zhchin** [comment]
Thanks for your reply. I did use v1.0.0. The system environment information is as follow:

### System information
- **OS Platform and Distribution: Ubuntu 18.04
- **NDK version: 15c
- **MACE version (Use the command: git describe --long --tags)**: v1.0.0-0-g0945e498
- **Python version(2.7)**:  3.6.9
- **Bazel version (e.g., 0.13.0)**:  0.13.0

**Comment by lu229** [comment]
@zhchin I'm sorry this is the MACE's bug, please apply this [patch](https://github.com/lu229/repository/blob/master/issue694.patch) and fix it, thanks for your report.

**Comment by zhchin** [comment]
Issue fixed. Thanks for your support.
