### ISSUE TITLE
Does anyone know what kind of error this is? I also want to get a little hint.

### ISSUE THREAD

**Issue by chartores** [XiaoMi/mace#696]
Error(concat.cc:230 Check failed: inputs_count == 2 || divisible_four Dimensions of inputs should be divisible by 4 when inputs_count > 2.)

https://github.com/XiaoMi/mace/issues/695

**Comment by lu229** [comment]
@chartores Please trace this issue in [#695](https://github.com/XiaoMi/mace/issues/695)
