### ISSUE TITLE
量化工具的使用：获取range log

### ISSUE THREAD

**Issue by wtmilk** [XiaoMi/mace#699]
参照官方文档，对inceptrionv3量化；对cmake的用户，使用的run_model.py 脚本，是对的吗？run_model.py 没有--quantize_stat 这个参数？
python tools/image/image_to_tensor.py --input /path/to/directory/of/input/images
  --output_dir /path/to/directory/of/input/tensors --image_shape=299,299,3

# Rename input tensors to start with input tensor name(to differentiate multiple
# inputs of a model), input tensor name is what you specified as "input_tensors"
# in yaml config. For example, "input" is the input tensor name of InceptionV3 as below.
rename 's/^/input/' *

# Run with input tensors
# For CMake users:
python tools/python/run_model.py --config ../mace-models/inception-v3/inception-v3.yml
  --quantize_stat --input_dir /path/to/directory/of/input/tensors > range_log

# For Bazel users:
python tools/converter.py run --config ../mace-models/inception-v3/inception-v3.yml
  --quantize_stat --input_dir /path/to/directory/of/input/tensors > range_log

Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@wtmilk Cmake方式目前不支持量化，还请使用bazel．我们正在支持@zhangzhimin

**Comment by wtmilk** [comment]
> @wtmilk Cmake方式目前不支持量化，还请使用bazel．我们正在支持@zhangzhimin

了解了
