### ISSUE TITLE
Conversion Issue

### ISSUE THREAD

**Issue by rose-jinyang** [XiaoMi/mace#704]
1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
Sure

2. Have you ever read the document for your usage?
Yes

------------------------

### System information
- OS Platform and Distribution: Ubuntu 18.04 LTS 64 bit aarch64
 - NDK version: Not installed
- GCC version: 7.5.0
- MACE version: 0.13.0, 1.0.1
- Python version: 3.7 
- Bazel version : Not installed

- Model deploy file (*.yml)

/mace-models/mobilenet-v1/mobilenet-v1.yml

### Describe the problem
I was going to convert MobileNet model of mace-models.
I installed all the dependencies.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /home/marvsmart/Jin/mace
2. python tools/converter.py convert --config_file=/home/marvsmart/Jin/mace-models/mobilenet-v1/mobilenet-v1.yml
```

### Error information / logs

WARNING: tools/python/py_proto/__init__.py:37: No bazel, use cmake.
CMD> bash tools/cmake/cmake-generate-proto-py-host.sh
CMAKE_VERSION: 3.18.0
CMAKE_INSTALL_PREFIX: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marvsmart/Jin/mace/build/cmake-build/host
[  0%] Performing build step for 'protoc_bin'
[  1%] Building CXX object CMakeFiles/libprotobuf-lite.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/extension_set.cc.o
[  2%] Building CXX object CMakeFiles/libprotobuf-lite.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/arena.cc.o
[  2%] Building CXX object CMakeFiles/libprotobuf-lite.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/implicit_weak_message.cc.o
.... .... ....
... ... ... ...

[ 49%] Building CXX object CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/wrappers.pb.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf.dir/build.make:458: recipe for target 'CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/descriptor.pb.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/descriptor.pb.cc.o] Error 4
make[6]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf.dir/build.make:133: recipe for target 'CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_util.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_util.cc.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf-lite.dir/build.make:133: recipe for target 'CMakeFiles/libprotobuf-lite.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_util.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf-lite.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_util.cc.o] Error 4
make[6]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf.dir/build.make:835: recipe for target 'CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/util/internal/datapiece.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/util/internal/datapiece.cc.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf.dir/build.make:549: recipe for target 'CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_reflection.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf.dir/home/marvsmart/Jin/mace/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_reflection.cc.o] Error 4

... .... .... ....
... .... .... ....

### Additional context
None

**Comment by lu229** [comment]
Many reasons can cause this problem, the most common reason is the memory is not enough, what is the memory size of your computer?

**Comment by rose-jinyang** [comment]
The memory size is 4GB.

**Comment by lu229** [comment]
@rose-jinyang Did you use the code mode in 'yml' file? What is the size of your model file?

**Comment by rose-jinyang** [comment]
Yes, I tried ONNX and Tensorflow pb models, the model size is about 91 MB.

**Comment by lu229** [comment]
> Yes, I tried ONNX and Tensorflow pb models, the model size is about 91 MB.

Your computer's memory size is not big so that the code mode building failed, perhaps you can try the file mode in the yml file.
