### ISSUE TITLE
mace 算子的参数描述文档

### ISSUE THREAD

**Issue by gglin001** [XiaoMi/mace#705]
请问各个转化后的算子参数有整理后的文档吗？

链接
https://mace.readthedocs.io/en/latest/user_guide/op_lists.html

只有算子列表， 似乎没有参数描述

**Comment by lu229** [comment]
@gglin001 不好意思，这个没有，可以参考mace/ops里面各个算子的代码实现？

**Comment by gglin001** [comment]
好的，感谢回复
