### ISSUE TITLE
undefined reference to `mace::CreateMaceEngineFromProto

### ISSUE THREAD

**Issue by groovemaxRong** [XiaoMi/mace#706]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **NDK version(e.g., 15c)**: r16b
- **ADNROID_API**：21
- **ANDROID_BUILD_TOOLS_VERSION**： 21.1.2
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v1.0.1-0-gc8c2429
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Describe the problem
Hi, i try to merge the mace dockerfile and mace-kit kaldi dockerfile into one, and test with different android API and android arch. 
For armv8: 
ndk-r19c & android_api-26: good
...
ndk-r19c & android_api-23: good

ndk-r16b & android_api-18：fail with error undefined reference to mace::CreateMaceEngineFromProto
[libmace-failed.zip](https://github.com/XiaoMi/mace/files/5780795/libmace-failed.zip)
, but i can find the function in the library;
```
root@3d8728fad96b:/opt/kaldi# nm -D tools/libmace/libmace.so | grep CreateMaceEngineFromProto
000000000004a968 T _ZN4mace25CreateMaceEngineFromProtoEPKhmS1_mRKSt6vectorISsSaISsEES6_RKNS_16MaceEngineConfigEPSt10shared_ptrINS_10MaceEngineEE
000000000004ab74 T _ZN4mace25CreateMaceEngineFromProtoERKSt6vectorIhSaIhEERKSsRKS0_ISsSaISsEESA_RKNS_16MaceEngineConfigEPSt10shared_ptrINS_10MaceEngineEE
```
ndk-r16b & android_api-18：then i try using the offical built libmace.so(i don know which ndk and android it is), but it success!

My question is, 
1. why the built failed in ndk-r16b & android_api-18, but in some nkd version it's okay.
2. is the libmace can be directly even in different ndk version and android api.

Thanks.

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@groovemaxRong Perhaps you compile the `libmace` with the `ndk` version >= 17c, which uses the libc++, and when you use `ndk-r16b` to compile the make kit, the `ndk-r16b` use the libstdc++. You can compile them with the same `ndk` version and you will link them success.

**Comment by groovemaxRong** [comment]
@lu229 I have merged the mace and mace kit into single dockerfile, so the ndk version is set as r16b in both mace and mace-kit; And i wander if any parameter i should change when compiling with the kaldi in mace-kit.

The ndk Env
```
# Install SDK
ENV ANDROID_SDK_FILENAME sdk-tools-linux-${ANDROID_SDK_VERSION}.zip
ENV ANDROID_SDK_URL https://dl.google.com/android/repository/${ANDROID_SDK_FILENAME}
ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
RUN mkdir -p /opt/sdk && \
    cd /opt && \
    wget -q ${ANDROID_SDK_URL} && \
    unzip ${ANDROID_SDK_FILENAME} -d ${ANDROID_HOME} && \
    rm ${ANDROID_SDK_FILENAME} && \
    yes | android update sdk --no-ui -a --filter tools,platform-tools,android-${ADNROID_API},build-tools-${ANDROID_BUILD_TOOLS_VERSION}
RUN ${ANDROID_HOME}/tools/bin/sdkmanager "cmake;${CMAKE_VERSION}"

# Download NDK
ENV ANDROID_NDK_FILENAME android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
ENV ANDROID_NDK_URL https://dl.google.com/android/repository/${ANDROID_NDK_FILENAME}
RUN cd /opt/ && \
    wget -q $ANDROID_NDK_URL && \
    unzip -q ${ANDROID_NDK_FILENAME} && \
    rm -f ${ANDROID_NDK_FILENAME}
RUN cd /opt/android-ndk-${ANDROID_NDK_VERSION}/toolchains && \
    ln -sf `pwd`/aarch64-linux-android-4.9 mips64el-linux-android && \
    ln -sf `pwd`/arm-linux-androideabi-4.9 mipsel-linux-android
# Install Android toolchain
# see detail: https://developer.android.com/ndk/guides/standalone_toolchain
RUN ${ANDROID_NDK_HOME}/build/tools/make_standalone_toolchain.py --arch ${ADNROID_TOOLCHAIN_ARCH} --api ${ADNROID_API} --stl=${CPLUSPLUSLIB} --install-dir ${ANDROID_TOOLCHAIN_PATH}
```

2. The Mace Env
```
# Making Mace
# Notes: the default library is: dynamic, add "-static" if you want
RUN cd /opt && \
    git clone https://github.com/XiaoMi/mace && \
    cd mace && \
    chmod +x tools/bazel_build_standalone_lib.sh

# minimize the mace library
# "https://github.com/XiaoMi/mace/blob/master/docs/user_guide/advanced_usage.rst#reduce-library-size"
RUN cd /opt/mace && \
    sed -i "s/hexagon=true/hexagon=false/g" tools/bazel_build_standalone_lib.sh && \
    sed -i "s/opencl=true/opencl=false/g" tools/bazel_build_standalone_lib.sh 

RUN cd /opt/mace && \
    bash tools/bazel_build_standalone_lib.sh -abi=${ADNROID_ARCH}
```

**Comment by lu229** [comment]
@groovemaxRong I think there are no parameters that need to be changed, communicate whenever you have problems.
