### ISSUE TITLE
The plan to add the deconv OP

### ISSUE THREAD

**Issue by learnerwang** [XiaoMi/mace#71]
Dear MACE group:
   I have two questions, the 1st is how can we hide the model file? We don't want to leak the model file pr the srcs when using the MACE.
  The 2nd question is there any plan to add the deconv OP? And could you please tell me the schedule?
Best regards

**Comment by TonyMou** [comment]
1. Refer to: https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#id1
config like this in your model deployment file.
```
model_data_format: code
model_graph_format: code
```

2. Mace already supports tensorflow tf.layers.conv2d_transpose.  Deconvolution for Caffe will be released very soon.

**Comment by learnerwang** [comment]
Thanks a lot! Looking forward to your update for caffee Deconvolution!
