### ISSUE TITLE
ERROR: tools/python/transform/onnx_converter.py:571: Mace does not support onnx op type Tdnn yet

### ISSUE THREAD

**Issue by beyondych11** [XiaoMi/mace#716]
Mace does not support onnx op type  Kaldi Tdnn yet?

**Comment by lu229** [comment]
@beyondych11 Yes, it's not supported yet. I saw a developer use an alternative method: in Kaldi's model definition file（ final.config ）, transformed the definition of `Tdnn` into an equivalent `Affine`, and then use Kaldi to train the network(the `Affine` is supported in MACE).

**Comment by beyondych11** [comment]
> @beyondych11 Yes, it's not supported yet. I saw a developer use an alternative method: in Kaldi's model definition file（ final.config ）, transformed the definition of `Tdnn` into an equivalent `Affine`, and then use Kaldi to train the network(the `Affine` is supported in MACE).
OK！thank for your reply!

**Comment by beyondych11** [comment]
@lu229 Hi！In my opinion, MACE is used to accelerate the inference of kaldi AM. But how to deploy the kaldi decode part on the mobile(android or ios) based on MACE? Are there some reference documents?

**Comment by lu229** [comment]
@beyondych11 Sorry for the late reply. MACE is a deep-learning framework on mobile devices and micro-controllers. Kaldi-ONNX is a tool for porting Kaldi Speech Recognition Toolkit neural network models to ONNX models for inference. The decoding part of Kaldi does not involve deep learning model, so you may need to deploy it yourself.
