### ISSUE TITLE
mace results do not match tensorflow results for quantization model

### ISSUE THREAD

**Issue by EchoIR** [XiaoMi/mace#728]
大佬好，我在验证onnx量化模型输出与mace输出结果一致性问题时，发现部分图的输出结果不一致，如下：
imdn_as/conv2d_46/act_quant/FakeQuantWithMinMaxVars MACE VS TENSORFLOW similarity: 0.5227736159921134 , sqnr: 1.072140544320622 , pixel_accuracy: 0.10447916666666666
ERROR: [] /container/path/onnx2mace/docker_path/mace_20210223/tools/validate.py:125: ******************************************
          Similarity Test Failed
******************************************
我基于tensorflow1.15.3平台量化，目的是在dsp上跑的（高通骁龙660 8 核 AIE芯片），以下是我的yml:
library_name: mobilenet-v2-quantize-retrain
target_abis: [arm64-v8a,armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v2_quantize_retrain:
    platform: tensorflow
    model_file_path: /container/path/onnx2mace/docker_path/fingertip0.3.3/unet_iteration_29000_relu_mean_nopow_nosqrt.pb
    model_sha256_checksum: 911489cf77d0fa0b5d73862d26f46af1e6b0d8f5b894a59f715ed0a361bb68f9
    subgraphs:
      - input_tensors:
          - Placeholder
        input_shapes:
          - 1,480,640,3
        input_ranges:
          - 0.0,1.0
        output_tensors:
          - imdn_as/conv2d_46/act_quant/FakeQuantWithMinMaxVars
        output_shapes:
          - 1,120,160,16
        check_tensors:
          - imdn_as/conv2d_46/act_quant/FakeQuantWithMinMaxVars
        check_shapes:
          - 1,120,160,16
        validation_inputs_data: 
          - /container/path/onnx2mace/docker_path/fingertip0.3.3/inputs_TF1/Placeholder0.npy
    runtime: dsp
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
    quantize: 1

同时改在cpu上跑时，mace报错：
I mace/tools/mace_run.cc:573] device: CPU
I mace/tools/mace_run.cc:574] round: 1
I mace/tools/mace_run.cc:575] restart_round: 1
I mace/tools/mace_run.cc:576] gpu_perf_hint: 3
I mace/tools/mace_run.cc:577] gpu_priority_hint: 3
I mace/tools/mace_run.cc:578] num_threads: -1
I mace/tools/mace_run.cc:579] cpu_affinity_policy: 1
I mace/tools/mace_run.cc:582] limit_opencl_kernel_time: 0
I mace/tools/mace_run.cc:587] opencl_queue_window_size: 0
I mace/libmace/mace.cc:564] Creating MaceEngine, MACE version: v1.0.2-22-gce1f704
I mace/libmace/mace.cc:634] Initializing MaceEngine
I mace/libmace/mace.cc:796] Destroying MaceEngine
I mace/tools/mace_run.cc:630] restart round 0
I mace/libmace/mace.cc:1152] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:564] Creating MaceEngine, MACE version: v1.0.2-22-gce1f704
I mace/libmace/mace.cc:634] Initializing MaceEngine
I mace/tools/mace_run.cc:291] Create Mace Engine latency: 45.467 ms
I mace/tools/mace_run.cc:298] Total init latency: 45.721 ms
I mace/tools/mace_run.cc:398] Warm up run
F mace/ops/eltwise.cc:1161] Check failed: input0->size() == input1->size() input0 and input1 must have the same shape.
F mace/ops/eltwise.cc:1161] backtrace:
F mace/ops/eltwise.cc:1161]  pc 0x5a53ed2ea4
F mace/ops/eltwise.cc:1161]  pc 0x5a53ed4f80
F mace/ops/eltwise.cc:1161]  pc 0x5a53ed4f34
F mace/ops/eltwise.cc:1161]  pc 0x5a53ed5130
F mace/ops/eltwise.cc:1161]  pc 0x5a53ed518c
F mace/ops/eltwise.cc:1161]  pc 0x5a53e38bec
F mace/ops/eltwise.cc:1161]  pc 0x5a53eb5430
F mace/ops/eltwise.cc:1161]  pc 0x5a53dfbf80
F mace/ops/eltwise.cc:1161]  pc 0x5a53de4f48
F mace/ops/eltwise.cc:1161]  pc 0x5a53de730c
F mace/ops/eltwise.cc:1161]  pc 0x5a53de74a4
F mace/ops/eltwise.cc:1161]  pc 0x7b0a5d0510 __libc_init
Aborted (core dumped)
ERROR: [Mace Run] /container/path/onnx2mace/docker_path/mace_20210223/tools/device.py:410: Mace run failed.
模型，yml和数据请在下面下载：链接：https://pan.baidu.com/s/15RxTBEVyvb2ZlGve3XB_Bw 
提取码：2g5t

**Comment by lu229** [comment]
如QQ沟通，因为是浮点推理与量化推理的对比，个别图片不准确没有特别的意义。
