### ISSUE TITLE
How to disable writing openCL binaries to file?

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#729]
When running MACE on GPU, the openCL binaries get dumped to file in the device, is there any way to prevent this to happen? For example I don't have permission to access device storage in Android. @lu229

**Comment by lu229** [comment]
@gasgallo If you did not invoke the method `GPUContextBuilder::SetStoragePath`, MACE will not dump the bin to a file, but on that occasion, MACE will run very slowly in the initialization and the first run.

**Comment by gasgallo** [comment]
@lu229 thanks, that works. Do you know why this solution runs more slowly during initialization and warmup?

**Comment by lu229** [comment]
@gasgallo If you refer to [this document](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#tuning-for-specific-soc-s-gpu) and set the tuning bin file, the performance will run fast, but after the OpenCL Driver update, the bin file will be invalid, on this occasion, MACE will run and dump the bin file and store it on the device, in the next time MACE will load the dumped bin file and MACE will fun fast, too.
If you did not invoke the method 'GPUContextBuilder::SetStoragePath', MACE will not store the bin file, the next time MACE will can not load the bin file and MACE will run more slowly.
The bin file is the binary from the OpenCL source code's compilation, which can accelerate the performance.
