### ISSUE TITLE
Convert yolov5s.onnx failed,  report "IndexError: Input model.0.conv.conv.weight is undefined!"

### ISSUE THREAD

**Issue by yank666** [XiaoMi/mace#740]
I just convert  yolov5s in onnx format by convert.py,  but always report error "IndexError: Input model.0.conv.conv.weight is undefined!",  I sure the yolov5s.onnx is no problem which is export follow "https://github.com/ultralytics/yolov5", can you help me resolve this error.  the dependency of mace is same with guide

![image](https://user-images.githubusercontent.com/79586188/123936056-66b83680-d9c7-11eb-8b97-04c55988bcd5.png)
![image](https://user-images.githubusercontent.com/79586188/123936907-3755f980-d9c8-11eb-9c66-1e7bc5bb7b72.png)

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by yll3518974** [comment]
@yank666 This is a onnx check issue, you can add "keep_initializers_as_inputs=True" into torch.onnx.export().

**Comment by yank666** [comment]
> @yank666 This is a onnx check issue, you can add "keep_initializers_as_inputs=True" into torch.onnx.export().

where is torch.onnx.export(), I can't find it in onnx_converter.py

**Comment by yll3518974** [comment]
You can find it at your export pytorch model to onnx model code.

**Comment by yank666** [comment]
> You can find it at your export pytorch model to onnx model code.
Ok, i have a try,  thx

**Comment by yank666** [comment]
> You can find it at your export pytorch model to onnx model code.

ok, I success in convert model, thx.
By the way,  when I got multi input or output in model , the intput_tensors(output_tensors) and input_shapes(output_shapes) in *.yml
