### ISSUE TITLE
Pytorch version for conversion directly from Pytorch models

### ISSUE THREAD

**Issue by ParusMajor60** [XiaoMi/mace#744]
### System information
- **MacOS**
- **MACE version 1.0.4**:
- **Python version(2.7 & 3.6)**: 
- **Bazel version 0.13.0**:

### Describe the problem
Hi, I saw that MACE supports converting Pytorch models since version 1.0.0. I am wondering which Pytorch version (eg 1.0.1) should be used if I want to convert a Pytorch model directly, without converting to ONNX first. I did not find relevant information in the docs.

Thanks in advance.

**Comment by yll3518974** [comment]
Dear customer

At present, we do not recommend use this, First convert model to ONNX is better choose.

Thanks
