### ISSUE TITLE
com.android.builder.testing.api.DeviceException: No connected devices!

### ISSUE THREAD

**Issue by zhangkom** [XiaoMi/mace#75]
when I build mace by build.sh, there is a error as following:

~/workspace_mace/mace/mace/examples/android

> Task :macelibrary:externalNativeBuildRelease
Build mace_mobile_jni arm64-v8a
[1/2] Building CXX object CMakeFiles/mace_mobile_jni.dir/src/main/cpp/image_classify.cc.o
[2/2] Linking CXX shared library ../../../../build/intermediates/cmake/release/obj/arm64-v8a/libmace_mobile_jni.so

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installAppRelease'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
49 actionable tasks: 10 executed, 39 up-to-date

**Comment by lee-bin** [comment]
You should connect your android phone and turn on USB debug to install the built APK.
