### ISSUE TITLE
MACE CPU GPU data transfer latency related questions 

### ISSUE THREAD

**Issue by madhu-korada** [XiaoMi/mace#750]
### Describe the problem
I was wondering about how MACE handles CPU GPU data transfer for neural networks. I have a very old GPU (Adreno 306 - OpenCL 1.1 supports) which has around 128KB of GPU memory and I need to use it efficiently. I have some questions, 
1. Does MACE transfers all of the weights of NN completely to GPU memory while invoking the MACE engine or does it do layer by layer ???
2. Is there any way to profile or monitor CPU GPU data transfer latency ??

I tried with several sized MACE models, Mobilenet inference on my GPU was very bad compared to CPU (GPU was doing a lot of work, because not big enough GPU I guess), the same happened when I checked inference speed with very small models (probably CPU GPU data transfer latency was too high).  I found a sweet spot where CPU and GPU time are approximately equal.  Still not a big difference when I compare CPU, GPU inference times. What do you think the issue might be ??
- Is it because my GPU is too small??

I am a beginner at using MACE and handling GPU stuff. Any suggestions would be appreciated.

**Comment by lu229** [comment]
@madhu-korada Yes MACE transfers all of the weights of NN completely to GPU memory while invoking the MACE engine.
You can benchmark the op's latency as follows:
`python tools/converter.py run --config=/path/to/model_deployment_file.yml --benchmark`
