### ISSUE TITLE
CreateMaceEngineFromCode errors

### ISSUE THREAD

**Issue by learnerwang** [XiaoMi/mace#76]
Dear MACE group:
  I have a question about using CreateMaceEngineFromCode.  In the url:https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#id1, It said that we could 
hide our models using following hink: model_graph_format: code and model_data_format: code,
Then link the static library libmace.a and ${library_name}.a . Using the following code to CreateMaceEngine:
create_engine_status =CreateMaceEngineFromCode(model_name.c_str(),
                              nullptr,
                             input_names,
                             output_names,
                             device_type,
                             &engine);
However, I meet an error like bellow when I run the program on my sdm845 devices:
 terminate called after throwing an instance of 'std::logic_error'  what():  basic_string::_S_construct null not valid.  
Do you have any idea to solvw it?
会不会是CreateMaceEngineFromCode第二个参数的问题,可以设为空么？
Best regards

**Comment by nolanliou** [comment]
空字符串，不能用nullptr

**Comment by learnerwang** [comment]
Thanks, I have validated your suggestions!Thanks a lot.
