### ISSUE TITLE
how to produce mobilenet.a

### ISSUE THREAD

**Issue by zhangkom** [XiaoMi/mace#77]
In android example, the CmakeLists need a mobilnet.a as following:

/mace/examples/android/macelibrary/CMakeLists.txt:18:set(mobilenet_file ${CMAKE_SOURCE_DIR}/src/main/cpp/model/mobilenet.a)

But I convert the model only output two file as following:
mobilenet_v2.data  mobilenet_v2.pb

How can I convert data and pb to *.a?

**Comment by lee-bin** [comment]
You can modify `model_graph_format` and `model_data_format` to `code`. Here is the what android demo use: https://github.com/XiaoMi/mace/blob/master/mace/examples/android/mobilenet.yml

**Comment by zhangkom** [comment]
I can not understand how to convert mobilenet_v2.data and mobilenet_v2.pb to mobilenet_v2.a yet.

**Comment by lee-bin** [comment]
- You don't convert convert mobilenet_v2.data and mobilenet_v2.pb to mobilenet_v2.a.
- Just like you use tools/converter.py to convert mobilenet_v2.yml to mobilenet_v2.data and mobilenet_v2.pb, you can also use tools/converter.py to convert mobilenet_v2.yml to mobilenet_v2.a.
