### ISSUE TITLE
GPU implementation use float32 or float16?

### ISSUE THREAD

**Issue by raninbowlalala** [XiaoMi/mace#78]
Hi,
I want to know in your benchmark, you use float32 or float16 in GPU?
Thank you very much!

**Comment by nolanliou** [comment]
Ops' benchmark or Model benchmark?

**Comment by raninbowlalala** [comment]
@nolanliou model benchmark in https://gitlab.com/llhe/mace-models/-/jobs/78152526

**Comment by yejw5** [comment]
@raninbowlalala we use float16 for GPU by default. And it can be specified by `data_type` option in deployment file. Refer to: https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html

**Comment by raninbowlalala** [comment]
@yejw5 Thank you very much!
