### ISSUE TITLE
NNX_RELEASE.ModelProto exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by qiangxinixn** [XiaoMi/mace#783]
在onnx转mace中，对于onnx模型超过2GB支持是怎么处理的呢？由于我使用的模型参数过大故在保存onnx的时候选择了external_data的方式，在mace的convert中不支持大模型的转换吗？

**Comment by TonyMou** [comment]
> 在onnx转mace中，对于onnx模型超过2GB支持是怎么处理的呢？由于我使用的模型参数过大故在保存onnx的时候选择了external_data的方式，在mace的convert中不支持大模型的转换吗？

是的，目前还不支持大模型的转换。
