### ISSUE TITLE
tensroflow的FC支持

### ISSUE THREAD

**Issue by conansherry** [XiaoMi/mace#80]
瞅了一圈，我看tensorflow的fc都是用matmul实现的，但是matmul mace还不支持gpu。。。。
![image](https://user-images.githubusercontent.com/2148224/42690836-6c0cf2c8-86d8-11e8-863c-c2b11d3e1e40.png)

**Comment by nolanliou** [comment]
用的TF的哪个API来做的FC？

**Comment by conansherry** [comment]
tf.layers.dense
