### ISSUE TITLE
构建Android工程时遇到的问题

### ISSUE THREAD

**Issue by lyp0413** [XiaoMi/mace#82]
当我的工程里包含mace_engine_factory.h文件时，编译现实未定义函数，请问这个文件里的LoadModelData函数是在哪个库中给出定义的

**Comment by nolanliou** [comment]
用的MACE的哪个版本呢？

**Comment by lyp0413** [comment]
@nolanliou 应该是最新版master

**Comment by nolanliou** [comment]
有个model.a link了吗？具体使用流程请阅读https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html

**Comment by lyp0413** [comment]
@nolanliou 有的，都是按照流程来的

**Comment by lyp0413** [comment]
@nolanliou 我想知道在安卓上跑，除了转换出来的model.a和libmace.a，还需要什么链接库

**Comment by nolanliou** [comment]
没了，可以参考我们给的android的example
