### ISSUE TITLE
python: can't open file 'tools/converter.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wuyajun19900627** [XiaoMi/mace#83]
Build failed when I command: ./build.sh

**Comment by wuyajun19900627** [comment]
Plus: I can not visit the link: NDK installation guide.

**Comment by nolanliou** [comment]
where is the build.sh?

**Comment by wuyajun19900627** [comment]
cd mace/exampls/android
./build.sh

**Comment by nolanliou** [comment]
@lee-bin could you help with this issue?

**Comment by wuyajun19900627** [comment]
I have solved it, thanks all the same.

**Comment by wuyajun19900627** [comment]
Here is a new issue:

1 error generated.
Target //mace/codegen:generated_models failed to build
INFO: Elapsed time: 133.710s, Critical Path: 14.29s
INFO: 314 processes: 314 linux-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1551, in <module>
    flags.func(flags)
  File "tools/converter.py", line 774, in convert_func
    build_model_lib(configs, flags.address_sanitizer)
  File "tools/converter.py", line 743, in build_model_lib
    address_sanitizer=address_sanitizer
  File "/home/user/wuyajun/mace-master/tools/sh_commands.py", line 317, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/user/bin/bazel build //mace/codegen:generated_models --config android --cpu=arm64-v8a --define neon=true --define openmp=true --define hexagon=false --config optimization

**Comment by lee-bin** [comment]
Which commit are you working on?
How did you execute build.sh?
Is there still the problem `can't open file 'tools/converter.py'`?
How can you reproduce the following problem?
>Here is a new issue:
>
>1 error generated.
Target //mace/codegen:generated_models failed to build
INFO: Elapsed time: 133.710s, Critical Path: 14.29s
INFO: 314 processes: 314 linux-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
File "tools/converter.py", line 1551, in 
flags.func(flags)
File "tools/converter.py", line 774, in convert_func
build_model_lib(configs, flags.address_sanitizer)
File "tools/converter.py", line 743, in build_model_lib
address_sanitizer=address_sanitizer
File "/home/user/wuyajun/mace-master/tools/sh_commands.py", line 317, in bazel_build
*bazel_args)
File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in call
raise exc
sh.ErrorReturnCode_1:
>
>RAN: /home/user/bin/bazel build //mace/codegen:generated_models --config android --cpu=arm64-v8a --define neon=true --define openmp=true --define hexagon=false --config optimization

Could you please paste all the related logs and what you have executed?

**Comment by wuyajun19900627** [comment]
The previous issue(can't open file 'tools/converter.py') is solved. But it failed when I try to cd mace/exampls/android
./build.sh. 
 Logs as follows:

************************************************
          Model mobilenet_v2 converted          
************************************************

************************************
          Building library          
************************************

* generate common source files...
generate common source files done
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 17. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16]. Bazel will attempt to treat the NDK as if it was r16. This may cause compilation and linkage problems. Please download a supported NDK version.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/tools/validation:mace_run_static (14 packages loaded).
INFO: Found 1 target...
INFO: From Executing genrule @opencl_clhpp//:gen_opencl_clhpp:
/tmp/opencl-clhpp-build.F9keYxPYYl /home/user/.cache/bazel/_bazel_user/d5c285c9e1b4aeab053edcdb9855b0e7/sandbox/linux-sandbox/178/execroot/mace
/tmp/opencl-clhpp-build.F9keYxPYYl/build /tmp/opencl-clhpp-build.F9keYxPYYl /home/user/.cache/bazel/_bazel_user/d5c285c9e1b4aeab053edcdb9855b0e7/sandbox/linux-sandbox/178/execroot/mace
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/opencl-clhpp-build.F9keYxPYYl/build
Scanning dependencies of target generate_clhpp
[100%] Rebuilding cl.hpp ...
[100%] Built target generate_clhpp
Scanning dependencies of target generate_cl2hpp
[100%] Rebuilding cl2.hpp ...
[100%] Built target generate_cl2hpp
/tmp/opencl-clhpp-build.F9keYxPYYl /home/user/.cache/bazel/_bazel_user/d5c285c9e1b4aeab053edcdb9855b0e7/sandbox/linux-sandbox/178/execroot/mace
/home/user/.cache/bazel/_bazel_user/d5c285c9e1b4aeab053edcdb9855b0e7/sandbox/linux-sandbox/178/execroot/mace
installing to bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp
INFO: From Compiling external/com_google_protobuf/src/google/protobuf/stubs/strutil.cc:
external/com_google_protobuf/src/google/protobuf/stubs/strutil.cc:657:35: warning: comparison 'const long' < -2147483648 is always false [-Wtautological-constant-compare]
  } else if (errno == 0 && result < kint32min) {
                           ~~~~~~ ^ ~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/stubs/strutil.cc:660:35: warning: comparison 'const long' > 2147483647 is always false [-Wtautological-constant-compare]
  } else if (errno == 0 && result > kint32max) {
                           ~~~~~~ ^ ~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/stubs/strutil.cc:675:35: warning: comparison 'const unsigned long' > 4294967295 is always false [-Wtautological-constant-compare]
  } else if (errno == 0 && result > kuint32max) {
                           ~~~~~~ ^ ~~~~~~~~~~
3 warnings generated.
ERROR: /home/user/wuyajun/mace/mace/utils/BUILD:12:1: C++ compilation of rule '//mace/utils:utils' failed (Exit 1): clang failed: error executing command 
  (cd /home/user/.cache/bazel/_bazel_user/d5c285c9e1b4aeab053edcdb9855b0e7/execroot/mace && \
  exec env - \
    PATH=/home/user/wuyajun/software/gradle-4.1/bin:/home/user/wuyajun/software/android-studio/bin:/home/user/wuyajun/software/jdk1.8.0_171/bin:/home/user/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=21' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools '-std=c++11' -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -O3 -ffunction-sections -fdata-sections '-fvisibility=hidden' -Werror -Wextra -Wno-missing-field-initializers '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/android/support/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c mace/utils/string_util.cc -o bazel-out/armeabi-v7a-opt/bin/mace/utils/_objs/utils/mace/utils/string_util.o)

Use --sandbox_debug to see verbose messages from the sandbox
mace/utils/string_util.cc:53:12: error: no member named 'accumulate' in namespace 'std'
      std::accumulate(max_column_len.begin(), max_column_len.end(),
      ~~~~~^
1 error generated.
Target //mace/tools/validation:mace_run_static failed to build
INFO: Elapsed time: 279.914s, Critical Path: 60.30s
INFO: 506 processes: 506 linux-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1376, in <module>
    flags.func(flags)
  File "tools/converter.py", line 893, in build_library
    flags.disable_openmp, flags.address_sanitizer)
  File "tools/converter.py", line 856, in generate_library
    tuning, enable_openmp, address_sanitizer)
  File "tools/converter.py", line 717, in build_specific_lib
    address_sanitizer=address_sanitizer
  File "/home/user/wuyajun/mace/tools/sh_commands.py", line 327, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/user/bin/bazel build //mace/tools/validation:mace_run_static --config android --cpu=armeabi-v7a --define neon=true --define openmp=true --define hexagon=false --config optimization

  STDOUT:


  STDERR:

**Comment by lee-bin** [comment]
What's your NDK version? You should follow the following guide and install all the dependencies with the suggested version. https://mace.readthedocs.io/en/latest/installation/env_requirement.html

**Comment by yejw5** [comment]
@wuyajun19900627 
Bazel haven't support `NDK 17`. Version `12`, `15` or `16` are adviced.
