### ISSUE TITLE
how to modify yml file if there are more than one tensor as input

### ISSUE THREAD

**Issue by learnerwang** [XiaoMi/mace#86]
Dear MACE group:
 I have one question, if there are 2 or more tensors as input file ,在convert的时候成功，跑CPU版本的也是成功的，可是在跑GPU版本的时候出现了如下错误：
Check failed: inputs_count == 2 || divisible_four Dimensions of inputs should be divisible by 4 when inputs_count > 2.
Aborted
这是什么问题啊？我改如下修改deployment 文件或者网络？
Best Regards

**Comment by nolanliou** [comment]
基于性能考虑，目前GPU concat层输入tensor的channel维必须是4的倍数，你可以选择改一下网络，应该没什么影响

**Comment by learnerwang** [comment]
谢谢！我修改一下网络看看！

**Comment by nolanliou** [comment]
先关了，有问题可以再打开。

**Comment by leeburt** [comment]
你是怎么改的，我怎么改都报同样的错误。
