### ISSUE TITLE
bash tools/build-standalone-lib.sh  出错

### ISSUE THREAD

**Issue by SankQin** [XiaoMi/mace#89]
build shared lib for armeabi-v7a
ERROR: /home/ql/mace-master/mace/codegen/BUILD:22:1: no such package '@local_opencl_kernel_encrypt//': Not a regular file: /home/ql/mace-master/.git/HEAD and referenced by '//mace/codegen:encrypt_opencl_kernel_gen'
ERROR: Analysis of target '//mace/libmace:libmace_dynamic' failed; build aborted: Analysis failed
INFO: Elapsed time: 18.967s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (22 packages loaded)
    currently loading: @com_google_protobuf//

**Comment by yejw5** [comment]
Did you pull the latest code?

**Comment by SankQin** [comment]
I pulled yesterday

**Comment by SankQin** [comment]
What is the cause of this problem?  help me ，please

**Comment by yejw5** [comment]
@SankQin The current building depends on git message. Please download code by command `git pull`.  And we will fix it later. Thanks for feedback.

**Comment by nolanliou** [comment]
Fixed, please try again.

**Comment by SankQin** [comment]
thx,successfully
