### ISSUE TITLE
arm-v7a 有没有关闭默认添加libhexagon_controller.so 的功能？

### ISSUE THREAD

**Issue by akbarxie** [XiaoMi/mace#92]
部分手机三星Note3：
caused by could not load library "libcdsprpc.so" needed by "libhexagon_controller.so"; caused by library "libcdsprpc.so" not found

有没有办法关闭这个DSP库，不需要运行DSP，它会导致在部分手机上链接不到库，运行失败？

config文件已经把runTime设置成了cpu+gpu：
runtime: cpu+gpu

**Comment by akbarxie** [comment]
在/mace/libmace/BUILD 文件中，找到 "-DMACE_ENABLE_HEXAGON",找到这一行，注释掉即可。
.a 文件可以正常使用了OK

**Comment by yejw5** [comment]
@akbarxie 可否按照[模板](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)填写一下错误信息？我这边详细看下这个问题

**Comment by yejw5** [comment]
@akbarxie 我们的目标不只是开源，还会一直把这个项目维护下去。
这个问题我从本地的代码逻辑或者手动编译，都没能复现，后面有了详细的过程，将调研一下具体的原因。

**Comment by akbarxie** [comment]
下载的应该是Commits on Jul 18, 2018 的一次提交，由于是下载的zip文件，忘记了提交号：
https://github.com/akbarxie/maceissue
所以给出源码地址。应该只是部分机型上的问题，我这边s7 edge没问题
我已经编译好了mace的core，在Android Studio 上编译的时候，发现arm-v7a 的库会自动链接和加载libhexagon_controller.so库，该库的使用应该会需要自动链接加载libcdsprpc.so。
不过，不是所有的手机都有libcdsprpc.so该库，所有链接运行失败。

**Comment by yejw5** [comment]
@akbarxie 应该是用的`./tools/build-standalone-lib.sh`命令编译的`libmace.a/libmace.so`？这个脚本的编译默认把dsp加上了，我fix一下，做一下区分

**Comment by akbarxie** [comment]
对的，我是用这个脚本编译的libmace.a，如果你做一下区分就更好了。

**Comment by akbarxie** [comment]
为小米的同学，点赞哦
