### ISSUE TITLE
caffe的group conv/deconv支持，或者depthwise deconv支持

### ISSUE THREAD

**Issue by conansherry** [XiaoMi/mace#93]
反卷积在caffe里还是有比较重要的作用的，在很多场景里都需要上采样。其中depthwise的deconv是效率比较高的方式，比纯粹的deconv计算量要小很多，希望可以得到支持。

**Comment by TonyMou** [comment]
@conansherry 谢谢你的反馈。之前主要是针对TF的模型，没有支持depthwise的deconv。目前depthwise deconv正在开发中，针对你的需求，方便提供一个Caffe的测试模型吗？

**Comment by TonyMou** [comment]
已经支持了，cpu下支持group和depthwise的deconv，gpu下支持depthwise deconv。
