### ISSUE TITLE
encrypt_opencl_codegen module 出错

### ISSUE THREAD

**Issue by SankQin** [XiaoMi/mace#95]
ql@ql-VirtualBox:~$ python mace/tools/converter.py build --config=/mace/mace-modles/mobilenet-v2/mobilenet-v2.yml
Import error:
No module named encrypt_opencl_codegen

how to get encrypt_opencl_codegen module？

**Comment by SankQin** [comment]
ubuntu 16.04
python 2.7

**Comment by SankQin** [comment]
thanks  i finished

**Comment by YijiaZhao** [comment]
> thanks i finished

how to deal with it?
