### ISSUE TITLE
It failed when I convert my own model

### ISSUE THREAD

**Issue by wuyajun19900627** [XiaoMi/mace#96]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage? Yes
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:I don't know
- **MACE version (Use the command: git describe --long --tags)**:v0.8.1-143-gfc1c855
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:I don't know

### Model deploy file (*.yml)
library_name: test
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: /home/user/wuyajun/model/output_graph.pb
    model_sha256_checksum: a123ab19fc3048ac7a4fd5e37d819cc369cff8a80f55b5fdac25144ca0c5625c
    subgraphs:
      - input_tensors:
          - Placeholder
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - final_result
        output_shapes:
          - 1,6
    runtime: cpu+gpu
    winograd: 0

### Describe the problem
It failed when I convert my own model

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Logs as follow:

**********************************************
          Convert mobilenet_v1 model          
**********************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.342s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Traceback (most recent call last):
  File "/home/user/wuyajun/mace_success/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 300, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/user/wuyajun/mace_success/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 145, in main
    output_graph_def = converter.run()
  File "/home/user/wuyajun/mace_success/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 214, in run
    self.convert_ops()
  File "/home/user/wuyajun/mace_success/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 256, in convert_ops
    % tf_op.type)
  File "/home/user/wuyajun/mace_success/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 18, in mace_check
    raise Exception(msg)
Exception: Mace does not support tensorflow op type PlaceholderWithDefault yet
Traceback (most recent call last):
  File "tools/converter.py", line 1580, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/user/wuyajun/mace_success/tools/sh_commands.py", line 530, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/user/wuyajun/model/output_graph.pb --weight_file= --model_checksum=a123ab19fc3048ac7a4fd5e37d819cc369cff8a80f55b5fdac25144ca0c5625c --weight_checksum= --input_node=Placeholder --output_node=final_result --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by nolanliou** [comment]
```
Exception: Mace does not support tensorflow op type PlaceholderWithDefault yet
```

**Comment by nolanliou** [comment]
Have you ever optimized your model using TF tools `transform_graph`? please refer to https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html

**Comment by liyinhgqw** [comment]
See #104 , close this issue now
