### ISSUE TITLE
libmace_mobile_jni.so 无法编译

### ISSUE THREAD

**Issue by SankQin** [XiaoMi/mace#97]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':macelibrary:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process D:\Development\studio_sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\DownLoad\mace-master\mace\examples\android\macelibrary\.externalNativeBuild\cmake\debug\arm64-v8a --target mace_mobile_jni}
  ninja: error: '../../../../src/main/cpp/model/arm64-v8a/mobilenet.a', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libmace_mobile_jni.so', missing and no known rule to make it

CmakeList 

include_directories(${CMAKE_SOURCE_DIR}/)
include_directories(${CMAKE_SOURCE_DIR}/src/main/cpp/include)
set(mace_lib ${CMAKE_SOURCE_DIR}/src/main/cpp/lib/arm64-v8a/libmace.a)
set(mobilenet_lib ${CMAKE_SOURCE_DIR}/src/main/cpp/model/arm64-v8a/mobilenet.a)
add_library (mace_lib STATIC IMPORTED)
set_target_properties(mace_lib PROPERTIES IMPORTED_LOCATION ${mace_lib})
add_library (mobilenet_lib STATIC IMPORTED)
set_target_properties(mobilenet_lib PROPERTIES IMPORTED_LOCATION ${mobilenet_lib})

add_library( # Sets the name of the library.
             mace_mobile_jni

             # Sets the library as a shared library.
             SHARED

             # Provides a relative path to your source file(s).
             src/main/cpp/image_classify.cc )

find_library( # Sets the name of the path variable.
              log-lib

              # Specifies the name of the NDK library that
              # you want CMake to locate.
              log )

target_link_libraries( # Specifies the target library.
                       mace_mobile_jni
                       mace_lib
                       mobilenet_lib
                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib} )

**Comment by nolanliou** [comment]
@lee-bin could you help with this issue?

**Comment by lee-bin** [comment]
请按此表单提交问题（不要遗漏任何一项），并注意格式，谢谢。
https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md

**Comment by SankQin** [comment]
模型文件已经编译好了， 在studio中生成ibmace_mobile_jni.so  失败，能帮忙看看cmakelist 已经贴上了 @lee-bin

**Comment by nolanliou** [comment]
@SankQin 如果没有环境配置信息，不好找到问题原因的，请按照issue的模板，把环境信息都列出来。

**Comment by SankQin** [comment]
我是在ubuntu 16.04  ndk 15c 环境下编译出的模型文件和源码
拿到win10 下的编译android 工程，这样垮环境的文件编译会有问题吗？win10 是cmake编译的

**Comment by lee-bin** [comment]
- 目前仅支持Linux构建，WIN10构建可以先自己尝试一下，同时欢迎贡献相关文档和代码。
- 对于出现的问题，请确保`mace/examples/android/macelibrary/src/main/cpp/model/arm64-v8a/mobilenet.a`存在且合法。

**Comment by llhe** [comment]
@SankQin 应该是没有问题的，NDK只是交叉编译工具，跟运行的平台无关。如果有问题应该是NDK的linux和windows版本之间不兼容。

**Comment by SankQin** [comment]
@llhe  linux下编译出来的mobilenet.a，跑在windows环境下的studio工程里，报上述错误。 不同环境的ndk 是不是有影响呢

**Comment by llhe** [comment]
`missing and no known rule to make it` 看起来是没找到这个文件呀。还没涉及到兼容性的问题。

**Comment by llhe** [comment]
检查下makefile里面的目录是否正确，文件是否放对位置了

**Comment by SankQin** [comment]
include_directories(${CMAKE_SOURCE_DIR}/)
include_directories(${CMAKE_SOURCE_DIR}/src/main/cpp/include)
set(mace_lib ${CMAKE_SOURCE_DIR}/src/main/cpp/lib/arm64-v8a/libmace.a)
set(mobilenet_lib ${CMAKE_SOURCE_DIR}/src/main/cpp/model/arm64-v8a/mobilenet.a)
add_library (mace_lib STATIC IMPORTED)
set_target_properties(mace_lib PROPERTIES IMPORTED_LOCATION ${mace_lib})
add_library (mobilenet_lib STATIC IMPORTED)
set_target_properties(mobilenet_lib PROPERTIES IMPORTED_LOCATION ${mobilenet_lib})

上面是cmakelist 配置

**Comment by SankQin** [comment]
CMAKE_SOURCE_DIR 是默认cmakelist 根目录吗？ @llhe

**Comment by llhe** [comment]
cmake我不是很熟，但是这个错应该是没找到那个库文件吧

**Comment by liyinhgqw** [comment]
Close it. Feel free to reopen it if still have issues
