### ISSUE TITLE
Failed to create multiply subgraphs of MTCNN 

### ISSUE THREAD

**Issue by peyer** [XiaoMi/mace#98]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution : Linux Ubuntu 16.04
- **NDK version : r16b
- **MACE version: 0.8
- **Python version: Python 2.7.12
- **Bazel version: 0.14.0

### Model deploy file (*.yml)
# The name of library
library_name: mtcnn
target_abis: [arm64-v8a]
embed_model_data: 1
# The build mode for model(s).
# 'code' stand for transfer model(s) into cpp code, 'proto' for model(s) in protobuf file(s).
build_type: code
linkshared: 0
# One yaml config file can contain multi models' config message.
models:
  pnet: 
    platform: caffe
    # support local path, http:// and https://
    model_file_path: /path/of/local/model/of/det1.prototxt
    model_sha256_checksum: adc1756d8515d3ca3a6a186c0fadab66fcae04bd8d3c6388e2fe8797a626dde4
    weight_file_path: /path/of/local/model/of/det1.caffemodel
    weight_sha256_checksum: d6085e7f48ba7e6b6f1b58964595f6bce5b97bcc4866751f7b4bdc98f920c096
    subgraphs:
      - input_tensors: data
        input_shapes: 1,12,12,3
        output_tensors: prob1
        output_shapes: 1,2
    subgraphs:
      - input_tensors: data
        input_shapes: 1,12,12,3
        output_tensors: conv4-2
        output_shapes: 1,4
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
  rnet: 
    platform: caffe
    # support local path, http:// and https://
    model_file_path: /path/of/local/model/of/det2.prototxt
    model_sha256_checksum: 077686e89e606354f425366afdb2018777d93c6450b50e2c12301f8a97f6bb47
    weight_file_path: /path/of/local/model/of/det2.caffemodel
    weight_sha256_checksum: 39b20f7a57bb8176cc9466cea4dfd52da6a6f876de60c7ab222a309f2d0ca08c
    subgraphs:
      - input_tensors: data
        input_shapes: 1,24,24,3
        output_tensors: prob1
        output_shapes: 1,2
    subgraphs:
      - input_tensors: data
        input_shapes: 1,24,24,3
        output_tensors: conv5-2
        output_shapes: 1,4
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
  onet: 
    platform: caffe
    # support local path, http:// and https://
    model_file_path: /path/of/local/model/of/det3.prototxt
    model_sha256_checksum: a8385a3aad241acf5902b79466f9a359ea9f03a3b6dcbe1e1efa050908cf7d04
    weight_file_path: /path/of/local/model/of/det3.caffemodel
    weight_sha256_checksum: 9d6098829a4d6d318f37cec42142465637fafe4c673f2e93b69495bf7ca23d2d
    subgraphs:
      - input_tensors: data
        input_shapes: 1,48,48,3
        output_tensors: prob1
        output_shapes: 1,2
    subgraphs:
      - input_tensors: data
        input_shapes: 1,48,48,3
        output_tensors: conv6-2
        output_shapes: 1,4
    subgraphs:
      - input_tensors: data
        input_shapes: 1,48,48,3
        output_tensors: conv6-3
        output_shapes: 1,10
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

### Describe the problem
Although I successfully converted PNet, RNet, ONet with caffe interface into mace library, however, When I tried to use mace::CreateMaceEngineFromCode(), it shown that "prob1" is not belong to model's outputs,  so I guessed that it maybe caused by failure to create multiply subgraphs

### Error information / logs
07-19 15:40:38.392 32051-32051/? I/MACE: mace.cc:127 Creating MaceEngine, MACE version: v0.8.1-17-g7096627-20180711
07-19 15:40:38.393 32051-32051/? I/MACE: mace.cc:135 Initializing MaceEngine
07-19 15:40:38.393 32051-32051/? A/MACE: mace.cc:155 'prob1' is not belong to model's outputs [conv4-2]
    
    --------- beginning of crash
07-19 15:40:38.393 32051-32051/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 32051 (com.mtcnn)
07-19 15:40:38.411 656-1046/? E/libnav: CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
07-19 15:40:38.460 32097-32097/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-19 15:40:38.461 32097-32097/? A/DEBUG: Build fingerprint: '360/QK1707/QK1707:7.1.1/NMF26X/7.1.076.PX.180105.360_360_QK1707_CN:user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    pid: 32051, tid: 32051, name: com.mtcnn  >>> com.mtcnn <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-19 15:40:38.464 32097-32097/? A/DEBUG: Abort message: 'mace.cc:155 'prob1' is not belong to model's outputs [conv4-2]'
        x0   0000000000000000  x1   0000000000007d33  x2   0000000000000006  x3   0000000000000008
        x4   0000007f8d002140  x5   0000007f8ce0c768  x6   0000007f81dbed16  x7   000000002149e7c0
        x8   0000000000000083  x9   0000007f9139fa98  x10  9eed795e39db951d  x11  9eed795e39db951d
        x12  0000000000000000  x13  0000000000000020  x14  ffffffffffffffdf  x15  0000007f8f65e818
        x16  0000007f8f653ed0  x17  0000007f8f5f5624  x18  000000000000007f  x19  0000007f9139fb40
        x20  0000000000000006  x21  0000007f9139fa98  x22  000000000000000e  x23  0000007f9139fb30
        x24  0000007f7e22feb0  x25  0000000080000000  x26  0000007f7e26e660  x27  0000007f7e26e618
        x28  0000007f8b77fd10  x29  0000007fef026280  x30  0000007f8f5f28a8
        sp   0000007fef026260  pc   0000007f8f5f562c  pstate 0000000060000000

**Comment by nolanliou** [comment]
Please re-format your issue.

**Comment by liguiyuan** [comment]
@peyer Did you solved this problem? I have the same problems as you, I want to that how you deal with this problem. Thanks~
